### ISSUE TITLE
Consider applying prometheus guidelines regarding alerting rules

### ISSUE THREAD

**Issue by paulfantom** [metallb/metallb#1019]
Consider applying the following guidelines to existing alerting rules - https://github.com/monitoring-mixins/docs#guidelines-for-alert-names-labels-and-annotations. 

Here is a list of possible improvements:
- Use alert severity which is consistent with alerting rules from other projects (use only `warning` and `critical`).
- Consider switching from `message` annotation to `summary` + `description`.
- Avoid creating [the same alert with the same severity but different thresholds](https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml#L114-L119). This is an easy path towards alerting fatigue.
- Consider writing runbooks for alerts

**Comment by SISheogorath** [comment]
I wrote some runbooks and adjusted the alert severity for my infrastructure: https://git.shivering-isles.com/shivering-isles/infrastructure-gitops/-/commit/5732d4c59b92c09397c3393e24443c41280695c6

I would be willing to contribute them here if there is interested in having them around. The runbooks themselves should be trivial to integrate with the existing documentation given that both seem use hugo.

**Comment by fedepaol** [comment]
That'd be cool @SISheogorath !
Assigning you to the issue.
