### ISSUE TITLE
Amazon EKS Anywhere support

### ISSUE THREAD

**Issue by WillNilges** [metallb/metallb#1023]
I'm running a local EKSA cluster on Ubuntu Server 20.04 LTS on ext4 disk. I'd like to use MetalLB to enable ingress for an app I want to deploy, but it's just... not working. Nothing in the logs; I name the IPs I reserved on my subnet, MetalLB picks them up, binds LoadBalancer services and... the IPs just don't connect. I'm guessing this is an incompatibility with how EKSA does networking. Seems like the local mode uses Cilium for networking, and does not provide Load Balancing services. **I'm throwing this issue up here to ask if there's plans to support EKSA, and what I can do to help. I'll try to gather information and post it here as I learn.**

MetalLB version: `0.11.0` installed thru `helm`
Kubernetes version: `v1.21.2-eks-1-21-5`
Network Addon: Cilium
IPVS mode: No
Iptables mode: Yes

**Comment by russellb** [comment]
I imagine to close this ticket we should update https://metallb.universe.tf/installation/clouds/ with whatever is learned about MetalLB for this platform.  I saw that you also started a conversation on `#metallb` on slack - thanks.

**Comment by russellb** [comment]
I know that Cilium embedded MetalLB to provide LoadBalancer support via BGP. I wonder if they support layer2 mode as well?  I'd look there.  https://cilium.io/blog/2021/05/20/cilium-110

This is really more a question about EKS Anywhere, its network architecture, and Cilium as well.

**Comment by WillNilges** [comment]
Interesting, yeah I'll go look there and see what the deal is. Maybe I should instead open an issue on EKSA?

**Comment by champtar** [comment]
Cilium only uses the controller, and uses their BGP implementation instead of the speakers (so no L2)
