### ISSUE TITLE
Provide a better feedback in case of failed frr reloading

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1046]
Today the real configuration reloading is lost behind a sighup call.
It would be ideal to provide a better feedback to the user.
Some ideas to understand if the configuration is failed are:
- some kind of versioning / timestamp between the desired and applied configuration. If they drift, there has been an error
- a sync call (more rich than sighup), that returns in case of failure (this was discarded originally, but we may want to take it back)

**Comment by liornoy** [comment]
I'm working on a solution for this issue, soon will link a PR

**Comment by fedepaol** [comment]
Assigned the PR to you
