### ISSUE TITLE
Helm: Include release namespace in all relevant resources

### ISSUE THREAD

**Issue by flyinggecko** [metallb/metallb#1048]
Hey,

I will try to explain this a bit:
We use gitlab-k8s-agents to bootstrap some applications in our clusters. To generate manifests, that get deployed, we use mostly helm like this for metallb:
```bash
> helm template --namespace metallb-system metallb metallb/metallb > manifest.yaml
```

This results in the following manifest: https://gist.github.com/flyinggecko/89f22815da8131d9e8fecb1fed6320b0

The problem is, that some resources now contain the namespace and some don't.
For example the roles and role-bindings contain the ns, but the deployment/daemonset and config don't.

This doesn't happen if you use helm the normal way e.g. `helm upgrade --install --namespace metallb-system metallb metallb/metallb`. 

Versions:
  - MetalLB: 0.11.0
  - Kubernetes: independent of version
  - Network: independent of used network
  - Kube-Proxy/Ipvs: independent of this

So, is this something you would except a merge request? I would then create one.

Best regard

**Comment by fedepaol** [comment]
cc @gclawes

**Comment by gclawes** [comment]
Good catch!  The `.metadata.namespace` field should be removed from all resources, helm should apply that on install to namespaced resources.

I also noticed that the default value of `.Values.prometheus.namespace` is `monitoring`, this was probably carried over from my test setup when I wrote the chart.  Properly, it should be un-set, and the chart should throw an error when `.Values.prometheus.podmonitor.enabled` is `true`.  I'll prepare a PR containing both of these fixes.

**Comment by gclawes** [comment]
Ah, I see, `.Values.prometheus.namespace` was added here: https://github.com/metallb/metallb/commit/48cb1c3b8a97487a825f24860ecbf5c2b3919817.

@fedepaol, I think it makes sense for `.Values.prometheus.namespace` and `.Values.prometheus.serviceAccount` not to have default values, and instead have validation in `_helpers.tpl` functions that fail if they are not provided only when `.Values.prometheus.podMonitor.enabled` is `true`.  Thoughts?

**Comment by fedepaol** [comment]
Ah dang, so I was responsible!
Yes, makes total sense

> Good catch! The `.metadata.namespace` field should be removed from all resources, helm should apply that on install to namespaced resources.
> 
> I also noticed that the default value of `.Values.prometheus.namespace` is `monitoring`, this was probably carried over from my test setup when I wrote the chart. Properly, it should be un-set, and the chart should throw an error when `.Values.prometheus.podmonitor.enabled` is `true`. I'll prepare a PR containing both of these fixes.

Ah my bad

**Comment by fedepaol** [comment]
Re: prometheus default values, I added them to match what you get by installing prometheus from upstream, but it makes sense to defer to the user. Sorry, I am not fluent with Helm as I'd like to be.
