### ISSUE TITLE
Document whether MetalLB supports MixedProtocolLBService

### ISSUE THREAD

**Issue by haslersn** [metallb/metallb#1050]
I think the title is self-explanatory. If not, then reach out to me, please.

**Comment by fedepaol** [comment]
Hi @haslersn , thanks for filing this issue. With https://github.com/metallb/metallb/issues/1026 we are going to cover this scenario in CI (and eventually hammer it if it doesn't work).
Hope this helps.

**Comment by haslersn** [comment]
@fedepaol I don't see how #1026 is related. MixedProtocolLBService is a Kubernetes feature gate and is about mixing TCP and UDP on the same LoadBalancer-typed service.

**Comment by fedepaol** [comment]
> @fedepaol I don't see how #1026 is related. MixedProtocolLBService is a Kubernetes feature gate and is about mixing TCP and UDP on the same LoadBalancer-typed service.

Oh, sorry I rushed up on the title, and as I had the other one in mind, I assumed it was the same. Will dig a bit and get back with an answer. My gut feeling is that metallb probably supports it out of the box, but it's worth double checking.

**Comment by msherif1234** [comment]
@haslersn does this address your need https://metallb.universe.tf/usage/#ip-address-sharing towards the end it explains how using this annotation can help with mixprotocolLBsvc ?

**Comment by haslersn** [comment]
@msherif1234 It doesn't mention MixedProtocolLBService. When the MixedProtocolLBService feature gate is enabled, then I assume that you **don't** need that annotation (at least not for the "first reason"). However, this is only the case if MetalLB supports MixedProtocolLBService, and the documentation doesn't mention whether this is the case.

**Comment by DerRockWolf** [comment]
@haslersn could you already test this?

**Comment by javydekoning** [comment]
This was moved to beta in 1.24

Any plans for MetalLB to support this?

**Comment by DerRockWolf** [comment]
From what I could observe on one of my clusters this is indeed already supported and working with MetalLB.

**Comment by fedepaol** [comment]
Hi, sorry for the delay. This is supported by metallb.
I also filed a PR to validate it in our CI.
Closing the issue.
