### ISSUE TITLE
Consider migrating CI to github actions

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1063]
GH actions is the recommended CI for CNCF projects (https://github.com/cncf/toc/issues/720#issuecomment-971824099).
This issue is to track how much work it would take and if gh actions cover all our needs (including the release process).

**Comment by tylerauerbeck** [comment]
@fedepaol Would be happy to lend a hand here if nobody else is taking a look.

**Comment by fedepaol** [comment]
> @fedepaol Would be happy to lend a hand here if nobody else is taking a look.

That'd be awesome! I'd suggest moving in steps, starting with the test jobs first, and handling the release one later.

**Comment by tylerauerbeck** [comment]
@fedepaol This is mostly done: https://github.com/tylerauerbeck/metallb/tree/add-gha

The problem that I'm running into is that I can't get all tests to pass reliably (seeming to have to do with some timeouts in the test). I'm going to continue playing around with this, but are there existing flakes/timeout issues I should know about that may help resolve some of these issues?

**Comment by fedepaol** [comment]
Neat! Yes, there are a couple of flakes we are chasing, I'll have a look if it's the same flakes we are talking about.
I saw your pr, will have a look in the next few days.

**Comment by fedepaol** [comment]
@tylerauerbeck we removed the e2e lanes from circle ci, do you want to migrate the image promotion jobs too (it's fine to say no :P )

**Comment by tylerauerbeck** [comment]
Yepp. Actually almost have this ready. Should have some time this week to wrap things up.

**Comment by fedepaol** [comment]
Awesome, thanks a lot!
