### ISSUE TITLE
Generate the manifests from the helm charts

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1080]
We are maintaining two different methods for configuration.
It would make sense to have the basics manifests (and variations) generated starting from the helm charts, and providing CI that ensure the manifests change when the helm charts are updated.

**Comment by gclawes** [comment]
It would be nice to provide several flavors of manifests, based on pre-set variations on `charts/metallb/values.yaml`. When helm packages a chart, only the `values.yaml` file really counts towards the chart's default values, but we can places other `values-<variant>.yaml` files in the same directory for convenience.
