### ISSUE TITLE
L2 Configuration: How to see which nodes is the "active node" for a cluster-ip

### ISSUE THREAD

**Issue by zenhighzer** [metallb/metallb#1085]
Hi there, hope your doing fine! 

I have a simple question about MetalLB / L2 Configuration: whats the best way to see which node is the "active" one for an IP which was mapped to a loadbalancer-service? I can do something like "curl to the service" , show the arp-cache and compare the arp-entry of service/load-balancer-ip to all nodes´ arp-entries...  but i wonder if there is a simpler way, like grepping pod-logs, etc. 

thanks and best regards! :-)

**Comment by fedepaol** [comment]
Hi @zenhighzer , only one announcer pod declares its announcing the service with a log like "announcing the service.. ".
Otherwise, if you have prometheus integrated, metallb exposes a "announced" metric that contains the service, the protocol, the node and the ip.
