### ISSUE TITLE
Unable to assign single IP

### ISSUE THREAD

**Issue by drisaro** [metallb/metallb#1102]
- The bug itself, as detailed as you can.
I'm not able to assign a single IP to MetalLB on L2 mode, or a set of hand picked IP's. Only pools
     - Version of MetalLB
v0.11.0
     - Version of Kubernetes
1.22
     - Name and version of network addon (e.g. Calico, Weave...)
Flannel
     - Whether you've configured kube-proxy for iptables or ipvs mode
Iptables
---

Hello.

To expand on the above. I'm implementing MetalLB v0.11.0 on a on-prem Kubernetes cluster v1.22. With Nginx as a Load Balancer. 
We currently don't have a lot of free IP's, and the infrastructure team has assigned a handpicked bunch (i.e. not consecutive). After applying the ConfigMap, Nginx is stuck on pending, no matter if I use only 1 IP, or all of the bunch.

I wasn't able to find anything on the documentation, or online regarding this, and I wasn't able to find any similar issue here.

Thanks

**Comment by thetillhoff** [comment]
I'm experiencing the very same. Using Calico though.

The configmap is created under the name `config`, but the speaker still logs `not processing, still waiting for config`.

Only occurs when using helm for the deployment. (Didn't test kustomize...)
Tested deployment by manifests, which worked fine.

**Comment by fedepaol** [comment]
@drisaro would you mind checking if you are experiencing the same issue as @thetillhoff ?

**Comment by drisaro** [comment]
Hello @fedepaol I checked the speaker logs, and it is the same as Thetillhoff said. 

`"event":"noConfig","msg":"not processing, still waiting for config","service":"ingress-nginx/ingress-nginx-controller"`

But I tried using `A.B.C.D/32` as the range, and it's assigning the correct IP address for the LoadBalancer. So I think this issue can be closed.

**Comment by fedepaol** [comment]
Thanks for confirming. Let's keep the issue open until we fix the bug.

**Comment by fedepaol** [comment]
Great. I am gonna close this @drisaro, will go out in the next release.
