### ISSUE TITLE
Signed releases / which image is the latest?

### ISSUE THREAD

**Issue by ita1024** [metallb/metallb#1107]
The [installation instructions](https://metallb.universe.tf/installation/) point to this file https://raw.githubusercontent.com/metallb/metallb/v0.11.0/manifests/metallb.yaml which is set to download data from `quay.io/metallb/controller:v0.11.0` and `quay.io/metallb/speaker:v0.11.0`. No hashes are provided, and the [ci job list](https://app.circleci.com/pipelines/github/metallb/metallb?branch=v0.11) does not indicate which files are intended to be downloaded. Also, the current tag listed on quay.io shows [12 known vulnerabilities](https://quay.io/repository/metallb/speaker/manifest/sha256:1293c1890bd21803b3537b8c2832afd6b7c94e0c0e1fc880db10f68da91a8c3a?tab=vulnerabilities).

While the project commits on github are signed, it is unclear which files are actually provided by the binary release. Are these the current hashes to use with release `v0.11.0`?
```
quay.io/metallb/speaker:v0.11.0@sha256:0809ad167894af62121db7d4158e5cf26705701f3bfcbb8b6be527fd3eac2886
quay.io/metallb/controller:v0.11.0@sha256:79062fe5d43211825ab6851f9b9deda71e3b7a075abf728c4ab11a0e1b2c850f
```

Alternatively, what are the commands to build the image locally? The file `.circleci/config.yml` seems to contain unpinned images as well.

**Comment by fedepaol** [comment]
Hi @ita1024 , quay auto builds images out of tags.
Each gh tag corresponds to a tag on quay, i.e v0.11.0 as you wrote corresponds to
sha256:0809ad167894af62121db7d4158e5cf26705701f3bfcbb8b6be527fd3eac2886 for the speaker and sha256:79062fe5d43211825ab6851f9b9deda71e3b7a075abf728c4ab11a0e1b2c850f for the controller.
You can check that on quay, i.e. https://quay.io/repository/metallb/controller?tab=tags

Re- building the images locally, you can use 
```
inv build --help
Usage: inv[oke] [--core-opts] build [--options] [other tasks here ...]

Docstring:
  Build MetalLB docker images.

Options:
  -a, --architectures            architectures to build. One or more of amd64, arm, arm64, ppc64le, s390x, or 'all'
  -b, --binaries                 binaries to build. One or more of controller, mirror-server, speaker, or 'all'
  -e STRING, --repo=STRING       Docker repository under which to tag the images. Default 'metallb'.
  -r STRING, --registry=STRING   Docker registry under which to tag the images. Default 'quay.io'.
  -t STRING, --tag=STRING        Docker image tag prefix to use. Actual tag will be <tag>-<arch>. Default 'dev'.
```
