### ISSUE TITLE
Enable pprof

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1121]
In order to understand performance hits, it would be beneficial to enable pprof (even accessible from inside the pod only).

**Comment by shivamanipatil** [comment]
Hey @fedepaol can I work on this issue?

**Comment by shivamanipatil** [comment]
Hey @fedepaol  I am a beginner so I was trying to run the project in development environment mode and examining the code base. 
After looking at the code I am seeing the Frr metrics are being exposed at /metrics HTTP endpoint by Prometheus but this exporter binary is placed inside speaker pods. So to test it I had to exec into one of the speaker pod and then run this frr-metrics binary and I could access some metrics at (docker-worker-node-for-speaker-ip):7473/metrics. 
As I understand there seems to be 2 main binaries controller and speaker for which I assume pprof is needed. 
Could you please elaborate a little bit about leveraging the existing listener for metrics? 
Also have I followed the flow correctly?

Thank you

**Comment by fedepaol** [comment]
I'd leave the exporter binary aside for the moment, and focus on the controller and the speaker.
I'd leverage this https://github.com/metallb/metallb/blob/7a35db7fe83ae3b40046429b54116484388a60f3/internal/k8s/k8s.go#L315 to append also the pprof listener.

You can use this https://github.com/ovn-org/ovn-kubernetes/blob/999f4fbf70e9ba568a03d0c7f92735fed1c823b0/go-controller/pkg/metrics/metrics.go#L371 as an example on how that was done in another project.

We must have a parameter to enable pprof, especially since in a hostNetworked container we don't want to have the pprof port open in the wild.

**Comment by shivamanipatil** [comment]
I have created a draft pull request with parameterized option to enable pprof as you suggested. Are these changes in right direction? Also, can anything more be added here? 

Thank you,

**Comment by fedepaol** [comment]
Closed by #1131
