### ISSUE TITLE
Layer 2 mode failover is slow/not working as expected

### ISSUE THREAD

**Issue by pupseba** [metallb/metallb#1147]
Hi,

We are testing MetalLB functionality and we notice (random?) situations  where IPs fail to failover leading to outages of any service exposed by it.

In our current testing cluster we have:
5 Kubernetes worker nodes ([w01-05])
3 nodes with "metallb" label
MetalLB speaker configured as a DaemonSet with nodeSelector "metallb"
3 IPs for testing (x.x.x.[201-203])

During normal behaivour, node w01 holds one IP (203) and nodes w02 holds the two other IPs (201 and 202). Node w03 is not holding any IP.

If we remove label "metallb" from w01 and w02, we assume all the IPs to be failedover to w03 (the only one with the proper label in place and thus, the only one with a metallb-speaker running on it).

What happens is that not all the IPs get into the node. In previous tests, we managed to do that by restarting the controller and the speaker in pods...after 15 minutes of wait. In other tests, IPs took as long as 18 minutes to be reassigned to the node without our intervention.

We do not see any log either in metallb-controller or metallb-speaker showing any particular action or anything changing.

We can't consistenly reproduce this error, same test, "sometimes" it works. We tested this with the controller scaled to "0" and with controller scalled to "1" (normal operation) and results do not seem to be altered by this.

Is there anything that we could check to see what is happening?

**Comment by fedepaol** [comment]
When failover happens, the speaker sends (or should send) a gratuitous arp to announce that the new node is holding the ip.
The logs of the speaker pods should help us to understand if this happens or not.

**Comment by pupseba** [comment]
Right now is failing again. I issued the command to remove the label from 2 out of the 3 nodes with "metallb" label so only one speaker pod was running. 2 out of the 3 IPs are responding just fine (201 and 203), but 202 is still not reacheable via ARPING (nor the service that it exposes). We can see in the speaker logs that it does seems to announce it

Command was issued at 10:51:54 (09:51:54 utc matching speaker logs)

`[pod/metallb-speaker-rl64r/speaker] {"caller":"level.go:63","event":"serviceAnnounced","ip":"10.147.52.202","level":"info","msg":"service has IP, announcing","pool":"system-components","protocol":"layer2","service":"metallb-system/ambassador-lb","ts":"2021-12-23T09:51:55.23388201Z"}
`

So it seems the speaker takes "1 second" to announce? but still, right now over 35 minutes passed and we can't reach that IP by any means. The other 2 work just perfect.

**Comment by fedepaol** [comment]
Other things:
There should be a `gratuitous_sent` metric saying if a gratuitous arp was sent for a particular IP.
Another thing to check is a tcpdump to see if that was actually sent (and received on the client side). 

It could be that some anti-mac spoofing mechanism prevents that to be handled.

**Comment by pupseba** [comment]
Metrics confirm that the announcement is done. We are checking on the networking side to see if some rule to avoid "flapping macs" is being the reason behind this.

![image](https://user-images.githubusercontent.com/38133294/147231016-5cbe8400-7503-4dca-9a07-88d55f0575f9.png)


At the time of testing, we were looking at tcpdump but only on the client side. We'll change this.

**Comment by fedepaol** [comment]
Hi @pupseba , do you have any updates on this issue?

**Comment by pupseba** [comment]
Hi! Yes, although not conclusive yet thus the lack of update so far here. We belive that the problem is related to our networking configuration itslef and how ARP is allowed. Next week I'll get the change to talk with networking guys, but ARP flooding options and GARP configuration seems to be the responsible for this behaviour. I'll update this issue as soon as possible (hopefully next week) so for completness, we have all the info in here. Although at this point, it seems pretty clear is not a metallb issue and this could be safely closed if you prefer.

**Comment by fedepaol** [comment]
Cool, I am going to close the issue, feel free to reopen it if something pointing at metallb arises.
