### ISSUE TITLE
layer 2模式部署metallb测试，speaker日志报错

### ISSUE THREAD

**Issue by chengtg520** [metallb/metallb#1151]
kubectl logs -n metallb-system pod/speaker-gn4k5
{"branch":"v0.11.0","caller":"level.go:63","commit":"846c55a","goversion":"gc / go1.17.2 / amd64","level":"info","msg":"MetalLB speaker starting version 0.11.0 (commit 846c55a, branch v0.11.0)","ts":"2021-12-27T12:20:43.58710626Z","version":"0.11.0"}
{"caller":"level.go:63","error":"creating ARP responder for \"eth0\": operation not permitted","interface":"eth0","level":"error","msg":"failed to create ARP responder","op":"createARPResponder","ts":"2021-12-27T12:20:43.596594838Z"}
{"caller":"level.go:63","level":"info","msg":"using endpoint slices","op":"New","ts":"2021-12-27T12:20:43.614150924Z"}
{"caller":"level.go:63","level":"info","msg":"node event - forcing sync","node addr":"192.168.10.235","node event":"NodeJoin","node name":"worker01","ts":"2021-12-27T12:20:43.646783901Z"}
{"caller":"level.go:63","level":"info","msg":"node event - forcing sync","node addr":"192.168.10.232","node event":"NodeJoin","node name":"master01","ts":"2021-12-27T12:20:43.646907042Z"}
{"caller":"level.go:63","level":"info","msg":"node event - forcing sync","node addr":"192.168.10.233","node event":"NodeJoin","node name":"master02","ts":"2021-12-27T12:20:43.64692026Z"}
{"caller":"level.go:63","configmap":"metallb-system/config","event":"configLoaded","level":"info","msg":"config (re)loaded","ts":"2021-12-27T12:20:43.749140388Z"}
{"caller":"level.go:63","event":"nodeLabelsChanged","level":"info","msg":"Node labels changed, resyncing BGP peers","ts":"2021-12-27T12:20:43.749222684Z"}
{"caller":"level.go:63","level":"info","msg":"triggering discovery","op":"memberDiscovery","ts":"2021-12-27T12:20:43.749236506Z"}
{"caller":"level.go:63","error":"3 errors occurred:\n\t* Failed to join 192.168.10.234: dial tcp 192.168.10.234:7946: connect: connection refused\n\t* Failed to join 192.168.10.236: dial tcp 192.168.10.236:7946: connect: connection refused\n\t* Failed to join 192.168.10.237: dial tcp 192.168.10.237:7946: connect: connection refused\n\n","expected":3,"joined":0,"level":"error","msg":"partial join","op":"memberDiscovery","ts":"2021-12-27T12:20:43.752355742Z"}
{"caller":"level.go:63","level":"info","msg":"node event - forcing sync","node addr":"192.168.10.234","node event":"NodeJoin","node name":"master03","ts":"2021-12-27T12:20:43.970371349Z"}
{"caller":"level.go:63","level":"info","msg":"node event - forcing sync","node addr":"192.168.10.237","node event":"NodeJoin","node name":"worker03","ts":"2021-12-27T12:20:44.077523649Z"}
{"caller":"level.go:63","level":"info","msg":"node event - forcing sync","node addr":"192.168.10.236","node event":"NodeJoin","node name":"worker02","ts":"2021-12-27T12:20:44.077615662Z"}
{"caller":"level.go:63","error":"creating ARP responder for \"eth0\": operation not permitted","interface":"eth0","level":"error","msg":"failed to create ARP responder","op":"createARPResponder","ts":"2021-12-27T12:20:53.599295251Z"}
{"caller":"level.go:63","error":"creating ARP responder for \"eth0\": operation not permitted","interface":"eth0","level":"error","msg":"failed to create ARP responder","op":"createARPResponder","ts":"2021-12-27T12:21:03.601460894Z"}
{"caller":"level.go:63","error":"creating ARP responder for \"eth0\": operation not permitted","interface":"eth0","level":"error","msg":"failed to create ARP responder","op":"createARPResponder","ts":"2021-12-27T12:21:13.604559924Z"}
{"caller":"level.go:63","error":"creating ARP responder for \"eth0\": operation not permitted","interface":"eth0","level":"error","msg":"failed to create ARP responder","op":"createARPResponder","ts":"2021-12-27T12:21:23.607867166Z"}
{"caller":"level.go:63","error":"creating ARP responder for \"eth0\": operation not permitted","interface":"eth0","level":"error","msg":"failed to create ARP responder","op":"createARPResponder","ts":"2021-12-27T12:21:33.611057619Z"}
{"caller":"level.go:63","level":"info","msg":"triggering discovery","op":"memberDiscovery","ts":"2021-12-27T12:21:40.894773752Z"}
{"caller":"level.go:63","error":"creating ARP responder for \"eth0\": operation not permitted","interface":"eth0","level":"error","msg":"failed to create ARP responder","op":"createARPResponder","ts":"2021-12-27T12:21:43.614166791Z"}
{"caller":"level.go:63","error":"creating ARP responder for \"eth0\": operation not permitted","interface":"eth0","level":"error","msg":"failed to create ARP responder","op":"createARPResponder","ts":"2021-12-27T12:21:53.616799654Z"}
{"caller":"level.go:63","error":"creating ARP responder for \"eth0\": operation not permitted","interface":"eth0","level":"error","msg":"failed to create ARP responder","op":"createARPResponder","ts":"2021-12-27T12:22:03.620457365Z"}
{"caller":"level.go:63","error":"creating ARP responder for \"eth0\": operation not permitted","interface":"eth0","level":"error","msg":"failed to create ARP responder","op":"createARPResponder","ts":"2021-12-27T12:22:13.623397781Z"}

**Comment by fedepaol** [comment]
Can you add more details on what's happening, and what cluster are you running metallb on?
A get pods -o yaml of the speaker would help as well, looks like a net capability issue.

**Comment by fedepaol** [comment]
Closing this, feel free to reopen when providing the requested info.

**Comment by gfppower** [comment]
我也遇到这个问题，大佬怎么解决的？

**Comment by baozitao** [comment]
同样也遇到问题，如何解决？

**Comment by GYMmaorui** [comment]
没有权限，让speaker用root启动即可
```yaml
spec:
  securityContext:
    runAsUser: 0
```
