### ISSUE TITLE
Dual stack service not getting IPs assigned

### ISSUE THREAD

**Issue by PKizzle** [metallb/metallb#1156]
Used versions:
- docker.io/metallb/controller: main
- docker.io/metallb/speaker: main

I have configured two layer2 address pools. One for IPv4 and one for IPv6.
When setting `ipFamilyPolicy: SingleStack` the services receive an IP address from metallb.
It works for IPv4 and IPv6 individually by specifying `ipFamilies`.

However `ipFamilyPolicy: PreferDualStack` results in the `no available IPs` error message.
Since support for dual stack was merged already (#1065) this must be a bug.

**Comment by fedepaol** [comment]
I think the way dual stack works is by choosing the v4 and v6 addresses from the same pool, so you need to have a single pool with both the ranges. Mind trying?

**Comment by PKizzle** [comment]
Thank you very much. Changing the two pools to one works!
I guess the missing documentation for this feature was the problem here.
Is there already an issue for adding the documentation to dual stack or providing an example?

**Comment by fedepaol** [comment]
> Thank you very much. Changing the two pools to one works! I guess the missing documentation for this feature was the problem here. Is there already an issue for adding the documentation to dual stack or providing an example?

There's no doc yet as it's not officially out yet. We added a bunch of changes in the version currently being developed, and the documentation will be updated to reflect all of those.
