### ISSUE TITLE
Option to listen on specific IP address

### ISSUE THREAD

**Issue by kevin-lindsay-1** [metallb/metallb#1159]
I use WSL2 for local development at home, while also running certain services at home to manage my home network and so forth. The idea is to expose load balanced services on a "k8s" IP address, and then do things like run local tooling services and k8s port forwards on my "development" IP address.

Right now I use `x.x.x.11` for my local development, and metallb is set to listen on `x.x.x.12`. However, metallb binds to `::<port>`, which prevents me from using that port on `.11`, even though I set metallb to listen on `.12` specifically in an attempt to separate out the ports.

As a result, if I attempt to use `kubectl port-forward` on `8080` into the services I'm developing on (probably the most sought-after port these days), I have to not use that port, even though I'm specifically trying to connect to it from Windows via `.11` on that port, which is being used by another service running on `.12`.

It would be really nice to be able to simply state on an address pool to bind on the host to specific IPs, rather than `::`.

**Comment by fedepaol** [comment]
Hi @kevin-lindsay-1 , I am assuming you are talking about l2 metallb.
Not sure what port you refer to. MetalLB only advertises the ip around replying to ARP requests, then the load balancer service has a port associated with that.

When it comes to the port used by the load balancer service, that is handled entirely by your cluster's CNI and metallb is out of scope.
Hope it helps.

**Comment by kevin-lindsay-1** [comment]
@fedepaol According to the [docs](https://metallb.universe.tf/faq/#in-layer-2-mode-how-to-specify-the-host-interface-for-an-address-pool), metallb is the thing binding to the host's interfaces.

When it does so, it listens on a specific port defined by my kubernetes service, however the IP address it listens on _on the host_ always appears to be `::`.

I would like to be able to change `::` to the IP address of the address pool, for example.

So, on the host for port `8080`, rather than listening on `::8080`, it would listen on `x.x.x.11`, which should be an IP address that the host has available to it, which I would have to ensure.

This would allow me to use dual IPs, listening on ports per IP, for different use cases/services.

**Comment by kevin-lindsay-1** [comment]
Sorry, I'm disputing anything you're saying, but what's actually listening on the port? On the host, the port is being listened on, and it's due to my metallb config that it's doing that.

Are you saying that metallb doesn't perform the operations that actually cause the host to listen on that port? If so, is there a way to tell whatever is performing the "listening", to listen on a specific IP, rather than `::`?

I guess I'm asking for this clarification because the verbiage in the FAQ specifically says that Metallb is the thing doing the "listening". It says the exact words "MetalLB automatically listens/advertises on all interfaces".

So to me, that sounds like it's using all interfaces, sure, but I'm not asking for that behavior to be different, I'm just asking for different IPs to be listened to on the host.

If the CNI is the thing that's actually opening the port on the host, is there an annotation or something that you can set on a service to have the CNI listen on a specific IP?

I'm not 100% sure which layer this exact functionality lives on, but I'm raising the issue in metallb because I'm only seeing this issue because metallb has gotten me to the point where I'm looking for this functionality.

**Comment by kevin-lindsay-1** [comment]
Okay so I'm using docker for desktop, so I'll have to see what CNI it's using, and hope that it has some kind of way to provide this annotation on the `Service`.

I'll close this issue and follow up in future if I find an annotation or something that causes the behavior I'm looking for.

**Comment by fedepaol** [comment]
One last note, when I talk about CNI I mean the one used by your k8s cluster (which I am not sure is provided by docker desktop)

**Comment by kevin-lindsay-1** [comment]
/shrug well, it sounds like that's going to be a fun rabbit hole to go down.
