### ISSUE TITLE
Next release date - release cycle

### ISSUE THREAD

**Issue by thetillhoff** [metallb/metallb#1170]
Is there something like a progress tracker on when the next release(s) will happen?
Can't wait for it 🤟

**Comment by fedepaol** [comment]
Hi @thetillhoff , next release will be pretty packed in content.

We discussed cutting off a new release in yesterday's community meeting.
We need a couple of fixes to get in (most notable https://github.com/metallb/metallb/pull/1172 ) and the docs, which I am currently working on. I would say a couple of weeks at most, and a new release will be available.
