### ISSUE TITLE
Notice: Service.Spec.LoadBalancerIP being deprecated in v1.24

### ISSUE THREAD

**Issue by danmanners** [metallb/metallb#1182]
Hey folks, my apologies if this is the wrong place for this. Just saw this open issue and realized I've used this functionality in the past. [`Service.Spec.LoadBalancerIP` functionality is being deprecated in Kubernetes v1.24](https://github.com/kubernetes/kubernetes/pull/107235), and it may be worth updating docs and/or deprecating support for that feature in MetalLB.

If this is the wrong place to put this, feel free to close the issue, and my sincere apologies!

**Comment by fedepaol** [comment]
Hi @danmanners , thanks for raising this! We are aware and taking initiative in https://github.com/metallb/metallb/pull/1174 which is gonna converge soon (and likely before 1.24 lands).

**Comment by danmanners** [comment]
Awesome, totally missed it here (https://github.com/metallb/metallb/pull/1174#issuecomment-1016977109).

Keep up the awesome work, I love MetalLB!

**Comment by fedepaol** [comment]
Closing this, since https://github.com/metallb/metallb/pull/1174 is merged AND released.

**Comment by aojea** [comment]
Just FYI, Deprecated doesn't mean it is going to be dropped https://github.com/kubernetes/kubernetes/pull/107235#issuecomment-1320020675
