### ISSUE TITLE
Add a new lane for deploying metallb via the operator and running e2e in operator mode

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1185]
No need to have the full coverage.
A simple lane with ipv4 + frr that deploys metallb via the operator using the manifests and run e2e to make sure operator mode is solid.

**Comment by fedepaol** [comment]
The operator's manifests are https://github.com/metallb/metallb-operator/tree/main/bin

**Comment by fedepaol** [comment]
To checkout the operator, something similar to https://github.com/metallb/metallb-operator/blob/main/.github/workflows/metallb_e2e.yml#L24 can be done

**Comment by pperiyasamy** [comment]
@fedepaol I'll work on this.
