### ISSUE TITLE
Workaround for calico/BGP for small scale users

### ISSUE THREAD

**Issue by gdhaworth** [metallb/metallb#1199]
I'm running k8s at home and I have only a single router (TOR or otherwise). I do have a spare raspberry pi that was running other parts of my network though so I used frrouting to come up with a way around the BGP problem. I'm not sure if you'd be interested in this but I imagine there are a few lost homelab admins out there who might find this useful. I set up docker to run frrouting using the files here: https://gist.github.com/gdhaworth/9f1819d46e0af989dcae87aa6cf3e429 and pointed calico at that instead. It's not revolutionary (and its statically configured) but figured I'd put it out there.

**Comment by fedepaol** [comment]
Closing this as it doesn't seem a metallb issue
