### ISSUE TITLE
Dump e2e tests failure information to a file

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1200]
CI runs are hard to analyze.

We could benefit from to a file named after the test:
- all the frr information we dump to the standard output 
- the config (and eventually the crds)
- the service definition
- the last logs of the speakers
- the last logs of the controller

And in general any information that could be useful for debugging
An even better option would be to have a folder named after the test and the information above split in different files.

**Comment by manikanth04** [comment]
@fedepaol i am interested to work on this.

**Comment by fedepaol** [comment]
@manikanth04 cool!

Couple of things:
- I am working on making a go library out of a thing we did for this very specific purpouse (https://github.com/openshift-kni/k8sreporter). See the first open pr, I thing that will help in doing what's needed this (after that PR merges and we cut a tag).
- The right place were to hook into is https://github.com/metallb/metallb/blob/27fc90150c033e006dc5330bc427b509d938ae64/e2etest/bgptests/bgp.go#L63

Please start have a look, I am gonna assign you to this issue. Come over to `#metallb-dev` channel of the k8s slack if you need any help on this.

**Comment by fedepaol** [comment]
@manikanth04 just checking, are you still interested to work on this?
Thanks

**Comment by manikanth04** [comment]
@fedepaol yes, I am working on that

**Comment by fedepaol** [comment]
@manikanth04 re-assigned this to me as this is becoming urgent and we need this.
