### ISSUE TITLE
Are IPV6 address pool advertisement supported using BGP

### ISSUE THREAD

**Issue by svallala** [metallb/metallb#1212]
K8s Version: v1.21.5
MetalLB Version: v0.11.0

configmap
------------
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: fdd2:337d:e558:13ca::1
      peer-asn: 63410
      my-asn: 63401
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - fdd2:337d:e558:13ca:10::020-fdd2:337d:e558:13ca:10::02f

I see that the BGP connections are established with the peer router

routera# show bgp  summary
BGP router identifier 10.9.62.245, local AS number 63410
RIB entries 0, using 0 bytes of memory
Peers 3, using 13 KiB of memory

Neighbor        V    AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
fdd2:337d:e558:13ca::244
                4 63401     136     162        0    0    0 00:11:00        0
fdd2:337d:e558:13ca::245
                4 63401      57      95        0    0    0 00:10:49        0
fdd2:337d:e558:13ca::246
                4 63401     128     149        0    0    0 00:10:45        0

But the Load Balancer IP allocated is not advertised to the peer

[root@cscale-82-244 ~]# kubectl get svc
NAME         TYPE           CLUSTER-IP                          EXTERNAL-IP                  PORT(S)        AGE
kubernetes   ClusterIP      fd74:ca9b:3a09:868c:172:18:0:8001   <none>                       443/TCP        4h31m
nginx        LoadBalancer   fd74:ca9b:3a09:868c:172:18:0:a9ce   fdd2:337d:e558:13ca:10::20   80:30832/TCP   15m

I see the following error in the speaker logs

{"caller":"level.go:63","error":"cannot advertise non-v4 prefix \"\u003cnil\u003e\"","ip":"fdd2:337d:e558:13ca:10::20","level":"error","msg":"failed to announce service","op":"setBalancer","pool":"default","protocol":"bgp","service":"default/nginx","ts":"2022-02-05T08:38:27.8499757Z"}

Is this configuration supported?

Thanks

**Comment by fedepaol** [comment]
Hi @svallala , ipv6 is not currently supported in BGP.
The upcoming release (which is going to be released roughly this week) will ship an experimental FRR mode which will support it (and dual stack too).

**Comment by svallala** [comment]
> Hi @svallala , ipv6 is not currently supported in BGP. The upcoming release (which is going to be released roughly this week) will ship an experimental FRR mode which will support it (and dual stack too).

@fedepaol Thanks for the response.
