### ISSUE TITLE
frr images on quay are not multiarch

### ISSUE THREAD

**Issue by nberlee** [metallb/metallb#1216]
on an ARM platform metallb-frr.yaml fails because FRR containers output:
```
standard_init_linux.go:228: exec user process caused: exec format error
```
This is because the frr contrainer images on quay.io are not multiarch. Meaning they are only published for x86_64. Swapping the container registry for docker hub in the manifests actually works.

So please consider asking frr to publish the now old FRR 7.5 as an multi-arch manifest on quay, or change the container registry to dockerhub (which does have a 7.5.1 tag with arm support)

**Comment by fedepaol** [comment]
Filed https://github.com/FRRouting/frr/issues/10587

**Comment by fedepaol** [comment]
Thanks @nberlee for reporting this!

**Comment by anthr76** [comment]
Considering the dockerhub variant is multiarch should we consider switching to that for now?

**Comment by fedepaol** [comment]
> Considering the dockerhub variant is multiarch should we consider switching to that for now?

I wanted to give the frr folks some time to elaborate our issue, just to avoid doing another release for this, but that's the other only viable solution.

**Comment by fedepaol** [comment]
Closing this, we reverted using dockerhub
