### ISSUE TITLE
Charts.yaml is missing when installing from terraform helm provider in submodule

### ISSUE THREAD

**Issue by ivanov-slk** [metallb/metallb#1233]
terraform: 
```
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/bmatcuk/vagrant v4.1.0
+ provider registry.terraform.io/gavinbunney/kubectl v1.13.1
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

helm:
```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

MetalLB:
downloading helm chart from `https://metallb.github.io/metallb`.

Running on Ubuntu 20.04.

____________________

I am having a problem when trying to install MetalLB with Terraform and Helm. The error I am getting is `Chart.yaml file is missing`.
I get this error when MetalLB configuration is in Terraform submodule. If I put the Terraform resources in the root module it runs fine. I can install another Helm chart from a submodule, tested with bitnami/apache.

My setup is as follows:

./main.tf
```
terraform {
  required_providers {
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.7.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = ">= 2.4.1"
    }
    external = {
      source  = "hashicorp/external"
      version = ">=2.2.0"
    }
  }
}

provider "kubectl" {
  load_config_file = true
}

provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}

module "metallb" {
  source = "./metallb"
}
```

./metallb/main.tf
```
terraform {
  required_providers {

    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.7.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = ">= 2.4.1"
    }
    external = {
      source  = "hashicorp/external"
      version = ">=2.2.0"
    }
  }
}

provider "kubectl" {
  load_config_file = true
}

provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}

resource "kubectl_manifest" "metallb_namespace" {
  yaml_body = file("./metallb/namespace_metallb.yaml")
}

resource "helm_release" "metallb" {
  name       = "metallb"
  repository = "https://metallb.github.io/metallb"
  chart      = "metallb"

  timeout         = 120
  cleanup_on_fail = true
  force_update    = true
  namespace       = "metallb-system"

  depends_on = [kubectl_manifest.metallb_namespace]
}

resource "kubectl_manifest" "metallb_configmap" {
  yaml_body = file("./metallb/configmap_metallb.yaml")

  depends_on = [helm_release.metallb]
}
```

./metallb/configmap_metallb.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.50.240-192.168.50.250
```

./metallb/namespace_metallb.yaml
```
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
```

**Comment by fedepaol** [comment]
Hey @ivanov-slk , sorry but I miss knowledge on the terraform side to understand what's missing.
As you describe, if metallb is not working as a submodule but another chart is, we are probably missing something (which is not the Chart.yaml, as it's there). Would it be possible to reach the terraform provider maintainers and get some insights on what we are doing wrong so we can fix?

Thanks

**Comment by fedepaol** [comment]
@ivanov-slk do you have any updates on this?

**Comment by ivanov-slk** [comment]
All right, I got this working by manually downloading and compiling the `main` branch of [the helm provider](https://github.com/hashicorp/terraform-provider-helm). I suspect that it has something to do with `helm` versions. For reference, here is [the issue](https://github.com/hashicorp/terraform-provider-helm/issues/831).

**Comment by fedepaol** [comment]
Closing the issue, missed this.
