### ISSUE TITLE
frr-reloader fails: vtysh (frr): line 4: % Command incomplete: domainname

### ISSUE THREAD

**Issue by nberlee** [metallb/metallb#1241]
Using metallb 0.12.1, with kubernetes 1.23.3, using minimal changes to  `manifests/example-config.yaml` and `manifest/metallb-frr.yaml`, reloader fails:

```
PID is: 60, writing to /etc/frr_reloader/reloader.pid
Caught SIGHUP and acquired lock! Reloading FRR..
Checking the configuration file syntax
/usr/lib/frr/frr-reload.py:805: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if line is not "exit-vrf":
2022-02-27 00:01:35,231  INFO: Called via "Namespace(bindir='/usr/bin', confdir='/etc/frr', daemon='', debug=False, filename='/etc/frr_reloader/frr.conf', input=None, log_level='info', overwrite=False, pathspace=None, reload=False, rundir='/var/run/frr', stdout=True, test=True, vty_socket=None)"
2022-02-27 00:01:35,232  INFO: Loading Config object from file /etc/frr_reloader/frr.conf
2022-02-27 00:01:35,531  INFO: Loading Config object from vtysh show running
line 4: % Command incomplete: domainname

Traceback (most recent call last):
  File "/usr/lib/frr/frr-reload.py", line 1390, in <module>
    running.load_from_show_running(args.daemon)
  File "/usr/lib/frr/frr-reload.py", line 270, in load_from_show_running
    config_text = self.vtysh.mark_show_run(daemon)
  File "/usr/lib/frr/frr-reload.py", line 162, in mark_show_run
    raise VtyshException('vtysh (mark running-config) exited with status %d'
__main__.VtyshException: vtysh (mark running-config) exited with status 4
Syntax error spotted: aborting..
```
to make a functional config I had to make a few changes: (just enumerating here for replication purposes)

`metallb-frr.yaml` changes: (for arm compatibilty and version pinning)
* `image: quay.io/frrouting/frr:stable_7.5` --> `image: frrouting/frr:v7.5.1`
* `image: quay.io/metallb/speaker:main` --> `image: quay.io/metallb/speaker:v0.12.1`

`example-config.yaml` changes (bear minimum to get accepted by controller and start reloading):
```
39d38
<       bfdProfile: "bfdProfile1"
42c41
<       ebgp-multihop: true
---
>       ebgp-multihop: false
50,58d48
<       node-selectors:
<       - # Match by label=value
<         match-labels:
<           kubernetes.io/hostname: prod-01
<         # Match by 'key OP values' expressions
<         match-expressions:
<         - key: beta.kubernetes.io/arch
<           operator: In
<           values: [amd64, arm]
```

**Comment by nberlee** [comment]
Hmm.. setting a domainname on the kubernetes host made it work.

**Comment by fedepaol** [comment]
> Hmm.. setting a domainname on the kubernetes linux host made it work. I was unaware of this requirement

So, the issue was the domain name only right? Not what you added in the first comment?

**Comment by nberlee** [comment]
> So, the issue was the domain name only right? Not what you added in the first comment?

Not having a domain name on the kubernetes node generates this unexpected error.

I am unsure where the empty `domainname` statement comes from. As it does not seems to be in `internals/bgp/frr` but once I set a domain name on the node, the `domainname localdomain` statement is there on line 4 looking at `/etc/frr/frr.conf` in the frr container.

**Comment by fedepaol** [comment]
Yes, must be something that frr defaults with the domainname if not provided from outside, likely easy to override with the node name.
We'll try to fix it.

**Comment by nberlee** [comment]
This was fixed upstream. https://github.com/FRRouting/frr/pull/11067

So once frr gets updated in metallb this issue can be closed

**Comment by nberlee** [comment]
Tested it with frr 8.5 images, and its fixed...

This issue can be closed when FRR is updated...

**Comment by zacheryph** [comment]
I started hitting this when I upgraded from `0.13.9 -> 0.13.10`. Zero problems with .9, nothing works with .10.

**Comment by fedepaol** [comment]
> I started hitting this when I upgraded from `0.13.9 -> 0.13.10`. Zero problems with .9, nothing works with .10.
> 
> _EDIT:_ After looking at the release noted I noticed this. It seems like a rather large change for a mere patch version update of the chart?
> 
> > _- Make the FRR mode the default one when deploying via charts ([PR 1931](https://github.com/metallb/metallb/pull/1931))_

well it was supposed to be backward compatible, and all the efforts are going into the FRR direction. We could've probably change the middle version, but would've that make a difference?
In any case, we can certainly make this more robust. Until now @nberlee was the only one affected and he had a workaround.

**Comment by zacheryph** [comment]
@fedepaol yeah its alright, was just unexpected.  I actually updated to 0.13.10 and forced the frr image to 8.5.1 and everything is working good :)

**Comment by craisis** [comment]
I also ran into this issue recently. It looks like FRR's latest docker build, 8.5.1, does include the upstream fix.  Bumping that up from 8.4.2 as the image for the frr image solved it for me.

**Comment by si458** [comment]
ive encounted this bug as well with talos, since the helm chart changed to FRR as default,
i needed to update the FRR version to fix the domainname issue too so i have submitted a PR
