### ISSUE TITLE
Proposal: enable service / hostname resolution

### ISSUE THREAD

**Issue by jreamy** [metallb/metallb#1243]
I've started using metallb in my homelab and it work's great for getting IP addresses with standard ports for services I'm developing. I'd really like to get some form of hostname resolution working as well either using avahi or directly responding to mdns hostname queries (or some other method I haven't tried). I'm hoping for something more plug & play than having to configure my router or anything.

What I've learned so far:
 - the avahi route I've tried makes the hostnames resolvable on the same machine, but I haven't gotten them resolvable from a separate machine
 - the mdns route I've tried would require enabling multicast within the entire cluster -- not something that's very plug & play

I'm interested in helping get this working if others have ideas / thoughts on how it could work? Thanks!

**Comment by Adphi** [comment]
Have you looked at [the k8s external core dns plugin](https://coredns.io/plugins/k8s_external/) ?

**Comment by Expro** [comment]
[k8s gateway](https://github.com/ori-edge/k8s_gateway) is superior.

**Comment by fedepaol** [comment]
If the integration with the two aforementioned projects is good, I'd convert this to documenting the usage somehow.

**Comment by m-yosefpor** [comment]
We have a working setup with metallb+k8s_external coredns plugin and now we can resolve svc hostnames. However I need to be able to set this hostname on service.Status so that it is shown when listing services:

```
$ oc get svc
example-svc      LoadBalancer   172.30.230.151   172.21.34.237,my-svc.my-ns.svc.example.com   8080:31153/TCP      25m
```

I have another controller which can write `service.status.loadBalancer.ingress[].hostname` however it is reverted when metallb controller is running. As a feature request, I would like metallb to ignore hostnames on status and only work with  `ingress[].ip` instead, and leaves `hostnames` intact.

**Comment by zargony** [comment]
Came here to suggest something similar. For homelab setups, it'd be super convenient if services could optionally get static mdns hostnames. E.g. using an annotation like `metallb.universe.tf/mdnsHostName: myservice` could announce `myservice.local` and therefore make the service reachable easily via name from within the local network. Sure you can configure and run an avahi instance to do the same, but this would be so much easier (and e.g. could announce it only when it's ready)

It sounds like all that would be needed is metallb speakers responding to mdns broadcasts on the host network, which doesn't sound too hard. Unfortunately my go skills are too low to implement it and submit a PR, but if anyone is going to give it a try, I'll be happy to help with testing.

Going further, it could also be nice to eventually also add mdns service discovery, e.g. with `metallb.universe.tf/mdnsServiceName: MyService` and `metallb.universe.tf/mdnsServiceType: http`, you'd get mdns / zeroconf service discovery of `MyService._http._tcp.local` as PTR/SRV to `myservice.local`, and maybe optional TXT entry from another annotation.

**Comment by fedepaol** [comment]
closing this as it seems a bit out of metallb scope.
Open to engage a discussion, but as I wrote seems more for an external controller.
