### ISSUE TITLE
metallb chart not available on metallb.github.io/metallb

### ISSUE THREAD

**Issue by Eagleman7** [metallb/metallb#1246]
Page returns a 404, cannot use the metallb chart repository for installing metallb through Helm.

Or maybe documentation is wrong? https://metallb.universe.tf/installation/#installation-with-helm

**Comment by tylerauerbeck** [comment]
@Eagleman7 Was just checking this. After following the docs, I was able to see the chart without any issue:

```bash
╰─ helm repo add metallb https://metallb.github.io/metallb
"metallb" has been added to your repositories

╰─ helm search repo metallb
NAME           	CHART VERSION	APP VERSION	DESCRIPTION
metallb/metallb	0.12.1       	v0.12.1    	A network load-balancer implementation for Kube...
```

**Comment by fedepaol** [comment]
Cloising this, feel free to reopen in case something is missing
