### ISSUE TITLE
How to find assigned IP in MetalLB?

### ISSUE THREAD

**Issue by ipeacocks** [metallb/metallb#1248]
I've installed MetalLB and it's working fine in layer 2 mode. Official documentation says:
```
Keepalived and MetalLB “look” the same from the client’s perspective: the service IP address seems to migrate from one machine to another when a failover occurs, and the rest of the time it just looks like machines have more than one IP address.
```
But I can't find MetalLB' IP on any k8s nodes. How to find it attached to network interface?

**Comment by fedepaol** [comment]
You won't. 
MetalLB works by replying to arp requests with the mac address of the interface the arp requests came in, but the ip is not assigned to any interface.
See https://metallb.universe.tf/concepts/layer2/ for more details.

**Comment by ipeacocks** [comment]
Thank you @fedepaol
