### ISSUE TITLE
[documentation] traffic split behavior when externalTrafficPolicy=local is documented incorrectly

### ISSUE THREAD

**Issue by rahulait** [metallb/metallb#1249]
Hi,

I am referring to this documentation: https://github.com/metallb/metallb/blob/main/website/content/usage/_index.md
```
For example, if your service has 2 pods running on node A and one pod running on node B, the Local traffic policy will send 50% of the service's traffic to each node. Node A will split the traffic it receives evenly between its two pods, so the final per-pod load distribution is 25% for each of node A's pods, and 50% for node B's pod. In contrast, if you used the Cluster traffic policy, each pod would receive 33% of the overall traffic.
```

It incorrectly states that the local traffic policy will send 50% of the service's traffic to each node. In case of externalTrafficPolicy=local, traffic is never sent outside of the node and all the traffic is sent to pods on the same node.

I have tested it and verified with my deployment of cilium + metallb that in case a service sets externalTrafficPolicy=local, the traffic is sent to pod on that node only. So based on the example in documentation, if a service has 2 pods running on node A and one pod running on node B, then based on one of the node which is advertising for the loadbalancer IP, all the traffic will go to pods running on that node only. If metallb-speaker on node A is advertising the loadbalancer IP, the traffic will be split 50% each to the two pods running on it. If node B is advertising for the loadbalancer IP, then 100% of the traffic will be sent to pod on node B.

**Comment by rahulait** [comment]
If this is with "BGP" mode only, then it makes sense as the router will load balance/split the traffic between the two nodes equally.

**Comment by fedepaol** [comment]
That is under the bgp section, so I think the documentation is not wrong.
See https://metallb.universe.tf/usage/#bgp
