### ISSUE TITLE
HEADS UP: Breaking changes in the MetalLB main branch

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1257]
We are in the process of implementing https://github.com/metallb/metallb/pull/942

The main branch is the development branch, and with merging [this PR](https://github.com/metallb/metallb/pull/1237) the configuration using the configmap was removed and the CRDs used currently in the metallb operator are the only way to configure metallb. This means that whoever is using metallb consuming main images may find their configuration is not working anymore.

Until the development settles I'd suggest to use the released version:
https://github.com/metallb/metallb/tree/v0.12.1

**Comment by sathieu** [comment]
What is the ETA of this new version?

**Comment by fedepaol** [comment]
@sathieu we are finishing the last details, doc is already up.
I'd say a couple of weeks at most

**Comment by fedepaol** [comment]
Also, if you want to have a look, the main branch is quite stable now.

**Comment by jr0dd** [comment]
Pull that trigger 😬

**Comment by fedepaol** [comment]
Done :o
