### ISSUE TITLE
Wrong image version for FRR manifests

### ISSUE THREAD

**Issue by Elettronik** [metallb/metallb#1265]
In the manifests relative to v0.12.1 (FRR release) the image used for metallb components, are tagged with main, not with version v01.12.1. 

https://github.com/metallb/metallb/blob/v0.12.1/manifests/metallb-frr.yaml

**Comment by fedepaol** [comment]
Good catch, I guess we are gonna do another release soon. Sorry about that.
In the meanwhile, a workaround is either replacing the images manually or use helm.

**Comment by dimm0** [comment]
> In the meanwhile, a workaround is either replacing the images manually or use helm.

Use helm from where? I'm trying to deploy FRR with IPV6 in some variant, and recent helm is still deploying 0.12.1 images with no IPV6 support...

**Comment by fedepaol** [comment]
@dimm0 0.12.1 already has frr support and ipv6 (I hope)

**Comment by fedepaol** [comment]
And this https://github.com/metallb/metallb/blob/v0.12.1/charts/metallb/values.yaml#L233 is the value to enable frr

**Comment by fedepaol** [comment]
Closing this, is fixed
