### ISSUE TITLE
Image publishing with github actions

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1278]
https://github.com/metallb/metallb/pull/1137 was translating the current publishing mechanism in circleci to github actions.
However, while trying to add the secrets to make the action added there work, I realized that those would have been dumped as part of the lane run.

It probably makes sense to look for gh actions that do the publishing for us, instead of manually doing `docker login` as the old circleci publishing job was doing.

Once that is merged and we see it passing successfully, we can retire the circle ci job.

Lastly, we realized image publishing to dockerhub is still in place, although all the current manifests are consuming images from quay.
For this reason, it makes sense to have the new job to publish only to quay and announce the retirement of the images hosted on dockerhub.

**Comment by fedepaol** [comment]
cc @tylerauerbeck , sorry for the change of mind. Please let me know if you have bandwidth / are willing to work on this (I can set the secrets), or I'll try.
https://github.com/marketplace/actions/push-to-registry and https://github.com/docker/build-push-action seem good candidates (maybe there are others, the latter seems only dockerhub oriented).

**Comment by tylerauerbeck** [comment]
@fedepaol No problem. I'll see if I can get to this over the next day or so.

**Comment by fedepaol** [comment]
Thanks a lot!

**Comment by fedepaol** [comment]
Hi @tylerauerbeck just checking back to this, mostly because circle lint lane is giving us headaches and I'd prefer to put energy in this instead.
Thanks!
