### ISSUE TITLE
When a controller's configuration reload fails, how do we know the error message, other than looking at the controller's pod logs? 

### ISSUE THREAD

**Issue by qingwusunny** [metallb/metallb#1284]
When a controller's configuration reload fails, how do we know the error message, other than looking at the controller's pod logs? Can be informed by events or status

**Comment by fedepaol** [comment]
Hi @qingwusunny , there's a config_stale_bool metric that should tell you if a config reload failed.
Also, now that we are transitioning to crds, a next step is to enhance them with a status field that is more explicit, plus some validation webhooks that would block syntactically wrong configurations.
