### ISSUE TITLE
Leverage Calico only BGP speaker with MetalLB

### ISSUE THREAD

**Issue by ivansharamok** [metallb/metallb#1298]
This is a suggestion for another solution to [issues with Calico](https://metallb.universe.tf/configuration/calico/) article.

Existing suggested solutions in the article outline ways to configure both Calico BGP and MetalLB BGP speakers to peer with network infrastructure. There is another way to configure service LoadBalancer route distribution using just the Calico BGP speaker. This simplifies configuration and doesn't require working around the duplicate BGP session issue.

The solution overview:

* modify MetalLB manifest to exclude deployment of resources related to BGP speaker
* configure Calico's [BGPConfiguration](https://projectcalico.docs.tigera.io/reference/resources/bgpconfig) resource to [advertise service LoadBalancer IP range](https://projectcalico.docs.tigera.io/networking/advertise-service-ips#advertise-service-load-balancer-ip-addresses) configured for MetalLB IP management
* configure Calico's [BGPPeer](https://projectcalico.docs.tigera.io/reference/resources/bgppeer) resource to [peer Kubernetes cluster with on-prem network](https://projectcalico.docs.tigera.io/networking/bgp) infrastructure

**Comment by fedepaol** [comment]
Hi @ivansharamok , with the new configuration layout described in https://github.com/metallb/metallb/blob/main/design/pool-configuration.md , it will be possible to define only the ip assignement part without the need of removing the speakers.

So there will no need to remove the speakers (apart from resource consumption).

Also, there's an open pr to extend the docs about calico (https://github.com/metallb/metallb/pull/1103) which did never followed up.

**Comment by fedepaol** [comment]
Closing this, feel free to reopen if I am missing something
