### ISSUE TITLE
Remove the dependency from cert-manager when using the webhooks

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1303]
We are moving the logic from the operator to metallb, where we were declaring cert-manager as a pre-requisite to use the operator with webhooks. 
As pointed out by @gclawes , we should a look at how the prometheus operator deploys a job to patch the webhooks [by deploying a standalone component](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch) and effectively removing the dependency from cert-manager.

**Comment by sabinaaledort** [comment]
I created two patch jobs to create a secret and patch the webhook using https://github.com/jet/kube-webhook-certgen/: 
https://github.com/metallb/metallb/pull/1360

The only thing not supported in this project is patching the CRD webhook caBundle which we set [here](https://github.com/metallb/metallb/blob/7d8f69e37ca149e96eceed1dbd8794abb8f6ee24/charts/metallb/templates/crds.yaml#L29) for conversion.

One option is to state that conversion webhooks are only supported with cert-manager. Another option is to add support for CRD webhooks in the kube-webhook-certgen project: https://github.com/jet/kube-webhook-certgen/issues/35#issuecomment-1121199526

@gclawes @fedepaol any other ideas?

**Comment by fedepaol** [comment]
I don't see many other options.
- we say that as of today backward compatibility with the old operator works only if cert-manager is deployed
- in the meanwhile we try to have the feature in the webhook-cert-gen

A note about webhook-cert-gen:
Although it's used (at least by) prometheus operator, it looks like:
- the original repo is not supported anymore (see https://github.com/jet/kube-webhook-certgen/pull/32#issuecomment-909297792)
- the fork doesn't advocate for the image to be used outside (see https://github.com/kubernetes/ingress-nginx/tree/main/images )

So all in all, I think it's fine to document kube-webhook-certgen limitations (and try to add the missing feature there)

**Comment by gclawes** [comment]
If we can't get the CRD webhook feature added to the webhook-cert-gen, then maybe it's better just to use cert-manager for everything and use a consistent method for webhook management.  I think this would mean that cert-manager effectively becomes a mandatory dependency, but I see that as better than using 2 different methods for effectively the same job.  This doesn't appear to be an issue in ingress-nginx because they don't use CRDs.

Installing cert-manager as a dependency in the helm chart is fairly easy (though it should be on a toggle in case cluster operators run their own cert-manager instance).  I'd be more worried about users of the raw manifests, it would increase the complexity of releasing manifests.

**Comment by fedepaol** [comment]
How about having it as an optional dependency, and provide a toggle to enable / disable the webhooks (which is pretty much what main is today)?
Users would have the option to give up on validation of CRs when deploying without webhooks (which is what we are offering today with the operator). Not sure having it as part of helm (and having the operator deplyoing it) adds much value than providing instructions on how to deploy it, as it is a separate component.

Manifests wise, we could have two variants (as we have now) with - without webhooks. Kustomize would allow us to generate those variants (almost) easily.

**Comment by fedepaol** [comment]
And it seems to support conversion webhooks: https://github.com/open-policy-agent/cert-controller/blob/master/pkg/rotator/rotator.go#L293

**Comment by fedepaol** [comment]
Oh, I misunderstood your comment. OPA Gatekeeper is still using it (https://github.com/open-policy-agent/gatekeeper/blob/b6ea208bf31a8acfbdd60b7909af1a6b396c30f1/main.go#L188), reading that comment the support was originally embedded in controller-runtime but then removed.

I think it's worth exploring.

**Comment by fedepaol** [comment]
Cert-controller is in, closing the issue
