### ISSUE TITLE
tasks.py - deploy all the needed dependencies

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1307]
Now that we have extra deps, such as controller-gen and kustomize, we should be able to deploy them automatically from tasks.py

**Comment by fedepaol** [comment]
sorry if I reply so late. The idea here is to have a simple command in tasks.py that deploys the dependencies required such as controller-gen

**Comment by 26tanishabanik** [comment]
@fedepaol , I think commands for installing controller-gen is added, is that right?

**Comment by 2SpaceMasterRace** [comment]
Hey @fedepaol I should be able to work on this

Is it cool if I get assigned to this issue?

**Comment by fulviodenza** [comment]
Hi @fedepaol I was starting looking into this and found out that `controller-gen` has already been implemented. While Kustomize is not, I can take the issue if Kustomize dep is still valid.

**Comment by fedepaol** [comment]
@fulviodenza absolutely, and thanks!

**Comment by fedepaol** [comment]
Closing, kustomize is not really needed as we moved to `kubectl kustomizze` and I added gingko which was the last standing one
