### ISSUE TITLE
Use helm crds/ directory to manage CRDS

### ISSUE THREAD

**Issue by gclawes** [metallb/metallb#1346]
Currently CRDs are templated: https://github.com/metallb/metallb/blob/main/charts/metallb/templates/crds.yaml

The [primary method](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you) recommended in the helm documentation formally recommends using the `crds/` directory to managed CRDs, which get applied at the beginning of the `helm install` lifecycle of a chart.  Using this method precludes templating in CRDs, so the following changes would be necessary:

* Remove cert-manager annotations:
https://github.com/metallb/metallb/blob/9985a602b7c93a51dcce6c5d6f9bb4ec98760115/charts/metallb/templates/crds.yaml#L7
https://github.com/metallb/metallb/blob/9985a602b7c93a51dcce6c5d6f9bb4ec98760115/charts/metallb/templates/crds.yaml#L495

* Permanently enable conversion webhook:
https://github.com/metallb/metallb/blob/9985a602b7c93a51dcce6c5d6f9bb4ec98760115/charts/metallb/templates/crds.yaml#L20
https://github.com/metallb/metallb/blob/9985a602b7c93a51dcce6c5d6f9bb4ec98760115/charts/metallb/templates/crds.yaml#L508

The [second method](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you) is to create a sub-chart as a dependency.  This would enable templating, but is more moving pieces.

Full documentation: https://github.com/metallb/metallb/blob/main/charts/metallb/templates/crds.yaml

**Comment by fedepaol** [comment]
Closed by https://github.com/metallb/metallb/pull/1420
