### ISSUE TITLE
Document how L2 election works for each VIP

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1348]
This is to add a small section in the docs to record how we elect the leader node for each ip.

**Comment by anavarro10** [comment]
Yes, Please.
I have a Canary Environment and two Production Environments using Platform9's Managed Kubernetes and we were performing upgrades to v1.21 from v.1.20.5

Pre-upgrade version of Metallb v0.9.6
Three Master Nodes and Two Worker Nodes with v1.20.5 K8s
The three Masters are VMs and the Two Workers are beefy BareMetal Servers.
We also run jcmoraisjr/haproxy-ingress v0.10 for Layer 7.
We had scripts prepared to send tons of curl requests through the load-balancer IP we assigned to the ingress controller to nginx pods that are spread out among the two workers.

We noticed during the test upgrades, On Average there was at least 1-2mins of downtime when told that there should be zero.
We were also told that metallb elects a leader node for each IP it gives out so we suspect that if we could found out how that leader node election works we could batch upgrade the non-leader nodes first to further reduce or provide zero downtime? 
However, there doesn't seem to be any trusted documentation out there on this topic.

Please Advice,

Thank you.

**Comment by fedepaol** [comment]
closed by https://github.com/metallb/metallb/pull/2064
