### ISSUE TITLE
Automate Helm readme generation

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1373]
We should generate the helm readme automatically, and we should enforce it via CI.

**Comment by jtcarnes** [comment]
Quick question: there are two ci systems (circle and GitHub). Is there a preferred solution?

**Comment by gclawes** [comment]
@fedepaol should we resolve this before merging the 2 chart changes #1340  #1369 ?

**Comment by fedepaol** [comment]
@gclawes I agree.

@jtcarnes we are migrating away from circleci, the last bits are the image publication steps that are being addressed in https://github.com/metallb/metallb/pull/1374

@jtcarnes what I'd suggest to do is to follow the same approach that we take with other code generation steps, where we provide an action to update and we enforce the generated to be in sync in CI.

Here is the CI entry point https://github.com/metallb/metallb/blob/033b79537d5d6ff7f2382126a1c7cd873763a08e/.github/workflows/ci.yaml#L52 where we try to re-generate and we verify nothing changed.

and here https://github.com/metallb/metallb/blob/f0798a5a9329418dbb9b4a85e7e418aa33ebaf4d/tasks.py#L808 is the corresponding inv task.

**Comment by fedepaol** [comment]
@jtcarnes assigned the issue to you, let us know if you have any issues. You can also find us in the #metallb-dev channel of the kubernetes slack.
Thanks!

**Comment by jtcarnes** [comment]
Absolutely. Question for you, do you want GH to be the one that updates the docs, or to fail if the docs are not what it expects? (generation vs a check).

**Comment by fedepaol** [comment]
> Absolutely. Question for you, do you want GH to be the one that updates the docs, or to fail if the docs are not what it expects? (generation vs a check).

I'd say check, as we do with the others so we have more control on what gets committed. And thanks again!
