### ISSUE TITLE
BGP remote-as internal/external

### ISSUE THREAD

**Issue by duylong** [metallb/metallb#1382]
Hi,

I wanted to personalize my remote-as to internal, but impossible to do so via the my-asn option. I have an error that requires that the value must absolutely be an integer:
```
{"caller":"level.go:63","configmap":"metallb-system/config","error":"could not parse config: yaml: unmarshal errors:\n line 4: cannot unmarshal !!str `internal` into uint32\n line 8: cannot unmarshal !!str `internal` into uint32\n line 12: cannot unmarshal !!str `internal` into uint32\n line 16: cannot unmarshal !!str `internal` into uint32 \n line 20: cannot unmarshal !!str `internal` into uint32\n line 29: cannot unmarshal !!str `internal` into uint32\n line 38: cannot unmarshal !!str `internal` into uint32\n line 47: cannot unmarshal !!str `internal` into uint32","event":"configStale","level":"error","msg":"config (re)load failed, config marked stale","ts":" 2022-05-19T08:42:48.465064637Z"}
```
The option exists in the frr configuration:

http://docs.frrouting.org/en/latest/bgp.html#clicmd-neighbor-PEER-remote-as-internal
http://docs.frrouting.org/en/latest/bgp.html#clicmd-neighbor-PEER-remote-as-external

For example:
```
router bgp 65432
 bgp router-id A.B.C.D
 neighbor A.B.C.E remote-as internal
 neighbor A.B.C.E password ***
 neighbor A.B.C.F remote-as internal
 neighbor A.B.C.F password **
```
Is it possible to allow the values "internal" and "external"?

Version of MetalLB : 0.0.12.1

**Comment by fedepaol** [comment]
Hi @duylong , currently is not possible to set such values to asns, you need to explicitly set the asn.

**Comment by fedepaol** [comment]
Closing this as there's not much traction. Will reopen in case it's requested and makes sense
