### ISSUE TITLE
Debug tool

### ISSUE THREAD

**Issue by oribon** [metallb/metallb#1386]
When there's a new issue we usually ask for different logs to understand the cause: controller/speaker pod logs, custom resources (replaces the configmap), and when FRR is involved we also need its configuration from each speaker pod: `show running-config`, `show bgp neighbor` ...
The idea is to have a cli tool that gathers everything we need for debugging into some zip a user can attach with his issue, instead of manually fetching these logs.

Our E2E does something similar when a test fails so we could probably re-use some of the stuff from there: e.g. https://github.com/metallb/metallb/blob/f3c924088a8aea91feec456576b89cba74283eb7/e2etest/bgptests/dump.go#L20

or write a bash script that fetches the relevant logs / resources

**Comment by tylerauerbeck** [comment]
@fedepaol Maybe this could be bake into a kube plugin along the lines of how `rook` does things? In most cases, you could just pass along the commands you want to be run against your target (i.e. the commands mentioned above `show running-config`, `show bgp neighbor`). But then we could also do something like `kubectl metallb collect-debug` which does some defined set of data aggregation for troubleshooting needs.

An example of what I mentioned above would like something like:

```
kubectl metallb show .... (this could be any string of commands that we want to run against the deployment)
kubectl metallb collect-debug (this does some defined set of data aggregation and zips it up for the user to upload to an issue)
```

**Comment by kevydotvinu** [comment]
Would this be maintained as `kubectl-metallb` separately like [rook](https://github.com/rook/kubectl-rook-ceph)?

**Comment by fedepaol** [comment]
> Would this be maintained as `kubectl-metallb` separately like [rook](https://github.com/rook/kubectl-rook-ceph)?

tbh, I haven't thought about that. I would start easy and collect the information we require for when we ask details, and as @oribon said, a bash script can be a good starting point.

**Comment by kevydotvinu** [comment]
Can I try this, then?

**Comment by fedepaol** [comment]
> Can I try this, then?

try what?

**Comment by kevydotvinu** [comment]
I will try to create a bash script/binary to collect the data.

**Comment by fedepaol** [comment]
ah cool! Thanks, assigning this too to you

**Comment by fedepaol** [comment]
you can _take inspiration_ from https://github.com/openshift/must-gather/blob/master/collection-scripts/gather_metallb
