### ISSUE TITLE
Config manifests: `creationTimestamp: null`

### ISSUE THREAD

**Issue by sabinaaledort** [metallb/metallb#1399]
The webhooks and CRDs manifests are generated with `creationTimestamp: null`.
https://github.com/metallb/metallb/blob/fc3a0f40571c85a7faeaaa332af46f9b2367f0de/config/crd/bases/metallb.io_ipaddresspools.yaml#L8
https://github.com/metallb/metallb/blob/fc3a0f40571c85a7faeaaa332af46f9b2367f0de/config/webhook/manifests.yaml#L6

**Comment by yellowhat** [comment]
Hi,
is there a reason for the presence of `creationTimestamp` in the `metadata` section?

Thanks

**Comment by fedepaol** [comment]
They are generated automatically and if I remember correctly we didn't find a way to remove it (and it's not harming so :shrug: )

**Comment by yellowhat** [comment]
it is a bit annoying if you try to pass the manifests through datree.
