### ISSUE TITLE
MP BGP (ipv6) is broken in main with crds

### ISSUE THREAD

**Issue by nberlee** [metallb/metallb#1402]
Using 0.12 i was able to do MP-BGP with an ipv4 bgp peer (advertising also ipv6). However, when running latest main with crds, I am unable to get MP-BGP working.

The controller says in events it will advertise the ipv6 service on two nodes. But when doing in the corresponded speaker pod frr:
```
vtysh
show running-config
```
It is missing a `address-family ipv6 unicast` section and `ipv6 prefix-list 100-v6localpref-prefixes seq 5 permit` ... line(s)  compared to 0.12

In the remote bgp router i only see AFI `ip` sesions, not `ip ipv6` sessions.

Reverting back to 0.12 makes MP-BGP function again.

**Comment by oribon** [comment]
Hi :smiley:, can you please share the speakers and controller logs (setting the loglevel parameter to debug before sending the logs if possible), CRs, the services spec when it is not working + the configmap that works when you're using this in 0.12?

**Comment by nberlee** [comment]
I runned the speaker in debug and saw noting suspicious. But I already spotted the bug in the code:
https://github.com/metallb/metallb/commit/0f33257c2b1533d211e82746fd5189c292052c95#diff-799fb51a85bb84147c1487eb5d728663c098fffce7f326c412fac1f619860516R272

I am build now a version without the:
```
			if family != neighbor.IPFamily {
				continue
			}
```
To confirm that this is the problem. If this fixes it, I will create a pull request. If not, i will sanitize my logs (as they contain my public ipv6 address) and upload them here

**Comment by Jean-Daniel** [comment]
> Could you also share the usecase - why you need to advertise v6 prefixes to a v4 peer? Does the peer have an IPv6 that you can peer with for now as a workaround?

Isn't it the main purpose of MP-BGP. Being able to advertise IPv6 prefixes on a v4 peers ? I'm using it too because having to create 2 sessions per peer would create too much sessions on my router. 

Moreover, I have devices where configuring BGP session using link-local addresses is more complex than it should be (and poorly supported),  so it would requires to create IPv6 networks only used to pass BGP advertisements. Actually,  my peers are advertising there link-local address as next-hop.

**Comment by fedepaol** [comment]
@nberlee any news about this?

> I runned the speaker in debug and saw noting suspicious. But I already spotted the bug in the code: [0f33257#diff-799fb51a85bb84147c1487eb5d728663c098fffce7f326c412fac1f619860516R272](https://github.com/metallb/metallb/commit/0f33257c2b1533d211e82746fd5189c292052c95#diff-799fb51a85bb84147c1487eb5d728663c098fffce7f326c412fac1f619860516R272)
> 
> I am build now a version without the:
> 
> ```
> 			if family != neighbor.IPFamily {
> 				continue
> 			}
> ```
> 
> To confirm that this is the problem. If this fixes it, I will create a pull request. If not, i will sanitize my logs (as they contain my public ipv6 address) and upload them here

@nberlee any news about this?

**Comment by nberlee** [comment]
> @nberlee any news about this?
Yes, its more broken than only this line. 

> Does the peer have an IPv6 that you can peer with for now as a workaround?
I have tested setting up v6 neigbors with v4 neigbors, and that works. 

> Could you also share the usecase - why you need to advertise v6 prefixes to a v4 peer?
This question worries me, configuring MP-BGP makes things easier on all side, as it reduces the amount of config on the router and in K8s..I totally agree with @Jean-Daniel .

And a lot of people want MP-BGP considering the effort in the rejected implementation:
* https://github.com/metallb/metallb/pull/470
* https://github.com/metallb/metallb/pull/574
* https://github.com/metallb/metallb/pull/590

> I'd still like to see your configuration
Changed the IPv6 address as its public
[config.sanitized.yaml](https://github.com/metallb/metallb/files/8938586/config.sanitized.yaml.txt)

**Comment by fedepaol** [comment]
My request was mostly about what you said about filing a PR with the fix.
If not, we're gonna work on it, hopefully before the next release.
