### ISSUE TITLE
Build directly in dockerfiles

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1408]
We currently build the images using inv and then we copy the binaries inside the container with a COPY instruction.
It'd be better to have the build process as part of the dockerfile itself. That will allow us to get rid of inv when publishing images and delegate everything to GH actions (which can be a follow up of https://github.com/metallb/metallb/pull/1374 )

**Comment by jtcarnes** [comment]
I'm working on it and will have an Mr out soon. Do you want me to refactor the ci after the docker file is ready?

**Comment by fedepaol** [comment]
> I'm working on it and will have an Mr out soon. Do you want me to refactor the ci after the docker file is ready?

That'd be great. I'd merge https://github.com/metallb/metallb/pull/1374 once it's ready and have your on top of it.

**Comment by fedepaol** [comment]
Closing this as the related PR was merged
