### ISSUE TITLE
Support for IPv6 Prefix delegation

### ISSUE THREAD

**Issue by ebkde** [metallb/metallb#1409]
using 0.12.1 I was able to setup a dual stack k3s Cluster in my private network. Due to the common usage of NAT for IPv4 in most internet Routers it is quite simple to access services within that cluster from the internet.
Since NAT66 is quite uncommon and most ISPs only provide dynamic IPv6 prefixes to their customers achieving the same via IPv6 is (at least for me) impossible.
This is not metallb's fault, thus this is more a enhancement request than a bug report.

What would be great is a possibility to configure metallb to get the IPv6 prefix via DHCPv6 and to define a Device ID/Suffix range to derive the actual IPv6 address of a Loadbalancer Service.

**Comment by fedepaol** [comment]
I think this is a dupe of what's being discussed in https://github.com/metallb/metallb/issues/157

**Comment by ebkde** [comment]
You're right, this is somehow a duplicate of https://github.com/metallb/metallb/issues/157.
Sorry I didn't recognized the term IPAM. Now I know.

**Comment by fedepaol** [comment]
NP at all! I wasn't totally sure either :P
