### ISSUE TITLE
CI: avoid code duplication in gh workflow actions

### ISSUE THREAD

**Issue by pperiyasamy** [metallb/metallb#1411]
some steps like checkout, install dependencies, lint etc. in the gh workflow jobs are so common, hence it would be appropriate if these are moved into a common place (example: having local actions) and make workflows to consume it.

https://github.com/metallb/metallb/blob/main/.github/workflows/ci.yaml#L22-L41
https://github.com/metallb/metallb/blob/main/.github/workflows/ci.yaml#L133-L153
https://github.com/metallb/metallb/blob/main/.github/workflows/ci.yaml#L209-L236

**Comment by tylerauerbeck** [comment]
Feels like this issue may have already been completed?
