### ISSUE TITLE
Layer2 mode failover mechanism in the same network

### ISSUE THREAD

**Issue by changzhi1990** [metallb/metallb#1412]
Hi,

I'm testing MetalLB functionality and I have a question about the failover mechanism.

For example, I have two IP address pools (192.168.10.10-192.168.10.11, 192.168.20.10-192.168.20.11) in the configmap of MetalLB. One IP address pool for the external network and the second one for the internal network. And each IP address pool have two loadbalancers. Like this:

```
Name                          IP address          Node
external-loadbalancer1        192.168.10.10       Node1
external-loadbalancer2        192.168.10.11       Node2
internal-loadbalancer1        192.168.20.10       Node3
internal-loadbalancer2        192.168.20.21       Node4
```

If the node1 is the leader node and the failover mechanism has been triggered. The MetalLB will be re-elected a leader node from the node2, node3 and node4.  The network will be stuck if the node3 or node4 was elected to the leader node because the different IP address pool. 

**I think that the node from the same IP address pool should be selected to the leader node.**

How does the MetalLB re-elected the new leader node? Randomly from the memberlist?

Does the MetalLB have the similar mechanism now? 

Thanks!

**Comment by fedepaol** [comment]
Hi @changzhi1990 , looks like you want to have different nodes on different networks.
If that is the case, we are implementing node selector in the next release, I'd suggest giving a look at https://github.com/metallb/metallb/blob/main/design/pool-configuration.md#announcing-the-ip-from-a-subset-of-nodes-1

Closing this issue, feel free to reopen if you need to expand or if I missed anything. Thanks!
