### ISSUE TITLE
Annotate a service with the pool used to provide its IP

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1448]
Especially now that we have multiple configurations tied to the ipaddresspool, it'd be useful to see which pool was used to assign the ip to a given service. It can be done contextually to the ip assignement.

**Comment by fedepaol** [comment]
@cyclinder that'd be great!
Assigning it to you

**Comment by cyclinder** [comment]
Yeah! But maybe I don't have extra time to work on this lately, maybe I'll look into it during the weekend.

**Comment by fedepaol** [comment]
No rush! I was just going through the issues and found this
