### ISSUE TITLE
Extend crds with additionalPrinterColumns

### ISSUE THREAD

**Issue by oribon** [metallb/metallb#1459]
With the new crds it would be useful to have a bit more info when using `kubectl get`, for example:
```
$ kubectl get bgppeers
NAME    IP            MYASN    ASN          ...
peer1   1.2.3.4       64512    64512
peer1   5.6.7.8       64512    64513

$ kubectl get ipaddresspools
NAME    ADDRESSES              ...
pool1   1.2.3.1-1.2.3.254
```
Should be a matter of adding (and thinking about) the relevant `+kubebuilder:printcolumn` markers and re-generating the crds.
https://book.kubebuilder.io/reference/generating-crd.html#additional-printer-columns
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns

**Comment by attiss** [comment]
@oribon @fedepaol I'd be happy to contribute this.

**Comment by fedepaol** [comment]
Thanks! Assigning this to you
