### ISSUE TITLE
New Helm chart released before publishing container images

### ISSUE THREAD

**Issue by VeetiPoutsalo** [metallb/metallb#1471]
As of writing this issue, there has been a period of almost an hour where attempting to install the latest Helm release of MetalLB results in an error due to it referring to an unpublished version of the container images.

The v0.13.0 release updated the MetalLB Helm chart (https://artifacthub.io/packages/helm/metallb/metallb) before the v0.13.0 containers had been pushed to quay.io (https://quay.io/repository/metallb/speaker?tab=tags).

To fix this, any new release Helm charts should not be published before all prerequisite container images have been successfully published, to ensure minimal disruption to Helm installation.

**Comment by fedepaol** [comment]
Apologies, we have some unexpected issues with the changes in our publishing process.
We are removing the release and try to fix it smoothly

**Comment by fedepaol** [comment]
Update: now the release is reverted, as the changes to the chart (not sure if artifacthub will reflect that, but we have no control).
We'll make sure the pipeline is working and retry.

**Comment by fedepaol** [comment]
The new 0.13.2 release is out, hopefully works as expected.
I am gonna keep this issue open to track the fact that we want to have dependencies between the image publishing job and teh helm release job.

Also, if you are automatically upgrading metallb, please be aware of the fact that the configmap won't work anymore: https://github.com/metallb/metallb/issues/1473
