### ISSUE TITLE
Image tag on quay.io differs from the one specified in manifest v0.13.2

### ISSUE THREAD

**Issue by PSSGCSim** [metallb/metallb#1474]
Manifest references different tag than is available on quay.io

The manifest contains v0.13.2
https://raw.githubusercontent.com/metallb/metallb/v0.13.2/config/manifests/metallb-native.yaml

but quay.io contains 0.13.2 (without the leading v)
https://quay.io/repository/metallb/controller?tab=tags&tag=latest
https://quay.io/repository/metallb/speaker?tab=tags&tag=latest

This results in failure to pull image

```
Failed to pull image "quay.io/metallb/controller:v0.13.2": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/metallb/controller:v0.13.2": failed to resolve reference "quay.io/metallb/controller:v0.13.2": quay.io/metallb/controller:v0.13.2: not found
```

```
metallb-system         controller-d584cc79-7cqxr                           0/1     ImagePullBackOff   0              9m51s
```

**Comment by fedepaol** [comment]
Ugh, this is another side effect of our latest ci changes.
Will fix it immediately

**Comment by PSSGCSim** [comment]
Can confirm upgrading using the manifest now works as expected, thank you

**Comment by jtcarnes** [comment]
@fedepaol do we want to make the images have the leading v or not moving forward? I can make this a quick change
