### ISSUE TITLE
Making the release process testable

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1475]
Due to a serie of changes, the 0.13.2 release wasn't as smooth as before.
See https://github.com/metallb/metallb/issues/1474 and https://github.com/metallb/metallb/issues/1471

It must be possible from our CI to test the release process from a fork, eventually changing the repository the images are published to to do a full cycle.

**Comment by gclawes** [comment]
We should probably allow forks to publish to `ghcr.io`, or just parallel publish there by default

**Comment by fedepaol** [comment]
Yep, either that or being able to override the repo
