### ISSUE TITLE
0.13.2: multi-arch images broken

### ISSUE THREAD

**Issue by gclawes** [metallb/metallb#1476]
It looks like multi-arch images are broken in 0.13.2:
```
ubuntu@pi01:~$ uname -a
Linux pi01 5.4.0-1065-raspi #75-Ubuntu SMP PREEMPT Fri Jun 3 14:24:57 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

ubuntu@pi01:~$ docker run -it --rm quay.io/metallb/controller:v0.12.1
{"branch":"HEAD","caller":"level.go:63","commit":"v0.12.1","goversion":"gc / go1.16.14 / arm64","level":"info","msg":"MetalLB controller starting version 0.12.1 (commit v0.12.1, branch HEAD)","ts":"2022-07-06T16:43:05.750879466Z","version":"0.12.1"}
{"caller":"level.go:63","error":"open /var/run/secrets/kubernetes.io/serviceaccount/namespace: no such file or directory","level":"error","msg":"Unable to get namespace from pod service account data, please specify --namespace or METALLB_NAMESPACE","op":"startup","ts":"2022-07-06T16:43:05.751340719Z"}

ubuntu@pi01:~$ docker run -it --rm quay.io/metallb/controller:v0.13.2
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by fedepaol** [comment]
@jtcarnes mind having a look here?

**Comment by werwolfby** [comment]
The same issue, with the same response or `raspbian` `arm64`.
Doesn't work on `v0.13.2` but works on `v0.12.1` with the same output.

**Comment by jtcarnes** [comment]
Issue was they were pegged to arm v6 when built. MR to fix it should be out. I invite those having an issue to build and ensure its working as expected. I've tested locally but want to make sure

**Comment by krohrsb** [comment]
Will the fix be retroactive, or shall we be waiting for a 0.13.3?

**Comment by fedepaol** [comment]
We'll publish a 0.13.3, probably tomorrow my morning (in 8 hours), because we don't want to recreate images with the same tag but different shas.

**Comment by werwolfby** [comment]
@fedepaol I've checked on my pi:
```bash
docker run -it --rm quay.io/fpaoline/controller:v1.100.3
Unable to find image 'quay.io/fpaoline/controller:v1.100.3' locally
v1.100.3: Pulling from fpaoline/controller
b3c136eddcbf: Already exists
04375d82adcb: Pull complete
9b3225ea2360: Pull complete
Digest: sha256:52c80bb0cf1a71b85b1ce4e5de270331dc771a147379ff6305d089da970cb428
Status: Downloaded newer image for quay.io/fpaoline/controller:v1.100.3
{"branch":"dev","caller":"main.go:141","commit":"dev","goversion":"gc / go1.18.3 / arm64","level":"info","msg":"MetalLB controller starting (commit dev, branch dev)","ts":"2022-07-07T07:29:13Z","version":""}
{"caller":"main.go:146","error":"open /var/run/secrets/kubernetes.io/serviceaccount/namespace: no such file or directory","level":"error","msg":"Unable to get namespace from pod service account data, please specify --namespace or METALLB_NAMESPACE","op":"startup","ts":"2022-07-07T07:29:13Z"}
```

Looks like this tag exactly works. Thank you.

**Comment by fedepaol** [comment]
Thanks @werwolfb! We need to wait a couple of prs to get in and we'll do a new release.

**Comment by werwolfby** [comment]
Will try full installation on clean PIs cluster in the morning (in ~8 hours).

Will let you know, thank you!

**Comment by werwolfby** [comment]
I works.. but partially only.

Everything were installed successfully and running. But I can't add any metallb CRDs:

```text
{"level":"error","ts":1657204726.0914934,"logger":"cert-rotation","msg":"secret is not well-formed, cannot update webhook configurations","error":"Cert secret is not well-formed, missing ca.crt","errorVerbose":"Cert secret is not well-formed, missing ca.crt\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.buildArtifactsFromSecret\n\t/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.3.0/pkg/rotator/rotator.go:380\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.(*ReconcileWH).Reconcile\n\t/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.3.0/pkg/rotator/rotator.go:635\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1263","stacktrace":"github.com/open-policy-agent/cert-controller/pkg/rotator.(*ReconcileWH).Reconcile\n\t/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.3.0/pkg/rotator/rotator.go:637\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234"}
W0707 14:38:46.103465       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: failed to list *v1beta1.AddressPool: Internal error occurred: error resolving resource
E0707 14:38:46.103560       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.AddressPool: failed to list *v1beta1.AddressPool: Internal error occurred: error resolving resource
W0707 14:38:47.461765       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: failed to list *v1beta1.AddressPool: Internal error occurred: error resolving resource
E0707 14:38:47.461827       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.AddressPool: failed to list *v1beta1.AddressPool: Internal error occurred: error resolving resource

```

**Comment by werwolfby** [comment]
Right after installing the metallb (from `manifests`) I can't add CRDs.
All this is done as part of single `kustomize` script, where first is the manifest and the second is the new CRDs. As result:

```
validatingwebhookconfiguration.admissionregistration.k8s.io/validating-webhook-configuration configured
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": proxy error from 127.0.0.1:6443 while dialing 10.42.3.56:9443, code 500: 500 Internal Server Error
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "l2advertisementvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-l2advertisement?timeout=10s": proxy error from 127.0.0.1:6443 while dialing 10.42.3.56:9443, code 500: 500 Internal Server Error
```

And it is in that state for some time.
And then after an hour or so, I tried it again and it works now!

Should we create a new issues for this? Cause this is not allow my automation to spin new clusters.
I think I can introduce some workarounds here, but if we can avoid it that would be nice!

**Comment by werwolfby** [comment]
Hi @fedepaol, I've installed everything into separate namespace so I went through #1481 but everything in place. Roles has `watch` on all `apiGroups`. And the service has `matchLabels`.

And as I said this is some issue on initial startup only, after sometime (without any changes) apply new CRDs just works fine.

**Comment by fedepaol** [comment]
Right, but it would be importnat to understand if "sometime" is a matter of minutes or hours.
If it's minutes, that's kind of expected. There are a few steps in order to satisfy the webhooks (pulling the right controller image, having the cert-controller to patch the webhooks).
Also, I'd like to understand if after it works, then it always works or it is intermittent (as per #1481)

**Comment by Octogonapus** [comment]
I am experiencing the same issue as https://github.com/metallb/metallb/issues/1476#issuecomment-1177849142 running a fresh deployment of metallb v0.13.3.
```
W0714 01:35:41.099371       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: failed to list *v1beta1.AddressPool: Internal error occurred: error resolving resource
E0714 01:35:41.099407       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.AddressPool: failed to list *v1beta1.AddressPool: Internal error occurred: error resolving resource
```

I haven't seen it stabilize after some startup period like @werwolfby states. After some time, the controller and all speaker nodes enter crash loop backoff state and eventually continue crashing.

**Comment by fedepaol** [comment]
> I am experiencing the same issue as [#1476 (comment)](https://github.com/metallb/metallb/issues/1476#issuecomment-1177849142) running a fresh deployment of metallb v0.13.3.
> 
> ```
> W0714 01:35:41.099371       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: failed to list *v1beta1.AddressPool: Internal error occurred: error resolving resource
> E0714 01:35:41.099407       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.AddressPool: failed to list *v1beta1.AddressPool: Internal error occurred: error resolving resource
> ```
> 
> I haven't seen it stabilize after some startup period like @werwolfby states. After some time, the controller and all speaker nodes enter crash loop backoff state and eventually continue crashing.

Would you mind filing a new issue (adding how you deployed metallb and the output of `kubectl get crds -A | grep metallb` ? Thanks!

**Comment by Octogonapus** [comment]
> Would you mind filing a new issue (adding how you deployed metallb and the output of kubectl get crds -A | grep metallb ? Thanks!

I made a fresh k3s cluster and installed metallb on it to make a short MWE for this issue, but now it's not happening :shrug: 
Will open an issue if I can reproduce it consistently

**Comment by fedepaol** [comment]
> Will open an issue if I can reproduce it consistently

Thanks! Please file the issue even if you spot it :-)
Also, can you confirm your deployment method?

**Comment by Octogonapus** [comment]
- k3s HA with 3 nodes on v1.23.8+k3s2
- metallb v0.13.3
- [helm chart](https://pastebin.com/6g8v0SPp)
- [metallb configuration](https://pastebin.com/wgHHhVdF)
- deploy cmd: `helm install --create-namespace --namespace metallb metallb metallb/metallb -f metallb-values.yml`
