### ISSUE TITLE
Traking the progress of the new feature:  announing LB IP from specified interface

### ISSUE THREAD

**Issue by qingwusunny** [metallb/metallb#1490]
The issue is to track the coding progress of [this feature](https://github.com/metallb/metallb/pull/1359): announcing IP from specified interfaces for layer2

**Comment by fedepaol** [comment]
@qingwusunny if you want, I can create a milestone we can put issues under, so it's clearer how to split the work and how to track the progress.

**Comment by qingwusunny** [comment]
ok

**Comment by qingwusunny** [comment]
backlog:
- Modify the data structure of L2Advertisement
- Build the mapping between LB IP and IP Pool
- Build the mapping between  IP Pool and local Node
- Handle the configuration(IPAddressPool and L2Advertisement) updates
- Announce IP from the specified interfaces

**Comment by fedepaol** [comment]
Added https://github.com/metallb/metallb/milestone/20 you can put issues under.

**Comment by qingwusunny** [comment]
Do you expect me to modify L2Advertisement directly under v1beta1 or add L2Advertisement under v1beta2?

**Comment by fedepaol** [comment]
> Do you expect me to modify L2Advertisement directly under v1beta1 or add L2Advertisement under v1beta2? @fedepaol Maybe I can modify it under v1beta1 because the modify is compatibility

Right, it's a new field so it's totally fine to keep it under v1beta1 because it's gonna be backward compatible.
If you have doubt / questions, you can also join the `#metallb-dev` channel on k8s slack.
