### ISSUE TITLE
 https://metallb.github.io/metallb - 404

### ISSUE THREAD

**Issue by h4wkmoon** [metallb/metallb#1493]
Hi, 
I can't find the helm charts repo. 
https://metallb.github.io/metallb gives a 404

Do you have move the charts elsewhere ? In that can't you should update the docs, plz.
Thx.

**Comment by fedepaol** [comment]
The chart is still there, at metallb.github.io/metallb/index.yaml
metallb.github.io/metallb/ always gave 404.
See for example https://github.com/metallb/metallb/issues/1246
