### ISSUE TITLE
change webhook name

### ISSUE THREAD

**Issue by jr0dd** [metallb/metallb#1494]
I just wanted to suggest changing the webhook name to something more descriptive.

```
mb-pro home-ops % k get validatingwebhookconfigurations.admissionregistration.k8s.io                                   
NAME                               WEBHOOKS   AGE
cert-manager-webhook               1          4d8h
ingress-nginx-admission            1          164d
kube-prometheus-stack-admission    1          7d22h
validating-webhook-configuration   7          3d20h.            <~~~ metallb-admission or something something
```

**Comment by fedepaol** [comment]
Makes sense. As discussed previously, we did not think about a use case where metallb was mixed with other components in the namespace, so despite the name was generic it did not see a big issue.
We'll change it.

**Comment by jr0dd** [comment]
> Makes sense. As discussed previously, we did not think about a use case where metallb was mixed with other components in the namespace, so despite the name was generic it did not see a big issue.
> We'll change it.

Awesome! Actually, I just realized that `validatingwebhookconfigurations` are not namespaced anyways.

**Comment by fedepaol** [comment]
> > Makes sense. As discussed previously, we did not think about a use case where metallb was mixed with other components in the namespace, so despite the name was generic it did not see a big issue.
> > We'll change it.
> 
> Awesome! Actually, I just realized that `validatingwebhookconfigurations` are not namespaced anyways.

Right, so that's even worse :/
Will change that

**Comment by nayrnet** [comment]
found this issue the hard way when I tried to install MetaLB into a cluster that had RabbitMQ, which also decided to use the name `validating-webhook-configuration`

looks like they recently changed that behavior too: https://github.com/rabbitmq/messaging-topology-operator/commit/f56f89b293e5453f7f5c7272a0b08fc3af723372
