### ISSUE TITLE
IP Sharing, with externalTrafficPolicy: Local

### ISSUE THREAD

**Issue by fr19k** [metallb/metallb#1499]
Hello,

Can I have shared external IP address (serviceType : LoadBalancer) with externalTrafficPolicy: Local, in multiple different kubernetes services?

Each service has unique port

When i set externalTrafficPolicy: Cluster, IP sharing works properly (Multiple services has the same externalIP).

MetalLB 0.11.0
Kubernetes 1.18/1.19

**Comment by Jean-Daniel** [comment]
Unless you collocate your services, I don't see how it can really work. BGP works at the IP level, and so is port/protocol agnostic.

You can't annonce a route only for TCP/UDP packet bound to a single port, so they will always behave (at least partially) as if policy Cluster is defined.

I'm not sure how Local policy works with shared IP actually. Defining it as directing traffic to at all nodes containing at least one service using the shared IP may be misleading, as there is no guarantee the packet will arrive on the right node.

**Comment by fedepaol** [comment]
Hi, the current requirement for ETP=local is to have the two services share the same backend selector:

https://github.com/metallb/metallb/blob/7fb3231966a0c2a6741122f4b81020abd3380011/internal/allocator/k8salloc/k8salloc.go#L31
