### ISSUE TITLE
[documentation] BGP Secret Reference Usage

### ISSUE THREAD

**Issue by junkiebev** [metallb/metallb#1500]
Requested in https://github.com/metallb/metallb/pull/1264

In the event that one uses a secret ref for BGP password in a BGPPeer CRD:

* I'd presume that that secret is required to be in the same namespace as the MetalLB deployment, but the docs don't mention that - it does look like you can call out the namespace in the CRD, but if I'm reading the RBAC roles/clusterroles correctly, it won't work because the SA doesn't have secret read on all namespaces
* What's the Key it uses to grab a value? I'd guess `password`, based on my reading, but the docs don't specify and I didn't see the ability to specify the key in the CRD spec

**Comment by fedepaol** [comment]
Thanks for filing this!
