### ISSUE TITLE
Deleting CRD results in `could not list instances: unable to find a custom resource client for addresspools.metallb.io: unable to load root certificates: unable to parse bytes as PEM block`

### ISSUE THREAD

**Issue by optix2000** [metallb/metallb#1501]
I'm getting the following error when trying to delete the `addresspools` or `bgppeers` CRDs.

```
% kubectl describe customresourcedefinitions.apiextensions.k8s.io addresspools.metallb.io
...
  Client Config:
        Ca Bundle:  Cg==
...
  Conditions:
    Last Transition Time:  2022-07-14T08:19:58Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2022-07-14T08:19:58Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
    Last Transition Time:  2022-07-14T08:20:36Z
    Message:               could not list instances: unable to find a custom resource client for addresspools.metallb.io: unable to load root certificates: unable to parse bytes as PEM block
    Reason:                InstanceDeletionFailed
    Status:                True
    Type:                  Terminating
```

Installed MetalLB using the metallb Helm chart `v0.13.3` from https://metallb.github.io/metallb.
I then deleted the helm install shortly after when I realized it was installed to the wrong namespace.
Running k3s: `v1.23.8+k3s2`
Using Cilium `v1.11.6`

Presumably, this is because I deleted the controller before the CA could be populated [here](https://github.com/metallb/metallb/blob/main/charts/metallb/charts/crds/templates/crds.yaml#L26). Assuming that's the case, it's probably worth putting a "real" dummy CA so the CRD can be deleted if the controller never started.

Seeking some advice on whether it's safe to force delete the CRD and to see if adding a CA is a valid solution.

**Comment by fedepaol** [comment]
Understood, thanks for the report
