### ISSUE TITLE
Version v0.13.3 not yet stable.

### ISSUE THREAD

**Issue by adeniyistephen** [metallb/metallb#1502]
Thanks for filing an issue! A few things before we get started:

1. This is not the place to ask for troubleshooting. Unfortunately
   troubleshooting LB issues in k8s takes a lot of time and effort
   that we simply don't have. If your load-balancers aren't working,
   please don't file an issue unless you have identified a _specific_
   bug to fix. Otherwise, please ask for help in the `#metallb`
   channel on the Kubernetes Slack.
2. Please search the bug tracker for duplicates before filing your
   bug.
3. If you're reporting a bug, please specify all of the following:
     - The bug itself, as detailed as you can.
     - Version of MetalLB
     - Version of Kubernetes
     - Name and version of network addon (e.g. Calico, Weave...)
     - Whether you've configured kube-proxy for iptables or ipvs mode
     
     
ISSUE: After deploying the metallb manifest into my cluster and having configured my configs, I had some issues with the containers not starting up (controller and speaker pod). Here is the error:
```
Warning  DNSConfigForming  87s (x59 over 11m)  kubelet            Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 2a01:4ff:ff00::add:1 2a01:4ff:ff00::add:2 185.12.64.1
```
Kubernetes version: 
```
1.23.8
```
Network configuration
```
Calico v3.23
```
MetalLB version
```
v0.13.3
```
I'm using DigitalOcean as my cloud provider, so it does not support LB services by cloud controller. Thanks

**Comment by fedepaol** [comment]
Sorry, could you add more details and maybe help to reproduce it? I see the error is dns related, while metallb doesn't have anything to do with dns.
