### ISSUE TITLE
BGPAdvertisement with avoid-buggy-ips

### ISSUE THREAD

**Issue by nobiit** [metallb/metallb#1513]
Description:
I'm wanting to configure it to use`BGAdvertisement` instead of `L2Advertisement`. But it seems with`BGAdvertisement` it won't accept `avoid-buggy-ips`, and IP assignment will go bad

Reality:
I cannot configure BGAdvertisement if IPAddressPool is an IP range of the form (x.x.x.1-x.x.x.254)
```
Error from server (invalid aggregation length 22: prefix 26 in this pool is more specific than the aggregation length for addresses 10.100.1.1-10.100.1.254): error when creating "STDIN": admission webhook "bgpadvertisementvalidationwebhook.metallb.io" denied the request: invalid aggregation length 22: prefix 26 in this pool is more specific than the aggregation length for addresses 10.100.1.1-10.100.1.254
```

Expected:
I can configure BGAdvertisement using the IP range avoid-buggy-ips (x.x.x.1-x.x.x.254)

Note:
- Version MetalLB: metallb-0.13.3
- Version Kubernetes: v1.23.9
- CNI: Cilium

```
$ kubectl get ipaddresspools.metallb.io -n metallb-system -o yaml
apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    name: load-balancer-pool
    namespace: metallb-system
  spec:
    addresses:
    - 10.100.0.1-10.100.0.254
    - 10.100.1.1-10.100.1.254
    - 10.100.2.1-10.100.2.254
    - 10.100.3.1-10.100.3.254
    autoAssign: true
kind: List
metadata:
  resourceVersion: ""
```
```
apiVersion: metallb.io/v1beta1
Kind: BGPAdvertisement
metadata:
  name: load-balancer
  namespace: metallb-system
spec:
  ipAddressPools:
    - load-balancer-pool
  aggregationLength: 22
  localPref: 100
```

**Comment by oribon** [comment]
hey, thanks for reporting! 
closing this as it looks like https://github.com/metallb/metallb/issues/1495 and would be solved in https://github.com/metallb/metallb/pull/1503.
feel free to re-open this if I got it wrong :)
