### ISSUE TITLE
Auto generate the CRDs under charts

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1520]
The crds under config are generated by controller-gen when we run inv generatemanifests.
Having a way to translate them in manifests under the chart will reduce the risk of manual error.

**Comment by tylerauerbeck** [comment]
@fedepaol I can take a look at this.

I've seen this done before, but it generally involves a workflow that runs on pushes to main that: 
- generates the crds
- copies them to /crds under the helm chart
- pushes the changes to main

Before I started anything here, wanted to see what the feeling on that approach was or if a different approach would be desired.

**Comment by fedepaol** [comment]
I think we just need the first two steps (not pushing the changes), plus:
- having CI enforcing they are always aligned
- probably (don't remember) having to add some sed-fu if part of the CRDs are templated

You can chain the check here https://github.com/metallb/metallb/blob/b8ad9626131e00d74a964572d19478a0e263b3c7/.github/workflows/ci.yaml#L71

**Comment by funkycode** [comment]
well, if you touching this area, any chance you adjust generation to include clientSet for metallb, as currently it only has definitions of CRs but not client that will allow to easily CRUD CRs. if not - I was planing to poke this around and try to make PR myself, but not sure when I'll be able to get there.
