### ISSUE TITLE
Problem with Kustomize installation resource for Metallb 0.13.z native bgp implementation

### ISSUE THREAD

**Issue by ehlesp** [metallb/metallb#1524]
While trying to deploy Metallb **0.13.3** (native bgp implementation) with kustomize, I've met the following error:

`Error: accumulating resources: accumulation err='accumulating resources from 'github.com/metallb/metallb/config/native?ref=0.13.0': evalsymlink failure on '/home/user/WS/k8sprjs/metallb/github.com/metallb/metallb/config/native?ref=0.13.0' : lstat /home/user/WS/k8sprjs/metallb/github.com: no such file or directory': git cmd = '/usr/bin/git fetch --depth=1 origin 0.13.0': exit status 128`

At first, I though it was a problem with my kubectl client (**v1.22.4**), so I upgraded it to the latest version available (**v1.24.3**), but the error still happens. This error **doesn't** occur with the resource indicated for the experimental FRR mode, nor with an older version's resource path such as the one for the **0.11.0** version (`github.com/metallb/metallb//manifests?ref=v0.11.0`).

So it seems that either the kustomize resource path for the Metallb **0.13.3** (native bgp implementation) is wrong, or there's a problem on the github side.

For reference, [here I link to the documentation about the installation with kustomize](https://metallb.universe.tf/installation/#installation-with-kustomize).

**Comment by fedepaol** [comment]
It's a doc issue referencing the wrong tags.
The right ones are:
  - github.com/metallb/metallb/config/native?ref=v0.13.3

and 
  - github.com/metallb/metallb/config/frr?ref=v0.13.3

**Comment by ehlesp** [comment]
That was fast! Many thanks, @fedepaol .
