### ISSUE TITLE
configmaptocrs: allow it to run in k8s and work only with the data part of the configMap

### ISSUE THREAD

**Issue by tamcore** [metallb/metallb#1527]
The described way to run the configmaptocrs image isn't ideal, as it requires to have Docker installed and the exported configMap available locally.

I thought about an approach like
```
kubectl -n metallb-system run configmaptocrs --restart=Never -it --rm --image overriden --overrides '
{
  "spec": {
    "containers": [
      {
        "name": "configmaptocrs",
        "image": "quay.io/metallb/configmaptocrs",
        "command": [
          "/configmaptocrs",
          "-source",
          "config"
        ],
        "volumeMounts": [
          {
            "name": "config",
            "mountPath": "/var/input"
          }
        ]
      }
    ],
    "volumes": [
      {
        "name": "config",
        "configMap": {
          "name": "config"
        }
      }
    ]
  }
}'
```
as that would make it much easier. But that brings a few issues:
- the tool forces the output file to be in /var/input as well (which would be R/O, if the configMap is mounted there)
- the tool expects the entire configMap defintion (which wouldn't be present, as only the configMap data is presented)

Suggestion:
- Make it possible to pass an output file, or fallback to /dev/stdout, if the resources.yaml can't be created due to R/O filesystem
- Make the entire configMap spec optional and allow the tool to work just with the exported configFile itself

**Comment by fedepaol** [comment]
We had a discussion about shipping the binary itself vs shipping the docker image, and we thought the latter would've benefits in terms of portability / shipping. We could think about shipping the binaries, but I am not sure it's worth the effort.
 
Both the suggestions sound doable, and your approach is also smart, I'll consider adding it to the docs.

**Comment by liornoy** [comment]
Hello @tamcore thanks for the great suggestions I am working on it!
