### ISSUE TITLE
Dev-env -p bgp / l2 fails the webhook validation

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1535]
When running dev-env with a prefixed configuration (-p bgp for example) we don't wait for the controller to be in place, so the creation of the configuration fails because the backend of the webhook is not running yet.

**Comment by karampok** [comment]
A simple sleep
```
cat tasks.py |grep -C2 sleep
        f.write(mlb_config)
    # Apply the MetalLB ConfigMap
    run("sleep 30")
    run("kubectl apply -f %s/config.yaml" % dev_env_dir)
```
seems to work consistently but maybe something more like checking a health endpoint or re-trying some times before fail would be better approach.

**Comment by fedepaol** [comment]
yep, either waiting for the pods to be running (I think we have that check somewhere before running the e2e tests) or retrying applying the configuration for some time should work
