### ISSUE TITLE
Speaker seems to need additional ports not only 7946 and 179

### ISSUE THREAD

**Issue by romulus-ai** [metallb/metallb#1539]
Running in RKE1 K8S Version 1.23.7 and calico 3.22.0. Metallb Version is 0.13.4. I've configured kube-proxy in IPVS Mode.

As described in the docs, I allowed port 7946 TCP and UDP on all K8S Hosts via Calico GlobalNetworkPolicy as ingress destination ports. Additionally I allowed Port 179 TCP and UDP as well, since I know, Bird needs it.

When I deploy MetalLB via the Manifest for your Docs or via Helm, the Speaker is not able to start. It logs the following and after a while it shuts down:

>
{"caller":"speakerlist.go:256","error":"1 error occurred:\n\t* Failed to join 10.100.100.135:7946: dial tcp 10.100.100.135:7946: connect: connection refused\n\n","expected":1,"joined":0,"level":"error","msg":"partial join","op":"memberDiscovery","ts":"2022-07-27T10:07:05Z"}

However, when I Additionally allow the TCP Ports from 1024-65535, Speaker comes Up without trouble. Even when I only allow 1024-10000 TCP it comes up.

So for me it seems there is somewhere some additional port or connection needed within this 1024-10000 TCP area. However I already checked 8080, 8443 and 9443 is not.

**Comment by fedepaol** [comment]
Hi @romulus-ai , that's the port used by the memberlist election for choosing the leader of l2 services.
If you use the helm charts, you can tweak the port via this value https://github.com/metallb/metallb/blob/710125677d2b443d8ea79f155241127a2269a28d/charts/metallb/values.yaml#L194

**Comment by romulus-ai** [comment]
Hi @fedepaol thanks for your reply. This port is definitly not blocked. And via Helmchart I do not change it.

**Comment by fedepaol** [comment]
Oh, sorry I think I misunderstood the question.
If the error you posted never goes away, then it might be the cause. Otherwise there might be other causes. Havign the full log of the speaker with loglevel set to debug would ease the analysis

**Comment by fedepaol** [comment]
That error states that it's not able to reach that host / port, which may be because of something on the network is blocking it, or because the other end is not listening. I don't recall that error causing the speaker to shutdown, so it might be a red herring

**Comment by romulus-ai** [comment]
Here we go, a nice debug log of one of the speakers.

[speaker.log](https://github.com/metallb/metallb/files/9197992/speaker.log)

It seems something is blocked which is needed by Speaker, however it is not Port 7946 since its definitly free and the other speaker is also listening. What I am wondering is what else is blocked here?

**Comment by fedepaol** [comment]
So this log
```
{"caller":"main.go:114","level":"info","msg":"starting shutdown","op":"shutdown","ts":"2022-07-27T11:18:32Z"}
```
is coming from here https://github.com/metallb/metallb/blob/9fce695d5b5b7ed1bc7e865f8122ffc7f5c5945d/speaker/main.go#L114
Which means that the process received one of
syscall.SIGINT, syscall.SIGQUIT, syscall.SIGTERM

Can you check the events? Maybe the pod was killed due to memory or some other constraint

**Comment by romulus-ai** [comment]
Hmm, may this event comes from the controller, because the pod is not coming up. I mean, it has a healthcheck that is failing as long as it cannot connect to the other speaker.

**Comment by fedepaol** [comment]
Can you run a describe on the pod? Should tell us why the container is terminated I think

**Comment by romulus-ai** [comment]
So, these are the events:

20s         Normal    Pulled      pod/metallb-speaker-4zjbj   Container image "quay.io/metallb/speaker:v0.13.4" already present on machine
20s         Normal    Created     pod/metallb-speaker-4zjbj   Created container speaker
20s         Normal    Started     pod/metallb-speaker-4zjbj   Started container speaker
1s          Warning   Unhealthy   pod/metallb-speaker-4zjbj   Liveness probe failed: Get "http://10.100.129.134:7472/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
20s         Warning   Unhealthy   pod/metallb-speaker-4zjbj   Readiness probe failed: Get "http://10.100.129.134:7472/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
1s          Warning   Unhealthy   pod/metallb-speaker-4zjbj   Readiness probe failed: Get "http://10.100.129.134:7472/metrics": dial tcp 10.100.129.134:7472: i/o timeout (Client.Timeout exceeded while awaiting headers)
21s         Normal    Killing     pod/metallb-speaker-4zjbj   Container speaker failed liveness probe, will be restarted
41s         Warning   Unhealthy   pod/metallb-speaker-4zjbj   Liveness probe failed: Get "http://10.100.129.134:7472/metrics": dial tcp 10.100.129.134:7472: i/o timeout (Client.Timeout exceeded while awaiting headers)
20s         Normal    Pulled      pod/metallb-speaker-x27lw   Container image "quay.io/metallb/speaker:v0.13.4" already present on machine
20s         Normal    Created     pod/metallb-speaker-x27lw   Created container speaker
20s         Normal    Started     pod/metallb-speaker-x27lw   Started container speaker
1s          Warning   Unhealthy   pod/metallb-speaker-x27lw   Readiness probe failed: Get "http://10.100.129.135:7472/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
1s          Warning   Unhealthy   pod/metallb-speaker-x27lw   Liveness probe failed: Get "http://10.100.129.135:7472/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
21s         Normal    Killing     pod/metallb-speaker-x27lw   Container speaker failed liveness probe, will be restarted
31s         Warning   Unhealthy   pod/metallb-speaker-x27lw   Readiness probe failed: Get "http://10.100.129.135:7472/metrics": dial tcp 10.100.129.135:7472: i/o timeout (Client.Timeout exceeded while awaiting headers)
21s         Warning   Unhealthy   pod/metallb-speaker-x27lw   Liveness probe failed: Get "http://10.100.129.135:7472/metrics": dial tcp 10.100.129.135:7472: i/o timeout (Client.Timeout exceeded while awaiting headers)


And the single pod also has the liveness and readynessprobe as reason for the restart.

**Comment by fedepaol** [comment]
Ok, so that's the reason why it's going down.
Can you give us the output of kubectl get pods -o yaml on that speaker?

**Comment by romulus-ai** [comment]
Here it is, of just one Speaker Pod, this way it is not this much yaml.

```yaml
# kubectl get pods metallb-speaker-4zjbj -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: "7472"
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-07-27T11:17:51Z"
  generateName: metallb-speaker-
  labels:
    app.kubernetes.io/component: speaker
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/name: metallb
    controller-revision-hash: c94bc8f4c
    pod-template-generation: "1"
  name: metallb-speaker-4zjbj
  namespace: metallb-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: metallb-speaker
    uid: 2248a31a-e19e-4e4d-8235-905848fa68a3
  resourceVersion: "43775"
  uid: 652a6de0-cdb9-4d1b-be6e-b0e778eb7258
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - de-szr-k8s-t4
  containers:
  - args:
    - --port=7472
    - --log-level=debug
    env:
    - name: METALLB_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: METALLB_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: METALLB_ML_BIND_ADDR
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: METALLB_ML_LABELS
      value: app.kubernetes.io/name=metallb,app.kubernetes.io/component=speaker
    - name: METALLB_ML_BIND_PORT
      value: "7946"
    - name: METALLB_ML_SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: secretkey
          name: metallb-memberlist
    image: quay.io/metallb/speaker:v0.13.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: monitoring
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: speaker
    ports:
    - containerPort: 7472
      hostPort: 7472
      name: monitoring
      protocol: TCP
    - containerPort: 7946
      hostPort: 7946
      name: memberlist-tcp
      protocol: TCP
    - containerPort: 7946
      hostPort: 7946
      name: memberlist-udp
      protocol: UDP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: monitoring
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_RAW
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zzs4p
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: de-szr-k8s-t4
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: metallb-speaker
  serviceAccountName: metallb-speaker
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - name: kube-api-access-zzs4p
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-07-27T11:17:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-07-27T12:54:22Z"
    message: 'containers with unready status: [speaker]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-07-27T12:54:22Z"
    message: 'containers with unready status: [speaker]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-07-27T11:17:51Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://91313d3deb22e2f084819c2cb7ca86077e804d51872c7e96103bfcc529a969ee
    image: quay.io/metallb/speaker:v0.13.4
    imageID: docker-pullable://quay.io/metallb/speaker@sha256:3f4c538bb3b3d2af51fbb3cf2a118a71aae3707cf42cdf179d14101bf2e0ea15
    lastState:
      terminated:
        containerID: docker://91313d3deb22e2f084819c2cb7ca86077e804d51872c7e96103bfcc529a969ee
        exitCode: 0
        finishedAt: "2022-07-27T13:03:02Z"
        reason: Completed
        startedAt: "2022-07-27T13:02:31Z"
    name: speaker
    ready: false
    restartCount: 13
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=speaker pod=metallb-speaker-4zjbj_metallb-system(652a6de0-cdb9-4d1b-be6e-b0e778eb7258)
        reason: CrashLoopBackOff
  hostIP: 10.100.129.134
  phase: Running
  podIP: 10.100.129.134
  podIPs:
  - ip: 10.100.129.134
  qosClass: BestEffort
  startTime: "2022-07-27T11:17:51Z"

```

**Comment by fedepaol** [comment]
Weird, the port is there, and looking at the logs I think it started listening. Can you try to remove the probe from the pod definition, jump on the pod and try to curl that endpoint to see if it responds?

**Comment by romulus-ai** [comment]
Hell, got the problem. At some place in the docs, I found, that MetalLB needs port 7946 TCP and UDP for the Speakers to find each other.

However it seems you also need to allow 7472/TCP (Metrics) on a host basis, for the liveness and readiness checks to be successful.

I only had a Policy to allow all traffic from 127.0.0.1 for the Liveness and Readinesschecks, however it seems that this is not enought, 7472 must be allowed for the host.

@fedepaol Thanks you so much for your help! I only found it, because of you last reply 6 Days ago! 

So I'll close this now, however may to list of needed Ports should be extended.

**Comment by asadanas** [comment]
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Normal   Pulled     38m (x24 over 98m)     kubelet  Container image "quay.io/metallb/controller:v0.13.7" already present on machine
  Warning  Unhealthy  8m41s (x53 over 98m)   kubelet  Liveness probe failed: Get "http://10.42.0.2:7472/metrics": dial tcp 10.42.0.2:7472: connect: connection refused
  Warning  BackOff    3m41s (x386 over 97m)  kubelet  Back-off restarting failed container controller in pod controller-789c75c689-464tk_metallb-system(0150eafc-5a23-436b-8517-1740c6ae4c49)
root@kubernetes-master:~#

I am facing this issue can you help me please?
