### ISSUE TITLE
configsamples URL is 404

### ISSUE THREAD

**Issue by lrosenman** [metallb/metallb#1541]
on the readme / install page, it links to this URL: 
```
https://raw.githubusercontent.com/metallb/metallb/v0.13.4/configsamples
```
but that URL is 404.

**Comment by lrosenman** [comment]
the pointer is (at least) at:
```
https://metallb.universe.tf/configuration/
```

**Comment by fedepaol** [comment]
Hi, thanks for the report. We have https://github.com/metallb/metallb/pull/1531 open that should address that

**Comment by fedepaol** [comment]
Merged, closing this

**Comment by lrosenman** [comment]
still 404 :(

**Comment by fedepaol** [comment]
The fix is in, but to see it we need to cut a new release and update the docs with that.

**Comment by lrosenman** [comment]
Ah -- sorry for the noise :)
