### ISSUE TITLE
CIS Benchmark and compliance for MetalLB community version 13.4

### ISSUE THREAD

**Issue by Manvir-nokia** [metallb/metallb#1550]
As part of CIS security compliance check we have below observations from Metallb. Can you please check and suggest what could be remediated and what are the fixes to remediate the below clauses:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/manvisin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/manvisin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Rule   Name | Metallb | Rule Description | Remediation
-- | -- | -- | --
Minimize access to secrets | Below two roles having access to   secret, please review if these are required and if not remove the access to   secret from the roles. | The Kubernetes   API stores secrets, which may be service account tokens for the Kubernetes   API or credentials used by workloads in the cluster. Access to these secrets   should be restricted to the smallest possible group of users to reduce the   risk of privilege escalation. | Where possible,   remove get, list and watch access to secret objects in the cluster.
Ensure that Service Account Tokens are only   mounted where necessary | Can check if automountServiceAccountToken:   false can be added to the pods definition ? | Service   accounts tokens should not be mounted in pods except where the workload   running in the pod explicitly needs to communicate with the API server | Modify the   definition of pods and service accounts which do not need to mount service   account tokens to disable it.
Prefer using secrets as files over secrets   as environment variables | Below   Daemonset is using the secret as environment variable but as per CIS rule   secrets should be mounted and used and should not be used as environment   variable. Can we check if this can be changed to not use the secrets as   environment variable?           Pod: metallb-nom-metallb-speaker-pbd9j     Pod: metallb-nom-metallb-speaker-sgfw2     DaemonSet: metallb-nom-metallb-speaker | Kubernetes   supports mounting secrets as data volumes or as environment variables.   Minimize the use of environment variable secrets | If   possible, rewrite application code to read secrets from mounted secret files,   rather than from environment variables
Ensure that   the seccomp profile is set to docker/default in your pod definitions | This we are checking with RedHat and   will update if need to add any seccomp profile. | Enable default   seccomp profile in your pod definitions | By default,   seccomp profile is set to unconfined which means that no seccomp profiles are   enabled
Apply Security Context to Your Pods and   Containers | Privileged scc is used – can we check if metallb will work   with less privileged scc like (non-root, anyuid or restricted ) | Apply Security Context to Your   Pods and Containers | Follow the Kubernetes   documentation and apply security contexts to your pods. For a suggested list   of security contexts, you may refer to the CIS Security Benchmark for Docker   Containers

</body>

</html>

**Comment by ssivasankarrao** [comment]
Can you tell us the reason why files are preferable to environment variables when it comes to secrets?

As per CIS benchmark - "It is reasonably common for application code to log out its environment (particularly in the event of an error). This will include any secret values passed in as environment variables, so secrets can easily be exposed to any user or entity who has access to the logs."

**Comment by ssivasankarrao** [comment]
Any update on this please.

**Comment by fedepaol** [comment]
If a user is able to access the logs, is also likely to be able to inspect the secrets in the namespace and even to jump on the pod to check the files. 
I am not even sure MetalLB ever dumps the env variable, I'd say it does not. This doesn't feel a priority to us by the time being.
