### ISSUE TITLE
PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

### ISSUE THREAD

**Issue by zulhfreelancer** [metallb/metallb#1555]
- The bug:

  I'm seeing `Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+` when installing the latest (v0.13.4) version of MetalLB.

  I know it's just a warning - but, given that k8s v1.25 is going to be [released soon](https://www.kubernetes.dev/resources/release/#timeline), I think the [install manifest](https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/manifests/metallb-native.yaml) needs to be updated.

  From [docs](https://kubernetes.io/docs/concepts/security/pod-security-policy/):

  > Caution: PodSecurityPolicy is deprecated as of Kubernetes v1.21, and will be removed in v1.25. We recommend migrating to [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/), or a 3rd party admission plugin.

  Full traces:

  ```
  $ kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/manifests/metallb-native.yaml
  
  namespace/metallb-system created
  customresourcedefinition.apiextensions.k8s.io/addresspools.metallb.io created
  customresourcedefinition.apiextensions.k8s.io/bfdprofiles.metallb.io created
  customresourcedefinition.apiextensions.k8s.io/bgpadvertisements.metallb.io created
  customresourcedefinition.apiextensions.k8s.io/bgppeers.metallb.io created
  customresourcedefinition.apiextensions.k8s.io/communities.metallb.io created
  customresourcedefinition.apiextensions.k8s.io/ipaddresspools.metallb.io created
  customresourcedefinition.apiextensions.k8s.io/l2advertisements.metallb.io created
  serviceaccount/controller created
  serviceaccount/speaker created
  Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  podsecuritypolicy.policy/controller created
  podsecuritypolicy.policy/speaker created
  role.rbac.authorization.k8s.io/controller created
  role.rbac.authorization.k8s.io/pod-lister created
  clusterrole.rbac.authorization.k8s.io/metallb-system:controller created
  clusterrole.rbac.authorization.k8s.io/metallb-system:speaker created
  rolebinding.rbac.authorization.k8s.io/controller created
  rolebinding.rbac.authorization.k8s.io/pod-lister created
  clusterrolebinding.rbac.authorization.k8s.io/metallb-system:controller created
  clusterrolebinding.rbac.authorization.k8s.io/metallb-system:speaker created
  secret/webhook-server-cert created
  service/webhook-service created
  deployment.apps/controller created
  daemonset.apps/speaker created
  validatingwebhookconfiguration.admissionregistration.k8s.io/metallb-webhook-configuration created
  ```

- Version of MetalLB: v0.13.4 
- Version of Kubernetes: v1.24.3+k0s
- Name and version of network addon: kube-router (v1.4.0)
- Whether you've configured kube-proxy for iptables or ipvs mode: iptables

**Comment by fedepaol** [comment]
Hi, thanks for raising the issue, we are aware of that. Closing as dupe of https://github.com/metallb/metallb/issues/1401
Once 1.25 goes out (and 1.22 is officially deprecated) we'll cut a new release and align our CI.

**Comment by rikirolly** [comment]
Has someone found a solution for this?
