### ISSUE TITLE
Add a status to IPAddressPool CR indicting if it is active or not

### ISSUE THREAD

**Issue by qingwusunny** [metallb/metallb#1556]
After update a IPAddressPool success, Controller will reload all IP pool config. If an allocated IP does not exist in the new IP pool, setPool will failed. So I think we can add a status to IPAddressPool CR indicting if it is effective or not.

**Comment by qingwusunny** [comment]
@fedepaol WDYT?

**Comment by fedepaol** [comment]
I think the general status exposure is way broader than this, and will file a design proposal soon-ish to collect all my considerations.
I'd rather trying to collect all the status we want to expose in a single document instead of starting implementing pieces.

**Comment by qingwusunny** [comment]
ok
I'm very happy about the status design

**Comment by chnhaoran** [comment]
Seems great! BTW, @fedepaol Federico can you pls let us know what kinds of fields may be inserted to the Status?

**Comment by fedepaol** [comment]
I am not sure yet! That will be part of the proposal, which will obviously open for discussion before we merge it
