### ISSUE TITLE
MetalLB fails to check endpoints availability when using Multus in the pods

### ISSUE THREAD

**Issue by smartinj** [metallb/metallb#1559]
Hello, we have a deployment were MetalLB is not able to know when and endpoint gets unavailable if the service is listening in a secondary interface configured with Multus.

New requests reaching MetalLB endpoint are forwarded to any endpoint regardless of its state, so the service consumer gets an error.

In this particular case the service behind MetalLB is a couple of Virtual Machines running in Openshift Virtualization

MetalLB was deployed with the operator v0.12.0 so the version is v0.12.0
We are using Openshift 4.8 so  Kubernetes 1.21
We are using Openshift SDN as the SDN

Thanks.

KR,
Javier.

**Comment by fedepaol** [comment]
Hi, the availability of the endpoint of a kubernetes service (and thus, the services exposed by metallb) is done by checking their endpoint condition (in the endpoint slices crd). This is given by kubernetes checking their readiness probe.
Multus and secondary interfaces doesn't get involved at all in metallb.

Closing the issue.
