### ISSUE TITLE
MetalLB provides LB Services with IP Addresses but doesn't announce and ARP for the address

### ISSUE THREAD

**Issue by Manvir-nokia** [metallb/metallb#1561]
Problem Statement: External IPs assigned by Metallb are getting assigned to Load balancer services but the Ips are not reachable.

Checked:
 - Controller logs: IP allocation success events are there.
 - Speaker Logs: IP announcement logs are not there
 - ipaddresspool: is created and working.
 - Tried ARPing to external IP from a different worker node not hosting speaker pods: ARPING has no response.

Need assistance to identify the fix of the issue.

**Comment by oribon** [comment]
hey, 
did you create l2advertisements for your ipaddresspool?
if so, can you specify what's the metallb/k8s version, attach the logs (after setting debug log level if possible) and a describe of the service?

**Comment by Manvir-nokia** [comment]
> hey, did you create l2advertisements for your ipaddresspool? if so, can you specify what's the metallb/k8s version, attach the logs (after setting debug log level if possible) and a describe of the service?

**Comment by Manvir-nokia** [comment]
> > hey, did you create l2advertisements for your ipaddresspool? if so, can you specify what's the metallb/k8s version, attach the logs (after setting debug log level if possible) and a describe of the service?

yea, i figured this out yesterday that l2advertisements was missing. creating the l2advertisement resolved the issue. I refered this https://github.com/metallb/metallb/issues/1358 to resolve the issue. However, thanks a lot for checking.
