### ISSUE TITLE
x509: certificate is valid for localhost, not webhook-service.metallb-system.svc

### ISSUE THREAD

**Issue by sanzhar-rakhimkul** [metallb/metallb#1563]
MetalLB 0.13.4

Kubernetes v1.23.3

cat pool.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.152.116.8-10.152.116.16
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool

10.152.116.8-10.152.116.16
kubectl apply -f pool.yaml

Error from server (InternalError): error when creating "configuration.yaml": Internal error occurred: failed calling webhook "l2advertisementvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-l2advertisement?timeout=10s": x509: certificate is valid for localhost, not webhook-service.metallb-system.svc

**Comment by Scubastooge** [comment]
Had the same issue.
Can confirm rolling back to 0.13.3 fixed.

**Comment by sanzhar-rakhimkul** [comment]
> Had the same issue. Can confirm rolling back to 0.13.3 fixed.

I roll back to 0.13.2 and 0.12.1 both didn't work. Have same error. Previously I had metallb working but after cluster reset everything stop working. Using same yaml files.

**Comment by fedepaol** [comment]
@sanzhar-rakhimkul there's no crds nor webhooks in 0.12.x, how can  you have the same error?

**Comment by fedepaol** [comment]
Closing in favor of https://github.com/metallb/metallb/issues/1597, please provide the information requested there.

**Comment by sanzhar-rakhimkul** [comment]
I solved the problem. It happened because of my http_proxy set and I could not access webhook directly. It went to proxy server which uses self-signed certificate and got the problem. It was really hard to debug

**Comment by fedepaol** [comment]
Thanks for the follow up!

**Comment by mschauf** [comment]
Got nearly the same problem when creating a ip pool:

`Error "failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": x509: certificate is valid for metallb-operator-webhook-server-service.metallb-system, metallb-operator-webhook-server-service.metallb-system.svc, not webhook-service.metallb-system.svc" for field "undefined".`

Proxy conf has ".svc" in NO_PROXY...so...?

```
name: HTTP_PROXY
              value: 'http://user:pass@proxy.domain.xx:8080'
            - name: HTTPS_PROXY
              value: 'http://user:pass@proxy.domain.xx:8080'
            - name: NO_PROXY
              value: >-
                .cluster.local,.svc,10.0.0.0/16,10.128.0.0/14,127.0.0.1,172.30.0.0/16,api-int.domain.xx,localhost
```

Any hints on this?
