### ISSUE TITLE
Improve logging around config status

### ISSUE THREAD

**Issue by djryanj** [metallb/metallb#1568]
Opening issue as requested by @fedepaol .

May I suggest as an improvement to the controller to help people that logging be improved around the config.

I was only able to sort out that I was missing a config because of this line after enabling debugging: https://github.com/metallb/metallb/blob/main/controller/main.go#L64

Which pointed me in the right direction, but as far as I can tell that's the only place where any mention of a config is made in the logs (and at a deeper debug level). 

Instead, on startup (and/or configuration/reconfiguration) some logging in the controller about the current state of the config (present, not present, correct, incorrect) be logged to `info` with details dumped to `debug` levels.

_Originally posted by @djryanj in https://github.com/metallb/metallb/issues/1473#issuecomment-1213226989_

**Comment by kevydotvinu** [comment]
@fedepaol, can I work on this?

**Comment by fedepaol** [comment]
sure thing! Assigning this to you

**Comment by fedepaol** [comment]
fixed by https://github.com/metallb/metallb/pull/1958

**Comment by fedepaol** [comment]
Closing, with the controllers the configuration is dumped (or at least a log is produced) the first time the config on the cluster is being processed.
