### ISSUE TITLE
Pending 0.13.5 release

### ISSUE THREAD

**Issue by carrodher** [metallb/metallb#1582]
Thanks for the new release! I just discovered that for this new version there are, as expected, two [tags](https://github.com/metallb/metallb/tags):
![Screenshot 2022-09-02 at 16 15 56](https://user-images.githubusercontent.com/13216600/188168850-8939ccf6-e0cb-45a3-b066-c162d8a744a4.png)

But there is only one [release](https://github.com/metallb/metallb/releases):
![Screenshot 2022-09-02 at 16 17 31](https://user-images.githubusercontent.com/13216600/188168964-868b6fa1-a332-4f52-807f-4473c9a0e3ca.png)

Do you have plans to cut a release for `v0.13.5` as usual? Thanks!

**Comment by fedepaol** [comment]
Apologies, I forgot to do that! I will do it right now.
Please note that the images and the charts are already available.
