### ISSUE TITLE
ERROR: ip allocated by controller not allowed by config [Only version v0.11.0 works]

### ISSUE THREAD

**Issue by tebaly** [metallb/metallb#1584]
Hello friends.

You can check? This is really a problem!
https://groups.google.com/g/metallb-users/c/4TGU39ZhLxQ

Weird errors like this. In the latest versions
> ip allocated by controller not allowed by config

Only version v0.11.0 works for me. The settings are identical, only the Helm Chart version is different (https://charts.bitnami.com/bitnami)

> I found that if I use v0.11.0 manifests to install metallb it still works.  So it seems like the "recent" change has broken metallb+kind
https://groups.google.com/g/metallb-users/c/4TGU39ZhLxQ/m/8pXujAqUAgAJ

**Comment by fedepaol** [comment]
Hi, can you paste your configuration and the full error?
Also, the logs of the speaker pods?

**Comment by fedepaol** [comment]
Hi @tebaly , can you make sure it's not related to https://github.com/metallb/metallb/issues/1473 too ?

**Comment by fedepaol** [comment]
Closing this because there was no reply, feel free to reopen if you have the information requested
