### ISSUE TITLE
Support Protocol: None / Speaker-less mode

### ISSUE THREAD

**Issue by simplysoft** [metallb/metallb#1585]
We are running kube-router with `--advertise-loadbalancer-ip`, so there is no need for metallb to advertise the ips via BGP or in layer 2. It would be great if the speaker-less mode would be "officially" supported by allowing to configure `protocol: none` as suggest in https://github.com/metallb/metallb/issues/114#issuecomment-858601259

**Comment by fedepaol** [comment]
Hi @simplysoft , with the current crd layout this is now possible.
Creating an instance of IPAddressPool will make the ip assigned to the service, but if you don't create any BGP / L2 advertisement instances, it won't be advertised.
