### ISSUE TITLE
kubernetes v.1.25.0 compatible APIs for metallb

### ISSUE THREAD

**Issue by Manvir-nokia** [metallb/metallb#1587]
with the release of kubernetes v.1.25.0 what is the plan to have compatible APIs for metallb because the below api resources use apiversion: metallb.io/v1beta1 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/manvisin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/manvisin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Name | APIVERSION | NAMESPACED | KIND
-- | -- | -- | --
addresspools | metallb.io/v1beta1 | TRUE | AddressPool
bfdprofiles | metallb.io/v1beta1 | TRUE | BFDProfile
bgpadvertisements | metallb.io/v1beta1 | TRUE | BGPAdvertisement
communities | metallb.io/v1beta1 | TRUE | Community
ipaddresspools | metallb.io/v1beta1 | TRUE | IPAddressPool
l2advertisements | metallb.io/v1beta1 | TRUE | L2Advertisement

</body>

</html>

**Comment by fedepaol** [comment]
That won't change the compatibility with 1.25
The beta1 is related to metallb crds, which are compatible with 1.25
