### ISSUE TITLE
feature-request: fallback to SingleStack when PreferDualStack

### ISSUE THREAD

**Issue by woodgear** [metallb/metallb#1589]
metallb-version 0.13.4
k8s-version 1.23.8

https://github.com/metallb/metallb/blob/91b34a0a7b8d6fe3735a204c6b2c205133bb9d6a/internal/allocator/allocator.go#L262

is should be better if we could fallback to singleStack when preferDualStack.

**Comment by fedepaol** [comment]
I think this makes sense, thanks for raising it!

**Comment by hongzhen-ma** [comment]
The details about this issue：
1、The cluster  is dual-stack，and the para in kube-apiserver is `- --service-cluster-ip-range=10.4.0.0/16,fd00:10:96::/112`
2、The  ipaddresspools crd used for metallb, all the pools are IPv4 protocol:
# kubectl get ipaddresspools -A
NAMESPACE        NAME   AGE
metallb-system   ip     4h25m
metallb-system   test   4h36m
# kubectl get ipaddresspools -o yaml -n metallb-system ip
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  annotations:
    cpaas.io/creator: admin@cpaas.io
    cpaas.io/updated-at: "2022-09-06T03:09:55Z"
  creationTimestamp: "2022-09-06T03:09:55Z"
  generation: 1
  name: ip
  namespace: metallb-system
  resourceVersion: "43816"
  uid: d7850ace-86f2-47d7-b535-697fea368a6d
spec:
  addresses:
  - 1.1.1.1/24
  autoAssign: true
  avoidBuggyIPs: false
# kubectl get ipaddresspools -o yaml -n metallb-system test
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  annotations:
    cpaas.io/creator: admin@cpaas.io
    cpaas.io/operator: admin@cpaas.io
    cpaas.io/updated-at: "2022-09-06T06:15:27Z"
  creationTimestamp: "2022-09-06T02:59:23Z"
  generation: 4
  name: test
  namespace: metallb-system
  resourceVersion: "233317"
  uid: 30986975-5bb2-41f5-aacb-04b23e5fa175
spec:
  addresses:
  - 192.168.131.15/32
  - 192.168.130.146/32
  - 192.168.130.243/32
  autoAssign: true
  avoidBuggyIPs: false 

3、create LB Svc with dual-stack，and the svc is pending
# kubectl get svc -n sy-o
NAME           TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)        AGE
svc1           LoadBalancer   10.4.213.91    <pending>        80:32667/TCP   4h28m
# kubectl get svc -n sy-o -o yaml svc1
apiVersion: v1
kind: Service
metadata:
  annotations:
    cpaas.io/creator: admin@cpaas.io
    cpaas.io/display-name: ""
    cpaas.io/operator: admin@cpaas.io
    cpaas.io/updated-at: "2022-09-06T03:11:05Z"
    ovn.kubernetes.io/vpc: ovn-cluster
    resource.cpaas.io/reference: '["Deployment.app-qaimages"]'
  creationTimestamp: "2022-09-06T03:10:12Z"
  name: svc1
  namespace: sy-o
  resourceVersion: "234050"
  uid: 22447fa6-94ac-4b94-bc3a-df6d629569e6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.4.213.91
  clusterIPs:
  - 10.4.213.91
  - fd00:10:96::b823
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
  - appProtocol: tcp
    name: tcp-80-80
    nodePort: 32667
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.cpaas.io/name: app.sy-o
    project.cpaas.io/name: sy
    service.cpaas.io/name: deployment-app-qaimages
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

**Comment by woodgear** [comment]
> I think this makes sense, thanks for raising it!

a simple and small change  could be https://github.com/metallb/metallb/pull/1590

**Comment by fedepaol** [comment]
closing as superseeded by https://github.com/metallb/metallb/issues/1776
