### ISSUE TITLE
ignore tentative dadfailed ipv6 address

### ISSUE THREAD

**Issue by woodgear** [metallb/metallb#1592]
metallb-version 0.13.4
k8s-version 1.23.8

https://github.com/metallb/metallb/blob/8377501adec634ecfa7a215560daa2c81c31c025/internal/layer2/announcer.go#L115
it may report error like ' cannot assign requested address' when you try to bind a ipv6 address which is [tentative dadfailed](https://serverfault.com/a/829646/767524)

to fix it. i though we could just ignore address which have those flag.

**Comment by fedepaol** [comment]
Sorry for the delay, not sure I understand the issue.
My understanding from the link you posted is, we are trying to use a dupe v6 address on the subnet.
If that is the case, I think it's totally legit to have the error.
