### ISSUE TITLE
Feature Request | Add possible to use address-pool per-namespace annotations

### ISSUE THREAD

**Issue by germetist** [metallb/metallb#1602]
Hello, 

It would be great if you add it possible to use `metallb.universe.tf/address-pool` per-namespace annotations 

For example by [calico ](https://projectcalico.docs.tigera.io/reference/cni-plugin/configuration#configuring-node-and-typha) I can specifying IP pools to all pods per-namespace  by add annotation like this
```
 annotations:
    "cni.projectcalico.org/ipv4pools": "[\"default-ipv4-ippool\"]"
```

**Comment by fedepaol** [comment]
Hi @germetist , it's already on our todo list, as described in https://github.com/metallb/metallb/blob/main/design/pool-configuration.md#using-a-given-ipaddresspool-only-for-a-subset-of-services

**Comment by germetist** [comment]
> Hi @germetist , it's already on our todo list, as described in https://github.com/metallb/metallb/blob/main/design/pool-configuration.md#using-a-given-ipaddresspool-only-for-a-subset-of-services

Oh. sorry
