### ISSUE TITLE
Readd limits and defaults

### ISSUE THREAD

**Issue by SchoolGuy** [metallb/metallb#1603]
With commit https://github.com/metallb/metallb/commit/ed1d25906dca94d9c56356f2cc49b36f23347e45 the resource limits were removed without any possibility to set them yourself (plus it was missing in the changelog). Since the values are not exposed via the Helm-Chart it is very inconvenient to set them.

According to https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/, containers without limits and/or requests will only be scheduled on a best-effort basis. Thus having those values set, should be desirable. I am aware that there are issues when the container is throttled, however this is then a per-user responsibility IMHO. For small users the limits and requests can be easily set to the old values. Admins of bigger clusters should be able to foresee and adjust these values as needed.

**Comment by fedepaol** [comment]
It's possible to set the resources in the helm charts here: https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml#L222

The referenced commits removes them from the all-in-one manifest, which is the only place lacking them.
Please note that we are also offering a kustomize-friendly configlayout that allow metallb users to override them.

**Comment by SchoolGuy** [comment]
@fedepaol Thanks for answering so quickly. Then I will switch my Metallb to Helm to make use of this.
