### ISSUE TITLE
Need a way track IP allocation from common pool

### ISSUE THREAD

**Issue by ffledgling** [metallb/metallb#161]
**Is this a bug report or a feature request?**:

Feature Request.

**What happened**:
I'm looking for a way to get metallb to expose what IPs it is announcing (and for what services) at any point in time. This is useful for tracking usage and assignment of the IPs from the common pool among users, namespaces and services.

**What you expected**:

A way to obtain aforementioned information, ideally programmatically such as via an API endpoint.

**Environment**:
- MetalLB version: 0.3.1
- Kubernetes version: 1.8.6
- BGP router type/version: N/A, using ARP mode
- OS (from `/etc/redhat-release`): CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-693.11.1.el7.x86_64

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[google/metallb] Need a way track I..." ]
>**Is this a bug report or a feature request?**:
>
>Feature Request.
>
>
>**What happened**:
>I'm looking for a way to get metallb to expose what IPs it is announcing (and for what services) at any point in time. This is useful for tracking usage and assignment of the IPs from the common pool among users, namespaces and services.

Isn't there a metric for this?

**Comment by danderson** [comment]
We chatted on slack about this a bit, and the context of this request is to essentially have an audit log of which namespace/service was using an IP at any given point in time. IIRC, our current metrics don't attach namespace+service, and I'd be worried about the cardinality explosion if we do that.

An alternative might be to have a way to produce a structured audit log with allocation/deallocation events, but that opens up a bunch more questions (where do you store the audit log? Do you expose it with an API? Do you need authentication/authorization now?...), so I asked @ffledgling to file this bug so we can think about all that.

**Comment by mleklund** [comment]
Couldn't this information be exposed with k8s custom resources?

**Comment by fedepaol** [comment]
Closing this. On one side, we have https://github.com/metallb/metallb/pull/1637 where with some jq-fu we can find all the services whose ips is coming from a given pool, on the other (for the numbers) we have https://github.com/metallb/metallb/issues/2155
