### ISSUE TITLE
NodeReconciler being invoked too frequently, may trigger errant reloads

### ISSUE THREAD

**Issue by mac-chaffee** [metallb/metallb#1639]
In issues #1562 and #1606 , there were frequent ConfigReconciler calls caused by frequent Node changes. That was fixed by #1607 by adding a filters inside the ConfigReconciler that ignored some Node changes. On the bright side, I can confirm that fix worked for ConfigReconciler!

But I think we need to apply a similar filter to the NodeReconciler: https://github.com/metallb/metallb/blob/a826be5f29547e418aaa52d0cf29d2219008675f/internal/k8s/controllers/node_controller.go#L67-L76 

so that this doesn't flood the logs:

```
{"caller":"node_controller.go:42","controller":"NodeReconciler","level":"info","start reconcile":"/n4-mac","ts":"2022-10-12T14:59:50Z"}
{"caller":"speakerlist.go:271","level":"info","msg":"triggering discovery","op":"memberDiscovery","ts":"2022-10-12T14:59:50Z"}
{"caller":"node_controller.go:64","controller":"NodeReconciler","end reconcile":"/n4-mac","level":"info","ts":"2022-10-12T14:59:50Z"}
{"caller":"node_controller.go:42","controller":"NodeReconciler","level":"info","start reconcile":"/n4-mac","ts":"2022-10-12T15:00:00Z"}
{"caller":"speakerlist.go:271","level":"info","msg":"triggering discovery","op":"memberDiscovery","ts":"2022-10-12T15:00:00Z"}
{"caller":"node_controller.go:64","controller":"NodeReconciler","end reconcile":"/n4-mac","level":"info","ts":"2022-10-12T15:00:00Z"}
```

I don't have hard proof, but I have seen very rare cases where metallb mistakenly triggers a failover of the VIP due to one of the node change events, even though none of the nodes appeared to have had any issues.

I think what we should learn from #1606 is that ALL node watching code needs some kind of filter, because nodes change very frequently under normal conditions (maybe the `conditions` or the `images` sections?).

What kind of node update events does the NodeReconciler really care about? Nodes being added or deleted? Or also nodes being NotReady/Cordoned? I think we should put those checks inside the filter [here](https://github.com/metallb/metallb/blob/a826be5f29547e418aaa52d0cf29d2219008675f/internal/k8s/controllers/node_controller.go#L75) to save CPU, reduce log spam, and avoid risks of errant failovers.

**Comment by fedepaol** [comment]
Makes sense. 
The low level handlers of nodes are https://github.com/metallb/metallb/blob/e9d319b1494359f30e153f45342ee1dffacf3547/speaker/layer2_controller.go#L161 which triggers a memberlist rejoin (triggers a rediscovery of the speakers) and https://github.com/metallb/metallb/blob/e9d319b1494359f30e153f45342ee1dffacf3547/speaker/bgp_controller.go#L320 where we do care about labels because of the bgppeer label selector.

**Comment by fedepaol** [comment]
Closed by https://github.com/metallb/metallb/pull/1666
