### ISSUE TITLE
ARP responses for Services without selectors in Layer 2 Mode

### ISSUE THREAD

**Issue by shaneutt** [metallb/metallb#1640]
### Problem Statement

When deploying a `LoadBalancer` type `Service` _without_ a `selector` metallb will assign an IP address, but that IP address will not route to the nodes (e.g. no traffic for that IP can be seen via `tcpdump`). While this is happening if you run `arpsend -U -i <IP> eth0` on the nodes (as a hack) traffic will start routing and showing up on the nodes via `tcpdump`. Ultimately, if you update the same `Service` to include a valid selector, traffic will start routing and showing up in `tcpdump` normally. After that, if you _remove_ the selector from the `Service` traffic (thus returning it to the original state) will **still continue to route** whereas before traffic would not route with the same state.

This seems to suggest that metallb will only start responding to ARP requests for assigned IPs once it has received a "usable" `Service` configuration, but it's not consistent about it because it will continue to respond even after the `Service` has been reverted and made "unusable".

### Proposed Solution

Make the `metallb-speaker` respond to ARP requests in any case for consistency, e.g.: any newly created `LoadBalancer` type `Service` which has no `selector` but receives an IP will respond to ARP requests for that IP.

### Versions

- kubernetes `v1.25.0`
- metallb `v0.13.6`

**Comment by fedepaol** [comment]
Just to understand better: are you saying that MetalLB continues replying to arp requests even if the endpoints are removed? If that's the case, it's a bug that must be fixed. Can you double check that with arping?
Otherwise, it might be that the arp table is still filled (but metallb doesn't reply anymore) and that's why the traffic is still routed.
I am not sure we can do anything about that.

I'd avoid replying to ARP requests if the service can't be served, and I am not sure this is causing any issues.

**Comment by shaneutt** [comment]
> are you saying that MetalLB continues replying to arp requests even if the endpoints are removed?
> Can you double check that with arping? 

Yes, after double checking this it seems to be the case.

> If that's the case, it's a bug that must be fixed.
> I am not sure this is causing any issues.
> I'd avoid replying to ARP requests if the service can't be served

I have a relevant use case for inspecting `Service` traffic with eBPF programs. I can't get deep into the details of it, but suffice to say it _prefers_ that an IP address which is "provisioned" be route-able so that it can observe all traffic, even if that traffic would not ultimately succeed.

For prior art, the `LoadBalancer` type `Service` implementation in GKE behaves in the opposite manner you are suggesting. That is to say, the same experiment on GKE `v1.22.12-gke.2300` consistently will route traffic regardless of whether or when endpoints are available for the service, and as such BPF programs can observe those packets.

I'm hoping the use case and the desire to be more consistent with other implementations will persuade you, however if not may I please ask you to share some detailed reasoning about your choice for posterity? We would want to reference this use case in our implementations as we would then require a workaround for clusters using metallb.

**Comment by shaneutt** [comment]
> I found the current behaviour (not announcing when no endpoints) when I took the maintainership of the project, and I don't know the full reasoning behind it (but I learned on my skin to respect the original author choices :-) ). One reason I can find is that if there are no endpoints, there's no point at all in steering the traffic to the nodes, so MetalLB implementation is more efficient.
> In general, I'd avoid adding this complexity (and all the unknown rabbit holes that may come from it) for both the L2 implementation and for the BGP implementation, while I think it makes sense to stop announcing when the endpoints are retired to have L2 to be consistent with BGP.

Ok, thank you for your considerations on this. We'll implement a workaround for when users are using metallb.

**Comment by fedepaol** [comment]
Closing this as per the discussion above
