### ISSUE TITLE
How is the release cycle of MetalLB ? How frequently the new versions are released ?

### ISSUE THREAD

**Issue by Manvir-nokia** [metallb/metallb#1643]
How is the release cycle of MetalLB planned? 
How frequently the new versions are released ?
Is there a specific release plan which is followed ?

**Comment by fedepaol** [comment]
Hi @Manvir-nokia , we don't follow a specific release plan at the moment. It really depends wether we find critical issues we have to fix, or if a big and awaited feature (like l2 interface selector) lands.
Another driver for releases is kubernetes releases, which normally include deprecations and other things we need to fix.

**Comment by Manvir-nokia** [comment]
> Hi @Manvir-nokia , we don't follow a specific release plan at the moment. It really depends wether we find critical issues we have to fix, or if a big and awaited feature (like l2 interface selector) lands. Another driver for releases is kubernetes releases, which normally include deprecations and other things we need to fix.

Thank you for being so rapid and answering this ...

**Comment by fedepaol** [comment]
> > Hi @Manvir-nokia , we don't follow a specific release plan at the moment. It really depends wether we find critical issues we have to fix, or if a big and awaited feature (like l2 interface selector) lands. Another driver for releases is kubernetes releases, which normally include deprecations and other things we need to fix.
> 
> Thank you for being so rapid and answering this ...

It was the first email on my list this morning :laughing:
