### ISSUE TITLE
metalLB controller error: unable to process a request with an unknown content type

### ISSUE THREAD

**Issue by Lukk17** [metallb/metallb#1644]
Version of MetalLB: 0.13.6
Version of Kubernetes: v1.25.2

installed via:
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.6/config/manifests/metallb-native.yaml

with configuration as here:
https://metallb.universe.tf/configuration

> apiVersion: v1
> data:
>   secretkey: <myPass>
> kind: Secret
> metadata:
>   name: memberlist
>   namespace: metallb-system
> type: Opaque
> ---
> apiVersion: metallb.io/v1beta1
> kind: IPAddressPool
> metadata:
>   name: first-pool
>   namespace: metallb-system
> spec:
>   addresses:
>     - 192.168.1.80-192.168.1.90
>   autoAssign: false
>   avoidBuggyIPs: true
> ---
> apiVersion: metallb.io/v1beta1
> kind: L2Advertisement
> metadata:
>   name: l2advertisement
>   namespace: metallb-system
> spec:
>   ipAddressPools:
>     - first-pool
> ---
> apiVersion: metallb.io/v1beta1
> kind: BGPAdvertisement
> metadata:
>   name: bgpadvertisement
>   namespace: metallb-system
> spec:
>   ipAddressPools:
>     - first-pool
> ---

error:

`{"level":"error","ts":1665674964.7985432,"logger":"controller-runtime.webhook.webhooks","msg":"unable to process a request with an unknown content type","webhook":"/validate-metallb-io-v1beta1-addresspool","content type":"","error":"contentType=, expected application/json","stacktrace":"sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/webhook/admission/http.go:72\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/promhttp/instrument_server.go:40\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/promhttp/instrument_server.go:117\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/promhttp/instrument_server.go:84\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2462\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.initALPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3523\nnet/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5903"}
`

**Comment by fedepaol** [comment]
Thanks for the report! I was just looking at this.
This is a regression caused by https://github.com/metallb/metallb/pull/1611
The webhook complains about not getting any payload, it causes no harm but it's less than optimal.
I am going to fix this, probably by reverting the change.
