### ISSUE TITLE
Leyer 2 installation on IPv6 only environment is not working.

### ISSUE THREAD

**Issue by rajeevpadinharepattu** [metallb/metallb#1680]
Metallb leyer2 installation is not working on IPv6 only environment.
After installation with Helm charts, Both metallb-speaker and metallb-controller pods are in running state, but  metallb-speaker pods showing the below error.

{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"metallb-system/metallb-webhook-service","level":"info","t
s":"2022-11-01T11:56:16Z"}
{"caller":"announcer.go:121","error":"creating NDP responder for \"docker0\": listen ip6:ipv6-icmp fe80::1%docker0: bind: cannot assign requested
 address","interface":"docker0","level":"error","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2022-11-01T11:56:22Z"}
**{"caller":"announcer.go:121","error":"creating NDP responder for \"docker0\": listen ip6:ipv6-icmp fe80::1%docker0: bind: cannot assign requested**
 address","interface":"docker0","level":"error","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2022-11-01T11:56:32Z"}

Applied the address pool and L2Advertisement configurations as explained in the documentation.

**apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
   '- 2403:0:81e:1::46/128'**

**apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system**

**The loadbalancer service is reachable within the cluster, but not from outside.
seems the ip advertize is not working as expected.**

     **- Version of MetalLB - 0.13.7
     - Version of Kubernetes - 1.22.12
     - Name and version of network addon Flannel
     - Whether you've configured kube-proxy for iptables or ipvs mode - kube-proxy**

**Comment by fedepaol** [comment]
That error is not relevant, and related to a docker network interface.
Can you try to follow the troubleshooting guide https://metallb.org/configuration/troubleshooting/?

**Comment by fedepaol** [comment]
Closing this as no feedback was provided.
