### ISSUE TITLE
FRR mode: Cannot use multiple BGP Peer with non-overlapping node selector

### ISSUE THREAD

**Issue by simplysoft** [metallb/metallb#1683]
We have node specific `BGPPeer` (due to node specific `sourceAddress`) with appropriate `nodeSelectors`. This works fine with native bgp mode, but after switching to FRR mode, the speaker complains about: 

```
peer XXX.XXX.XXX.XXX already exists, FRR mode doesn't support duplicate BGPPeers
```

It looks like validation does not consider nodeSelectors. This might be related to #1560

**Comment by liornoy** [comment]
Interesting issue.
Thanks for filing this and showing another angle of this bug.

**Comment by fedepaol** [comment]
It's more a limitation of the data model exposed by the frr mode rather than a bug.
Same considerations of https://github.com/metallb/metallb/issues/1560 apply here.
We should have a per-node way to declare those properties because relying on the node selector is too fragile and won't scale. And I am not even sure FRR would allow having different src ips based on peer it's connecting to

@simplysoft what is the problem you need to address by setting the srcaddress?

**Comment by simplysoft** [comment]
We use it to fixate the address in case of multiple interface addresses. 

I'd not say that it necessary limitation of the data model, the data model is actually quite flexible. It is just that the validation happens too early, before all the node selectors are applied. 

Same problem will apply when using CRD. They will also have to be tied to particular node, and any validation must only happen for one particular node / CRD, not across all CRDs for all nodes.

**Comment by fedepaol** [comment]
yes, I get that. What I am not entirely sold in is, elying on the node selector for a behaviour that will always be node specific.
Plus, even without the early check we (with frr) wont be able to have more than one srcip per node

**Comment by yellowpattern** [comment]
I have also run into this bug.

**Comment by NetActuateDrew** [comment]
If you really must specify `sourceAddress` , consider doing NAT on the node to translate the peer address. I'm not saying I think this shouldn't be fixed, but that's a workaround (also, make sure you really need sourceAddress). There are likely other ways on the node-level you can influence what source address is used by default for FRR.
