### ISSUE TITLE
Duplicate Role, RoleBindings `metallb-prometheus`

### ISSUE THREAD

**Issue by maany** [metallb/metallb#1694]
The metallb helm chart installation fails when `.Values.prometheus.rbacPrometheus` is true and `.Values.prometheus.serviceAccount` is specified. The error message is
`Error: INSTALLATION FAILED: roles.rbac.authorization.k8s.io "metallb-prometheus" already exists`

This happens because both podmonitor.yaml and servicemonitor.yaml define a `Role` called `metallb-prometheus` and a`RoleBinding` resource called  `metallb-prometheus`

https://github.com/metallb/metallb/blob/350855a42d4d2bd510c9cdd6d484d49224879436/charts/metallb/templates/servicemonitor.yaml#L166-L196

https://github.com/metallb/metallb/blob/350855a42d4d2bd510c9cdd6d484d49224879436/charts/metallb/templates/podmonitor.yaml#L78-L106

I propose renaming the role and rolebindings for podmonitor to `metallb-podmonitor-prometheus` and the role and rolebindings for servicemonitor to `metallb-servicemonitor-prometheus`

Version of MetalLB 0.13.7
Version of Kubernetes 1.23.6
Name and version of network addon (e.g. Calico, Weave...) Cilium
Whether you've configured kube-proxy for iptables or ipvs mode: ipvs

**Comment by XtremeOwnageDotCom** [comment]
Well, STILL indeed an issue.......

**Comment by fedepaol** [comment]
Leaving this as open. Please note that this is STILL an issue if you enable both pod monitors and speaker monitors, as described in https://github.com/metallb/metallb/pull/1695#issuecomment-1311880582

What we can do is to change the charts to avoid it.

**Comment by goldyfruit** [comment]
Same for me.

```
Error: 2 errors occurred:
	* roles.rbac.authorization.k8s.io "metallb-prometheus" already exists
	* rolebindings.rbac.authorization.k8s.io "metallb-prometheus" already exists
```

**Comment by fedepaol** [comment]
@goldyfruit please check https://github.com/metallb/metallb/pull/1695#issuecomment-1311880582
