### ISSUE TITLE
Update the docs with a note about the -prometheus manifests

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1703]
The "-prometheus" all-in-one manifests that can be found [here](https://github.com/metallb/metallb/tree/main/config/manifests) are not documented and they rely on an opinionated prometheus-operator deployment method.
We should add a section under "installation" about that.

**Comment by jpuskar** [comment]
Sorry about a 'me too' post, but, this definitely tripped me up for a couple hours also.

**Comment by fedepaol** [comment]
closed by https://github.com/metallb/metallb/pull/2064
