### ISSUE TITLE
MetalLB ignores NodeNetworkUnavailable condition

### ISSUE THREAD

**Issue by omeinderink** [metallb/metallb#1710]
Hi,

we're using MetalLB ~~3.0.10~~ 0.12.1 with Rancher v1.23.12-rancher1-1 (which equals Kubernetes 1.23.12) and the Canal network plugin.

We believe MetalLB executes a failback of an IP to a node that was just restarted (during a node reboot scenario), when the nodes networking stack isn't ready yet.

This bug seems to appear when a Kubernetes node containing both a MetalLB speaker and MetalLB controller Pod (which I'm calling $WORKER1 here) is restarted.
MetalLB always assigns our single configured IP address to the node containing the controller Pod as soon as possible, i.e. even when the speaker Pod has just started after a node reboot.

The following timeline might clarify the problem:

| Timestamp  | Event |
| ------------- | ------------- |
| 15:30:00 | $WORKER1 holds one IP address configured in MetalLB in layer2 mode |
| 15:31:07 | executing `systemctl reboot` on $WORKER1 |
| 15:31:17 | the MetalLB speaker Pod on $WORKER1 is terminated and the IP address switches to $WORKER2 |
| 15:31:58 | reboot of $WORKER1 |
| 15:33:43 | $WORKER1 has been rebooted and services start again |
| 15:33:44 | the MetalLB speaker Pod starts again on $WORKER1 |
| 15:33:44 | IP address switches back to $WORKER1 from $WORKER2 |
| 15:33:44 | Services in K8s cluster become unreachable from the outside as traffic is sent to the network interface of $WORKER1 |
| 15:33:53 | Container calico-node in Pod $CANAL_POD on $WORKER1 logs "Calico node started successfully"
| 15:33:59 | Container kube-flannel in Pod $CANAL_POD on $WORKER1 logs "Setting NodeNetworkUnavailable" (which sets that condition to false, i.e. the network is now ready)
| 15:33:59 | Container kube-flannel in Pod $CANAL_POD on $WORKER1 logs "Some iptables rules are missing; deleting and recreating rules" and creates and deletes some iptables rules
| 15:34:01 | Services in K8s cluster become reachable again

we are not using ipvs mode for kube-proxy but the standard iptables mode.

I believe this is a bug in MetalLB, as the condition NodeNetworkUnavailable isn't set to "false" until 15:33:59. MetalLB routes traffic to the node 15 seconds before this point, which is obviously not going to work.

**Comment by fedepaol** [comment]
Need to double check this, it might be that currently the speakers rely on memberlist only to detect the availability of the other peers. I'd also argue that metallb checks the status of the endpoints to see if they are available.

**Comment by fedepaol** [comment]
And thanks for the report!

**Comment by champtar** [comment]
From what I remember, If using `externalTrafficPolicy: local` then the IP will go on a node where endpoints are fully ready (so node network status is taken into account I believe). If using `externalTrafficPolicy: cluster` this is likely buggy.

**Comment by phifre** [comment]
However, the downside of `externalTrafficPolicy: Local` is that load balancing across, say, multiple ingress pods no longer works. This would not be ideal in high traffic scenarios.

**Comment by fedepaol** [comment]
> From what I remember, If using `externalTrafficPolicy: local` then the IP will go on a node where endpoints are fully ready (so node network status is taken into account I believe). If using `externalTrafficPolicy: cluster` this is likely buggy.

Yes, you are totally right, and it works like this for both bgp and l2.

**Comment by liornoy** [comment]
I'm working on that.
