### ISSUE TITLE
Add gosec to the ci pipeline

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1712]
Adding another static analyzer should be easy and will save us from audits

**Comment by yuvalk** [comment]
I'm working on this here
https://github.com/yuvalk/metallb/tree/gosec

**Comment by yuvalk** [comment]
and the idea is to add Static Application Security Testing (SAST) to CI

**Comment by fedepaol** [comment]
Sounds great! I am assigning this to you, let us know if you need help.
I'd say the first thing is to add CI and remove false positives, then we file issues, we fix them and we make the lane blocking after we reached a stable baseline

**Comment by yuvalk** [comment]
I've reported https://github.com/securego/gosec/issues/893
