### ISSUE TITLE
Helm chart - complains about inline config when there's no inline config 

### ISSUE THREAD

**Issue by asettouf** [metallb/metallb#1716]
As I try to upgrade MetalLB on my cluster, from `0.12.1` to `0.13.7`, I get the error `Starting from v0.13.0 configInline is no longer supported. Please see https://metallb.universe.tf/#backward-compatibility`, despite having removed `configInline` from my values.

values.yaml:

```
# prometheus:
#  serviceMonitor:
#    enabled: true
#  prometheusRule:
#    enabled: true
```
Kubernetes version: `v1.22.7`

As far as I understand, this shouldn't happen  https://github.com/metallb/metallb/blob/main/charts/metallb/templates/deprecated_configInline.yaml#L2 

Command line:

```
$helm   upgrade metallb metallb/metallb -f values.yaml  --version 0.13.7 
Error: UPGRADE FAILED: execution error at (metallb/templates/deprecated_configInline.yaml:2:4): Starting from v0.13.0 configInline is no longer supported. Please see https://metallb.universe.tf/#backward-compatibility

```

**Comment by fedepaol** [comment]
Can you provide your values.yaml file? The code seem to be pretty clear about the issue.
Not sure if helm caches it somewhere.

**Comment by asettouf** [comment]
> Can you provide your values.yaml file? The code seem to be pretty clear about the issue. Not sure if helm caches it somewhere.

Yeah it's in my OP:

```
# prometheus:
#  serviceMonitor:
#    enabled: true
#  prometheusRule:
#    enabled: true
```

**Comment by asettouf** [comment]
Well didn't solve it, but worked around by uninstalling, re installing...
