### ISSUE TITLE
How to create  ipaddresspool through with metallb api not through yaml(kubectl)?

### ISSUE THREAD

**Issue by zhucan** [metallb/metallb#1718]

**Comment by fedepaol** [comment]
Not a metallb issue (not even a question). Closing

**Comment by zhucan** [comment]
@fedepaol how to generate client code for metallb?

**Comment by zhucan** [comment]
like this:  c.RookClientset.CephV1().CephClusters(namespace).Create(ctx, cluster, metav1.CreateOptions{})

**Comment by fedepaol** [comment]
We currently don't generate / expose it. We theorically could. 
As an alternative you can use the unstructured client to access the api.

**Comment by liornoy** [comment]
@zhucan  Can  I ask, just out of curiosity, what use case do you have that requires you to have metallb api?
