### ISSUE TITLE
metallb in kubernete can not access extenel ip out side kubernetes cluster

### ISSUE THREAD

**Issue by nzb15555196162** [metallb/metallb#1720]
Thanks for filing an issue! A few things before we get started:

1. i create new kubernetes cluster then i create service nginx with metallb for lb, please see snapshot 
![image](https://user-images.githubusercontent.com/18350673/203965933-b40cf7c5-731a-4cba-931d-35218cb0cdd0.png)
![image](https://user-images.githubusercontent.com/18350673/203965991-8eaf8a4b-191b-462c-b6ad-68a81a1ac0a9.png)
2. for me i think it should access nginx servcie but unfortunately i can not access nginx server  
3.  any one can help me?

**Comment by fedepaol** [comment]
Please follow the troubleshooting guide https://metallb.org/configuration/troubleshooting/
Also, please try to ask on the slack metallb channel.

With this low amount of information is impossible to understand what is the problem.

**Comment by nzb15555196162** [comment]
my base environment, kubernetes version 1.13.4 network flannel, this problem trouble me a days
