### ISSUE TITLE
Best practice to bind IP AdressRange to a nodes in a juju-rack-controller

### ISSUE THREAD

**Issue by toaster74** [metallb/metallb#1728]
Hello metallb-ers,

is there a way to tell metallb to use two distinct IPAdressRanges depending on the juju-zone of the corresponding node?

My setting is as follows:

I have bare-metal provisionned by MAAS; there are two racks with IP Range 192.168.A.0/24 on the left rack and 192.168.B.0/24 on the right rack. Juju is on top providing charmed-kubernetes. The worker-nodes are balanced by juju on both left and right rack.

Now, I want metallb to assign an IP from IP-Range 192.168.A.0/24 if the node is on a worker in the left rack and from IP-Range 192.168.B.0/24 if the node is on a worker on the right rack. How can it be done?

Best regards and thanks for your time.

**Comment by fedepaol** [comment]
I'd do as follows, assuming that you want to expose the same service on both zones:
- You create two ipaddresspools, one for each cidr
- You create two services with the same backend, one pinned to one pool, the other pinned to the other
- Yoy create two l2 advertisements with nodes selector, one for one zone and one for the other. You pin each l2 advertisement to the right pool

**Comment by fedepaol** [comment]
Closing the issue, feel free to repoen if you have any questions
