### ISSUE TITLE
Select speaker pod / assign deployment to node of assigned speaker

### ISSUE THREAD

**Issue by abrondijk** [metallb/metallb#1748]
Hi,

In layer-2 mode with `externalTrafficPolicy: local`, only traffic gets send to pods on the same node as the assigned speaker pod.
How do I make sure that the selected pod in the server, gets scheduled on the same node as the assigned speaker?

I know of the `nodeSelectors` field in the `L2Advertisement`, but that would force me to select a single node for that L2Advertisement as well as for the deployment.

How can I let the selected nodes be dynamic, while still allowing `externalTrafficPolicy: local`?

**Comment by fedepaol** [comment]
It's the other way around. Metallb will elect the speaker among those running on nodes where you have a pod running.
This is the best it can do, it must be on you to ensure that at least one node has this property, normally achieved by running the speakers on all the nodes.
