### ISSUE TITLE
Bump the frr version

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1753]
We should jump on the latest frr version, even if using the 7.5 format.

**Comment by cyclinder** [comment]
I can do this 😄

**Comment by fedepaol** [comment]
it's more complex than it seems, bumping alone won't work I think. There is some hammering to be done here and there, but if you want to contribute I'd be happy

**Comment by cgoncalves** [comment]
Agreed. Latest stable 8.x version.
