### ISSUE TITLE
FR: L2 mode supports an option to send gratuitous ARP periodically

### ISSUE THREAD

**Issue by anfernee** [metallb/metallb#1761]
keepalived supports `vrrp_garp_master_refresh` like the following. A similar support in Metallb will be very nice. Thanks!

```
   # minimum time interval for refreshing gratuitous ARPs while MASTER.
   # in seconds (resolution seconds).
   # (default: 0 (no refreshing))
   vrrp_garp_master_refresh 60
```

Ref: https://manpages.debian.org/testing/keepalived/keepalived.conf.5.en.html

**Comment by cyclinder** [comment]
good idea. I try to working on this.

**Comment by pupseba** [comment]
Hi. Is it possible that this has been implemented as a feature already, thus, this behaviour is being seen?
https://github.com/metallb/metallb/issues/1770

**Comment by fedepaol** [comment]
I'd try to see this factored together with the other vrpp like work being discussed [here](https://github.com/metallb/metallb/pull/1773), and would also like to see a use case that justifies it. So far we didn't see any complains about missed arps

**Comment by fedepaol** [comment]
And in general, please let's discuss before start working on something. If the thing is small, an issue is enough, otherwise let's file a proposal which is easier to track and discuss over.
