### ISSUE TITLE
Confusion of memberlist IP adresses in dual stack setup

### ISSUE THREAD

**Issue by jonas-hagen** [metallb/metallb#1764]
Using metallb 0.13.7 (and 0.12.1) on a dual stack (IPv4 / IPv6) cluster, I encountered the following error and the speaker would run into CrashLoopBackoff:
```
{"caller":"speakerlist.go:256","error":"1 error occurred:\n\t* Failed to join 168.0.0.1:7946: dial tcp 168.0.0.1:7946: connect: connection refused\n\n","expected":1,"joined":0,"level":"error","msg":"partial join","op":"memberDiscovery","ts":"2022-12-31T01:07:15Z"}
```

Where the public IPs of my node are (redacted) 168.0.0.1/32 and  2a01::1/64.

The node has an open port 7946, but only on IPv6:
```
node:~ # ss -tulpn | grep :7946
udp   UNCONN 0      0      [2a01::1]:7946          [::]:*    users:(("speaker",pid=8338,fd=9))
tcp   LISTEN 0      4096   [2a01::1]:7946          [::]:*    users:(("speaker",pid=8338,fd=8))
```

So, the speaker seems to confuse the bind address (IPv6) and the connection address (IPv4) for memberlist. These are the relevant environment variables in speaker:

```
❯ kubectl --namespace metallb-system exec --stdin --tty metallb-speaker-28m7g -- /bin/sh
/ # printenv
METALLB_HOST=168.0.0.1
METALLB_ML_BIND_ADDR=2a01::1
METALLB_ML_BIND_PORT=7946
... truncated
```

The interesting part: I have two dual stack clusters at hand, one with kubeadm and calico and the other with k3s and flannel. With the former, everything works (only IPv6 adresses) and with the latter I have the above confusion. Not sure what is the difference exactly though. Happy to provide more info if needed.

**Comment by fedepaol** [comment]
This looks like a bug.
The theory (or, what I see looking at the code) is that both the env variable and the address used by the code to dial are taken from pod.status.ip on all the speaker pods.
Now, one thing that comes to my mind is that in flannel you have a mixed behaviour of the status.ip field, where in some speaker pods you have the v4 one and in some others you have the v6. Can you check that?

**Comment by fedepaol** [comment]
Here is the env variable definition https://github.com/fedepaol/metallb/blob/b96bce642175ec99ed4b3e29e552c2e4f7aeaafd/config/controllers/speaker.yaml#L35 

and here is the code that reads it

https://github.com/fedepaol/metallb/blob/b96bce642175ec99ed4b3e29e552c2e4f7aeaafd/internal/k8s/k8s.go#L370

**Comment by oivindoh** [comment]
Venturing into the brave new/old world of dualstack myself here out of unhappy necessity, and looking at my cluster (k3s with cilium cni), I think I can add some colour to this issue:

I have k3s installed with kubelet-args:"node-ip=::" and currently observing crashloopback as above.

When the daemonset first starts, status.podIP is the node's ipv4 address, but after a while the address gets updated to the node's ipv6 address, which causes a shutdown. The new pod then comes up the same way, ipv4 first.

During this process port 7946 on the ipv6 address is listened to on and off. The source of the oscillating status.podIP field seems to be that the status.podIPs list doesn't have a persistent order (and status.podIP appears to be whatever is listed first at any given point).

This initial ipv4 and then ipv6 behaviour appears to only happen to hostNetwork pods.

**Comment by oivindoh** [comment]
Digging a bit more, this behaviour only happens when `kubelet-arg: "node-ip=::"` is supplied to k3s as indicated in the k3s dual stack doc. Setting `kubelet-arg: "node-ip=0.0.0.0"` instead causes pods to get consistent ipv4 address assigned with no later change to ipv6.
