### ISSUE TITLE
serviceAnnounced for no reason and excesive ServiceReconciler logs after update to 0.13.7 from 0.12.1

### ISSUE THREAD

**Issue by pupseba** [metallb/metallb#1770]
After updating MetalLB in a few kubernetes clusters (v1.23.13 with calico cni and kube-proxy using iptables), moving from 0.12.1 to 0.13.7, we started getting these messages for no apparent reason. We only use L2 mode:

{"caller":"main.go:344","event":"serviceAnnounced","ips":["10.147.53.6"],"level":"info","msg":"service has IP, announcing","pool":"kafka-platform","protocol":"layer2","ts":"2023-01-10T13:41:25Z"}

They come in bursts, where all the IPs associated with one particular kubernetes node get announced. They are not moved from one server to another, is just that they get (re)announced by the same node they were already announced.

There is no restart, configuration change...nothing that we can see that explains why the IPs are announced "out of the blue". Yet, this is shown in logs (l2advertisement as an example, other CRs are also observed to log before the force SyncStateReprocessAll used to call ForceReload):
`
{"caller":"config_controller.go:139","controller":"ConfigReconciler","event":"force service reload","level":"info","ts":"2023-01-17T12:17:38Z"}
{"caller":"config_controller.go:51","controller":"ConfigReconciler","level":"info","start reconcile":"metallb-system/l2advertisement1","ts":"2023-01-17T12:17:38Z"}
{"caller":"config_controller.go:151","controller":"ConfigReconciler","end reconcile":"metallb-system/l2advertisement1","level":"info","ts":"2023-01-17T12:17:38Z"}
`

From one day to another, during which these sort of events are seen in logs, we are unalbe to see any change in the "under watch" resources (addresspools,bfdprofiles,bgpadvertisements,bgppeers,communities,ipaddresspools,l2advertisements). We did this comparisson by "get $i -oyaml" on different days and comparing the results, which include the .metadata.resourceVersion.

It is hard to send full logs since after the update, the amount of logging (info level) is scary. You can easily see in this graph from the last 7 days, "when" MetalLB was updated just by the amount of log entries registered. https://imgur.com/a/6Iqle6R

Most of those log entries are for "ServiceReconciler" happening over and over again. I am able to see that during ServiceAnnounced events, there are also events of type "config reloaded" and "force service reload".

**Comment by pupseba** [comment]
So following a bit more the code and the logs, it seems that the event comes from the config_controller. 

`{"caller":"config_controller.go:139","controller":"ConfigReconciler","event":"force` service `reload","level":"info","ts":"2023-01-17T12:17:38Z"}`
`{"caller":"config_controller.go:51","controller":"ConfigReconciler","level":"info","start reconcile":"metallb-system/l2advertisement1","ts":"2023-01-17T12:17:38Z"}`	
`{"caller":"config_controller.go:151","controller":"ConfigReconciler","end reconcile":"metallb-system/l2advertisement1","level":"info","ts":"2023-01-17T12:17:38Z"}`

And from this part of the code to be more precise:
https://github.com/metallb/metallb/blob/main/internal/k8s/controllers/config_controller.go#L144

The resource itself looks like this (on the 17/01/23 @17:16):
```
Name:         l2advertisement1
Namespace:    metallb-system
Labels:       app.kubernetes.io/instance=metallb-system
Annotations:  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
              argocd.argoproj.io/sync-wave: 2
API Version:  metallb.io/v1beta1
Kind:         L2Advertisement
Metadata:
  Creation Timestamp:  2023-01-09T10:40:02Z
  Generation:          1
  Managed Fields:
    API Version:  metallb.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:argocd.argoproj.io/sync-options:
          f:argocd.argoproj.io/sync-wave:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:app.kubernetes.io/instance:
    Manager:         argocd-application-controller
    Operation:       Update
    Time:            2023-01-09T10:40:02Z
  Resource Version:  4418900401
  UID:               0d1dc7f5-03a1-47d6-8e05-c5577f70e135
Events:              <none>
```

I strongly suspect that the services are being announced because of the metallb config_controller is not getting the responses from the API server.

**Comment by fedepaol** [comment]
I think I know what this is, or I suspect it at least.
The current behavior is like this. We have a controller listening to all the events contributing to the metallb's configuration.
This includes the secrets in the metallb's namespace
Whenever there's a configuration change, we reprocess all the services because some of them may be affected (think about new l2advertisements for example)

Now, even if you didn't change anything, the cert controller that we use to rotate the ca for the webhooks might be causing this.

We can certainly reduce it adding a caching layer, skipping out secrets we don't care about and so on.

**Comment by pupseba** [comment]
Hi!

For testing purposes, the validatingwebhookconfiguration for metallb is deleted and the controller is running with these args.

```
  spec:
      containers:
        - args:
            - '--port=7472'
            - '--log-level=info'
            - '--cert-service-name=metallb-webhook-service'
            - '--disable-cert-rotation=true'
```

Sadly, after 18hs of these test configurations are in place, we still see "serviceAnnounced" events around "force service reload" events logged from the "config_controller".

Hope this info helps.

Regards,
Seba
