### ISSUE TITLE
how does metallb as interal loadbalancer need an external loadbalancer

### ISSUE THREAD

**Issue by modigithub** [metallb/metallb#1771]
hi, i have the following question:
I'm still trying to figure out how metallb differs from an external load balancer.
If I understand correctly, layer2 is not really a load balancer but rather an entry point. metallb gives you an ip for the ingress nginx svc loadbalancer and then forwards all traffic to a server that is defined as the primary server for layer2.

my first question:
if I have two worker servers with the following ips:
worker 1: 192.168.0.1 (Static server ip)
worker 2: 192.168.0.2 (Static server ip)
and the load balancer gets an external ip address from metallb:
ingress svc: 10.111.0.150 (any one from the pool)

and now instead of 10.111.0.150 I use the ip 192.168.0.1 for the DNS, is metallb used at all? As far as I understood, yes, since the ingress-nginx controller does not know which pods are on which server. Is that correct?

I know if I use 10.111.0.150, then the traffic is forwarded directly to the primary server and navigated there via the controller to the pod. But if I do that, isn't that the same as having a nodeport open on every server?

my second question:
If I use metallb in BGP mode, then it's a normal load balancer. do I even need an external load balancer (own server with haproxy)? If so, how does load balancing work in a multi-master kubernetes cluster? or is metallb only intended as an internal load balancer between the worker nodes? In and of itself I would have considered this server structure. (metalb is not shown here)
![image](https://user-images.githubusercontent.com/108171635/211630797-d22afd61-fb30-42e3-8a6c-0991dadbc61b.png)

**Comment by fedepaol** [comment]
> hi, i have the following question: I'm still trying to figure out how metallb differs from an external load balancer. If I understand correctly, layer2 is not really a load balancer but rather an entry point. metallb gives you an ip for the ingress nginx svc loadbalancer and then forwards all traffic to a server that is defined as the primary server for layer2.
> 
> my first question: if I have two worker servers with the following ips: worker 1: 192.168.0.1 (Static server ip) worker 2: 192.168.0.2 (Static server ip) and the load balancer gets an external ip address from metallb: ingress svc: 10.111.0.150 (any one from the pool)
> 
> and now instead of 10.111.0.150 I use the ip 192.168.0.1 for the DNS, is metallb used at all? As far as I understood, yes, since the ingress-nginx controller does not know which pods are on which server. Is that correct?
> 

Nope. Once the traffic lands on the node, all the rest is taken care of by the cni. Metallb's purpouse is only to make the traffic land on teh node.


> I know if I use 10.111.0.150, then the traffic is forwarded directly to the primary server and navigated there via the controller to the pod. But if I do that, isn't that the same as having a nodeport open on every server?
> 

It is, but from metallb in this case you get freedom on the ip and failover. If you use a nodeip, that's static.


> my second question: If I use metallb in BGP mode, then it's a normal load balancer. do I even need an external load balancer (own server with haproxy)? If so, how does load balancing work in a multi-master kubernetes cluster? or is metallb only intended as an internal load balancer between the worker nodes? In and of itself I would have considered this server structure. (metalb is not shown here) ![image](https://user-images.githubusercontent.com/108171635/211630797-d22afd61-fb30-42e3-8a6c-0991dadbc61b.png)

As I wrote above, metallb is not even a loadbalancing. The loadbalancing among the nodes is given by ecmp to all the nodes in the router. I'd suggest going over the docs in order to understand how it works.

Closing the issue.
