### ISSUE TITLE
May access  fail   if adopt layer2 with Local traffic policy ?

### ISSUE THREAD

**Issue by szhengli** [metallb/metallb#1777]
for layer2 mode,  is it possible for node without runing the pod for the service, to be  selected as the  service’s leader node  and assume the arranged IP by metallb?

if that's case,  if choose layer2 with  “Local” traffic policy,  the access via the external IP of the service  may fail, because the leader node only send traffic to the service’s pod(s) that are on the same node,  IF it doesn't have.  

Could u please clarify on this ? thank u.

quoted from doc
*** “Local” traffic policy
With the Local traffic policy, kube-proxy on the node that received the traffic sends it only to the service’s pod(s) that are on the same node. There is no “horizontal” traffic flow between nodes.
Because kube-proxy doesn’t need to send traffic between cluster nodes, your pods can see the real source IP address of incoming connections.
***

**Comment by pupseba** [comment]
I can tell you my experience with it. In my case, I use metallb and a haproxy (no haproxy-ingress, just the haproxy part) that are forced to run in a subset of k8s nodes in the cluster, depending on the presence of a selector.

In this scenario, the haproxy lb service, uses the Local traffic policy which, as you already know, translates in traffic reaching the k8s node announcing the haproxy-lb service external-ip, going only to the pod which is local to the k8s node itself.

Under these circumstances and during the HA testing performed by me, killing the haproxy pod in the node with the external-ip of the haproxy-lb service, forced another node with metallb+haproxy (healthy) to start announcing that ip instead.

Once the haproxy pod that was initially killed, was back up and ready again, the external-ip came back to the initial k8s node. This is an easy to perform test. Either the metallb speaker logs, or arping command or even using tcpdump on the k8s nodes and filtering by the IP and ARP protocol would help you reproduce it too.

**Comment by szhengli** [comment]
I just brower the source code briefly,  only  the node running the service pod is eligible to be elected at leader.
