### ISSUE TITLE
how can we override the values.yaml in the argocd, when we use for metallb application

### ISSUE THREAD

**Issue by reddy2018** [metallb/metallb#1785]
Thanks for filing an issue! A few things before we get started:

1. This is not the place to ask for troubleshooting. Unfortunately
   troubleshooting LB issues in k8s takes a lot of time and effort
   that we simply don't have. If your load-balancers aren't working,
   please don't file an issue unless you have identified a _specific_
   bug to fix. Otherwise, please ask for help in the `#metallb`
   channel on the Kubernetes Slack.
2. Please search the bug tracker for duplicates before filing your
   bug.
3. If you're reporting a bug, please specify all of the following:
     - The bug itself, as detailed as you can.
     - Version of MetalLB
     - Version of Kubernetes
     - Name and version of network addon (e.g. Calico, Weave...)
     - Whether you've configured kube-proxy for iptables or ipvs mode

i am trying to deploy metallb using argocd. here i am using the metallb v.0.10.2.
when i try to create application in argocd, i am using the helm

here i am using the below command

helm install metallb metallb/metallb -f values.yaml

here they pass the values.yaml file, but in the argocd how can we pass values.yaml file with my own values.

**Comment by fedepaol** [comment]
Not a metallb question, more likely for argo.
CLosing the issue
