### ISSUE TITLE
MetalLB - running load balancer on top of existing non-k8s services (on linux)

### ISSUE THREAD

**Issue by dberardo-com** [metallb/metallb#1792]
in my use case i have one service running outside the k8s cluster on port 80 (a docker container exposing a service port on 0.0.0.0).

I would like to use melatlb to expose a k8s service "on top" of the existing docker service, but on a specific IP. So basically i would like all traffic to a specific IP to be routed to the k8s loadbalancer service and all the rest to the docker container.

both services will expose port 80.

---

I have managed to see this setup working once, but then i restarted the machine and it does not work anymore. My guess is that this has to do with the order in which the deamons write their rules in iptables. So i was thinking to perhaps add this rule:

`-A INPUT -p tcp --destination-port 80 -j <chain>`

to filter all traffic to go to k8s first, then move to the next rules if no match was found. But i am missing the name of the chain to forward the traffic to.

Is this the way to go?

**Comment by dberardo-com** [comment]
UPDATE 

seems like making sure that k8s service starts after the docker service solves this issue.  (workaround)

however, restarting docker causes the issue to reappear, perhaps because iptables are rewritten ... so is there any more permanent fix ?

**Comment by fedepaol** [comment]
Hi, not sure this is a question for metallb, it really depends on the cni of your cluster. MetalLB only makes it possible for the traffic to reach the nodes.

**Comment by dberardo-com** [comment]
> MetalLB only makes it possible for the traffic to reach the nodes.

ok, so basically it stops "before" the iptables routing stuff right? it is about IP announcement etc.

I will have a look at what happens then with different CNIs

**Comment by fedepaol** [comment]
Right. Closing this as it's not a metallb issue.
