### ISSUE TITLE
service "webhook-service" not found

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [metallb/metallb#1823]
Moving ticket to here from https://github.com/metallb/metallb-operator/issues/309

Installing via helm chart. Fresh install. No values.

```
helm install -n metallb-system metallb metallb/metallb
```

Attempting to apply IPAddressPool, throws error 

```
Error from server (InternalError): error when creating "ipaddresspool.yaml": Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": service "webhook-service" not found
Error from server (InternalError): error when creating "static-pool.yaml": Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": service "webhook-service" not found
Error from server (InternalError): error when creating "l2advertisement.yaml": Internal error occurred: failed calling webhook "l2advertisementvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-l2advertisement?timeout=10s": service "webhook-service" not found
```

Service-names are prefixed with helm release name.

```
root@kube01:~/Kubernetes/namespaces/metallb# kubectl get service -n metallb-system
NAME                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
metallb-speaker-monitor-service      ClusterIP   None             <none>        7472/TCP   43s
metallb-controller-monitor-service   ClusterIP   None             <none>        7472/TCP   43s
metallb-webhook-service              ClusterIP   10.152.183.176   <none>        443/TCP    43s
```

Suggest, fixing helm chart to specify the generated service name in CRD definitions.

After, looking around a bit- I found this-

1. webhooks.yaml specifies a static name, of metallb-webhook-service

https://github.com/metallb/metallb/blob/main/charts/metallb/templates/webhooks.yaml#L152

The nested crds chart, correctly specifies metallb-webhook-service.

AFTER digging around some more, I found the issue.

`kubectl get ValidatingWebhookConfiguration -A validating-webhook-configuration -o yaml`

I found a lingering webhook configuration. Upon removing it, issues went away.

Still- creating / closing this issue, in the off-chance somebody else runs into this problem.

**Comment by XtremeOwnageDotCom** [comment]
Solution, is to remove lingering webhook configuration.

`kubectl delete ValidatingWebhookConfiguration validating-webhook-configuration`

**Comment by LyKos4** [comment]
Still getting error creating package: error creating package: Internal error - Internal error occurred: failed calling webhook "mpackage.fission.io": failed to call webhook: Post "https://webhook-service.fission.svc:443/mutate-fission-io-v1-package?timeout=10s": service "webhook-service" not found
