### ISSUE TITLE
webhook service not found

### ISSUE THREAD

**Issue by evgenmedia** [metallb/metallb#1833]
Hello!

Got issue when try to apply CRDs. 
Installed MetalLB with helm charts without any changes in values

Then, try to apply CRDs for IPAddressPool, but got an error

`Error from server (InternalError): error when creating "metallb/dl-dev-ip-pool.yaml": Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": service "webhook-service" not found`

➜  k8s git:(main) ✗ kubectl get svc -n metallb-system                                                                              
NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
metallb-webhook-service   ClusterIP   10.43.185.217   <none>        443/TCP   2m40s

Cluster have **metallb-webhook-service**, but CRDs try to call **webhook-service**

How can we fix it?

**Comment by bordenit** [comment]
Rough guess....

You have this laying around....
https://github.com/metallb/metallb/blob/main/config/crd/crd-conversion-patch.yaml

But want this...?
https://github.com/metallb/metallb/blob/main/charts/metallb/charts/crds/templates/crds.yaml

kubectl delete -f https://github.com/metallb/metallb/blob/main/config/crd/crd-conversion-patch.yaml
kubectl apply -f https://github.com/metallb/metallb/blob/main/charts/metallb/charts/crds/templates/crds.yaml

**Comment by krakowski** [comment]
Stumbled upon the same issue and found the solution here : https://github.com/metallb/metallb/issues/1823#issuecomment-1420023215

In short, there may be an old `ValidatingWebhookConfiguration` containing values from a previous installation. Deleting it and reinstalling the Helm chart should fix the issue.

```
kubectl delete ValidatingWebhookConfiguration validating-webhook-configuration
```
