### ISSUE TITLE
FlowSpec support

### ISSUE THREAD

**Issue by gregsulek** [metallb/metallb#1836]
We are looking for specific usecase of BGP advertisements from K8s. We already have a solution for this in monolithic architecture and we are looking for ways to implement it in K8s cluster. 

Our solution is an Application Firewall/IDS that is being deployed in transport networks. We are interested in filtering traffic that runs on specific port (let's say UDP 1234). 

In our monolith deployment we are using BGP Flowspec plugin for that. To make the long story short, whenever our customer suspects that traffic on port 1234 from/to specific IP network is subject to external attacks, we are able to start advertising following FlowSpec rules to his network:
**Condition:**
`src IP: X.X.X.X/Y port 1234 OR`
`dst IP: X.X.X.X/Y port 1234`
**Action**
redirect to our FW IP (same as src IP of our router) or leak to other VRF. 

This way we are able to filter specific traffic transparently. 

As we are thinking of going cloud native with our solution, however FlowSpec in k8s seems to be our greatest concern. 
MetalLB does not support it as a matter of fact, however Frrr does support FlowSpec. Are there any plans to include it in future releases? 

Also of anyone has any suggestions on how to resolve our problem in k8s, I will be very happy to hear them!

**Comment by fedepaol** [comment]
need to think about it. Doesn't sound like a metallb specific thing.
The only thing that might be "metallb related" is to add rules that have the svc ip as the destination and some other discriminator.
