### ISSUE TITLE
MetalLB importing client-go with possibly wrong version number

### ISSUE THREAD

**Issue by cprivitere** [metallb/metallb#1842]
In #1802 the go dependencies were updated, but client-go was switched from a more current k8s version based tag to a really old tag: https://github.com/kubernetes/client-go/tree/v1.5.2. This likely was unintentional and it breaks any imports of metallb into code bases using modern k8s versions.

**Comment by fedepaol** [comment]
oh, thanks for raising this, will fix it hoping this won't become another dependency rabbit hole (or, keen filing a pr ? :P )
I didn't notice so I assume it won't have any direct effects on metallb itself.
