### ISSUE TITLE
Implement SIIT-DC to support dual-stack services on single-stack clusters

### ISSUE THREAD

**Issue by danderson** [metallb/metallb#186]
Kubernetes now supports IPv6. However, Kubernetes still only supports "single-stack" operation, i.e. a cluster is either fully IPv4 or fully IPv6, not both. Per https://groups.google.com/forum/#!topic/kubernetes-sig-network/xmttRVG2Lew , dual-stacking may happen someday, but is not currently being worked on, or planned with any definitive timelines.

So, what could MetalLB do to provide dual-stack external services despite this limitation?

Well, we could use SIIT-DC, which is a combination of stateless and stateful v4/v6 and v6/v4 translation.

Wait, what?

Life of a packet, v6-only cluster:

- Service `svc` is allocated an IPv4 address `v4svc`, in addition to its normal IPv6 `v6svc`. Gloss over how for now, it's a simple matter of config UX.
- v4 client sends a packet with `v4src -> v4svc`.
- MetalLB's protocols (BGP, ARP, RIP...) gets the packet to a node in the cluster.
- A translator running on the node recognizes that `v4svc` is assigned to `svc`, and that `svc` also has native address `v6svc`
- Translator does SIIT-DC, translates the packet to `v6src -> v6svc`, where `v6src` is statelessly constructed as a SIIT /96 + the client IPv4.
- Normal kube-proxy routing takes over from here, and one of the service's pods receives a packet `v6src -> v6svc`. If it's SIIT-aware, it can extract the client's true IPv4 from `v6src`. Otherwise, it can just log `v6src` and post-processing can do the translation.
- Pod responds with a packet `v6svc -> v6src`. Packet leaves the pod network, shows up at the node.
- Translator recognizes that the packet is destined to the SIIT /96, and that `v6svc` is assigned to `svc`, which also has non-native address `v4svc`
- Translator does SIIT-DC, translates the packet to `v4svc -> v4src`, where `v4src` is extracted from `v6src` by stripping the leading /96.
- Packet leaves the node, returns to the user.

Life of a packet, v4-only cluster:

- Service `svc` is allocated an IPv6 address `v6svc` in addition to its normal `v4svc`. The `v6svc` is a SIIT /96 + `v4svc`.
- v6 client sends a packet with `v6src -> v6svc`.
- MetalLB's protocols (BGP, NDP, RIP...) gets the packet to a node in the cluster.
- A translator running on the node recognizes that `v6svc` falls within the SIIT /96.
- Translator does SIIT-DC, translates the packet to `v4node -> v4svc`, where `v4svc` is extracted from `v6svc`, and `v4node` is the node's local IP address
- **Translator remembers the translated 5-tuple and associated original `v6src`**. Unlike the previous packet walk, we can't just hide the original client IP in the translated IP, the sizes don't work.
- Normal kube-proxy routing takes over from here, and one of the service's pods receives a packet `v4node -> v4svc`. The true client IP is always lost.
- Pod responds with a packet `v4svc -> v4node`. Packet leaves the pod network, shows up at the node.
- Translator recognizes that the packet matches a recorded 5-tuple, and that the tuple is associated with `v6src`.
- Translator does SIIT-DC, translates the packet to `v6svc -> v6src`, where `v6svc` is SIIT /96 + `v4svc` and `v6src` comes from the conntrack table.
- Packet leaves the node, returns to the user.

Somewhat open question remains how to implement the translator bits on the node. Linux doesn't (seem to) have facilites for this kind of SDN NAT-PT, so we would have to do it in userspace (or contribute to linux, _shudder_). Two obvious ways are AF_RAW socket and tuntap.

tuntap feels more palatable, because we can use routes to steer the relevant traffic to our userspace process, whereas AF_RAW needs a bunch of firewall hackery and a BPF program to filter the firehose. Tuntap also has the nice feature of tying the interface to the lifetime of the process, so we get automagic cleanup on shutdown/crash. It's likely also somewhat more performant than AF_RAW, although it won't be amazing no matter what.

Other question is firewalling. Ordinarily MetalLB relies on kube-proxy to tweak netfilter and install the appropriate flows, but in this case we would have to insert our own rules in a way that doesn't conflict with either the CNI plugin or kube-proxy, to allow this weird traffic to flow to the right places.

Recording this idea here because it's horrible and I love it, but it's definitely not something that's going to happen overnight, or maybe not at all.

**Comment by danderson** [comment]
Implicit in both v6-only and v4-only clusters, btw, is that the nodes (or at least _some_ nodes) have both v6 and v4 addresses. The translators need to live on a dual-stacked node, even if the k8s overlay network is single-stacked.

Reference reading for stateless v4/v6 translation: https://tools.ietf.org/html/rfc7915
Reference reading for more about v4/v6 translation: https://tools.ietf.org/html/rfc6052

**Comment by fedepaol** [comment]
Closing this as now we have dual stack clusters.
