### ISSUE TITLE
Metallb only expose IP internally instead of extern

### ISSUE THREAD

**Issue by Syntax3rror404** [metallb/metallb#1873]
I use:
K8s: 1.24.11 (rke2)
OS: Rocky 9.1 (firewalld disabled)

The speaker and controller logs looks fine.

In my example metallb expose NGINX (Ingress) but the problem is that the app can only reach via the worker nodes but not outside of the cluster (tested with curl)

Is this bug expected on RedHat OS?

**Comment by xueqizhang121** [comment]
I meet the same condition with you. but i do not find a effective solution with this problem.  now use this command :kubectl rollout restart daemonset speaker -n metallb-system .

**Comment by Syntax3rror404** [comment]
@xueqizhang121 with bgp protocoll the ips are also reachable outside the cluster... looks like layer2 in metallb is buggy

**Comment by fedepaol** [comment]
did you follow the troubleshooting guide?
When you curl from the nodes, metallb doesn't even do its part because the traffic is already on the node

**Comment by fedepaol** [comment]
https://metallb.universe.tf/configuration/troubleshooting/

**Comment by Syntax3rror404** [comment]
Yes i followed the guide. Its the same arping only works on the worker nodes not outside.

**Comment by fedepaol** [comment]
do you see the arp request getting to the node? Especially the one choosen by metallb?
You can find the choosen one by doing a kubectl describe on the service.

**Comment by fedepaol** [comment]
@Syntax3rror404 mind following up?

**Comment by Syntax3rror404** [comment]
@fedepaol i switched to cilium and now everything works fine. But I hope @xueqizhang121 can test it out.

But as a logical conclusion because I can reach the services on the worker nodes but not behind them that it would be logical if tcpdump can also only track the requests on the worker and not behind it. I have also tested metallb with bgp and that had also worked behind the worker node.

Firewalld was disabled on my configuration so thats also not the problem.

**Comment by odsock** [comment]
@fedepaol I'm seeing the same thing, tcpdump shows the ARP requests on a worker node when a service is added, but not outside. Arping only gets results on the worker nodes. I see the serviceAnnounced event in the logs for the speaker. I can share more if you tell me where to look, still trying to make it work.

**Comment by fedepaol** [comment]
> tcpdump shows the ARP requests on a worker node when a service is added, but not outside

mind expanding on this? If you arp-ing a service's ip from outside the cluster, do you see the request coming?

**Comment by fedepaol** [comment]
Then I think it's a problem of your network, something is blocking them.

**Comment by Syntax3rror404** [comment]
> Then I think it's a problem of your network, something is blocking them.

In my case the client was on the same subnet without need to route anything i dont think that some of the packages are dropped. This makes no sense. 
@odsock are you using a redhat OS? I get it to work on ubuntu systems but this kind of problems starts with new clusters on rhel os or rocky.

**Comment by fedepaol** [comment]
> In my case the client was on the same subnet without need to route anything i dont think that some of the packages are dropped.

You probably had a different issue. If arp don't make to the node, MetalLB can't work. The symtoms might be similar but for a different reason.

**Comment by odsock** [comment]
> @odsock are you using a redhat OS? I get it to work on ubuntu systems but this kind of problems starts with new clusters on rhel os or rocky.

I'm using redhat 7, kubernetes v1.25.6 created by Kubespray.

**Comment by fedepaol** [comment]
Just to be clear, the fact that a service is accessible from the workers doesn't mean that metallb is working only internally. Metallb's purpouse is to have the traffic **reach** the workers, and once the traffic is there all the rest is handled by the CNI.

If you see the arp requests are reaching the nodes and metallb is not replying, then we can dig and understand what's not working in metallb, otherwise I think it's not a metallb related issue.

**Comment by odsock** [comment]
> Then I think it's a problem of your network, something is blocking them.

This was exactly right for my issue, turned out my VIP was in a different subnet. Thanks for the help!

**Comment by xueqizhang121** [comment]
> > Then I think it's a problem of your network, something is blocking them.
> 
> This was exactly right for my issue, turned out my VIP was in a different subnet. Thanks for the help!

Can you describe in detail the scenario you encountered and the solution

**Comment by fedepaol** [comment]
Closing this as it seems both issues where not metallb issues. Feel free to reopen otherwise.

**Comment by Syntax3rror404** [comment]
@fedepaol i tryed again only for fun and it looks like I had a typo in my l2-announcement cr so the cr don't match the ip-pool......
