### ISSUE TITLE
Pfsense FRR BGP + Metallb: Intermittent Long Load Times For HTTP traffic

### ISSUE THREAD

**Issue by pchang388** [metallb/metallb#1887]
Hi,

I preface by saying I am still learning a lot about networking in general. I've been chasing this issue for a few weeks and have been unable to make traction on it. I am using pfsense with FRR BGP to set up internal IP address allocation to Metallb speakers/controller in a K3s cluster for ingress-nginx pods. These pods (2+) are behind a K8 service which receives it's LoadBalancerIP from Metallb via BGP peering with pfsense.

I pretty much followed the doc [here](https://geek-cookbook.funkypenguin.co.nz/kubernetes/loadbalancer/metallb/pfsense/) to get things set up:

I noticed that every ~20 requests or so would hang and take 15+ seconds to finally complete as shown below
![HTTP_long_load_times](https://user-images.githubusercontent.com/51681873/230837870-5079250e-3c15-4b8c-a083-5f46d67758df.png)

This happens consistently and makes it rather a pain to use BGP + Metallb + K3s for internal websites. I also stumbled upon another user experiencing the same thing: [here](https://www.reddit.com/r/PFSENSE/comments/11dc3ox/intermittent_hanging_of_bgp_frr_connection). I tried various things as discussed [here](https://github.com/metallb/metallb/issues/649) as well . But I am still running into the same issue after some tinkering.

I was wondering if anyone else had this same issue and was able to resolve it? Metallb also works with L2-advertisement but the user experience is better with BGP and I would like to make it work. I can try my best to provide any additional info/logs for this issue.

Versions:
- pfsense: `2.6.0`
- metallb (also tried with frr enabled):  
```
helm ls -n metallb
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
metallb metallb         4               2023-04-10 02:27:12.584049427 -0400 EDT deployed        metallb-0.13.9  v0.13.9
```
- k3s: `v1.26.3+k3s1`

**Comment by pchang388** [comment]
Additional Info below also posted [here](https://forum.netgate.com/topic/179356/bgp-metallb-k8-intermittent-long-load-times-for-http-traffic/3?_=1681171705613)

**How and what are you testing there to generate those results?**

- This is from the "Inspect -> Network" page from the Chrome browser. That page has the response/load times of the HTTP calls being made. Same issue happens with Edge browser, haven't tried any others yet.
I am testing various internal web pages (plex, proxmox UI, custom apps, etc.) that run through a reverse proxy ingress-nginx pods (2+ but also tried with just 1) deployed on a k3s cluster (on proxmox VMs - 3 leader/5 follower cluster - app pods only run on follower/workers)
- The Metallb (installed via helm - version: v0.13.9) pods deployed in the k3s cluster perform BGP peering with pfsense (FRR BGP) and request IP addresses in a specified subnet for any k8 service created with spec: type: LoadBalancer
In my case, I launch ingress-nginx (installed via helm - version: 1.6.4) with 2+ pods and a LoadBalancer service. These receive the IP address in the subnet range as expected and I am able to use any browser to access internal web pages behind the reverse proxy. I also have cert-manager handling certs through letsencrypt and route53 for these internal sites. Purchased a public domain for this purpose and also have pihole running internally that re-points the ip address for my public domain. Pihole has a wildcard DNS entry to point the public domain to Metallb IP address

**Do you see anything logged on either side?**

- I do not see much with pfsense but as stated very new to pfsense and BGP, so I can try to gather something specific (location or wording) that you might find helpful during the window the problem occurs. Since it occurs very often, I can definitely get some info out without too much work.
- From what I can tell though, no obvious errors in other applications in the stack. Metallb controller and speaker logs do not show anything at current/info level logging when the issue happens.
- Ingress-nginx logs are a bit more interesting though, when HTTP calls start to hang, the request does not show up in the nginx logs at all. This gap suggests that the traffic is not even getting there (so not an issue with slow apps) and during this hanging time, other browser tabs/sessions I have open to other internal sites work fine but will also experience the same issue later. This finding points at being a per connection thing/issue? That led me to experiment with TCP timeout values in the Firewall advanced settings but still same issue exists. When the requests do finally get to ingress-nginx it sends all that have been hanging/waiting on the web page at what appears to be the exact same time.

**Was the load-balancer working as expected before adding BGP?**

- So I had this exact same set up with Unifi USG working and did not run into this specific issue before. When the USG started randomly shutting down, I replaced it with a pfsense router (attempted to recreate BGP config via FRR) and the problem started occurring. So I came here hoping maybe someone else had similar issue(s) and resolved it.
- As linked, this exact issue appears for other users so I do believe it's something pfsense related at this moment. I just don't have enough knowledge in this area to potentially identify the problem.
- I've also tried tuning ingress-nginx various times to see if it would help. I did things like change timeouts for client/read/proxy, tuning http2, etc. and was unable to resolve the issue.

**Comment by fedepaol** [comment]
Can you:
- apply a nodeselector to the bgp advertisement so you have a single entry point node to monitor
- run tcpdump there, to see if the traffic lands on the node in an appropriate time and see how long it takes to the following reply

If tcpdump shows the traffic gets in, then the problem is not in metallb and might lie either in the application or in the fabric or in the cni. Otherwise, we must check if the routes are published correclty.

**Comment by pchang388** [comment]
Hi @fedepaol 

Thank you for your response/questions

I actually resolved the issue with the help from a pfsense forum user. He pointed me to some docs about asymmetric routing and how to resolve it after he looked through my TCP dump output and saw a lot of:

`ICMP redirects`

I read into it here: https://docs.netgate.com/pfsense/en/latest/routing/static.html#asymmetric-routing

```
With asymmetric routing such as in this example, any stateful firewall will drop legitimate traffic because it cannot properly keep state without seeing traffic in both directions. This generally only affects TCP, since other protocols do not have a formal connection handshake the firewall can recognize for use in state tracking
```

In my case, the asymmetric routing was caused by putting my k3s worker nodes (10.0.0.220-230) on the same subnet as the clients (10.0.0.0/24). To resolve the issue, I put my proxmox server (runs the k3s nodes) on a VLAN in pfsense and my unifi switch while also allowing traffic between the two with firewall rules. A more detailed answer is here in my comment near the bottom: https://forum.netgate.com/topic/179356/bgp-metallb-k8-intermittent-long-load-times-for-http-traffic

**Comment by inzanez** [comment]
@pchang388 assuming that Kubernetes pods talk to other Kubernetes exposed services,...could that not lead to the exact same issue again, as all the nodes are on the same network again? Wouldn't adding allowance on the gateway (sloppy state, all states for VIPs) be another viable solution?

**Comment by pchang388** [comment]
> @pchang388 assuming that Kubernetes pods talk to other Kubernetes exposed services,...could that not lead to the exact same issue again, as all the nodes are on the same network again? Wouldn't adding allowance on the gateway (sloppy state, all states for VIPs) be another viable solution?

From my limited understanding, pods shouldn't have the same issue since traffic is still going out/in through an internal K8 gateway instead of directly and bypassing it since the LB IP addresses will be outside of internal block/network. I haven't noticed the same issue for services that in run in K8 yet (or I think I haven't at least)

That sounds like it could also work, this is an issue for stateful firewalls from what I've read. Decreasing the satefulness of the firewall would help remove the requirement ` must see traffic for the entire connection to be able to filter traffic properly`.

Honestly though, I'm not well versed in these areas hah but always good to learn

**Comment by dbeltman** [comment]
@pchang388 thanks ever so much for your work on the forum post and github issue. 

I had the same issues. Moving 1-2 testing nodes to another VLAN, and deploying a test LB Service with multiple pods there seems to have fixed the issue.

I will move over my other nodes, and hopefully succesfully migrate to BGP LB :)
