### ISSUE TITLE
Metallb doesn't release ip after remove it.

### ISSUE THREAD

**Issue by i5Js** [metallb/metallb#1896]
Hello all, 

I am having problems installing pihole with metallb, however, I see something strange. When I delete metallb completely, I see the ip used as loadbalancer for the DNS is still in my master nodes., even after deleting the namespace. 

I am using the metallb latest version in a k3s kubernetes HA cluster, and flannel. 

I have tried to remove the ip with the command ip addr del ip dev eth0, but it doesn't work. 

Any tips?

Thanks

**Comment by fedepaol** [comment]
MetalLB doesn't work by assigning addresses to the local interfaces.
See https://metallb.universe.tf/concepts/layer2/

I will close this issue as it doesn't seem metallb related.

**Comment by mingmingshiliyu** [comment]
> Hello all,
> 
> I am having problems installing pihole with metallb, however, I see something strange. When I delete metallb completely, I see the ip used as loadbalancer for the DNS is still in my master nodes., even after deleting the namespace.
> 
> I am using the metallb latest version in a k3s kubernetes HA cluster, and flannel.
> 
> I have tried to remove the ip with the command ip addr del ip dev eth0, but it doesn't work.
> 
> Any tips?
> 
> Thanks

hey bro.i installed metalb,and uninstalled it for a while, but I found that my azure load balancer cannot allocate ip to my load balancer type service.how can I resolve it
