### ISSUE TITLE
opposite loadBalancerIPs and address-pool annotations on a service

### ISSUE THREAD

**Issue by mlguerrero12** [metallb/metallb#1916]
A service can set an ip with the annotation loadBalancerIPs that doesn't correspond to the pool set with the annotation address-pool.

From the code, when the ip is first allocated, it only takes into account the value on the loadBalancerIPs annotation. It doesn't verify if an address pool is set with the annotation address-pool.

When the svc (with an allocated ip) is updated, the controller verifies that the pool where the ip comes from is the same as the one specified in the address-pool annotation. Since the ip doesn't belong to this pool, it logs the error "user requested a different pool than the one currently assigned". It then proceeds to clear the ip (internally) and performs again an allocation. The result will be the same as when the allocation was executed from the first time.

So, the end result is deterministic, the loadBalancerIPs annotation takes precedence. However, the code and logs of the controller are not. Also, the docs do not mention this either.

Question now is, is this behavior intended? If yes, we should modify the code to prevent undesired logs and clearly state this on the docs. If not, we will need to verify that these two annotations are compatible.

**Comment by fedepaol** [comment]
I think we should just reject and not allocate to the service in this case, as in any case we are going against the user's will who clearly made some mistake.

**Comment by mlguerrero12** [comment]
alright, please assign this to me
