### ISSUE TITLE
Pool controller possible inconsistencies

### ISSUE THREAD

**Issue by mlguerrero12** [metallb/metallb#1929]
When there is a change in IPAddressPool or Namespaces (ignoring AddressPool and Community), the pool controller verifies that the allocated IPs can still be assigned a pool. Then, it instructs the service controller to process again all services.

I see the following issues in the pool controller.

**1.** When a pool is not found for a set of allocated IPs. For example, when an IPAddressPool with allocated IPs is deleted or when the Addresses parameter is changed, the pool controller returns an error and keeps on trying to reconcile. The pool in the allocator struct is not updated meaning that it will still have the previous configuration (an unexisting pool). SVCs with these IPs won't be cleared and it is even possible to create a new service and get an IP from a non-existing pool.

If the controller is restarted, the SVCs are cleared only if there are other pools in the config. If not, the controller will return because there is no config yet. The user can recreate the deleted pool and a new service will get the same IP of an existing one. The controller will then complain that 2 services have the same IP.

All this can be prevented by letting the service controller to clear the IPs when the reloadall event is received. The pool controller doesn't need to return an error when a pool is not found for an IP. Everything will be consistent. Right now, the restart leads to a different state as mentioned previously.

**2.** If a svc got an IP from a pool with specific namespaces and service selectors, this assignment won't change even if a new pool with higher priority is created. This might be desirable in some cases, however, it might lead to confusion among users. We could mention this explicitly in the documentation or add a new parameter "preempt" to force an assignment to be recalculated in case there is a pool with higher priority.

For other cases, the labels of the namespaces or the service might change and the selected pool might not comply anymore. The service in this case, will continue having the IP from this pool. We should do something with this case as well. The service should fall back to another pool.

**Comment by fedepaol** [comment]
> When there is a change in IPAddressPool or Namespaces (ignoring AddressPool and Community), the pool controller verifies that the allocated IPs can still be assigned a pool. Then, it instructs the service controller to process again all services.
> 
> I see the following issues in the pool controller.
> 
> **1.** When a pool is not found for a set of allocated IPs. For example, when an IPAddressPool with allocated IPs is deleted or when the Addresses parameter is changed, the pool controller returns an error and keeps on trying to reconcile. The pool in the allocator struct is not updated meaning that it will still have the previous configuration (an unexisting pool). SVCs with these IPs won't be cleared and it is even possible to create a new service and get an IP from a non-existing pool.
> 
> If the controller is restarted, the SVCs are cleared only if there are other pools in the config. If not, the controller will return because there is no config yet. The user can recreate the deleted pool and a new service will get the same IP of an existing one. The controller will then complain that 2 services have the same IP.
> 
> All this can be prevented by letting the service controller to clear the IPs when the reloadall event is received. The pool controller doesn't need to return an error when a pool is not found for an IP. Everything will be consistent. Right now, the restart leads to a different state as mentioned previously.
> 
> **2.** If a svc got an IP from a pool with specific namespaces and service selectors, this assignment won't change even if a new pool with higher priority is created. This might be desirable in some cases, however, it might lead to confusion among users. We could mention this explicitly in the documentation or add a new parameter "preempt" to force an assignment to be recalculated in case there is a pool with higher priority.
> 
> For other cases, the labels of the namespaces or the service might change and the selected pool might not comply anymore. The service in this case, will continue having the IP from this pool. We should do something with this case as well. The service should fall back to another pool.


In general, I think that preserving the current connectivity is the right thing to do. When a user changes the config in a way that impacts a service (by removing its ip from any pool, or by changing priorities, which is pretty much the same).
What we do is, we mark the configuration as stale, and we freeze the currently used configuration.
We have metrics for stale configs, and hopefully we'll have some status exposure that will show them.
This is already discussed and covered in the long standing issue https://github.com/metallb/metallb/issues/462 (including the "restart the controller part, to some extent).

So, on one side this doesn't feel terribly urgent to fix, given the timing and how many few times we got compains, on the other it may make sense to take an official decision and implement the change in behaviour or document more clearly this one.

I am going to close the issue as duplicate of the other one, what you wrote makes total sense.

**Comment by mlguerrero12** [comment]
there are 2 different things here. The first point is mentioned in #462, but for the second one, the config is updated. The problem is that we don't evaluate the labels again. I wouldn't close this issue due to the second part.

**Comment by fedepaol** [comment]
> there are 2 different things here. The first point is mentioned in #462, but for the second one, the config is updated. The problem is that we don't evaluate the labels again. I wouldn't close this issue due to the second part.

yeah but I feel it's still part of the "should we keep the services always in line with the configuration, even if this will cause a disruption in the service, or shouldn't we"? Once we have a clear answer to this question, we can decide what to do and where to fix (because even if we leave it as it is, the restart part doesn't look great despite being a good workaround).
If you are afraid we are going to forget about this, please file a separate issue so it's clear what we are missing.
