### ISSUE TITLE
Accessing the load balancer's IP with a specific port leads to accessing the port of the host IP.

### ISSUE THREAD

**Issue by zzzkl** [metallb/metallb#1930]
- The bug itself, as detailed as you can.
   -  Using MetalLB in BGP mode, when accessing a certain load balancer IP followed by port 8090 (which the service does not expose), it will reach the application on port 8090 of the host machine. In my case, it is Traefik, as the port of Traefik in our cluster is exposed using hostPort. The LB IP and host IP are different. 

- Version of MetalLB
    - v0.13.5
- Version of Kubernetes
    - v1.25
- Name and version of network addon (e.g. Calico, Weave...)
    -  Calico v3.24.5
- Whether you've configured kube-proxy for iptables or ipvs mode
    - kube-proxy using ipvs mode

**Comment by fedepaol** [comment]
Because of how metallb works, it only advertises the reacheability of the ip, regardless of the port. I am not entirely sure, but I'd say that the cni should take care of avoiding the traffic reaching the node with dst:lbip is accepted only if targeting the right ports.
This is true regardless of the fact that MetalLB is there or not.

**Comment by fedepaol** [comment]
getting back to this. MetalLB advertises the node ip as next hop for the lb ip, and that's it.
That means that the traffic directed to the lb ip lands on the node, and something else makes it reach traefik.
Host port (with no ip) defaults to 0.0.0.0, but the lb ip is not assigned to any of the interfaces of the node, so there must be something else that does that translation (calico, maybe)?
A tcpdump would help clearing up things, but this doesn't sound to be a metallb bug.

**Comment by fedepaol** [comment]
Closing this as non metallb issue
