### ISSUE TITLE
Run pylint on tasks.py

### ISSUE THREAD

**Issue by mlguerrero12** [metallb/metallb#1940]
We should run pylint on the file tasks.py. We could add a new job in github workflow for this as well.

**Comment by mlguerrero12** [comment]
yes, a lot. I ran it. That's why I decided to put it here. It could be a good first issue for someone.

**Comment by fedepaol** [comment]
I am gonna label help wanted, I'd feel guilty to label good first issue as it's a lot of pain

**Comment by liornoy** [comment]
update: there is a draft PR opened by CNLHC: #1941

**Comment by Mohit-Gaur** [comment]
@fedepaol Is this still up for grabs? I am interested in working on this

**Comment by fedepaol** [comment]
We are automatically formatting tasks.py using `black`, closing this issue.
