### ISSUE TITLE
BGP goes down on all nodes every time I create or delete a Service

### ISSUE THREAD

**Issue by benkelly12** [metallb/metallb#1944]
Thanks for filing an issue! A few things before we get started:

1. This is not the place to ask for troubleshooting. Unfortunately
   troubleshooting LB issues in k8s takes a lot of time and effort
   that we simply don't have. If your load-balancers aren't working,
   please don't file an issue unless you have identified a _specific_
   bug to fix. Otherwise, please ask for help in the `#metallb`
   channel on the Kubernetes Slack.
2. Please search the bug tracker for duplicates before filing your
   bug.
3. If you're reporting a bug, please specify all of the following:
     - The bug itself, as detailed as you can.
     - Version of MetalLB
     - Version of Kubernetes
     - Name and version of network addon (e.g. Calico, Weave...)
     - Whether you've configured kube-proxy for iptables or ipvs mode

Hi
I've found that whenever Metallb has to change the routes advertised it seems to delete and re-apply the BGP configuration causing BGP to flap. I've noticed both when creating or deleting a Service of type Load Balancer, as well as if I have a load balancer service with only one pod in and I delete that Pod (thus causing the address to be withdrawn). I've done some traces on the speakers and can see it definitely removing a re-applying the configuration. 

Using version 0.13.9 
K8s: 1.27.1 
Net plugin: Weave (not sure on version but will be recent) 
No for Iptables or ipvs mode

Logs from speaker:

[speaker-4k5nn reloader]   if line is not "exit-vrf": 
[speaker-4k5nn reloader] 2023-05-18 21:51:21,590  INFO: Called via "Namespace(input=None, reload=False, test=True, debug=False, log_level='info', stdout=True, pathspace=None, filename='/etc/frr_reloader/frr.conf', overwrite=False, bindir='/usr/bin', confdir='/etc/frr', rundir='/var/run/frr', vty_socket=None, daemon='')" 
[speaker-4k5nn reloader] 2023-05-18 21:51:21,590  INFO: Loading Config object from file /etc/frr_reloader/frr.conf 
[speaker-4k5nn reloader] 2023-05-18 21:51:21,681  INFO: Loading Config object from vtysh show running 
[speaker-4k5nn reloader] 2023-05-18 21:51:21,776  INFO: "frr version 7.5.1_git" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:21,776  INFO: "frr defaults traditional" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:21,776  INFO: "service integrated-vtysh-config" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:21,776  INFO: "line vty" cannot be removed 
[speaker-4k5nn reloader]  
[speaker-4k5nn reloader] Lines To Delete 
[speaker-4k5nn reloader] =============== 
[speaker-4k5nn reloader] ipv6 forwarding 
[speaker-4k5nn reloader] router bgp 64537 
[speaker-4k5nn reloader]  no neighbor 10.150.245.1 ebgp-multihop 255 
[speaker-4k5nn reloader]  
[speaker-4k5nn reloader] Lines To Add 
[speaker-4k5nn reloader] ============ 
[speaker-4k5nn reloader] no ip prefix-list 10.150.245.1-pl-ipv4 seq 5 permit 10.150.246.1/32 
[speaker-4k5nn reloader] no ip prefix-list 10.150.245.1-pl-ipv4 seq 10 permit 10.150.246.2/32 
[speaker-4k5nn reloader] no ip prefix-list 10.150.245.1-pl-ipv4 seq 15 deny any 
[speaker-4k5nn reloader] no ipv6 prefix-list 10.150.245.1-pl-ipv4 seq 5 deny any 
[speaker-4k5nn reloader] router bgp 64537 
[speaker-4k5nn reloader]  neighbor 10.150.245.1 ebgp-multihop 
[speaker-4k5nn reloader] router bgp 64537 
[speaker-4k5nn reloader]  neighbor 10.150.245.1 port 179 
[speaker-4k5nn reloader] ip prefix-list 10.150.245.1-pl-ipv4 permit 10.150.246.1/32 
[speaker-4k5nn reloader] ip prefix-list 10.150.245.1-pl-ipv4 permit 10.150.246.2/32 
[speaker-4k5nn reloader] ip prefix-list 10.150.245.1-pl-ipv4 deny any 
[speaker-4k5nn reloader] ipv6 prefix-list 10.150.245.1-pl-ipv4 deny any 
[speaker-4k5nn reloader] Applying the configuration file 
[speaker-4k5nn reloader] /usr/lib/frr/frr-reload.py:805: SyntaxWarning: "is not" with a literal. Did you mean "!="? 
[speaker-4k5nn reloader]   if line is not "exit-vrf": 
[speaker-4k5nn reloader] 2023-05-18 21:51:21,832  INFO: Called via "Namespace(input=None, reload=True, test=False, debug=False, log_level='info', stdout=True, pathspace=None, filename='/etc/frr_reloader/frr.conf', overwrite=True, bindir='/usr/bin', confdir='/etc/frr', rundir='/var/run/frr', vty_socket=None, daemon='')" 
[speaker-4k5nn reloader] 2023-05-18 21:51:21,832  INFO: Loading Config object from file /etc/frr_reloader/frr.conf 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,013  INFO: Loading Config object from vtysh show running 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,108  INFO: "frr version 7.5.1_git" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,108  INFO: "frr defaults traditional" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,108  INFO: "service integrated-vtysh-config" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,108  INFO: "line vty" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,200  INFO: Executed "ipv6 forwarding" 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,290  INFO: Executed "router bgp 64537  no neighbor 10.150.245.1 ebgp-multihop 255" 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,291  INFO: /var/run/frr/reload-LREG5X.txt content 
[speaker-4k5nn reloader] ['no ip prefix-list 10.150.245.1-pl-ipv4 seq 5 permit 10.150.246.1/32\n', 
[speaker-4k5nn reloader]  'no ip prefix-list 10.150.245.1-pl-ipv4 seq 10 permit 10.150.246.2/32\n', 
[speaker-4k5nn reloader]  'no ip prefix-list 10.150.245.1-pl-ipv4 seq 15 deny any\n', 
[speaker-4k5nn reloader]  'no ipv6 prefix-list 10.150.245.1-pl-ipv4 seq 5 deny any\n', 
[speaker-4k5nn reloader]  'router bgp 64537\n neighbor 10.150.245.1 ebgp-multihop\n', 
[speaker-4k5nn reloader]  'router bgp 64537\n neighbor 10.150.245.1 port 179\n', 
[speaker-4k5nn reloader]  'ip prefix-list 10.150.245.1-pl-ipv4 permit 10.150.246.1/32\n', 
[speaker-4k5nn reloader]  'ip prefix-list 10.150.245.1-pl-ipv4 permit 10.150.246.2/32\n', 
[speaker-4k5nn reloader]  'ip prefix-list 10.150.245.1-pl-ipv4 deny any\n', 
[speaker-4k5nn reloader]  'ipv6 prefix-list 10.150.245.1-pl-ipv4 deny any\n'] 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,390  INFO: Loading Config object from vtysh show running 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,484  INFO: "frr version 7.5.1_git" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,484  INFO: "frr defaults traditional" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,484  INFO: "service integrated-vtysh-config" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,484  INFO: "line vty" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:22,484  INFO: /var/run/frr/reload-5P7Q95.txt content 
[speaker-4k5nn reloader] ['router bgp 64537\n neighbor 10.150.245.1 ebgp-multihop\n', 
[speaker-4k5nn reloader]  'router bgp 64537\n neighbor 10.150.245.1 port 179\n', 
[speaker-4k5nn reloader]  'ip prefix-list 10.150.245.1-pl-ipv4 permit 10.150.246.1/32\n', 
[speaker-4k5nn reloader]  'ip prefix-list 10.150.245.1-pl-ipv4 permit 10.150.246.2/32\n', 
[speaker-4k5nn reloader]  'ip prefix-list 10.150.245.1-pl-ipv4 deny any\n', 
[speaker-4k5nn reloader]  'ipv6 prefix-list 10.150.245.1-pl-ipv4 deny any\n', 
[speaker-4k5nn reloader]  'router bgp 64537\n neighbor 10.150.245.1 ebgp-multihop\n', 
[speaker-4k5nn reloader]  'router bgp 64537\n neighbor 10.150.245.1 port 179\n', 
[speaker-4k5nn reloader]  'ip prefix-list 10.150.245.1-pl-ipv4 permit 10.150.246.1/32\n', 
[speaker-4k5nn reloader]  'ip prefix-list 10.150.245.1-pl-ipv4 permit 10.150.246.2/32\n', 
[speaker-4k5nn reloader]  'ip prefix-list 10.150.245.1-pl-ipv4 deny any\n', 
[speaker-4k5nn reloader]  'ipv6 prefix-list 10.150.245.1-pl-ipv4 deny any\n'] 
[speaker-4k5nn reloader] FRR reloaded successfully! 1 seconds 
[speaker-4k5nn speaker] {"caller":"frr.go:373","level":"info","op":"reload-validate","success":"reloaded config","ts":"2023-05-18T21:51:24Z"} 
[speaker-4k5nn frr] 2023/05/18 21:51:24.388 BGP: [EC 33554454] 10.150.245.1 [Error] bgp_read_packet error: Connection reset by peer 
[speaker-4k5nn speaker] {"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"flexget/svc-flexget","ts":"2023-05-18T21:51:35Z"} 
[speaker-4k5nn speaker] {"caller":"bgp_controller.go:302","event":"updatedAdvertisements","ips":["10.150.246.3"],"level":"info","msg":"making advertisements using BGP","numAds":1,"pool":"pool246","protocol":"bgp","ts":"2023-05-18T21:51:35Z"} 
[speaker-4k5nn speaker] {"caller":"main.go:355","event":"serviceAnnounced","ips":["10.150.246.3"],"level":"info","msg":"service has IP, announcing","pool":"pool246","protocol":"bgp","ts":"2023-05-18T21:51:35Z"} 
[speaker-4k5nn speaker] {"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"flexget/svc-flexget","level":"info","ts":"2023-05-18T21:51:35Z"} 
[speaker-4k5nn speaker] {"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"flexget/svc-flexget","ts":"2023-05-18T21:51:36Z"} 
[speaker-4k5nn speaker] {"caller":"main.go:400","event":"serviceWithdrawn","ip":null,"ips":["10.150.246.3"],"level":"info","msg":"withdrawing service announcement","pool":"pool246","protocol":"bgp","reason":"noEndpoints","ts":"2023-05-18T21:51:36Z"} 
[speaker-4k5nn speaker] {"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"flexget/svc-flexget","level":"info","ts":"2023-05-18T21:51:36Z"} 
[speaker-4k5nn reloader] Caught SIGHUP and acquired lock! Reloading FRR.. 
[speaker-4k5nn reloader] Checking the configuration file syntax 
[speaker-4k5nn reloader] /usr/lib/frr/frr-reload.py:805: SyntaxWarning: "is not" with a literal. Did you mean "!="? 
[speaker-4k5nn reloader]   if line is not "exit-vrf": 
[speaker-4k5nn reloader] 2023-05-18 21:51:38,671  INFO: Called via "Namespace(input=None, reload=False, test=True, debug=False, log_level='info', stdout=True, pathspace=None, filename='/etc/frr_reloader/frr.conf', overwrite=False, bindir='/usr/bin', confdir='/etc/frr', rundir='/var/run/frr', vty_socket=None, daemon='')" 
[speaker-4k5nn reloader] 2023-05-18 21:51:38,671  INFO: Loading Config object from file /etc/frr_reloader/frr.conf 
[speaker-4k5nn reloader] 2023-05-18 21:51:38,764  INFO: Loading Config object from vtysh show running 
[speaker-4k5nn reloader] 2023-05-18 21:51:38,859  INFO: "frr version 7.5.1_git" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:38,859  INFO: "frr defaults traditional" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:38,860  INFO: "service integrated-vtysh-config" cannot be removed 
[speaker-4k5nn reloader] 2023-05-18 21:51:38,860  INFO: "line vty" cannot be removed 
[speaker-4k5nn reloader]  
[speaker-4k5nn reloader] Lines To Delete 
[speaker-4k5nn reloader] =============== 
[speaker-4k5nn reloader] ipv6 forwarding 
[speaker-4k5nn reloader] router bgp 64537 
[speaker-4k5nn reloader]  no neighbor 10.150.245.1 ebgp-multihop 255 
[speaker-4k5nn reloader]  
[speaker-4k5nn reloader] Lines To Add 
[speaker-4k5nn reloader] ============ 
[speaker-4k5nn reloader] no ip prefix-list 10.150.245.1-pl-ipv4 seq 5 permit 10.150.246.1/32 
[speaker-4k5nn reloader] no ip prefix-list 10.150.245.1-pl-ipv4 seq 10 permit 10.150.246.2/32 
[speaker-4k5nn reloader] no ip prefix-list 10.150.245.1-pl-ipv4 seq 15 deny any 
[speaker-4k5nn reloader] no ipv6 prefix-list 10.150.245.1-pl-ipv4 seq 5 deny any 
[speaker-4k5nn reloader] router bgp 64537 
[speaker-4k5nn reloader]  neighbor 10.150.245.1 ebgp-multihop 
[speaker-4k5nn reloader] router bgp 64537 
[speaker-4k5nn reloader]  neighbor 10.150.245.1 port 179 
[speaker-4k5nn reloader] ip prefix-list 10.150.245.1-pl-ipv4 permit 10.150.246.1/32 
[speaker-4k5nn reloader] ip prefix-list 10.150.245.1-pl-ipv4 permit 10.150.246.2/32 
[speaker-4k5nn reloader] ip prefix-list 10.150.245.1-pl-ipv4 deny any 
[speaker-4k5nn reloader] ipv6 prefix-list 10.150.245.1-pl-ipv4 deny any 
[speaker-4k5nn reloader] Applying the configuration file

**Comment by benkelly12** [comment]
Hi 
Is anything going to happen with this?

**Comment by fedepaol** [comment]
yep, sorry but I am a bit swamped. Will get to you soon-ish. The behaviour doesn't sound right.

**Comment by benkelly12** [comment]
Cheers

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fedepaol** [comment]
https://metallb.universe.tf/troubleshooting/#the-logs-and-the-yaml-output-of-all-the-crs to see how to enable debug logs

**Comment by fedepaol** [comment]
@benkelly12 ping?
