### ISSUE TITLE
Enable startupprobe timeout value for the helm chart 

### ISSUE THREAD

**Issue by 2fst4u** [metallb/metallb#1963]
On lower powered devices like raspberry pis, the default startupprobe timeout value of "1 second" is too short for the frr container to become ready, causing it to eventually go into crashloopbackoff.

There are already some startupprobe values in the chart, but the timeout value isn't present as a value that can be changed.

Unless of course I can just put it in and it will work, but the default values option on artifacthub doesn't show it as an option.

**Comment by 2fst4u** [comment]
Actually on second thoughts this may not be so necessary. I'm still struggling to find a good resource request amount that works but if a single startupprobe is successful with 1 second timeout, then the livenessprobe settings take over and those are configurable.

Interested in thoughts.

**Comment by fedepaol** [comment]
sorry, I just opened the charts and it seems the startupprobe is configurable:
https://github.com/metallb/metallb/blob/main/charts/metallb/templates/speaker.yaml#L373

what am I missing?

**Comment by 2fst4u** [comment]
failureThreshold and periodSeconds are but  initialDelaySeconds, successThreshold and timeoutSeconds aren't for the startupprobe.

**Comment by fedepaol** [comment]
But failureThreshold and periodSeconds alone should give frr enough time to start?
We tolerate up to 30 failed probes ( https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml#L317) and we probe every 5 seconds.
See https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

Does it mean that frr takes more than 2.5 minutes to start?

**Comment by 2fst4u** [comment]
I may have been suffering from the same issue as https://github.com/metallb/metallb/issues/1926. I'm unsure if an update to the helm chart is required to overcome it.

**Comment by fedepaol** [comment]
Can you try to refetch the images / deploy from main to see if that fixes as it did in #1926?

**Comment by 2fst4u** [comment]
With the default frr image tag in the helm chart I still get the startup probe failing. I have to disable it completely for the container to start.

**Comment by fedepaol** [comment]
I am talking about the -cp containers that contain the frr-metrics binary

**Comment by 2fst4u** [comment]
Sorry I'm not much of an expert I can't tell how those containers are defined in the helm chart.

**Comment by fedepaol** [comment]
For the sake of the try, just edit the speaker daemonset manually. Otherwise you'd have to change the speaker image as a whole, but it may have unexpected side effects.

**Comment by fedepaol** [comment]
Fixed by https://github.com/metallb/metallb/pull/2034

**Comment by 2fst4u** [comment]
I'm not able to see the values in the helm chart. Should this work now?
