### ISSUE TITLE
Helm chart templates are missing the namespace

### ISSUE THREAD

**Issue by ankitm123** [metallb/metallb#1964]
I recently migrated from kustomize to helm charts for metallb. While the kutomize manifests had namespace (https://github.com/metallb/metallb/blob/e708fc9010afb80c379bdfadd5d543931164ca5e/config/native/kustomization.yaml#L10), the helm chart templates are missing namespaces for namespace scoped resources when generating manifests using helm templates (We generate manifests using helm and then apply using kubectl).
For example: https://github.com/metallb/metallb/blob/e708fc9010afb80c379bdfadd5d543931164ca5e/charts/metallb/templates/rbac.yaml#L109-L111

**Comment by gclawes** [comment]
Helm templates typically don't render namespaces, helm will inject that at deploy time with `helm install` or `helm upgrade`.  I believe it's typically considered an anti-pattern in chart development to include the `.metadata.namespace` in the templates.

If you are not using helm to do the install, you can do something like `helm template ... | kubectl apply -n <namespace>`

**Comment by ankitm123** [comment]
> Helm templates typically don't render namespaces

Not sure about this.
See https://github.com/argoproj/argo-helm/pull/1937#issuecomment-1504089484. I see almost all major projects specify that. Also in the PR, I am using `.Release.namespace`, a value that is injected by helm anyways (https://helm.sh/docs/chart_template_guide/builtin_objects/) :thinking:  

>  believe it's typically considered an anti-pattern in chart development to include the .metadata.namespace in the templates.

Any references for this? I don't see anything in the helm best practices (https://helm.sh/docs/chart_best_practices/) unless I am missing context. Probably this helm issue is what ur referring to. https://github.com/helm/helm/issues/3553, but in all honestly it seems more like a flaw with helm :shrug: 

> If you are not using helm to do the install, you can do something like helm template ... | kubectl apply -n <namespace>

Yes, that would work, but I think the point of `helm template` is so that other tools (could be kubectl, but also other tools which dont have a way to specify the namespace) use helm generated templates. A comment from argo: https://github.com/argoproj/argo-helm/pull/1937#issuecomment-1505056635

I can try to work around this with some ytt (In case we move away from kubectl to some other tool), if you think it is not worth including the namespace in the templates.

**Comment by ankitm123** [comment]
> Interesting issue. I believe, but feel free to burn me, that using the `--namespace metallb-system` parameter, optionally combined with `--create-namespace` installs MetalLB in the desired namespace. Wouldn't that fix this issue?

Not when using helm template. See: https://github.com/helm/helm/issues/3553
@fedepaol any updates?
