### ISSUE TITLE
MetallB L2 Loadbalancer behind home NAT

### ISSUE THREAD

**Issue by bernardgut** [metallb/metallb#1971]
NOTE: This is not an issue. It is both a Tutorial and a Feature request. If like me, you were trying to run a L2 lb in your k8s at home and got stuck at the part where you couldn't access your L2-mode Loadbalancer services, read on.

### The problem
If you install Metallb on your k8s at home, chances are you are trying to create services L2 connectivity, such as for exemple, a Gitlab instance. In order to push to your instance with SSH, port 22 needs to be accessed and loadbalanced properly from outside your cluster. After successfully installing Metallb in L2-mode, and using an IP range within your home network (but outside of your DHCP range), you will quickly hit a wall when trying to access those public Loadbalancer IPs from outside your LAN. Most home routers will give you errors such as the one below:

![image](https://github.com/metallb/metallb/assets/1610489/61627335-9e90-4f90-8203-248243d8c0f9)
_Example of the error you might see, assuming your LAN is 192.168.1.0/24 and you reserved 192.168.1.100-192.168.1.255 for Metallb_

This is due to the fact that most home routers will not support more than one IP/device. 

### The solution
At this point, you just wasted a lot of time for seemingly nothing. According to the internet, and at the time of this post, the only solutions are :
- migrate your Metallb configuration BGP mode and pay thousands of dollars for a Cisco router. (Hell no). 
- Disable NAT entirely in your home network and route everything to your K8s Metallb host (not very safe, especially if you have other family members in your LAN).

If you read the excellent post ["Configuring routing for MetalLB in L2 mode" by Andrei Kvapil](https://itnext.io/configuring-routing-for-metallb-in-l2-mode-7ea26e19219e), chances are you realized this also doesn't really fix the issue of router limitations. It did help me find the good solution. Read on. 

After digging a bit, here is a third solution I came up with: 
- **Assign a device with it's own MAC address to each Loadbalancer service created by MetallB, such that a home router can see/assign NAT entries for each service individually**: 

```
#!/bin/sh
# set-mcvln.sh <host-inet> <svc-name> <svc-ip> <cidr-subnet>
#
# Configure routing with single MAC address/service for Metallb in L2 Mode
# Goal : be able to use NAT with Metallb in a LAN.
#
# Run this first then run kubectl expose deploy <your-deployment> --port=XXX --target-port=XXX
#
# this is a stub. Check it before running it.


HWLINK=$1
NAME=$2
MACVLN=k8s.$2
IP=$3
SUBNET=$4
NETWORK=$(ip -4 route list exact default | head -n1 | cut -d' ' -f3)
GATEWAY=$(ip -o route | grep default | grep "$HWLINK" | awk '{print $3}')

#create interface
ip link add link "$HWLINK" "$MACVLN" type macvlan mode bridge
ip address add "$IP/$SUBNET" dev "$MACVLN"
ip link set dev "$MACVLN" up
#routing table
ip route add "$NETWORK" dev "$MACVLN" metric 0
ip route add default via "$GATEWAY" # assuming network was already configured for $HWLINK, this will not do anything
# configure metallb
echo "
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
 name: $NAME
 namespace: metallb-system
spec:
 addresses:
 - $IP/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
 name: $NAME-bc
 namespace: metallb-system
spec:
 interfaces:
 - $MACVLN
 ipAddressPools:
 - $NAME
" | kubectl apply -f -
# finally create your MetallB Loadbalancer svc
# kubectl expose deploy $NAME --port=22 --target-port=8822 --type=LoadBalancer

```

This will create and configure a MACVLAN interface named `k8s.name`. You can then create a Loadbalancer service and go to your home router profile to configure NAT. The above script is maintained [there](https://github.com/bernardgut/metallb-l2-nat/tree/master)

The problems now are 
- You need to run the above as a wrapper each time before running `kubectl expose deploy ...`
- You need to create a corresponding cleanup script that would run each time you delete these services.  
- This only works for a single node cluster

You could also modify and run it 10 times with names `pool-1`,`pool-2`,.. which will create 10 `IPAddressPools` objects and then let the normal auto-allocation in Metallb work its magic each time you create a Loadbalancer service. This is not very practical to maintain and I don't even know how it would work to run this automatically on the node where the Pod is created, so I am looking for a way to automate.

### Conclusion
This works for my small home setup, but I am not sure if this is the best solution, nor if there are other tools (Calico, Flannel ?) that could take care of that. 

I also don't know if there is any way to integrate something like this (I could re-write it in python) as a plugin for Metallb. I created a repo to maintain this feature because I really need it. If there is interest I will add more features. 

Let me know how what is the best option to automate/integrate this, as I am certain I am not the only one looking for NAT support

Cheers
Bernard

**Comment by fedepaol** [comment]
Thanks! This sounds nice and may help multiple users.

In order to make this work on multiple nodes, you could name each interface `k8s.name-node` and create the interfaces upfront on all the nodes (assuming you have a limited number of nodes, but should be the case if you want to resort to nat and not going bgp).

I am still not sure I understood how you would expose the LB ip outside. In any case, this can be implemented as a controller or as a chron job that runs externally to the cluster. I _think_ all the information is available (minus the part that sets the nat on the router). Let us know if something is missing and we should expose it (considering also what's already planned here https://github.com/metallb/metallb/blob/main/design/crd-status.md )

I am gonna close this, as it is not really a MetalLB issue.
