### ISSUE TITLE
Metallb doesn't work when the IP address pool is defined in a different VRF than the platform network at router end

### ISSUE THREAD

**Issue by tchauhan362** [metallb/metallb#1983]
Thanks for filing an issue! A few things before we get started:

1. This is not the place to ask for troubleshooting. Unfortunately
   troubleshooting LB issues in k8s takes a lot of time and effort
   that we simply don't have. If your load-balancers aren't working,
   please don't file an issue unless you have identified a _specific_
   bug to fix. Otherwise, please ask for help in the `#metallb`
   channel on the Kubernetes Slack.
2. Please search the bug tracker for duplicates before filing your
   bug.
3. If you're reporting a bug, please specify all of the following:
     - The bug itself, as detailed as you can.
     - Version of MetalLB
     - Version of Kubernetes
     - Name and version of network addon (e.g. Calico, Weave...)
     - Whether you've configured kube-proxy for iptables or ipvs mode

This is a bug I am reporting for below metallb.

Bug: When the used IP address pool for metallb is defined in any VRF or tenant other than the one where platform network or CNI network is defined, it doesn't work. It applies to both L2 and BGP mode. To be more specific, when it is configured in this way the requests come on the node (advertising the load balancing IP) via the interface configured for metallb address pool the initial TCP flow is not getting completed at first place. First SYN packet is reaching the node but no replies.

Version of metallb: v0.13.x

Version of kubernetes: 1.20.x

Network Addon: Calico

Kube-proxy for iptables

**Comment by yellowpattern** [comment]
I've made this work but you need to be very careful in how you do it. The first most important part is to have a different subnet for the BGP advertisement to that used for the address pools.

If VLAN 500 has IP# of 5.5.1.1 for your upstream BGP router and 5.5.1.10-5.5.1.19 for your 10 workers, then your BGPPeer IP# needs to be 5.5.1.1. The 5.5.1.10-19 are configured as additional network interfaces, be it using CNI or NNCP. You can then advertise your address pool of 1.1.1.1-20 via as being via those workers.

Openshift doesn't have native support for VRFs so there's nothing for metallb to leverage.

**Comment by fedepaol** [comment]
> Bug: When the used IP address pool for metallb is defined in any VRF or tenant other than the one where platform network or CNI network is defined, it doesn't work. It applies to both L2 and BGP mode. To be more specific, when it is configured in this way the requests come on the node (advertising the load balancing IP) via the interface configured for metallb address pool the initial TCP flow is not getting completed at first place. First SYN packet is reaching the node but no replies.
> 

This feels like a RPF issue (but I might be wrong). If there's no route to reach back the client, and the client reaches the host via a path that is not through the default gateway, the kernel stack will blackhole the syn packet.
In order to understand if this is the case, you can check the value of the rp_filter sysctl and try to loose it. You will probably require a static route back to the client, beacuse the reply will take the default gateway path.



> Version of metallb: v0.13.x
> 
> Version of kubernetes: 1.20.x
> 
> Network Addon: Calico
> 
> Kube-proxy for iptables

**Comment by fedepaol** [comment]
I am closing ithis under the assumption what I provided is correct. Please reopen in case it's not and you have tried to disable the rp_filter.
