### ISSUE TITLE
Support setting listen address for frr

### ISSUE THREAD

**Issue by yellowpattern** [metallb/metallb#1987]
frr supports providing a command line parameter to specify the "listen" address for frr. When running multiple speakers on a given node, being able to be specific about which speaker (BGPPeer) is active on which IP address is vital.

This is related to a few other issues to do with source addresses, e.g:
* https://github.com/metallb/metallb/issues/1560
* https://github.com/metallb/metallb/issues/689

**Comment by fedepaol** [comment]
I am not totally sure I understand. I'd be interested to learn about the use case a bit more. Are you referring to multiple speakers as metallb speakers? Or multiple BGPPeers reacheable by different nodes?

Is the problem related to the interface used to connect to each peer? Or do you expect metallb to override the address for a given session with something totally arbitrary?

**Comment by yellowpattern** [comment]
From FRR-BGPD(8):
...
```
   MODULE LOADING
...
       -l, --listenon
              Specify a specific IP address for bgpd to listen on, rather than its default of 0.0.0.0 / ::. This can be useful to constrain bgpd to an internal address, or to run multiple bgpd processes on one host.

```
When using multiple BGPPeers (or running multiple speakers) it is expected that they will each listen on their own IP address.

**Comment by fedepaol** [comment]
I understand, but what is the use case that you can't cover with the default behavior?
You can't run multiple speakers, so what is the real issue? Can you draw a diagram?

**Comment by fedepaol** [comment]
nope, there's one speaker only. And it doesn't listen. It initiates the session. What is the use case for this? Why using the ip of the interface to connect to the peer is not enough?

**Comment by yellowpattern** [comment]
well just close it then

**Comment by yellowpattern** [comment]
close
