### ISSUE TITLE
Admission control webhook for MetalLB's configuration

### ISSUE THREAD

**Issue by danderson** [metallb/metallb#2]
Kubernetes 1.8/1.9 support admission webhooks. MetalLB should register an admission webhook for its configuration, so that it can early-reject invalid and unsafe configurations.

We could also have the webhook register itself for all service creations/changes, so that we can validate the shape of a requested Service before even writing it to the cluster.

**Comment by danderson** [comment]
k8s 1.9 graduates admission control webhooks to beta, and makes backwards-incompatible changes. We probably don't want to support the alpha version of the API.

**Comment by rifaterdemsahin** [comment]
waiting for the update relating to the reddit thread
https://www.reddit.com/r/kubernetes/comments/a0kevu/cant_access_external_ip_other_than_the_kubernetes/

**Comment by fedepaol** [comment]
Closign this, webhooks were implemented in the transition to CRDs
