### ISSUE TITLE
Misleading deprecation warning when applyin metallb.io v1beta1 IPAddressPool

### ISSUE THREAD

**Issue by maltejk** [metallb/metallb#2000]
https://github.com/metallb/metallb/blob/main/charts/metallb/charts/crds/templates/crds.yaml#L117

This IMHO leads to warnings like

```
W0714 12:52:47.910004       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool`
```

even when applying 

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
```

**Comment by fedepaol** [comment]
I always thought that those logs were related to the watch action that the controller has on the deprecated API (which we can't do anything about). Are you sure that it appears contextually to applying ipaddresspools?

**Comment by fedepaol** [comment]
If that is the case, there's no need to prepare the pr. I prefer to keep having the red herring log but informing users that they should use the other one.

**Comment by fedepaol** [comment]
(and thanks for raising and looking into this!)
