### ISSUE TITLE
autoAssign does not take effect

### ISSUE THREAD

**Issue by jiayi-1994** [metallb/metallb#2003]
Version of MetalLB: v0.13.10
Version of Kubernetes: v1.24.6
Name and version of network addon: Calico v3.23.3
Whether you've configured kube-proxy for iptables or ipvs mode: ipvs
How to produce:
```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  annotations:
    description: ""
  creationTimestamp: "2023-07-17T03:49:46Z"
  generation: 13
  name: t1
  namespace: metallb-system
  resourceVersion: "106521386"
  uid: b598091d-205e-449e-9b0b-a5caace37c2b
spec:
  addresses:
  - 192.168.30.210/32
  - 192.168.30.211-192.168.30.212
  - 192.168.30.213/32
  autoAssign: true
  avoidBuggyIPs: false
  **serviceAllocation: {}**
```
if serviceAllocation is empty struct,  autoAssign does not take effect

**Comment by fedepaol** [comment]
I checked the code, and after all the behaviour seems legit. The serviceAllocation is an optional field, and not specifying it has a different semantic rather than adding it empty (which means, do not select any service).

Closing this.
