### ISSUE TITLE
Allow setting speaker log level from environment variable

### ISSUE THREAD

**Issue by Borrelhapje** [metallb/metallb#2007]
The speaker has a default log level of `info` and this is only changeable using additional command line arguments. It would be nice if this was configurable using an environment variable. I'd suggest `METALLB_SPEAKER_LOG_LEVEL`?

I'd prefer not to override all arguments of a container in order to set one additional argument, as that means I'll likely lose out on some updated defaults in the future.

It's about this line:
https://github.com/metallb/metallb/blob/22ffd63a2942a4cd5afd28926fa6a124cecf8ed3/speaker/main.go#L80

**Comment by Borrelhapje** [comment]
I'd be happy to provide a PR.

**Comment by oribon** [comment]
hey :) can you explain a bit more what are you trying to achieve? the helm charts already expose a knob for the logLevel, why does it matter to you if it's a flag or env var? how do you intend to add env vars in a way that wouldn't be overridden later?

**Comment by bh-tt** [comment]
I just realised I'm using the bitnami chart and that does not expose a setting. I'll just post a PR there to add that knob.

(I'm also borrelhapje, accidentally used my private account to create this issue).

**Comment by bh-tt** [comment]
https://github.com/bitnami/charts/pull/17996
