### ISSUE TITLE
Better error messages when things go wrong with IP ranges in the config

### ISSUE THREAD

**Issue by danderson** [metallb/metallb#201]
With #188, you can use explicit ranges of IPs instead of CIDR prefixes, but internally the config parser turns those ranges into a set of CIDR prefixes. This means that all subsequent validation of the config will spew errors about CIDR prefixes that don't exist verbatim in the configuration. This is obviously quite terrible.

**Comment by ReticentFacade** [comment]
@fedepaol, can I work on this?

**Comment by fedepaol** [comment]
@ReticentFacade sure thing!

**Comment by fedepaol** [comment]
and sorry for the delay

**Comment by ReticentFacade** [comment]
No problem! I just read the reply myself, I'll start working on it today.

**Comment by ReticentFacade** [comment]
@fedepaol I'm a beginner in open source so if there's anything that you could recommend I read before working, that'd be helpful. I've read the contribution guidelines and started with the documentation as well.

**Comment by fedepaol** [comment]
Closing this, we have a fail fast behavior which is pool specific in both the webhook and the config parsing.

The error is like `invalid CIDR %q in pool %q: %s", cidr, p.Name, err)` and then bubbled up here https://github.com/metallb/metallb/blob/7f87bf061165e50bd7b07d9018c0e8a2501f5058/internal/config/config.go#L312
