### ISSUE TITLE
PodSecurityPolicy and policy/v1beta1 errors in k8s 1.26

### ISSUE THREAD

**Issue by admun** [metallb/metallb#2012]
- Version of MetalLB: helm chart v0.13.3 (deploy via flux v2)
- Version of Kubernetes: rke2 1.26.3
- Name and version of network addon: cilium 1.13.2 (using rke2-cilium helm)

observed the following error events:
```
metallb-system    0s          Normal   error               helmrelease/metallb                     Helm upgrade failed: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"...
metallb-system    0s          Normal   error               helmrelease/metallb                     reconciliation failed: Helm upgrade failed: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```
I think PodSecurityPolicy and policy/v1beta1 and no longer in 1.24+

**Comment by fedepaol** [comment]
Thanks for raising this!
It was fixed in 0.13.5: https://metallb.universe.tf/release-notes/#version-0-13-5
Closing the issue

**Comment by admun** [comment]
Sorry for reporting the fixed issue. My mistake not check the metallb's repo.....

I was checking https://artifacthub.io/packages/helm/metallb/metallb and seeing latest is 3.13.10.

Not sure who manage that, but it looks like info there is outdated.

**Comment by fedepaol** [comment]
> Sorry for reporting the fixed issue. My mistake not check the metallb's repo.....
> 
> I was checking https://artifacthub.io/packages/helm/metallb/metallb and seeing latest is 3.13.10.
> 
> Not sure who manage that, but it looks like info there is outdated.

that is outside of our control :/
