### ISSUE TITLE
metallb assigned IP is not pinging

### ISSUE THREAD

**Issue by phaneesh11** [metallb/metallb#2013]
I have installed  metallb 0.13.10 , External IP assigned ip from metallb is not accessible getting destination unreachable

i am using ipvs mode
k8s version is 1.27.3

my address pool and l2sdvertising given below

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production
  namespace: metallb-system
spec:
  addresses:
  - 172.16.245.171-172.16.245.174
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system

**Comment by DerRockWolf** [comment]
Try `arping` instead of `ping`. Also try accessing the service via e.g. `curl`.

**Comment by phaneesh11** [comment]
@DerRockWolf Thank you, its working fine

**Comment by fedepaol** [comment]
Thanks @DerRockWolf for the help!
Closing the issue
