### ISSUE TITLE
Honor node.kubernetes.io/exclude-from-external-load-balancers

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#2021]
The label [node.kubernetes.io/exclude-from-external-load-balancers](http://node.kubernetes.io/exclude-from-external-load-balancers) is used to instruct the cluster to " exclude a worker node from the list of backend servers in a backend set"

**Comment by cyclinder** [comment]
Is it labeled for the loadbalancer service?

**Comment by fedepaol** [comment]
It's a bool: https://kubernetes.io/docs/reference/labels-annotations-taints/#node-kubernetes-io-exclude-from-external-load-balancers

**Comment by cyclinder** [comment]
got it, We need to exclude labeled nodes as service announce nodes.
