### ISSUE TITLE
APR broadcast mode which publish a MAC address with a downed NIC 

### ISSUE THREAD

**Issue by rogeryuchao** [metallb/metallb#2026]
### MetalLB Version

latest

### Deployment method

Manifests

### Main CNI

flannel

### Kubernetes Version

1.20.15

### Cluster Distribution

others

### Describe the bug

In each bare metal K8S node, we disable 1 of the NIC but only allow the other to announce the IP to the network device. When metalLB is using ARP mode to broadcast the NIC MAC to the router, sometimes we see the metallb system is broadcast the disabled NIC Addr to the router, which makes the router cannot find the VIP, may you please kindly help to let me know whether this is a bug or on-purpose design, and how can I fix the issue? Again the router's APR table refresh window is 20mins, we don't want to reduce it too much which makes a heavy loading to it

### To Reproduce

0. On a server, disable 1 NIC, enable 1 another
1. Apply a service with metallb IPPoolAdress
2. Check the ARP table on the router, will find the APR table shows the broadcase VIP-MAC mapping is mapped to the disabled NIC

### Expected Behavior

Sometimes the VIP cannot be visited, when checking the APR mapping table, the disabled NIC will always be mapped

### Additional Context

None

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Can you expand on how you disable the nic? If MetalLB replies, it means it received the ARP request on that interface.
Assuming the layout of the nodes is consistent, one way to fix this is to use the L2Advertisement's interface selector.

**Comment by rogeryuchao** [comment]
Hi, @fedepaol, thanks a lot for your such prompt response! I'm not sure how I disable the nic because I'm actually not the infra member, while I think your suggestion is great, we can try the interface selector~ In case we have multiple node maybe use different NIC (node A: eth0, node B: etch 1), should I config them into different L2Advertisement, or can I config it in the same object?

**Comment by fedepaol** [comment]
The interface selectors just limit the set of interfaces among the listed ones. So, if you don't have a scenario where eth1 is disabled on some nodes, you can have both on the same L2Advertisement. Otherwise you'll have to have two L2Advertisements with different node selectors.

**Comment by rogeryuchao** [comment]
Even I want to publish the same IPAddressPool on multiple node, I can claim multiple L2Advertisement for the same IPAddressPool list?

**Comment by fedepaol** [comment]
yep, that is the default unless you specify a pool selector. Please read the docs :-) !

**Comment by rogeryuchao** [comment]
@fedepaol Awesome, thanks a lot for your kind help, let me try on it~ very helpful~
