### ISSUE TITLE
Export annotation constants for import in products

### ISSUE THREAD

**Issue by glynternet** [metallb/metallb#2027]
### Is your feature request related to a problem?

Using the annotation label keys in manual typing that's susceptible to typos.

### Describe the solution you'd like

We'd like to directly refer to the annotation label keys plz 😄 

https://github.com/metallb/metallb/blob/4672d27ba6168e833c33a4f3ace337c079de57b3/controller/service.go#L34

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
@glynternet keen filing a PR for this :P ?

**Comment by cyclinder** [comment]
Is it okay to make it public?

**Comment by fedepaol** [comment]
I am not against it
