### ISSUE TITLE
exposed port cannot be accessed from outside the k8s network

### ISSUE THREAD

**Issue by vmhubs** [metallb/metallb#2032]
### MetalLB Version

0.13.10

### Deployment method

Manifests

### Main CNI

flannel

### Kubernetes Version

1.23.16

### Describe the bug

Some LoadBalancer,k8s cannot be connected outside the cluster, but is normal in the cluster. To do this, you need to start the speaker component, but the duration is not long，Each time, it is required to restart the speaker component for external network communication to function properly.

### To Reproduce

Ports in the k8s cluster network segment are normal, but external communication is interrupted

### Expected Behavior

Request support

### Additional Context

Request support

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by oribon** [comment]
hi, I don't understand which bug you're reporting here. If this is about troubleshooting help please start a thread over the #metallb slack channel. closing this for now, if I got this wrong feel free to re-open with more details.
