### ISSUE TITLE
Im starting with k8s and i deployed prometheus+grafana and also metallb. I was abble to put metallb to assign the IPs and it worked for Grafana however for prometheus the IP assigned by loadbalancer gives "Unable connection" on the browser

### ISSUE THREAD

**Issue by alexastro** [metallb/metallb#2037]
### MetalLB Version

metallb/controller:v0.13.10

### Deployment method

Charts

### Main CNI

Calico

### Kubernetes Version

1.26.7

### Describe the bug

MetalLB assigns IP to prometheus but its not reachble but grafana is!

### To Reproduce

1. helm repo add stable https://charts.helm.sh/stable
2. helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
3. helm repo update
4. kubectl create namespace prometheus
5. helm install stable prometheus-community/kube-prometheus-stack -n prometheus

Deploy metallb
1.kubectl edit configmap -n kube-system kube-proxy
"strictARP: true"

2. kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
3. Create ip pool and l2 advertisement
--------
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.56.150-192.168.56.165      
-----------
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-matallb
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
-------------

4. Change the stable-kube-prometheus-sta-prometheus service to LoadBalancer
5. Change the stable-grafana service to LoadBalancer

### Expected Behavior

Able to access both grafana and prometheus with the loadbalancer IPs.

### Additional Context

Its a local 3 node cluster centOS 7, virtual machines and both prometheus and grafana UI are accesible by nodeport service but when changed to loadbalance only grafana is reachble.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by oribon** [comment]
hey, can you also attach the debug logs and service/epslice definition?

**Comment by alexastro** [comment]
> hey, can you also attach the debug logs and service/epslice definition please?


[server1@node1 grafana]$ kubectl get ingress -n prometheus
NAME                        CLASS   HOSTS               ADDRESS          PORTS   AGE
stable-grafana-ingress      nginx   driftec.prom.com    192.168.56.151   80      20m
stable-prometheus-ingress   nginx   driftec.local.com   192.168.56.151   80      10m

[server1@node1 grafana]$ kubectl logs controller-5fd797fbf7-9l7c6 -n metallb-system
W0809 15:26:15.241718       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-prometheus-node-exporter","ts":"2023-08-09T15:28:18Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-prometheus-node-exporter","level":"info","ts":"2023-08-09T15:28:18Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-kube-prometheus-sta-alertmanager","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-kube-prometheus-sta-alertmanager","level":"info","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-kube-prometheus-sta-operator","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-kube-prometheus-sta-operator","level":"info","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-kube-prometheus-sta-prometheus","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-kube-prometheus-sta-prometheus","level":"info","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-kube-state-metrics","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-kube-state-metrics","level":"info","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-grafana","ts":"2023-08-09T15:28:19Z"}
{"caller":"main.go:56","event":"serviceDeleted","level":"info","msg":"service deleted","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:95","controller":"ServiceReconciler","event":"force service reload","level":"info","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:97","controller":"ServiceReconciler","end reconcile":"prometheus/stable-grafana","level":"info","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/stable-kube-prometheus-sta-kube-scheduler","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/stable-kube-prometheus-sta-kube-scheduler","level":"info","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller_reload.go:61","controller":"ServiceReconciler - reprocessAll","level":"info","start reconcile":"metallbreload/reload","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller_reload.go:104","controller":"ServiceReconciler - reprocessAll","end reconcile":"metallbreload/reload","level":"info","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/stable-kube-prometheus-sta-kube-proxy","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/stable-kube-prometheus-sta-kube-proxy","level":"info","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/stable-kube-prometheus-sta-kube-etcd","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/stable-kube-prometheus-sta-kube-etcd","level":"info","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/stable-kube-prometheus-sta-kube-controller-manager","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/stable-kube-prometheus-sta-kube-controller-manager","level":"info","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/stable-kube-prometheus-sta-coredns","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/stable-kube-prometheus-sta-coredns","level":"info","ts":"2023-08-09T15:28:19Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/alertmanager-operated","ts":"2023-08-09T15:28:22Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/alertmanager-operated","level":"info","ts":"2023-08-09T15:28:22Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/prometheus-operated","ts":"2023-08-09T15:28:22Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/prometheus-operated","level":"info","ts":"2023-08-09T15:28:22Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/stable-kube-prometheus-sta-coredns","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/stable-kube-prometheus-sta-coredns","level":"info","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/stable-kube-prometheus-sta-kube-scheduler","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/stable-kube-prometheus-sta-kube-scheduler","level":"info","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/stable-kube-prometheus-sta-kube-controller-manager","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/stable-kube-prometheus-sta-kube-controller-manager","level":"info","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/stable-kube-prometheus-sta-kube-proxy","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/stable-kube-prometheus-sta-kube-proxy","level":"info","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/stable-kube-prometheus-sta-kube-etcd","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/stable-kube-prometheus-sta-kube-etcd","level":"info","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-grafana","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-grafana","level":"info","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-kube-state-metrics","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-kube-state-metrics","level":"info","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-prometheus-node-exporter","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-prometheus-node-exporter","level":"info","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-kube-prometheus-sta-alertmanager","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-kube-prometheus-sta-alertmanager","level":"info","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-kube-prometheus-sta-prometheus","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-kube-prometheus-sta-prometheus","level":"info","ts":"2023-08-09T15:34:00Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-kube-prometheus-sta-operator","ts":"2023-08-09T15:34:01Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-kube-prometheus-sta-operator","level":"info","ts":"2023-08-09T15:34:01Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/alertmanager-operated","ts":"2023-08-09T15:34:27Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/alertmanager-operated","level":"info","ts":"2023-08-09T15:34:27Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/prometheus-operated","ts":"2023-08-09T15:34:30Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/prometheus-operated","level":"info","ts":"2023-08-09T15:34:30Z"}
W0809 15:34:35.349524       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-grafana","ts":"2023-08-09T15:37:12Z"}
{"caller":"service.go:142","event":"ipAllocated","ip":["192.168.56.150"],"level":"info","msg":"IP address assigned by controller","ts":"2023-08-09T15:37:12Z"}
{"caller":"main.go:107","event":"serviceUpdated","level":"info","msg":"updated service object","ts":"2023-08-09T15:37:12Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-grafana","level":"info","ts":"2023-08-09T15:37:12Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-grafana","ts":"2023-08-09T15:37:12Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-grafana","level":"info","ts":"2023-08-09T15:37:12Z"}
W0809 15:40:29.341301       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-kube-prometheus-sta-prometheus","ts":"2023-08-09T15:46:37Z"}
{"caller":"service.go:142","event":"ipAllocated","ip":["192.168.56.152"],"level":"info","msg":"IP address assigned by controller","ts":"2023-08-09T15:46:37Z"}
{"caller":"main.go:107","event":"serviceUpdated","level":"info","msg":"updated service object","ts":"2023-08-09T15:46:37Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-kube-prometheus-sta-prometheus","level":"info","ts":"2023-08-09T15:46:37Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"prometheus/stable-kube-prometheus-sta-prometheus","ts":"2023-08-09T15:46:37Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"prometheus/stable-kube-prometheus-sta-prometheus","level":"info","ts":"2023-08-09T15:46:37Z"}
W0809 15:48:19.343694       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W0809 15:53:23.345857       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W0809 16:01:19.348528       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W0809 16:06:31.350492       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool

**Comment by oribon** [comment]
can you use the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh), and the definitions of the LoadBalancer services?
also, how are you checking access to them?

**Comment by fedepaol** [comment]
@alexastro ping?

**Comment by AnakinFoxe** [comment]
@alexastro did you solve the issue eventually?

**Comment by AnakinFoxe** [comment]
> Closing this, feel free to reopen in case you are still hitting this

Never mind, I figured it out. It was because of the network policy for my case.
