### ISSUE TITLE
configmaptocrs can create resources with invalid names

### ISSUE THREAD

**Issue by Sebastian-RG** [metallb/metallb#2039]
### MetalLB Version

0.13.10

### Deployment method

Charts

### Main CNI

calico

### Kubernetes Version

1.24.6

### Cluster Distribution

kubespray

### Describe the bug

When using _configmaptocrs_ on configmaps that have resources with names that are not compatible with K8S, it can generate CR names that are not valid. This introduces an extra manual step for upgrading from 0.12.x to 0.13.x . I believe changing this will facilitate the adoption of 0.13.x in large projects such as Kubespray.

This may happen given that these invalid K8S names are valid for the configmap configuration. These names may include: Uppercase, underscores or length over 63 characters.

### To Reproduce

1. Create a configmap with an IPAddressPool with a name that has uppercase letters and underscores
2. Run it through configmaptocrs
3. The generated file cannot be directly applied to K8S, as it has invalid names

e.g.: The following CM:
`apiVersion: v1
data:
  config: |
    address-pools:
    - addresses:
      - 10.100.19.128/32
      - 10.100.16.153/32
      - 10.100.19.135/32
      - 10.100.16.150/32
      - 10.100.20.117/32
      - 10.100.18.171/32
      - 10.100.20.20/32
      - 10.100.19.7/32
      name: load_Balanced
      protocol: layer2`

Will be converted to:
`# This was autogenerated by MetalLB's custom resource generator.
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  creationTimestamp: null
  name: load_Balanced
  namespace: metallb-system
spec:
  addresses:
  - 10.100.19.128/32
  - 10.100.16.153/32
  - 10.100.19.135/32
  - 10.100.16.150/32
  - 10.100.20.117/32
  - 10.100.18.171/32
  - 10.100.20.20/32
  - 10.100.19.7/32
status: {}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  creationTimestamp: null
  name: l2advertisement1
  namespace: metallb-system
spec:
  ipAddressPools:
  - load_Balanced
status: {}
---`

### Expected Behavior

configmaptocrs converts CMs to valid K8S resources, and warns if it needs to change any names in the process.

### Additional Context

I've already made the changes necessary to make this work on my own fork. This modification of the original behavior only happens when a new flag "convert-names" is set to true. It is ready for a PR (complete with new tests). 
https://github.com/Sebastian-RG/metallb/commit/02ef1b96653ae5509d25f4f73ab80a16b7cc065e

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by oribon** [comment]
seems reasonable to me, wdyt @liornoy ?

**Comment by liornoy** [comment]
yup make sense.

**Comment by oribon** [comment]
@Sebastian-RG assigned this to you, feel free to open the PR :)

**Comment by Sebastian-RG** [comment]
@oribon @liornoy thank you! I'll send the PR in a couple of hours.
