### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by p64** [metallb/metallb#2040]
### Is your feature request related to a problem?

If one follows the documentation metallb APPEARS to not failover correctly.

### Describe the solution you'd like

First of all.  AMAZING SOFTWARE!  MetalLB fails over at the speed and precision of enterprise routing fault tolerance type devices.  Zero dropped arping on reboots.  I can't say enough positive things about the behavior once I got it to work.  At one point I was fairly certain it didn't work.  I'm hoping my experience can maybe improve the process for others that are new to the space.  I think one of the first things someone does with Kubernetes on metal is to get basically nginx and the LB IP to work.  So we are likely new to Kubernetes and maybe don't understand things like tolerations and such which gives the impression the software doesn't work.  But again, software is amazing.  Really well done.

Sorry this is some what lengthy but I hope it's complete enough to at least understand my path.  And maybe some adjustments to the documentation.  I hope this is well received.

What happened:

1. Followed https://kubernetes.github.io/ingress-nginx/deploy/ to install the 1.8.1 manifest with this https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/cloud/deploy.yaml
2. I followed https://metallb.universe.tf/installation/ and https://metallb.universe.tf/configuration/#layer-2-configuration to install and configure which had me install via this manifest https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
3. Also read this and chose the metalLB route: https://kubernetes.github.io/ingress-nginx/deploy/baremetal/

So after a while of tinkering, at some points I thought maybe it just doesn't work the way it should.  However it's SUPER as mentioned, so it was definitely my configuration.  Following the above steps I was left with:

- LB IPs that get assigned (SUPER) and are no longer "pending".
- NGINX working (also SUPER)
- L2 Announcements (SUPER)
- SPEAKERS on control planes (not so great)

So far, seemingly so good.  However when I tried to boot the node that had the VIP. the VIP never moved.  ARPING -b and tcpdump was definitely my friend.  Nothing was announcing during the boot.  In hindsight as it shouldn't with the way I set things up.  Issue #1937 seemed like the person was experiencing the same thing I was, but not exactly.  But kinda.

Eventually I figured out that the software is SO AMAZING that it only announces from a node that can service the request.  And since the default in the NGINX manifest was to have ONE NGINX controller replica, the NGINX pod never moved because of eviction timeouts and such.  Lowering that seemed like the wrong way to go.  My solution was to patch the nginx controller deployment to have replicas: 3 and to add antiaffinity so any nginx controller deployment to force nginx pods to run on separate worker nodes.

So two things I think would be helpful for other newbies:
1. Maybe two manifests?  One for a cluster with separate control plane nodes that shouldn't run the speaker (which seems to be default, but the manifest overrides this "default").  And another manifest with the tolerations to override the defaults to get the speaker to run on control planes.  Maybe it's just me but none of that was clear to me without hours of time.
3. Something about nodes will not advertise unless a pod is running that can "service" the LB service.  Again SUPER amazing that it won't advertise from a node that can't do it.  But not immediately evident to me.  Maybe others as well.

Thanks for making SUPER software.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by p64** [comment]
> > So two things I think would be helpful for other newbies:
> > 
> > 1. Maybe two manifests?  One for a cluster with separate control plane nodes that shouldn't run the speaker (which seems to be default, but the manifest overrides this "default").  And another manifest with the tolerations to override the defaults to get the speaker to run on control planes.  Maybe it's just me but none of that was clear to me without hours of time.
> 
> I am not sure how running the speakers on the master nodes too caused the issue.

It didn't cause the issue.  Separately from the issue, what I gleaned from the documentation was that by default the speaker should run on worker nodes.   Possible misinterpretation on my part.  But when I ran the manifest and checked the pods, I saw the speaker pod on the control-planes as well.  So It seemed like something wasn't right.  Eventually I figured out what a toleration was and that the manifest had such tolerations to make it run on the control-planes.  Maybe a default manifest (workers only) and then a patch for tolerations?  To match the "default" behavior expected?  My impression was / is the default behavior should be to run on worker nodes only.

> 
> > 2. Something about nodes will not advertise unless a pod is running that can "service" the LB service.  Again SUPER amazing that it won't advertise from a node that can't do it.  But not immediately evident to me.  Maybe others as well.
> 
> This part is covered in the troubleshooting guide (I hope): https://metallb.universe.tf/troubleshooting/#troubleshooting-service-advertisements

I see what you mean now.

---
A given speaker won’t advertise the service if:
- there are no active endpoints backing the service
- the service has externalTrafficPolicy=local and there are no running endpoints on the speaker’s node
....
---

I definitely didn't put that together when I ran the nginx manifest and had one replica of nginx ingress.  I guess part of me expected nginx to move quicker than it did or something to keep working.  Not a metalLB issue for sure.  Just a overall experience issue that was confusing.

I'm glad I didn't give up on MetalLB as it is truly amazing failover at the enterprise grade.  On a reboot of the worker node, I lose ZERO arpings.  Which is amazing.

**Comment by fedepaol** [comment]
Closing this as I think it's covered. Feel free to reopen if I missed some bits
