### ISSUE TITLE
Notice about PSA labels is under Helm installation

### ISSUE THREAD

**Issue by lindhe** [metallb/metallb#2043]
### MetalLB Version

0.13.10

### Deployment method

Not relevant

### Main CNI

n/a

### Describe the bug

There's a notice about setting PSA labels on the `metallb-system` namespace. But it's under "Installation with Helm", and I wonder if it shouldn't really be outside of that section?

https://github.com/metallb/metallb/blob/2ae8694087a9475f8c3664b45bdb3664130064a2/website/content/installation/_index.md?plain=1#L138-L151

### To Reproduce

1. Go to <https://metallb.org/installation/#installation-with-helm>.

### Expected Behavior

It seems to me like that is not a Helm specific configuration, so in that case it should be outside of the "Installation with Helm" section in the documentation.

### Additional Context

n/a

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
> There's a notice about setting PSA labels on the `metallb-system` namespace. But it's under "Installation with Helm", and I wonder if it shouldn't really be outside of that section?

It's there, because the all-in-one manifests / kustomize create the namespace with those labels.
Closing this issue.
