### ISSUE TITLE
error in speaker pods: "memberlist: failed to receive: Encryption is configured but remote state is not encrypted"

### ISSUE THREAD

**Issue by lethargosapatheia** [metallb/metallb#2050]
### MetalLB Version

0.13.10

### Deployment method

Manifests

### Main CNI

calico 3.26.1

### Kubernetes Version

1.27.2

### Cluster Distribution

vanilla (kubeadm)

### Describe the bug

After installing prometheus as a deployment, I start getting this kind of error in the speaker pods:
```
speaker-pjmpc speaker {"caller":"net.go:235","component":"Memberlist","level":"debug","msg":"memberlist: Stream connection from=10.20.20.227:25300","ts":"2023-08-22T10:18:06Z"}
speaker-pjmpc speaker {"caller":"net.go:268","component":"Memberlist","level":"error","msg":"memberlist: failed to receive: Encryption is configured but remote state is not encrypted from=10.20.20.227:25300","ts":"2023-08-22T10:18:06Z"}
```
And also:
```
speaker-brr8b speaker {"caller":"net.go:235","component":"Memberlist","level":"debug","msg":"memberlist: Stream connection from=10.230.172.65:44916","ts":"2023-08-22T10:18:08Z"}
speaker-brr8b speaker {"caller":"net.go:268","component":"Memberlist","level":"error","msg":"memberlist: failed to receive: Encryption is configured but remote state is not encrypted from=10.230.172.65:44916","ts":"2023-08-22T10:18:08Z"}
```
In the first case, `10.20.20.227` is the IP of the node the prometheus pod is running on and in the second case `10.230.172.65` is the IP of the prometheus pod.

### To Reproduce

I simply install a simple prometheus deployment (no operator) over a kubernetes cluster that runs with calico and metallb in frr mode.

### Expected Behavior

I expected no issues to be reported by the speaker related to encryption.

### Additional Context

[metallb_report.tgz](https://github.com/metallb/metallb/files/12407834/metallb_report.tgz)

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Sorry for the delay. @lethargosapatheia are you still experiencing the issue? And, do you confirm this is happening only AFTER you deploy prometheus? And and, mind providing the exact manifests you are using?
The only thing that comes to my mind is some port conflict.

**Comment by abasitt** [comment]
I noticed the same error in one of the cluster.
{"caller":"net.go:268","component":"Memberlist","level":"error","msg":"memberlist: failed to receive: Encryption is configured but remote state is not encrypted from=[fd74:ca9b:3a09:868c:10:9:63:105]:29314","ts":"2024-03-04T04:18:33Z"}

but with a very strange behavior.
If i am running a kube-prometheus stack, there is no such error.

but in that specific cluster I had a prometheus pod from istio-addons version 1.15.2 I am able to see this issue.
https://raw.githubusercontent.com/istio/istio/1.15.2/samples/addons/prometheus.yaml

but I am not able to see any such error even with Istio addon from 1.19.7 e.g. if i apply the below, the error will disappear.
https://raw.githubusercontent.com/istio/istio/1.19.7/samples/addons/prometheus.yaml

I am suspecting this issue may be related to specific Prometheus versions.

**Comment by fedepaol** [comment]
@abasitt the only thing that I can think of, is a clash of the ports used for memberlist. Can you check that?

**Comment by abasitt** [comment]
I have two nodes cluster and I had prometheus running without any such error. Just reinstalled older version of prometheus and I start seeing logs again.
I hope below is what you are asking ? I can see the same on both nodes. 
```
sudo lsof -nP -i:7946
COMMAND     PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
speaker 3834652 root    8u  IPv6 281748775      0t0  TCP [fd74:ca9b:3a09:868c:10:9:65:1]:7946 (LISTEN)
speaker 3834652 root    9u  IPv6 281748779      0t0  UDP [fd74:ca9b:3a09:868c:10:9:65:1]:7946 
```
Let me know if you need more details. Thank youl

**Comment by fedepaol** [comment]
yep (and sorry for the dealay), it doesn't seem the case as the speakers are the only components listening to that port :/

**Comment by fedepaol** [comment]
@abasitt can I ask you to verify on a kind cluster if this happens? If so I'll have a way to debug locally

**Comment by kyrofa** [comment]
I'm seeing this as well, using k3s and grafana agent (still prometheus, basically).

**Comment by fedepaol** [comment]
definetely worth investigating

**Comment by fedepaol** [comment]
Closing this as there were no followups and I wasn't able to reproduce. If it's still happening please reopen and we can move forward.

**Comment by dennis-xd** [comment]
Im facing the same issue

**Comment by fedepaol** [comment]
@dennis-xd mind expanding?
