### ISSUE TITLE
metallb ip address is not accessible when trying to connect from host machine, how to fix that?

### ISSUE THREAD

**Issue by uday1kiran** [metallb/metallb#2065]
### MetalLB Version

0.13.9

### Deployment method

Manifests

### Main CNI

calico

### Kubernetes Version

1.26.3

### Cluster Distribution

k3s

### Describe the bug

I have installed k3s on ubuntu 23 machine, which is installed on virtualbox and with bridged network set.

My windows 10 host machine ip address

```
    Wireless LAN adapter Wi-Fi:
    
       Connection-specific DNS Suffix  . :
       IPv6 Address. . . . . . . . . . . : 2409:40f0:1128:8664:eb06:34c7:ed1e:fab9
       Temporary IPv6 Address. . . . . . : 2409:40f0:1128:8664:346c:9b30:a91f:3e6b
       Link-local IPv6 Address . . . . . : fe80::568c:271a:f169:7312%19
       IPv4 Address. . . . . . . . . . . : 192.168.165.117
       Subnet Mask . . . . . . . . . . . : 255.255.255.0
       Default Gateway . . . . . . . . . : fe80::44a7:67ff:fe01:cd76%19
                                           192.168.165.115
```

My IPaddress on virtualbox ubuntu 23 machine. --> 192.168.165.230

So I installed metallb on that k3s cluster by follwing below steps.

    `kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.11/config/manifests/metallb-native.yaml`

And the ipaddress pool added.

    ```
apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: first-pool
      namespace: metallb-system
    spec:
      addresses:
      #- 192.168.165.0/24
      - 192.168.165.240-192.168.165.250

```

below ipaddresses allocated to nginx services.

  ```
  NAMESPACE        NAME              TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)                  AGE
    default          kubernetes        ClusterIP      10.43.0.1       <none>            443/TCP                  7h33m
    kube-system      kube-dns          ClusterIP      10.43.0.10      <none>            53/UDP,53/TCP,9153/TCP   7h33m
    kube-system      metrics-server    ClusterIP      10.43.150.25    <none>            443/TCP                  7h33m
    metallb-system   webhook-service   ClusterIP      10.43.121.158   <none>            443/TCP                  24m
    testing          nginx             LoadBalancer   10.43.172.206   192.168.165.240   80:31210/TCP             168m
    default          nginx             LoadBalancer   10.43.249.109   192.168.165.241   80:31548/TCP             29s
```

On the virtualbox ubuntu machine, I can access in firefox http://192.168.165.240 and http://192.168.165.241

But can't access them from my host machine.

How to fix that?

### To Reproduce

So I installed metallb on that k3s cluster by follwing below steps.

kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.11/config/manifests/metallb-native.yaml
And the ipaddress pool added.

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  #- 192.168.165.0/24
  - 192.168.165.240-192.168.165.250
```
below ipaddresses allocated to nginx services.

```
NAMESPACE        NAME              TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)                  AGE
default          kubernetes        ClusterIP      10.43.0.1       <none>            443/TCP                  7h33m
kube-system      kube-dns          ClusterIP      10.43.0.10      <none>            53/UDP,53/TCP,9153/TCP   7h33m
kube-system      metrics-server    ClusterIP      10.43.150.25    <none>            443/TCP                  7h33m
metallb-system   webhook-service   ClusterIP      10.43.121.158   <none>            443/TCP                  24m
testing          nginx             LoadBalancer   10.43.172.206   192.168.165.240   80:31210/TCP             168m
default          nginx             LoadBalancer   10.43.249.109   192.168.165.241   80:31548/TCP             29s
```

### Expected Behavior

Should be accessible from host machine.

On the virtualbox ubuntu machine, I can access in firefox http://192.168.165.240/ and http://192.168.165.241/

But can't access them from my host machine.

### Additional Context

none

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Did you create the L2 advertisement?
Did you read / follow the troubleshooting guide?

**Comment by uday1kiran** [comment]
yes already created, sorry I missed to share that above.

`apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool`

**Comment by fedepaol** [comment]
Hi @uday1kiran , sorry for the delay. IS this still an issue? Did you try to follow the troubleshooting guide? What is the outcome?

**Comment by fedepaol** [comment]
closing as no further info provided, feel free to reopen if this is still an issue and you can provide the extra info required
