### ISSUE TITLE
Let the user know if their LoadBalancer request cannot be satisfied

### ISSUE THREAD

**Issue by phoracek** [metallb/metallb#2079]
### Is your feature request related to a problem?

If the IP pool is depleted, any request for a new LoadBalancer Service will remain untouched. The status would be empty and the user left confused as to why is no IP assigned to their Service.

### Describe the solution you'd like

An event or a custom condition should be added to the Service, explaining to the user why their request cannot be satisfied and what they should do to resolve it.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
Make sense, we add an event when the ip is assigned, I guess we can do something similar (or play with the status) if no ip is available

**Comment by rafiramadhana** [comment]
hi @fedepaol im interested to work on this issue

would you mind to give me some pointers to get started? (e.g. related files, similar implementations, or else)

thanks

**Comment by fedepaol** [comment]
Hey @rafiramadhana ! Thanks for stepping in
So, I'd go for the event route. The controller (the piece in charge of allocations) has this client thing that throws events https://github.com/metallb/metallb/blob/1a49c3045237a3934bb4510c0a21961c841400f1/controller/main.go#L44

This https://github.com/metallb/metallb/blob/1a49c3045237a3934bb4510c0a21961c841400f1/controller/service.go#L143 is when we throw the allocated event for example.
I accepted this under the assumption that we don't have an event if the controller was not able to find a valid ip for the service, but maybe the event is already raised, looking at https://github.com/metallb/metallb/blob/1a49c3045237a3934bb4510c0a21961c841400f1/controller/service.go#L148

So first thing to check is that is the case (and maybe just change the error message). @phoracek can you confirm you see no events related to the not available pools?

Another thing I'd ask is to add an e2e test under https://github.com/metallb/metallb/blob/0c24d4c79c99eba84da5e1feab0ecef6d1685e1a/e2etest/l2tests/assignment.go#L36

**Comment by fedepaol** [comment]
Also, @rafiramadhana feel free to chime in the #metallb-dev slack channel on the kubernetes workspace if you need help

**Comment by AlinaSecret** [comment]
Hi @fedepaol, would love to work on this issue!

**Comment by fedepaol** [comment]
sure thing, assigning this to you

**Comment by AlinaSecret** [comment]
I started to look into this issue, and started from checking if there aren't any events in cases when the ip cant be allocated. i created an address pool containing only 2 address and created 3 services. 
And as @fedepaol  pointed out there is an event, as you can see in the following screenshot (the screenshot is from my tests where the event has been raised):

![Screenshot from 2023-10-15 15-37-42](https://github.com/metallb/metallb/assets/22447856/dad42531-a196-4c4d-9e1a-865fb46a4025)

 the event will be created on line 144 as seen here

https://github.com/metallb/metallb/blob/c6c733dd08c9d7ec1325d66d4da5d042fb6b3fc8/controller/service.go#L144

It looks good to me,  is there anything to add?
Did i understand the use case\scenario correctly?  

@fedepaol i saw in your comment  you pointed out a different line containing  the  event creation. if i understand correctly the event you mentioned is an internal error, are there any cases it can be created that are not bugs?

**Comment by fedepaol** [comment]
> @fedepaol i saw in your comment you pointed out a different line containing the event creation. if i understand correctly the event you mentioned is an internal error, are there any cases it can be created that are not bugs?

nope, I think we are good here, probably the reporter did not notice the events. I am going to close this, @phoracek feel free to reopen / chime in on slack if this is not enough.
