### ISSUE TITLE
Make BGP connect retry time configurable

### ISSUE THREAD

**Issue by gkleen** [metallb/metallb#2093]
### Is your feature request related to a problem?

With the current configuration options, I can't express that I would like FRR running under control of metallb to (re-)try connecting to my upstream bgp peer more frequently than every 120 seconds.

### Describe the solution you'd like

I would like another field under `spec` for `BGPPeer`: `connectTime` that get's translated into the correct setting in `frr.conf`.

### Additional context

See [an issue relevant to connect time in frr](https://github.com/FRRouting/frr/issues/4745).

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
I guess this is doable. The use case is, the router is detected quickly when it goes down but it takes longer to reconnect, right?

**Comment by gkleen** [comment]
Yes, when the TCP connection to the router (another service on the same system, in my case) breaks the client backs off for 2 minutes before retrying.  
When the cause is just the router being restarted (which takes seconds in my case) that's quite long. 

P.S.: Sorry for the late response – apparently had some imap issues that went unnoticed.

**Comment by kwakubiney** [comment]
I can pick this up

**Comment by AlinaSecret** [comment]
Hey @fedepaol if its OK with you, I would like to work on this issue :)

**Comment by fedepaol** [comment]
Sure! Assigning this to you
