### ISSUE TITLE
i installed metalb,and uninstalled it for a while using helm, but I found that my azure load balancer cannot allocate ip to my load balancer type service.how can I resolve it

### ISSUE THREAD

**Issue by mingmingshiliyu** [metallb/metallb#2096]
### MetalLB Version

latest

### Deployment method

Charts

### Main CNI

calico

### Describe the bug

i installed metalb,and uninstalled it for a while using helm, but I found that my azure load balancer cannot allocate ip to my load balancer type service.how can I resolve it. externalp is always pending 

### To Reproduce

install and uninstall in azure aks

### Expected Behavior

to be normal

### Additional Context

none

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by mingmingshiliyu** [comment]
emergency!

**Comment by fedepaol** [comment]
please follow the troubleshooting guide and provide the info requested above.

**Comment by fedepaol** [comment]
Closing, feel free to reopen if you follow the guide and find this to be an issue
