### ISSUE TITLE
Update "Usage" documentation to fix outdated reference to Kubernetes limitation

### ISSUE THREAD

**Issue by clee** [metallb/metallb#2100]
### Is your feature request related to a problem?

> There are two main reasons to colocate services in this fashion: **to work around a Kubernetes limitation**, and to work with limited IP addresses.

When the "Usage" page was written, I'm sure this was true, but since kubernetes v1.24, this is apparently no longer the case. You can now have a LoadBalancer Service with both UDP and TCP ports and you don't need to do the two-services-with-shared-IP workaround anymore.

### Describe the solution you'd like

Update the "Usage" page to no longer mention "working around a Kubernetes limitation" since v1.24 came out nearly a year and a half ago.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
Hi, thanks for raising this! Keen filing a pr to fix the docs? They live under `https://github.com/metallb/metallb/tree/main/website/content` 

if not, we'll fix this!
