### ISSUE TITLE
Make MP BGP configurable

### ISSUE THREAD

**Issue by ljy-qax** [metallb/metallb#2106]
I recently encountered a similar issue.  I hope for more flexibility in configuring the address family for neighbors.

May I inquire if there have been any recent developments regarding issue #1757?

> So far, we are using 0.12 version, I tested 0.13.7, however, it does not work as our BGP routers are split so that IPv4 handles IPv4 only connections and the same for IPv6, and MP sessions are rejected.
It would be good to make MP BGP configurable.
_Originally posted by @xhejtman in https://github.com/metallb/metallb/issues/1736#issuecomment-1357304394_

**Comment by fedepaol** [comment]
nope, but I'd be happy to review if somebody is willing to work on it

**Comment by AlinaSecret** [comment]
I would like to work on this one :)

**Comment by fedepaol** [comment]
assigned!
