### ISSUE TITLE
Avoid warning "v1beta1 AddressPool is deprecated, consider using IPAddressPool"

### ISSUE THREAD

**Issue by guettli** [metallb/metallb#2108]
### Is your feature request related to a problem?

I installed metallb via 

```
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.11/config/manifests/metallb-native.yaml
```

Like explained [in the docs](https://metallb.universe.tf/installation/)

Now I get this error:

> W1009 12:26:45.642117  247766 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool

If I use client-go based applications.

Example:

```
❯ go run github.com/guettli/check-conditions@latest all
W1009 12:29:04.624527  252737 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
Checked 368 conditions of 641 resources of 94 types. Duration: 392.25309ms
```

### Describe the solution you'd like

I would like to see no warning.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
That warning can be safely ignored. It's returned by the apiserver because we are deprecating that API (but we did not do it yet), so every access returns that error (including the watches being set by metallb's controllers).
We could un-deprecate it but I don't think it'd make sense

**Comment by fedepaol** [comment]
closing as non issue
