### ISSUE TITLE
service external-ip is not reachable from external network

### ISSUE THREAD

**Issue by vr2388** [metallb/metallb#2109]
### MetalLB Version

4.4.2

### Deployment method

Charts

### Main CNI

flannel

### Kubernetes Version

1.25 +

### Cluster Distribution

k3s

### Describe the bug

I am using metallb for loadbalancing my app. I have deployed ip-addresspool for assigning ip as follows

> apiVersion: metallb.io/v1beta1
> kind: IPAddressPool
> metadata:
>   annotations:
>     meta.helm.sh/release-name: ipaddresspool
>     meta.helm.sh/release-namespace: kube-system
>   creationTimestamp: "2023-10-10T06:36:08Z"
>   generation: 1
>   labels:
>     app.kubernetes.io/managed-by: Helm
>   name: first-pool
>   namespace: kube-system
>   resourceVersion: "940"
>   uid: d8e0847e-f044-4275-bb92-942ca17d21a4
> spec:
>   addresses:
>   - 192.25.26.12-192.25.26.17
>   autoAssign: true
>   avoidBuggyIPs: false

Ip is getting assigned to service and is is reachable from same node but it is not accessible from external network(different vm)

> NAME                       TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)          AGE
> dell-powermax-entrypoint   LoadBalancer   10.43.235.15   192.25.26.12   7073:31329/TCP   4m21s
> kubernetes                 ClusterIP      10.43.0.1      <none>         443/TCP          8m18s

> telnet 192.25.26.12 7073
> Trying 192.25.26.12...
> telnet: Unable to connect to remote host: No route to host

**NOTE:   When i use my vm ip-address as loadbalancing ip then it is working as expected.**

### To Reproduce

Deploy Metallb helm chart (version 4.4.2) and deploy ipaddresspool yaml file. 
deploy any deployment with service
Check whether ip got assigned to that service and try to access it from external network

### Expected Behavior

Service external-ip should connect from external network

### Additional Context

Service external-ip should connect from external network

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Please follow the troubleshooting guide and provide what is asked there

**Comment by fedepaol** [comment]
closing as the requested infos were not provided. Feel free to reopen in case you are still experiencing this and you cna provide all the information requested in the troubleshooting guide.
