### ISSUE TITLE
Use distroless images for the speaker and the controller

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#2110]
### Is your feature request related to a problem?

Dupe of https://github.com/metallb/metallb/issues/676 , raising this to make it more evident.
We might want to get the images built from:scratch instead of alpine.

The only pitfall is the speaker container that needs to move binaries around, to fill the frr-metrics or the reloader containers.

### Describe the solution you'd like

Distroless containers for the speaker and the controller.

Also, the troubleshooting doc updated to understand how to ssh into those containers using ephemeral containers.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
That'd be great @georgettica !

**Comment by fedepaol** [comment]
Assigned this to you, let us know if you need any help!

**Comment by minmzzhang** [comment]
Hello Ori, I would like to work on this issue to get some upstream experience. :)

**Comment by fedepaol** [comment]
@minmzzhang assigning this to you

**Comment by fedepaol** [comment]
Feel free to chime in on the #metallb-dev slack channel if you have any questions
