### ISSUE TITLE
Remove colon (:) from names of kubernetes manifests produced by helm chart

### ISSUE THREAD

**Issue by tporeba** [metallb/metallb#2114]
### Is your feature request related to a problem?

I've used the metallb helm chart and some manifests produced include colon `:` in object names and filenames:
```
ClusterRoleBinding_metallb:controller.yaml
ClusterRoleBinding_metallb:speaker.yaml
ClusterRole_metallb:controller.yaml
ClusterRole_metallb:speaker.yaml
```

If those manifests files are stored in source code repository then they cause trouble for windows users, who try to check them out - on windows colon is not allowed in filenames. 

### Describe the solution you'd like

Would it be much trouble to replace those colon in names with underscore `_` or dash `-` ? 
Probably dash would be best as it would be also more consistent with other objects - for example there is a `RoleBinding_metallb-controller.yaml` and `RoleBinding_metallb-pod-lister.yaml`. 

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
hi! sorry for the ignorance, how do you use the chart to produce the files?

**Comment by tporeba** [comment]
I use helm to generate manifests and I dump them to files in the form of `<kind>_<name>.yaml` for further use in [GitOps ](https://en.wikipedia.org/wiki/DevOps#GitOps) approach.

**Comment by tporeba** [comment]
The problem was on my side, closing.
