### ISSUE TITLE
persist node allacated to some service, maybe by annotaion?

### ISSUE THREAD

**Issue by lwabish** [metallb/metallb#2125]
### Is your feature request related to a problem?

My team is currently using MetalLB's Layer2 mode in a small cluster scenario. The cluster only has three nodes, with no other machines available to act as clients, and the speaker logs are not persistent. 

If everything is working as expected, we don't necessarily need to know which speaker is responsible for sending ARP for a particular service. However, when communication issues arise with a service, or when we need to debug MetalLB, knowing which speaker is involved becomes a necessary prerequisite. 

Currently, aside from the event at the service creation and the speaker pod logs, there are no other convenient, persistent methods to quickly obtain the mapping relationship between the service and the speaker. Could we consider adding such a method, for example, using Kubernetes annotations?

### Describe the solution you'd like

Maybe annotate the service with mapping relationship info along with the creation of the event?
https://github.com/metallb/metallb/blob/ac85098b2d52994d57769bd6115d393e43044041/speaker/main.go#L375

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by oribon** [comment]
thanks for opening this! this will be solved as part of https://github.com/metallb/metallb/issues/2158, closing as a dupe for now.

**Comment by lwabish** [comment]
Good to hear that! By the way , After reading the design related to #2158, I feel like participating the implementation.Is there anything I can contribute to?

**Comment by oribon** [comment]
sure, we can assign it to you if you want to work on it (and help along the way)

**Comment by lwabish** [comment]
Ok,please assign #2158 to me and I'll start to work on it.

**Comment by oribon** [comment]
sure, I need you to comment on that issue otherwise it doesn't let me :smile:

**Comment by fedepaol** [comment]
@lwabish please comment on the issue https://github.com/metallb/metallb/issues/2158 or gh won't allows add to assign it :man_shrugging:

**Comment by lwabish** [comment]
@fedepaol Ok, Done.
