### ISSUE TITLE
How does a LB assign ip addresses to namespaces ?

### ISSUE THREAD

**Issue by MalikaML** [metallb/metallb#2126]
### Is your feature request related to a problem?

Hey everyone, I need your help in this. for the context: Various users have access to my Kubernetes cluster, but their access is limited to specific namespace(s); these are the main points to make my issue clearer.

### Describe the solution you'd like

- When an administrator creates a namespace, they statically assign an IPv4 address to that namespace. As a result, the user cannot modify this IP address or choose an IP address belonging to another namespace. If the user attempts to do so, we want Kubernetes to block this attempt and not grant them that permission.

- The administrator manually configures an IPv4 address for a namespace using a MetalLB configuration file. In the case where multiple pods are deployed, an input/output port is assigned to each pod.

### Additional context

Thank you in advance for your help 

@fedepaol can you please check my issue ? thank you 

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
Sorry, I am not sure I understood what the issue is.
The IPs are shared across namespaces unless you use the namespace selector in the ipaddresspool crd. https://metallb.universe.tf/configuration/_advanced_ipaddresspool_configuration/#reduce-scope-of-address-allocation-to-specific-namespace-and-service

**Comment by MalikaML** [comment]
Thank you for your response, I've checked your link and it makes sense to me but it doesn't seem to work, I want to clarify my issue more to make sure we're on the same page

I reformulate: I want to ensure that when a LB service is created in a particular namespace within the cluster, it can only receive an IP address from a specific IP address range or pool associated with that namespace. So how can I define an IP address range for a namespace ? 

thank you
