### ISSUE TITLE
Migrate to crd-ref-docs for the api docs generation

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#2138]
### Is your feature request related to a problem?

https://github.com/ahmetb/gen-crd-api-reference-docs is not maintained anymore, we should switch to use
https://github.com/elastic/crd-ref-docs

### Describe the solution you'd like

https://github.com/ahmetb/gen-crd-api-reference-docs is not maintained anymore, we should switch to use
https://github.com/elastic/crd-ref-docs

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by michaelasp** [comment]
I can take on this change. @fedepaol could you assign to me?

**Comment by fedepaol** [comment]
Sure thing, and thanks!
