### ISSUE TITLE
Version 0.13.12 is not compatible with Kubernetes 1.26

### ISSUE THREAD

**Issue by zigmund** [metallb/metallb#2145]
### MetalLB Version

0.13.12

### Deployment method

Manifests

### Main CNI

flannel

### Kubernetes Version

v1.26.4

### Cluster Distribution

vanilla

### Describe the bug

On the way to upgrade existing Metallb installations. Tried to run latest 0.13.12 on Kubernetes 1.26.4, but got controller crash loop.

In version 0.13.12 [Kubernetes deps were updated to 1.28](https://github.com/metallb/metallb/commit/e92344701bd52703aec9c6eaa6d56977a9793b33) and now controller unable to start on Kubernetes 1.26 with error:
```
{"level":"error","ts":"2023-10-30T03:31:45Z","logger":"setup","msg":"unable to start manager","error":"failed to determine if *v1beta2.BGPPeer is namespaced: failed to get restmapping: failed to get server groups: the server has asked for the client to provide credentials","stacktrace":"go.universe.tf/metallb/internal/k8s.New\n\t/go/go.universe.tf/metallb/internal/k8s/k8s.go:153\nmain.main\n\t/go/go.universe.tf/metallb/main.go:209\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

Downgraded to 0.13.11 and it works just fine.

### To Reproduce

1. Install metallb 0.13.12 on Kubernetes 1.26.
2. Observe controller container restarts with logs provided.

### Expected Behavior

Metallb controller works on Kubernetes 1.26.

### Additional Context

None

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by oribon** [comment]
hi, I tried reproducing this multiple times on kind using v1.26.4 with no success, can you explain a bit more what steps are you taking and if you can reproduce it constantly?

**Comment by fedepaol** [comment]
Closing as no feedback was provided. Feel free to reopen in case you can provide the requested information!
