### ISSUE TITLE
CRD Status: Implement L2 Service Status

### ISSUE THREAD

**Issue by oribon** [metallb/metallb#2158]
### Is your feature request related to a problem?

https://github.com/metallb/metallb/blob/main/design/crd-status.md

### Describe the solution you'd like

As described in https://github.com/metallb/metallb/blob/main/design/crd-status.md#service-announcement---l2 we want to implement the `ServiceL2Status` resource

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by lwabish** [comment]
I'd love to implement this

**Comment by oribon** [comment]
thanks! assigned, let us know if you need any help in #metallb-dev or here

**Comment by lwabish** [comment]
The very first problem I met is: 
```
❯ kubebuilder create api --version v1beta1 --kind ServiceL2Status --group metallb.io
Error: failed to create API: unable to load configuration file: 
unable to load the configuration: 
unable to read "PROJECT" file: open PROJECT: no such file or directory
```
On the other hand, it seems not possible to init a kubebuilder project based on a non empty folder.
```
❯ kubebuilder init --domain metallb.io
Error: failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v4": 
target directory is not empty (only go.mod, go.sum, files and directories with the prefix ".", 
files with the suffix ".md" or capitalized files name are allowed); found existing file "api"
```
So now there seems no way to generate the xxx_type.go ? I wonder how was the xxx_types.go written before?

**Comment by fedepaol** [comment]
> The very first problem I met is:
> 
> ```
> ❯ kubebuilder create api --version v1beta1 --kind ServiceL2Status --group metallb.io
> Error: failed to create API: unable to load configuration file: 
> unable to load the configuration: 
> unable to read "PROJECT" file: open PROJECT: no such file or directory
> ```
> 
> On the other hand, it seems not possible to init a kubebuilder project based on a non empty folder.
> 
> ```
> ❯ kubebuilder init --domain metallb.io
> Error: failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v4": 
> target directory is not empty (only go.mod, go.sum, files and directories with the prefix ".", 
> files with the suffix ".md" or capitalized files name are allowed); found existing file "api"
> ```
> 
> So now there seems no way to generate the xxx_type.go ? I wonder how was the xxx_types.go written before?

I honestly don't remember how it was done (and I did it). The thing is, metallb is kind of a frankenstein that started before kubebuilder (or controller runtime) was a thing. Lately, we introduced CRDs and the controller-runtime based controllers in place of the existing configmap.

If I were you, I'd just copy one existing file and adjust it, doesn't seem a big deal.

**Comment by fedepaol** [comment]
@lwabish did you manage to sort it out?

**Comment by lwabish** [comment]
> @lwabish did you manage to sort it out?

I think so. I have finished coding and start working on testing them.
