### ISSUE TITLE
looping "end reconcile" and ARP requests für LB-IP looping

### ISSUE THREAD

**Issue by DirkDatzert** [metallb/metallb#2177]
### MetalLB Version

0.13.12

### Deployment method

Charts

### Main CNI

flannel

### Kubernetes Version

1.27.7+k3s2

### Cluster Distribution

k3s

### Describe the bug

We add an external ip for coredns via yaml and after that I see ARP request on the Interface and looping logs like this:

{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/ext-dns-udp","level":"info","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/ext-dns-udp","ts":"2023-11-21T12:55:20Z"}
{"caller":"main.go:374","event":"serviceAnnounced","ips":["10.9.70.1"],"level":"info","msg":"service has IP, announcing","pool":"reserved-for-coredns","protocol":"layer2","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/ext-dns-udp","level":"info","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/ext-dns-udp","ts":"2023-11-21T12:55:20Z"}
{"caller":"main.go:374","event":"serviceAnnounced","ips":["10.9.70.1"],"level":"info","msg":"service has IP, announcing","pool":"reserved-for-coredns","protocol":"layer2","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/ext-dns-udp","level":"info","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/ext-dns-udp","ts":"2023-11-21T12:55:20Z"}
{"caller":"main.go:374","event":"serviceAnnounced","ips":["10.9.70.1"],"level":"info","msg":"service has IP, announcing","pool":"reserved-for-coredns","protocol":"layer2","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/ext-dns-udp","level":"info","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/ext-dns-udp","ts":"2023-11-21T12:55:20Z"}
{"caller":"main.go:374","event":"serviceAnnounced","ips":["10.9.70.1"],"level":"info","msg":"service has IP, announcing","pool":"reserved-for-coredns","protocol":"layer2","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/ext-dns-udp","level":"info","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/ext-dns-udp","ts":"2023-11-21T12:55:20Z"}
{"caller":"main.go:374","event":"serviceAnnounced","ips":["10.9.70.1"],"level":"info","msg":"service has IP, announcing","pool":"reserved-for-coredns","protocol":"layer2","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/ext-dns-udp","level":"info","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/ext-dns-udp","ts":"2023-11-21T12:55:20Z"}
{"caller":"main.go:374","event":"serviceAnnounced","ips":["10.9.70.1"],"level":"info","msg":"service has IP, announcing","pool":"reserved-for-coredns","protocol":"layer2","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/ext-dns-udp","level":"info","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/ext-dns-udp","ts":"2023-11-21T12:55:20Z"}
{"caller":"main.go:374","event":"serviceAnnounced","ips":["10.9.70.1"],"level":"info","msg":"service has IP, announcing","pool":"reserved-for-coredns","protocol":"layer2","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/ext-dns-udp","level":"info","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/ext-dns-udp","ts":"2023-11-21T12:55:20Z"}
{"caller":"main.go:374","event":"serviceAnnounced","ips":["10.9.70.1"],"level":"info","msg":"service has IP, announcing","pool":"reserved-for-coredns","protocol":"layer2","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/ext-dns-udp","level":"info","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/ext-dns-udp","ts":"2023-11-21T12:55:20Z"}
{"caller":"main.go:374","event":"serviceAnnounced","ips":["10.9.70.1"],"level":"info","msg":"service has IP, announcing","pool":"reserved-for-coredns","protocol":"layer2","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/ext-dns-udp","level":"info","ts":"2023-11-21T12:55:20Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/ext-dns-udp","ts":"2023-11-21T12:55:20Z"}
{"caller":"main.go:374","event":"serviceAnnounced","ips":["10.9.70.1"],"level":"info","msg":"service has IP, announcing","pool":"reserved-for-coredns","protocol":"layer2","ts":"2023-11-21T12:55:20Z"}

### To Reproduce

1. install an k3s 1.27.7 without service-lb
2.  deploy metallb

cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- metallb-config.yaml
- pooled-ips.yaml
- l2-advertisement.yaml

 cat metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: reserved-for-coredns
spec:
  addresses:
  - 10.9.70.1/32

cat pooled-ips.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: pooled-ips
spec:
  addresses:
  - 10.9.70.32-10.9.70.255

 cat l2-advertisement.yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: l2-advertisment
spec:
  ipAddressPools:
  - pooled-ips
  - reserved-for-coredns

3. modify coredns service

 cat tmp.yaml
apiVersion: v1
kind: Service
metadata:
  name: ext-dns-udp
  namespace: kube-system
spec:
  type: LoadBalancer
  loadBalancerIP: 10.9.70.1
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
  selector:
    k8s-app: kube-dns

### Expected Behavior

limited count of layer2 announcement for ip 10.9.70.1

### Additional Context

This was not detected a log time after an upgrade to 0.13.x and our Core-Router team only saw high cpu during  massive GARP announcements loop for 1000 ARPs per seconde. This bug report comes after we saw that metallb was the issue for our Core router problem and some investigation into to metallb speakerlogs.

We can instantly stop the ARP looping by deleting the external service for coredns.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Do you mind raising the logs to debug and sharing the speaker logs? There
must be something that is causing the service to change continuously
(maybe another loadbalancer fighting with metallb or a pod that is bouncing
up and down).

Thanks!

**Comment by DirkDatzert** [comment]
[metallb_report.tar.gz](https://github.com/metallb/metallb/files/13427348/metallb_report.tar.gz)

debugging and collected logs

**Comment by oribon** [comment]
Thanks for sending those, do you have kube-vip running in that cluster as well? I see a `kube-vip.io/vipHost` annotation on the service.
it appears the controller constantly updates the service as it detects a change in its status, specifically it bounces between (the controller's desired status is the first):
```
\"status\":{\"loadBalancer\":{\"ingress\":[{\"ip\":\"10.9.70.1\"}]}}}
```
and
```
\"status\":{\"loadBalancer\":{\"ingress\":[{\"ip\":\"10.9.70.1\",\"ports\":[{\"port\":53,\"protocol\":\"UDP\"}]}]}}}"
```
which probably causes what you're seeing

**Comment by DirkDatzert** [comment]
yes, kube-vip is running, but the vip ip should different 10.9.250.80

**Comment by oribon** [comment]
not sure I understand, wdym the vip ip should be different? why do you need metallb and kube-vip running alongside eachother?

**Comment by DirkDatzert** [comment]
I will deactivate kube-vip and test again

**Comment by DirkDatzert** [comment]
After deactivating kube-vip the arp requests stops after 5 counts.

**Comment by fedepaol** [comment]
you can't have two loadbalancer implementations running on the same cluster, or you can but you need to leverage the https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class to specify which loadbalancer you want to handle your service.
Otherwise they will fight for the service and each one will apply it's configuration.

**Comment by DirkDatzert** [comment]
Thanks for pointing to that page. I did a search on kube-vip docs and found that I generated kube-vip not only for the controlplane (as I wanted it) also for services, where I setup metallb for.

**Comment by DirkDatzert** [comment]
metallb servicing is acting stable after disable kube-vip --services

**Comment by fedepaol** [comment]
Awesome!
