### ISSUE TITLE
add label to nodes based on the advertised IP addresses

### ISSUE THREAD

**Issue by ftsell** [metallb/metallb#2179]
### Is your feature request related to a problem?

I would like to access the real source IP addresses when clients connect to services running on my cluster.

### Describe the solution you'd like

I'm generally envisioning the following:
- I set the `externalTrafficPolicy` of my load-balanced service to `local` so that kube-proxy does not rewrite the source ip address
- MetalLB adds a label to the node that advertises that IP address
- The pods which back that service have scheduling constraints set so that they are automatically scheduled to that node and can be reached even though the `externalTrafficPolicy` is `local`

### Additional context

I know there are other solutions to this problem, e.g. using a network backend configuration that does not mangle the original source IP but unfortunately I can't change that.

For context, I'm using calico as my network backend without direct server return and without the eBPF dataplane (see [their docs](https://docs.tigera.io/calico/latest/about/kubernetes-training/about-kubernetes-services) for details.

I'm also using MetalLB in Layer2 advertising mode.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
Sorry but I am not sure I got the what you are trying to achieve.

The current behaviour works fine with etp=local, and it's the other way around from what you describe.
When etp=local, metallb will always choose the node to announce the service from among those where an endpoint is running. You don't have to schedule it using a label.

Based on the above considerations I am closing the issue, feel free to reopen if I did not undestand properly.

**Comment by ftsell** [comment]
> metallb will always choose the node to announce the service from among those where an endpoint is running

That information does solve it for me thanks.

My misunderstanding was that I didn't know that metallb takes into considerations which nodes have a pod running that backs the service. If that's the case then you're right and I indeed don't need such a label.

**Comment by fedepaol** [comment]
> > metallb will always choose the node to announce the service from among those where an endpoint is running
> 
> That information does solve it for me thanks.
> 
> My misunderstanding was that I didn't know that metallb takes into considerations which nodes have a pod running that backs the service. If that's the case then you're right and I indeed don't need such a label.

Awesome! Thanks for opening the issue and contributing to the project anyway!
