### ISSUE TITLE
metallb.io v1beta1 AddressPool is deprecated, Certificate Rotation Issues, Webhook Issues

### ISSUE THREAD

**Issue by LDamjanov** [metallb/metallb#2206]
### MetalLB Version

0.13.12

### Deployment method

Manifests

### Main CNI

None

### Kubernetes Version

1.31.2

### Cluster Distribution

Minikube

### Describe the bug

MetalLB assigns an IP Address to a Nginx Ingress Controller but the site cannot be reached.
I've followed the exact guide as said on the website as well as a couple youtube videos and nothing else makes sense to me other than this being a bug.

I installed MetalLB using Manifests and the installation went without issue. I have a nginx ingress running in a minikube cluster and was hoping to use MetalLB to give it an external ip since minikube isnt a real cloud provider.

This worked, metallb gave the ingress controller an external ip but I cannot access it nor ping it.

Running the logs on the metallb controller gave me this:
`kubectl logs -n metallb-system controller-565ccc769f-npn8v
{"branch":"dev","caller":"main.go:156","commit":"dev","goversion":"gc / go1.20.10 / amd64","level":"info","msg":"MetalLB controller starting version 0.13.12 (commit dev, branch dev)","ts":"2023-12-10T21:41:37Z","version":"0.13.12"}
{"action":"setting up cert rotation","caller":"webhook.go:34","level":"info","op":"startup","ts":"2023-12-10T21:41:37Z"}
{"caller":"k8s.go:371","level":"info","msg":"secret successfully created","op":"CreateMlSecret","ts":"2023-12-10T21:41:37Z"}
{"caller":"k8s.go:394","level":"info","msg":"Starting Manager","op":"Run","ts":"2023-12-10T21:41:37Z"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting EventSource","controller":"cert-rotator","source":"kind source: *v1.Secret"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting EventSource","controller":"cert-rotator","source":"kind source: *unstructured.Unstructured"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting EventSource","controller":"cert-rotator","source":"kind source: *unstructured.Unstructured"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting EventSource","controller":"cert-rotator","source":"kind source: *unstructured.Unstructured"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting Controller","controller":"cert-rotator"}
{"level":"info","ts":"2023-12-10T21:41:37Z","logger":"cert-rotation","msg":"starting cert rotator controller"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting EventSource","controller":"service","controllerGroup":"","controllerKind":"Service","source":"kind source: *v1.Service"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting EventSource","controller":"service","controllerGroup":"","controllerKind":"Service","source":"channel source: 0xc0002b4780"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting Controller","controller":"service","controllerGroup":"","controllerKind":"Service"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting EventSource","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool","source":"kind source: *v1beta1.IPAddressPool"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting EventSource","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool","source":"kind source: *v1beta1.AddressPool"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting EventSource","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool","source":"kind source: *v1beta1.Community"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting EventSource","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool","source":"kind source: *v1.Namespace"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting Controller","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool"}
W1210 21:41:37.704789       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 21:41:37.706144       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
{"level":"info","ts":"2023-12-10T21:41:37Z","logger":"cert-rotation","msg":"refreshing CA and server certs"}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting workers","controller":"service","controllerGroup":"","controllerKind":"Service","worker count":1}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting workers","controller":"cert-rotator","worker count":1}
{"level":"info","ts":"2023-12-10T21:41:37Z","msg":"Starting workers","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool","worker count":1}
{"level":"info","ts":"2023-12-10T21:41:37Z","logger":"cert-rotation","msg":"refreshing CA and server certs"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"default/kubernetes","ts":"2023-12-10T21:41:37Z"}
{"caller":"pool_controller.go:48","controller":"PoolReconciler","level":"info","start reconcile":"/default","ts":"2023-12-10T21:41:37Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"default/kubernetes","level":"info","ts":"2023-12-10T21:41:37Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"kube-system/kube-dns","ts":"2023-12-10T21:41:37Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"kube-system/kube-dns","level":"info","ts":"2023-12-10T21:41:37Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"metallb-system/webhook-service","ts":"2023-12-10T21:41:37Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"metallb-system/webhook-service","level":"info","ts":"2023-12-10T21:41:37Z"}
{"caller":"pool_controller.go:106","controller":"PoolReconciler","event":"force service reload","level":"info","ts":"2023-12-10T21:41:37Z"}
{"caller":"pool_controller.go:119","controller":"PoolReconciler","event":"config reloaded","level":"info","ts":"2023-12-10T21:41:37Z"}
{"caller":"pool_controller.go:120","controller":"PoolReconciler","end reconcile":"/default","level":"info","ts":"2023-12-10T21:41:37Z"}
{"caller":"pool_controller.go:48","controller":"PoolReconciler","level":"info","start reconcile":"/kube-node-lease","ts":"2023-12-10T21:41:37Z"}
{"caller":"pool_controller.go:95","controller":"PoolReconciler","end reconcile":"/kube-node-lease","level":"info","ts":"2023-12-10T21:41:37Z"}
{"caller":"pool_controller.go:48","controller":"PoolReconciler","level":"info","start reconcile":"/kube-public","ts":"2023-12-10T21:41:37Z"}
{"caller":"service_controller_reload.go:61","controller":"ServiceReconciler - reprocessAll","level":"info","start reconcile":"metallbreload/reload","ts":"2023-12-10T21:41:37Z"}
{"caller":"pool_controller.go:95","controller":"PoolReconciler","end reconcile":"/kube-public","level":"info","ts":"2023-12-10T21:41:37Z"}
{"caller":"pool_controller.go:48","controller":"PoolReconciler","level":"info","start reconcile":"/kube-system","ts":"2023-12-10T21:41:37Z"}
{"caller":"service_controller_reload.go:104","controller":"ServiceReconciler - reprocessAll","end reconcile":"metallbreload/reload","level":"info","ts":"2023-12-10T21:41:37Z"}
{"caller":"pool_controller.go:95","controller":"PoolReconciler","end reconcile":"/kube-system","level":"info","ts":"2023-12-10T21:41:37Z"}
{"caller":"pool_controller.go:48","controller":"PoolReconciler","level":"info","start reconcile":"/metallb-system","ts":"2023-12-10T21:41:37Z"}
{"caller":"pool_controller.go:95","controller":"PoolReconciler","end reconcile":"/metallb-system","level":"info","ts":"2023-12-10T21:41:37Z"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"server certs refreshed"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"no cert refresh needed"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"Ensuring CA cert","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"}
{"level":"error","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"could not refresh CA and server certs","error":"Operation cannot be fulfilled on secrets \"webhook-server-cert\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/open-policy-agent/cert-controller/pkg/rotator.(*CertRotator).refreshCertIfNeeded.func1\n\t/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.10.0/pkg/rotator/rotator.go:309\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/wait.go:145\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/backoff.go:461\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.(*CertRotator).refreshCertIfNeeded\n\t/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.10.0/pkg/rotator/rotator.go:337\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.(*CertRotator).Start\n\t/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.10.0/pkg/rotator/rotator.go:265\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/manager/runnable_group.go:223"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"Ensuring CA cert","name":"addresspools.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition","name":"addresspools.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"no cert refresh needed"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"Ensuring CA cert","name":"bgppeers.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition","name":"bgppeers.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"no cert refresh needed"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"Ensuring CA cert","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"Ensuring CA cert","name":"addresspools.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition","name":"addresspools.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"Ensuring CA cert","name":"bgppeers.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition","name":"bgppeers.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"no cert refresh needed"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"Ensuring CA cert","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"Ensuring CA cert","name":"addresspools.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition","name":"addresspools.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"}
{"level":"info","ts":"2023-12-10T21:41:38Z","logger":"cert-rotation","msg":"Ensuring CA cert","name":"bgppeers.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition","name":"bgppeers.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"}
W1210 21:41:39.248236       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"cert-rotation","msg":"certs are ready in /tmp/k8s-webhook-server/serving-certs"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"cert-rotation","msg":"CA certs are injected to webhooks"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called","GVK":"metallb.io/v1beta1, Kind=AddressPool"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"metallb.io/v1beta1, Kind=AddressPool","path":"/validate-metallb-io-v1beta1-addresspool"}
{"action":"webhooks enabled","caller":"webhook.go:55","level":"info","op":"startup","ts":"2023-12-10T21:41:39Z"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-metallb-io-v1beta1-addresspool"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.webhook","msg":"Starting webhook server"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/convert"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"Conversion webhook enabled","GVK":"metallb.io/v1beta1, Kind=AddressPool"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called","GVK":"metallb.io/v1beta1, Kind=IPAddressPool"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"metallb.io/v1beta1, Kind=IPAddressPool","path":"/validate-metallb-io-v1beta1-ipaddresspool"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-metallb-io-v1beta1-ipaddresspool"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called","GVK":"metallb.io/v1beta2, Kind=BGPPeer"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"metallb.io/v1beta2, Kind=BGPPeer","path":"/validate-metallb-io-v1beta2-bgppeer"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-metallb-io-v1beta2-bgppeer"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"Conversion webhook enabled","GVK":"metallb.io/v1beta2, Kind=BGPPeer"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called","GVK":"metallb.io/v1beta1, Kind=BGPAdvertisement"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"metallb.io/v1beta1, Kind=BGPAdvertisement","path":"/validate-metallb-io-v1beta1-bgpadvertisement"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-metallb-io-v1beta1-bgpadvertisement"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called","GVK":"metallb.io/v1beta1, Kind=L2Advertisement"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"metallb.io/v1beta1, Kind=L2Advertisement","path":"/validate-metallb-io-v1beta1-l2advertisement"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-metallb-io-v1beta1-l2advertisement"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called","GVK":"metallb.io/v1beta1, Kind=Community"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.webhook","msg":"Serving webhook server","host":"","port":9443}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"metallb.io/v1beta1, Kind=Community","path":"/validate-metallb-io-v1beta1-community"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-metallb-io-v1beta1-community"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called","GVK":"metallb.io/v1beta1, Kind=BFDProfile"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"metallb.io/v1beta1, Kind=BFDProfile","path":"/validate-metallb-io-v1beta1-bfdprofile"}
{"level":"info","ts":"2023-12-10T21:41:39Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-metallb-io-v1beta1-bfdprofile"}
W1210 21:41:40.300313       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 21:41:40.301414       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
{"level":"info","ts":"2023-12-10T21:45:54Z","logger":"KubeAPIWarningLogger","msg":"metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool"}
{"caller":"pool_controller.go:48","controller":"PoolReconciler","level":"info","start reconcile":"metallb-system/first-pool","ts":"2023-12-10T21:45:54Z"}
{"caller":"pool_controller.go:106","controller":"PoolReconciler","event":"force service reload","level":"info","ts":"2023-12-10T21:45:54Z"}
{"caller":"pool_controller.go:119","controller":"PoolReconciler","event":"config reloaded","level":"info","ts":"2023-12-10T21:45:54Z"}
{"caller":"pool_controller.go:120","controller":"PoolReconciler","end reconcile":"metallb-system/first-pool","level":"info","ts":"2023-12-10T21:45:54Z"}
{"caller":"service_controller_reload.go:61","controller":"ServiceReconciler - reprocessAll","level":"info","start reconcile":"metallbreload/reload","ts":"2023-12-10T21:45:54Z"}
{"caller":"service_controller_reload.go:104","controller":"ServiceReconciler - reprocessAll","end reconcile":"metallbreload/reload","level":"info","ts":"2023-12-10T21:45:54Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"default/nginx-ingress-ingress-nginx-controller-admission","ts":"2023-12-10T21:46:35Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"default/nginx-ingress-ingress-nginx-controller-admission","level":"info","ts":"2023-12-10T21:46:35Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"default/nginx-ingress-ingress-nginx-controller","ts":"2023-12-10T21:46:35Z"}
{"caller":"service.go:142","event":"ipAllocated","ip":["192.168.0.200"],"level":"info","msg":"IP address assigned by controller","ts":"2023-12-10T21:46:35Z"}
{"caller":"main.go:107","event":"serviceUpdated","level":"info","msg":"updated service object","ts":"2023-12-10T21:46:35Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"default/nginx-ingress-ingress-nginx-controller","level":"info","ts":"2023-12-10T21:46:35Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"default/nginx-ingress-ingress-nginx-controller","ts":"2023-12-10T21:46:35Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"default/nginx-ingress-ingress-nginx-controller","level":"info","ts":"2023-12-10T21:46:35Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"default/simple-ecommerce-backend","ts":"2023-12-10T21:46:46Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"default/simple-ecommerce-backend","level":"info","ts":"2023-12-10T21:46:46Z"}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"default/simple-ecommerce-frontend","ts":"2023-12-10T21:46:58Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"default/simple-ecommerce-frontend","level":"info","ts":"2023-12-10T21:46:58Z"}
W1210 21:51:26.303782       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 22:00:03.302406       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 22:07:17.302623       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 22:15:11.302999       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 22:20:45.305229       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 22:29:26.305531       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 22:34:53.308067       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 22:42:22.309108       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 22:48:59.310466       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 22:58:05.312114       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 23:06:52.314188       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 23:16:12.312286       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 23:23:47.310653       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 23:32:27.311638       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 23:39:30.313542       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 23:48:23.311279       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1210 23:53:31.311249       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1211 00:01:14.313057       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1211 00:06:41.894336       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1211 00:14:35.891469       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1211 00:23:22.889515       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1211 00:32:30.891895       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1211 00:41:13.892609       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool`

Im pretty sure my configuration files are correct so I do not understand why this issue is happening:
`apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.200-192.168.0.210`

`  apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: second-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool`
  
  
  

### To Reproduce

The service gets created without a problem and the ip assignment works as well. The issue is that the IP assigned does not work.
I've tried disabling my firewall but this did not make a difference.

### Expected Behavior

I expected the external IP given to the ingress controller to work.

### Additional Context

By themselves the rest of my services in the cluster worked so this seems to be an issue on the metallb part.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
If the controller is assigning the ip, then the problem (if any) is in hte speaker. Please check the troubleshooting guide and do what's described in there.

**Comment by fedepaol** [comment]
Closing the issue. Feel free to reopen if it's still happening and you can provided the informations requested in the troubleshooting guide.
