### ISSUE TITLE
controller replicas?

### ISSUE THREAD

**Issue by supermario18b** [metallb/metallb#2216]
### MetalLB Version

0.13.12

### Deployment method

Charts

### Main CNI

calico

### Kubernetes Version

1.28.4

### Cluster Distribution

k3s

### Describe the bug

Hi everyone,
I'm trying to deploy more replicas of the controller.
I've read this [issue](https://github.com/metallb/metallb/issues/725) of 2020. At the time this possibility was removed.
Is it now possible or is metallb still designed to work with only one controller?

Thanks for any clarification,

supermario18b

### To Reproduce

-

### Expected Behavior

get two or more replicas of the controller.

### Additional Context

-

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Things haven't changed. Why are you trying to deploy multiple controllers?
Is there a business reason why you'd need that? The controller should work fine in single instance, and it's designed (especially with the recent changes of maintaining the IPs) to resist to crashes. The services won't loose / change their ip when the controller is down / restarts and the speakers will keep advertising them.

I am closing hte issue as this is not gonna happen, but please provide your rationale.

**Comment by supermario18b** [comment]
@fedepaol thanks for the reply.
I've read this sentence on the site:
`The metallb-system/controller deployment. This is the cluster-wide controller that handles IP address assignments.`

I thought, in case a node goes down and on that node run the controller and some load balancer, then metallb would not be able to notice that the load balancer is down and it wouldn't announce the mac-change via arp.

**Comment by fedepaol** [comment]
> @fedepaol thanks for the reply. I've read this sentence on the site: `The metallb-system/controller deployment. This is the cluster-wide controller that handles IP address assignments.`
> 
> I thought, in case a node goes down and on that node run the controller and some load balancer, then metallb would not be able to notice that the load balancer is down and it wouldn't announce the mac-change via arp.

That part is handled by the speaker, which runs in multiple instances (one per node). So this should not this a problem.
