### ISSUE TITLE
Leader elect when adding multiple replicas to controller

### ISSUE THREAD

**Issue by Fish-pro** [metallb/metallb#2226]
### Is your feature request related to a problem?

In the following issue, it was mentioned that metallb-controller is designed to be a single point, but recently I have encountered the same need. So I would like to ask the community again whether there is a need for multiple replicas of the controller. 

https://github.com/metallb/metallb/issues/725

https://github.com/metallb/metallb/issues/2216

### Describe the solution you'd like

And I have made multiple replicas of the local support, so I would like to ask again, my change is OK, is there a scene I did not consider, thanks

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Fish-pro** [comment]
@fedepaol @russellb Please help evaluate whether this feature is needed. If not, I will close this issue, thanks

**Comment by fedepaol** [comment]
The controller is meant to run in single instance. Having multiple controllers will cause unexpected results. See my reply in https://github.com/metallb/metallb/issues/2216 for more details on why having a single controller is not a problem.

**Comment by fedepaol** [comment]
Closing this issue

**Comment by Fish-pro** [comment]
@fedepaol Thanks for your reply

**Comment by Fish-pro** [comment]
> The controller is meant to run in single instance. Having multiple controllers will cause unexpected results. See my reply in #2216 for more details on why having a single controller is not a problem.

@fedepaol 
 I understand that in issue #2216, the core is the following reply. However, I understand that you mean that after controller restarts, IP allocation can be guaranteed. I understand that this is not the core reason for not supporting multiple copies. I looked at the code, and it looks like this
```go
type controller struct {
	client service
	pools  *config.Pools
	ips    *allocator.Allocator
}
```
The controller structure holds the pool information. Is it because the restart will cause inconsistency in the recorded pool information? If so, will the same problem occur with the current single instance restart? If the leader election is added, the restart guarantee is only increased, and no changes are made in essence, what unexpected problems will be caused?

![image](https://github.com/metallb/metallb/assets/47143494/c71d1aad-207c-4c01-8bd2-356624597833)
