### ISSUE TITLE
ip is not reachable out of the node

### ISSUE THREAD

**Issue by dark4igi** [metallb/metallb#2231]
### MetalLB Version

v0.13.12

### Deployment method

Manifests

### Main CNI

flannel

### Kubernetes Version

v1.29.0

### Cluster Distribution

vanila

### Describe the bug

Hi community

my k8s v1.29.0 cluster deployed on singel raspberry pi 5 node with ubuntu 23.10 (only this available for rpi 5)
metallb deployed latest version (v0.13.12)
IPAddressPool was created 

### To Reproduce

cat ipaddresspoll.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main
  namespace: metallb-system
spec:
  addresses:
  - 192.168.7.40-192.168.7.49
  autoAssign: true
  avoidBuggyIPs: true
  
cat test.yaml
  apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: test
spec:
  selector:
    matchLabels:
      app: whoami
  replicas: 2
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: whoami-lb
  namespace: test
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.7.43
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: whoami
  type: LoadBalancer

### Expected Behavior

expected that service will be available on 192.168.7.43:80

it works only from k8s node, but doesn't works for any other device on my network (192.168.7.0/24)

### Additional Context

when i add ip 192.168.7.43 to /etc/netplan/50-cloud-init.yaml it start works
but it's wrong approach for metallb

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by oribon** [comment]
did you create any l2/bgp advertisement resource?

**Comment by fedepaol** [comment]
Please use the collect script to provide all the info required.

**Comment by dark4igi** [comment]
@oribon 
no(((
half year ago it works without this resource
thank a lot
