### ISSUE TITLE
Stale flag not reset while reapplying a valid config after invalid IPpool config

### ISSUE THREAD

**Issue by anjuthom** [metallb/metallb#2245]
### MetalLB Version

0.13.12

### Deployment method

Charts

### Main CNI

calico

### Kubernetes Version

1.29.0

### Cluster Distribution

other

### Describe the bug

Applying a previously applied valid IPaddresspool config after applying an invalid IPaddressPool config does not clear the stale flag

### To Reproduce

1. Apply a valid IP address pool config
2. Check stale flag is not set in the controller metrics
3.Apply an invalid IP address pool config
4. Check stale flag is set in the controller metrics
5. Apply the valid IPpool config that was applied in step1
6. Check the stale flag , it is still reported as stale

### Expected Behavior

Stale flag metallb_k8s_client_config_stale_bool  is unset when the valid config is reapplied

### Additional Context

This issue was not seen in v0.13.10
I think the problematic issue may be related to https://github.com/metallb/metallb/pull/1951

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by shimritproj** [comment]
I would like to work on it.

**Comment by oribon** [comment]
thanks, assigning this to you :)

**Comment by shimritproj** [comment]
Could you attach the YAML files you used? @anjuthom

**Comment by fedepaol** [comment]
Closing this as no feedback, @anjuthom feel free to reopen in case you can provide the requested config.
