### ISSUE TITLE
frr on localhost

### ISSUE THREAD

**Issue by aep** [metallb/metallb#2256]
### Is your feature request related to a problem?

the current native speaker does not support v6.
however, frr doesnt connect to bird running on the same host
https://github.com/metallb/metallb/issues/1966

### Describe the solution you'd like

a possible solution might be adding a third speaker with gobgp that behaves exactly like the native speaker but with more features.

on the other hand the native speaker is actually very nice and simple. as far as i understand it could be sufficient to just add a v6 message here?

[func sendUpdate(w io.Writer, asn uint32, ibgp, fbasn bool, nextHop net.IP, adv *bgp.Advertisement) error {](https://github.com/metallb/metallb/blob/b42fc17b70323b5fd7d53828e14fcbe29ae5b965/internal/bgp/native/messages.go#L292)

there's also been an attempt here i think https://github.com/metallb/metallb/pull/590/files
which i could pick back up, but it was decided back then that only FRR will be worked on (which has the issue with not connecting to localhost) 

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
Hey, thanks for filing this issue! Native mode is in "maintenance mode" and we decided to invest our energy in expanding the FRR mode.

Said this, the localhost limitation was removed in FRR (I think in 9.x, see https://github.com/FRRouting/frr/issues/11366 ) so an easy-ish thing to do is to bump our FRR.

**Comment by aep** [comment]
or could we maybe just have a flag to not run frr in host-network?
at least in my setup there's no need for anything outside to connect to frr,
and if its contained within a pod network, i could just have it speak to the host ip

**Comment by superbrothers** [comment]
FRR has been updated to 9.x, and it is now possible to peer with the local host, but the following settings need to be added to peer with the local host, and currently it is not possible to connect.

- [`allow-reserved-ranges`](https://docs.frrouting.org/en/latest/basic.html#clicmd-allow-reserved-ranges)

**Comment by fedepaol** [comment]
@superbrothers keen filing a PR to enable that (under a parameter with helm, I guess) ?
Otherwise we'll work on it

**Comment by superbrothers** [comment]
It seems that frr settings cannot be changed in Helm Chart. Those included in ConfigMap are temporary.

https://github.com/metallb/metallb/blob/main/charts/metallb/templates/speaker.yaml#L107-L115

Do we need to add the following part?

https://github.com/metallb/metallb/blob/110fbf0e47379d8af847b8dc31ec1751cdf6139d/internal/bgp/frr/templates/frr.tmpl
