### ISSUE TITLE
Fix documentation article: Requesting Specific IPs

### ISSUE THREAD

**Issue by ksemele** [metallb/metallb#2262]
### Is your feature request related to a problem?

In the documentation [there](https://metallb.universe.tf/usage/#requesting-specific-ips) is a link to indicate that this works until it is deprecated:

> Please note that spec.LoadBalancerIP is planned to be deprecated in [k8s apis](https://github.com/kubernetes/kubernetes/pull/107235).

It seems like it's already deprecated:
https://github.com/kubernetes/kubernetes/pull/107235

1. Need to fix the documentation, removing the old code
2. Need to add a new option for querying a specific IP address

### Describe the solution you'd like

1. docs are actualized
2. requesting specific IP address process described

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
Thanks for raising this!

Referring to https://github.com/metallb/metallb/issues/1182 and specifically to https://github.com/metallb/metallb/issues/1182#issuecomment-1377544857 , deprecated doesn't mean the field is going away.

Also, we have already an annotations based alternative still documented at https://metallb.universe.tf/usage/#requesting-specific-ips

Closing the issue
