### ISSUE TITLE
Deploying MetalLB 0.13.1 on Kubernetes Version 1.25.6 using Helm. I need help on How to Pass IPaddressPool using vaules.yaml 

### ISSUE THREAD

**Issue by ashishstationcasinos** [metallb/metallb#2273]
### Is your feature request related to a problem?

I am Deploying MetalLB 0.13.1 on Kubernetes Verison 1.25.6. I am using helm charts to deploy MetalLB, Need help on How to pass values.yaml

Where in verison 0.12.x
values.yaml
 configInline:
   address-pools:
   - name: default
      protocol: layer2
      addresses:
      - METALLBADDRESSRANGE_VALUE

Which is kind of throwing an Error of configinLine cant be used. 

Please help me 

### Describe the solution you'd like

I dont have any suggestion for Solution

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by steled** [comment]
Hi,

configInnline is deprecated, see: [deprecated_configInline.yaml](https://github.com/metallb/metallb/blob/main/charts/metallb/templates/deprecated_configInline.yaml)

Check [Backward Compatibility](https://metallb.universe.tf/#backward-compatibility) for more information.
You also should check [Advanced AddressPool configuration](https://metallb.universe.tf/configuration/_advanced_ipaddresspool_configuration/)

**Comment by ashishstationcasinos** [comment]
Does that Mean I need to Deploy metallb using Helm Chart and Run kubectl command to Create IPAddresspool and other resources ? 

Cant I Configure/deploy all with helmcharts using values.yaml file ?
