### ISSUE TITLE
Advertive pod subnets via BGP with MetalLB speakers

### ISSUE THREAD

**Issue by balioune** [metallb/metallb#2277]
### Is your feature request related to a problem?

Hi,
I'm using MetalLB in my Kubernetes cluster to advertise  the service network to the DC LAN.
The cluster runs also KubeVirt and I would like to connect directly to Pod hosting virtual machine using the pod network.
I would like to know if i can use FRR speaker to advertise Pod network to  my router in the datacenter ?
Best Regards,

### Describe the solution you'd like

Advertive pod subnets via BGP with MetalLB speakers

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
Hey, in the last release we introduced frr-k8s as a backend (https://github.com/metallb/frr-k8s) which is meant to allow extra configurations for purpouses that go beyond metallb. What's not available at the moment is a controller that produces a per node frrconfiguration with the cidr of that particular node, the frr-k8s configuration is on a lower level.

That aside, MetalLB is not meant to advertise anything else but lb services. Closing this issue, hope this helps
