### ISSUE TITLE
chart appVersion always at v0.0.0

### ISSUE THREAD

**Issue by steled** [metallb/metallb#2278]
### Is your feature request related to a problem?

I'm deploying mettalb via argoCD and always get the following error:

```
Failed to pull image "quay.io/metallb/controller:v0.0.0": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/metallb/controller:v0.0.0": failed to resolve reference "quay.io/metallb/controller:v0.0.0": quay.io/metallb/controller:v0.0.0: not found
```

The problem is that for the charts the appVersion is wrong, see [appVersion](https://github.com/metallb/metallb/blob/c3693e551ef20ee2e12a3591bec422c7aa83b3b5/charts/metallb/Chart.yaml#L44) of chart version 0.14.3

Because of `appVersion: v0.0.0` the images can't be pulled and I have to overwrite the value for `image.tag` manually.

### Describe the solution you'd like

It would be great if the `appVersion` is set correctly for each chart so the images can be pulled and I don't need to overwrite the `image.tag` manually.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
Hello, not sure how you are deploying but:
- The tagged chart has the right versions: https://github.com/metallb/metallb/blob/v0.14.3/charts/metallb/Chart.yaml
- The chart available at https://metallb.github.io/metallb/index.yaml has the right version

So you are probably aiming at some wrong branch?
Closing this issue, feel free to reopen if I missed something that needs to be fixed. Thanks!
