### ISSUE TITLE
MetalLB doesn't advertise from control plane nodes (or single node) since 0.13.4

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#2285]
### MetalLB Version

0.13.4

### Deployment method

Not relevant

### Main CNI

Not relevant

### Describe the bug

Since 0.13.4, metallb does not advertise from nodes labeled `exclude-from-external-load-balancers`. This may cause disruptions. Kubeadmin labels control plane nodes with the label. 

### To Reproduce

--

### Expected Behavior

--

### Additional Context

The next release will contain a documented flag to disable this behaviour in MetalLB

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by Jc2k** [comment]
Thanks for working on this. Will there be a 0.14.4 soon? :pray:

**Comment by farodin91** [comment]
It looks like have a similar problem but it only happens on service with publishNotReadyAddresses: true. 

Any idea?

```
{"caller":"layer2_controller.go:82","event":"shouldannounce","ips":["10.25.21.7"],"level":"debug","message":"failed no active endpoints","pool":"default","protocol":"l2","service":"projects-system/tempo-ingestor-tunnel-0","ts":"2024-03-26T10:51:13Z"}
```

**Comment by fedepaol** [comment]
@Jc2k we released yesterday, sorry for the delay

**Comment by Jc2k** [comment]
Cheers!

**Comment by fedepaol** [comment]
closing this, we have the issue described in the troubleshooting guide (which hopefully be read)
