### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by paulofrazao** [metallb/metallb#2293]
### MetalLB Version

0.13.9

### Deployment method

Charts

### Main CNI

calico

### Kubernetes Version

1.27

### Cluster Distribution

k3s

### Describe the bug

Getting a 404 when trying to download helm charts. Is site down?

### To Reproduce

https://metallb.github.io/metallb/

### Expected Behavior

Should be getting a response

### Additional Context

Site is down

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
The charts are up. Did you try to install via helm?
The right url to check is https://metallb.github.io/metallb/index.yaml

Closing the issue and filing a new one for extending the troubleshooting guide and / or the docs to explain this.
