### ISSUE TITLE
Document the chart reacheability

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#2294]
### Is your feature request related to a problem?

More often than expected, people check the availability of the charts by checking either https://metallb.github.io/ or https://metallb.github.io/metallb while the only page we serve is actually https://metallb.github.io/metallb/index.yaml

### Describe the solution you'd like

What we could do is either documenting this, or even better, adding a nice 404 page that tells the user not to worry, the chart is not down, just use helm or check for the index.yaml full path

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by tico88612** [comment]
Hi, @fedepaol 

I can add a simple `index.html` in the `gh-pages` branch.
Remind user to use use helm or check the index.yaml, it can fix `https://metallb.github.io/metallb`.

But `https://metallb.github.io/` need to create new repo `metallb/metallb.github.io`, add the pages and redirect to `https://metallb.github.io/metallb`.
FYI: https://pages.github.com/

I can fix `https://metallb.github.io/metallb` page. Can I work on this issue?

**Comment by tico88612** [comment]
Hi, @fedepaol 

You can see PR #2303 result.

**Comment by fedepaol** [comment]
This can be closed
