### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by salih-ozdemir** [metallb/metallb#2309]
### MetalLB Version

0.14.3

### Deployment method

Manifests

### Main CNI

calico

### Kubernetes Version

1.28

### Describe the bug

In my cluster running MetalLB. controller working but metallb-speaker has error.

Logs:

`$ kubectl logs speaker-9b46s -n metallb-system
{"branch":"v0.14.3","caller":"main.go:101","commit":"7051d76","goversion":"gc / go1.20.14 / amd64","level":"info","msg":"MetalLB speaker starting version 0.14.3 (commit 7051d76, branch v0.14.3)","ts":"2024-03-05T09:15:05Z","version":"0.14.3"}
{"caller":"main.go:147","error":"open /etc/metallb/excludel2.yaml: permission denied","level":"error","msg":"failed to parse announcedInterfacesToExclude from configMap","op":"startup","ts":"2024-03-05T09:15:05Z"}
`

use: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
image: docker.io/bitnami/metallb-speaker:latest  (0.14.3)

### To Reproduce

1. apply configuration/setting :  strictARP: true
2. download https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
3. edit image to docker.io/bitnami/metallb-speaker and docker.io/bitnami/metallb-contoller
4. apply kubectl apply -f metallb-native.yaml
5. result: controller working, 3 replicas of metallb-speaker not working , and go to CrashLoopBackOff

### Expected Behavior

metallb-speaker all replicas needs to be running

### Additional Context

-

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Why would you need to edit the image?
Does it work without editing the images?

**Comment by salih-ozdemir** [comment]
because no access  permission to quay.io

**Comment by fedepaol** [comment]
those images are public and used by all the other users.

```
docker image pull quay.io/metallb/controller:v0.14.3
v0.14.3: Pulling from metallb/controller
4abcf2066143: Already exists
4365e27e8d41: Pull complete
3dbad3380b84: Pull complete
Digest: sha256:b201a4764ba19ae3c8570582bf96bd3586d25ffd29daa78da171db9d19035c99
Status: Downloaded newer image for quay.io/metallb/controller:v0.14.3
quay.io/metallb/controller:v0.14.3
```

**Comment by salih-ozdemir** [comment]
problem is network policies/firewall settings. quay.io Restrict access for me.

**Comment by fedepaol** [comment]
We don't support the images on bitnami, You probably have a version skew between the images and the manifests.
I'd suggest to find a way to mirror the images.
Closing the issue
