### ISSUE TITLE
L2: No nodeAssigned events created when switching back to a previoulsy announcing pod

### ISSUE THREAD

**Issue by delthas** [metallb/metallb#2310]
### MetalLB Version

0.13.12

### Deployment method

Charts

### Main CNI

calico

### Kubernetes Version

1.28.2

### Describe the bug

Given two pods on two different nodes (in a Layer 2 setup): when the pod bearing the VIP becomes unhealthy, the VIP switches back to the other pod (as expected), but if that other pod was recently advertised, no nodeAssigned event is emitted for the service on that pod.

### To Reproduce

- Create two pods on two different nodes (with a simple L2 setup with 1 IP; I use ExternalTrafficPolicy Local)
- Say Pod A has the VIP and Pod B does not. The Service has a nodeAssigned event for node A (of pod A)
- Make Pod A unhealthy
- The VIP moves to Pod B. The speaker for node B logs "service has IP, announcing". The VIP is correctly moved on pod B as can be checked by eg connecting to a server hosted by the pod
- Check the Service events: The Service has a nodeAssigned event for node B (of pod B)
- Make Pod A healthy again
- The VIP moves back to Pod A. The speaker for node A logs "service has IP, announcing". The VIP is correctly moved on pod A as can be checked by eg connecting to a server hosted by the pod
- Check the Service events: There is no nodeAssigned event for node A (of pod A). The last event is still that of node B.

*After ~30 minutes events are finally created again for node A.*

### Expected Behavior

I'd expect a nodeAssigned event to be created for node A right as the VIP is moved back.

### Additional Context

Since I see the log `service has IP, announcing`, I'd expect the `nodeAssigned` event to be created immediately, as this is the next line of code in the speaker:
https://github.com/metallb/metallb/blob/7b733f0b6568499e3a67e40948191b0c1862f80a/speaker/main.go#L402
https://github.com/metallb/metallb/blob/7b733f0b6568499e3a67e40948191b0c1862f80a/speaker/main.go#L403

Of note is that the event is only missing if I switch to A->B->A quickly enough (in the order of a few minutes). If I move to B, then wait 30 minutes, then move back to A, the event is created.

Could this be some rate limiting / throttling / caching on events? As in, the A speaker pushes many nodeAssigned events, then no events while B is adveristing, then when A is advertising again, it creates nodeAssigned events again; but those are dropped entirely because there are already some recent identical events?

*(Just to clarify, I know about events being aggregated, but the LastTimestamp is indeed not updated. Which is the same as saying that the event was dropped.)*

*No error logs or anything worthy of note.*

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by delthas** [comment]
Maybe this is due to throttling / "caching" of the client logging interface; that would drop repeated calls to create the same event?

**Comment by delthas** [comment]
Ideally I'd create a MWE failing e2etest/l2tests, but I can't get the tests to work on my end (panic during inv dev-env)

**Comment by fedepaol** [comment]
Sorry for the delay. I tried to reproduce, single pod jumping between two nodes.

Here's when I moved from worker2 to worker:

```
12m         Normal   IPAllocated               service/nginx                 Assigned IP ["192.168.1.2"]
7s          Normal   nodeAssigned              service/nginx                 announcing from node "kind-worker" with protocol "layer2"
5m45s       Normal   nodeAssigned              service/nginx                 announcing from node "kind-worker2" with protocol "layer2"
```

Here's where I moved it back to worker2

```
k get events | grep service/nginx
12m         Normal   IPAllocated               service/nginx                 Assigned IP ["192.168.1.2"]
15s         Normal   nodeAssigned              service/nginx                 announcing from node "kind-worker" with protocol "layer2"
14s         Normal   nodeAssigned              service/nginx                 announcing from node "kind-worker2" with protocol "layer2"
```

and here's where I moved again to worker

```
k get events | grep service/nginx
14m         Normal   IPAllocated               service/nginx                 Assigned IP ["192.168.1.2"]
1s          Normal   nodeAssigned              service/nginx                 announcing from node "kind-worker" with protocol "layer2"
2m23s       Normal   nodeAssigned              service/nginx                 announcing from node "kind-worker2" with protocol "layer2"
```

Things seem correct to me (note the times).

I am gonna close this, feel free to reopen if this is still biting you and can provide a better reproducer.
