### ISSUE TITLE
CI: generate the test report as junit and feed gh action with it

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#2313]
### Is your feature request related to a problem?

I am pretty sure GH actions have a nice way to format junit reports. We should explore if that is possible and produce it out of our e2e tests so triaging CI failures does not require digging into logs.

### Describe the solution you'd like

The junit is produced, the output of CI is clear about which tests failed

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by tico88612** [comment]
Hi @fedepaol,

I'm new to open-source contributions and interested in this issue.
It looks like it's currently written as an overview; some details will need to be discussed with you, perhaps using Slack?

**Comment by fedepaol** [comment]
@tico88612 hey! It's an overview because the majority of the work is probably researching the two things we need to make it work:
- how to have ginkgo (the e2e framework) spit out a junit.xml file
- how to have github render it nicely

You can find me on #metallb-dev on the kubernetes slack, I can provide directions, and thanks!

**Comment by tico88612** [comment]
@fedepaol I have completed this work and welcome any comments. :D
