### ISSUE TITLE
failed to populate resolver cache from source redhat-operators/openshift-marketplac

### ISSUE THREAD

**Issue by luke2261git** [metallb/metallb#2318]
### MetalLB Version

4.15.0-202402161907

### Deployment method

Operator

### Main CNI

calico

### Kubernetes Version

v1.28.6+6216ea1

### Cluster Distribution

openshift ocp4 baremetal

### Describe the bug

Metallb fails to install in newly created 4.15 OCP4 Bare Metal Cluster .

### To Reproduce

Simply try to install with the latest OCP4 version from the console web site.

The steps outlined here do not work to completion.

https://docs.openshift.com/container-platform/4.15/networking/metallb/metallb-operator-install.html#metallb-operator-install

### Expected Behavior

Install to install without issue from the https://console-openshift-console.apps default page.

### Additional Context

The last time I tried to install in a test lab environment, 4.9.5, it installed without issue.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by luke2261git** [comment]
I reinstalled the OCP4 Bare Metal Test again.  This time metallb installed without an issue.   The installation process is not consistent nor reliable.

**Comment by fedepaol** [comment]
@luke2261git if you are eligible to openshift support, I'd suggest filing a case. This is the upstream project repository, and the deployment method is not exactly the same.
