### ISSUE TITLE
Do you know is there functionalities in metallb can support in Layer2 Mode configuration but can config routing for loadbalanced IP for traffic

### ISSUE THREAD

**Issue by AlexZhao** [metallb/metallb#2326]
### Is your feature request related to a problem?

it is not related to problem, but if want to have layer 2 working mode loadbalanced IP address, if in the K8S node there is no routing configured, it will not possible for loadbalanced IP to routing traffic out of K8S cluster.

### Describe the solution you'd like

for precise controlling routing traffics, is it possible to have metallb can support to configure policy routing, to have DNATed  loadbalanced IP address can have configured ip mangle mark the input traffic with marks and then use ip rule policy routing to configure the DNATed traffic to go outside of the K8S cluster. it can achieve a loadbalance IP associated policy routing which not depends on K8S configured routes on different node. 
currently without preconfigured routing on K8S node, it will make layer 2 mode loadbalanced IP can not direct working with host side preconfigured routes.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by cyclinder** [comment]
> If in the K8S node, there is no routing configured, it will not possible for loadbalanced IP to routing traffic out of K8S cluster.

Can you describe more details about the routing configured?  default route or static route?  If k8s nodes have no routing configured, it causes a network issue between the k8s nodes, and the k8s cluster will not work.

**Comment by AlexZhao** [comment]
If the K8S cluster configured use native IP addresses and connected with switch, it shall not require to have routing configured, consider the basic network shall work with basic L2 IP address connectivity across all nodes, if in this case there is no default or static routing configured on K8S node, if metallb working in L2 arp speaker mode, so it only can communicate with its same subnet client to access, so is it possible to have metallb can configure routing for its allocated loadbalance IP addresses? and to precise control its routing if metallb can support to use source IP based policy routing, it means even there is no loadbalance IP configured on any K8S node, but with its arp responding and also routing out traffic based on loadbalanced IP and it can precise control the gateway of the outgoing traffic.

currently my understanding is metallb in arp mode, it will responding arp request with its configured loadbalanced IP addresses, so if the external want to access this IP through a L3 routing configuration, the traffic can routing to this IP address by a gateway device, but when the respond traffic need to use loadbalanced IP to leave K8S cluster, it will require on the node to have routing configured which needs to pre-configured on the cluster, it is not that convenient.  and if direct use linux command to configure linux policy routing according to each allocated loadbalanced IP it is also not that feasible. 
I'm wondering is that possible metallb can support to configure src based policy routing according to each allocated IP address, then it can limit only loadbalanced IP can have routable traffic to leave the K8S cluster.

**Comment by cyclinder** [comment]
>  but when the respond traffic need to use loadbalanced IP to leave K8S cluster, it will require on the node to have routing configured which needs to pre-configured on the cluster

In fact, for k8s clusters, we should have at least one default route, otherwise we'll have more trouble. please see https://github.com/kubernetes/kubernetes/issues/123120. When we have at least one default route, the loadbalance traffic leaving the cluster can forwarded with the default route. 

Maybe what you want is the flexibility to control the egress traffic of the loadbalance..., You want metallb to be able to match policy-routing table by source address to automatically select an egress address. This is not possible with metallb, since you can't guarantee that the packet's source address is the loadbalance IP when it matches a policy-routing table or leaves the cluster. As far as I know, the egress gateway is usually chosen based on the destination address for the packet.

You may want an egress-gateway project, like https://github.com/spidernet-io/egressgateway.

**Comment by fedepaol** [comment]
Yeah, I agree. In general, L2 is thought for simple scenarios where the cluster and the client sit on the same subnet (or the gateway acts as such). The host network configuration can't be handled by metallb, and we can't make assumptions on the src ip that will hit that rule as it really depends on when the snat of the reply will happen and with which IP.

Closing this as non metallb issue.
