### ISSUE TITLE
failed to handle service

### ISSUE THREAD

**Issue by trinct1412** [metallb/metallb#2328]
### MetalLB Version

0.14.3

### Deployment method

Charts

### Main CNI

calico

### Describe the bug

i got the error at metallb controller 
<img width="1336" alt="image" src="https://github.com/metallb/metallb/assets/74185291/de7cae75-4d6d-4137-aae9-69250c1b84bd">
after i create a loadbalancer service

config map 
<img width="314" alt="image" src="https://github.com/metallb/metallb/assets/74185291/2b78ee59-40dc-4f74-9d0b-523cc4c05bbd">
two node 
<img width="1291" alt="image" src="https://github.com/metallb/metallb/assets/74185291/566adae8-a3d8-43c9-9d07-a061c2b5ec6f">

<img width="857" alt="image" src="https://github.com/metallb/metallb/assets/74185291/00be25c5-f504-4ccc-8137-c0f9e1b5d567">
any help 

### To Reproduce

additional context:
i follow at https://metallb.universe.tf/installation/
expected behavior:
svc nginx have the ip

### Expected Behavior

additional context : svc nginx still pending
expected behavior:
svc nginx have the ip

### Additional Context

additional context : svc nginx still pending
expected behavior:
svc nginx have the ip

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by cyclinder** [comment]
oh,  It seems you using metallb 0.14.3, but you are still using ConfigMap to configure IPAddressPool, Can you follow the docs(https://metallb.universe.tf/configuration/_advanced_l2_configuration/) for any help?

**Comment by fedepaol** [comment]
thanks @cyclinder !
Based on the emoticons (!!) I am closing this issue as I suspect it was misconfiguration only, @trinct1412 feel free to reopen in case it's still not working

**Comment by sfratini** [comment]
For people coming here with this issue, mine was that the L2 yaml file was missing the namespace and being deployed in ArgoCD it was being created in another namespace. Once I put it in metallb-system ns all worked fine.

**Comment by yifengwang66** [comment]
God! I've been struggling with this issue for a whole week!
It finally worked as soon as I moved the L2advertisements and IPAddressPool to metallb-system namespace.
Thank you very much ! You are the most handsome man in the world !

> For people coming here with this issue, mine was that the L2 yaml file was missing the namespace and being deployed in ArgoCD it was being created in another namespace. Once I put it in metallb-system ns all worked fine.
