### ISSUE TITLE
How to view the IP addresses already used by metallb, or the utilization of the address pool

### ISSUE THREAD

**Issue by macaty** [metallb/metallb#2352]
### Is your feature request related to a problem?

How to view the IP addresses already used by metallb, or the utilization of the address pool

### Describe the solution you'd like

How to view the IP addresses already used by metallb, or the utilization of the address pool

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by cyclinder** [comment]
Please see https://github.com/metallb/metallb/pull/1685#discussion_r1021307306

**Comment by fedepaol** [comment]
as per the previous comment, I am not sold on explicitly listing what ips are handed over from each pool.

@macaty for the numbers, you can currently check the metrics https://metallb.universe.tf/prometheus-metrics/#metallb-allocator-addresses-metrics  until that status lands.
