### ISSUE TITLE
MetalLB L3 mode - IP Fragments reassembly issue

### ISSUE THREAD

**Issue by venkatadivvi** [metallb/metallb#2369]
### MetalLB Version

0.13.9

### Deployment method

Charts

### Main CNI

calico

### Kubernetes Version

v1.24.3

### Cluster Distribution

rancher (RKE2)

### Describe the bug

Problem scenario where IP fragmentation is happening on traffic to Service VIP in an application deployed over RANCHER cluster. Its a TLS handshake, the client sends its certificate details in two IP fragments (due to MTU 1500). Observing both fragments hitting the interface (VIP metalLB) but then there is no response from server. Client retries (as there is no response to its certificate, supposed to get "Finished" or certs error if certs invalid) but no response.
Pls see attached packet trace (tcpdump from workernode ), frame 44786/44787 is showing the destination as VIP ( metalLB IP 10.92.96.97), but its not routed to PoD ( supposed to have a PoD receiving that fragment? reassembled packet with destination as 10.42.157.131.

### To Reproduce

Create TLS handshake (mutual authentication) with Client sending TLS certificate of size beyond MTU (1500).

### Expected Behavior

Fragments should reach the respective POD behind the service VIP.
Not clear how metalLB handles this case of IP fragments- Fragments gets delivered to POD and POD resembles them?
MetalLB reassembles the received Fragments and then send it to the respective POD. ( would assume this is the case).

### Additional Context

please refer attached
![TLS_Fragments_metalLB](https://github.com/metallb/metallb/assets/167231831/7694ef9d-01b5-40e3-a377-76561183c24c)
 trace screen for more details.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Please read about the MetalLB concepts. MetalLB is not the component that is actively forwarding packets, so it can't be the one responsible for the fragmentation issue.

https://metallb.universe.tf/concepts/

Closing the issue, it's probably something to sort out with your CNI.
