### ISSUE TITLE
Deprecate the metallb.universe.tf annotations and start handling metallb.io

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#2392]
### Is your feature request related to a problem?

metallb.universe.tf based annotations need to be deprecated and we should move to metallb.io based ones.
We should start slowly warning the users that the old ones are going to disappear soon or later, but in first instance we should handle both.

### Describe the solution you'd like

Handling both types of annotations, and I think the webhook can throw a warning to the user, so we could leverage it to notify that the old annotation is going to be deprecated.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by tylerauerbeck** [comment]
👋🏻 @fedepaol I can take a look at this if no one has picked it up yet.

**Comment by fedepaol** [comment]
That'd be great! Assigning this to you

**Comment by fedepaol** [comment]
@tylerauerbeck just checking if you still have the bandwith to work on this
