### ISSUE TITLE
Inquiry on Maturity and Potential Immature Aspects of the FRR-k8s Project

### ISSUE THREAD

**Issue by changluyi** [metallb/metallb#2397]
### Is your feature request related to a problem?

Hello community

I am considering the adoption of FRR-k8s for managing our network routing within our Kubernetes production environment. The project appears promising due to its integration capabilities with Kubernetes and potential to streamline FRRouting management. However, before proceeding, I would like to gain a deeper understanding of the project's current state of maturity and any known limitations or areas that might be considered less stable or feature-incomplete.

Specifically, I am interested in:

1. Stability and Production Readiness: What is the current status of FRR-k8s regarding stability in production environments? Are there any known issues or limitations that could potentially impact service availability or performance?

2. Feature Completeness: Are there critical FRRouting features that are yet to be fully implemented or supported in FRR-k8s? If so, what is the roadmap for addressing these gaps?

3. Finally, I would like to ask at what point the FRR-K8S will become relatively mature if it is still experimental.
Thanks

### Describe the solution you'd like

As described above

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
> ### Is your feature request related to a problem?
> 
> Hello community
> 
> I am considering the adoption of FRR-k8s for managing our network routing within our Kubernetes production environment. The project appears promising due to its integration capabilities with Kubernetes and potential to streamline FRRouting management. However, before proceeding, I would like to gain a deeper understanding of the project's current state of maturity and any known limitations or areas that might be considered less stable or feature-incomplete.
> 
> Specifically, I am interested in:
> 
>     1. Stability and Production Readiness: What is the current status of FRR-k8s regarding stability in production environments? Are there any known issues or limitations that could potentially impact service availability or performance?
> 

This is a community project, so the stability and production readiness come generally from knowing that the project is being used. Currently, despite some indication of interest, we are not aware of anyone who is using it in prod (but the same can be said about MetalLB's users).
What I can say is that we have a good amount of CI ensuring its stability adn feature parity with MetalLB with embedded FRR, and that Red Hat is going to release it (although as tech preview) in the Openshift 4.16 release (and that there is interest from us in making sure it works).

>     2. Feature Completeness: Are there critical FRRouting features that are yet to be fully implemented or supported in FRR-k8s? If so, what is the roadmap for addressing these gaps?
> 

FRR configuration is very wide, but we are not planning to add anything more than what the current api offers as of today. Any new feature needs to be carefully discussed, especially from an API perspective which can be tricky.

>     3. Finally, I would like to ask at what point the FRR-K8S will become relatively mature if it is still experimental.

See my answer to the first item.

>        Thanks
> 
> 

Closing hte issue, feel free to reopen if you still need something.
