### ISSUE TITLE
Please support MetalLB on Kubernetes v1.30

### ISSUE THREAD

**Issue by adzinzhalifunnas** [metallb/metallb#2426]
### Is your feature request related to a problem?

Yes, the problem is that MetalLB does not officially support the latest Kubernetes version 1.30 yet. As a user running Kubernetes 1.30, I would like to be able to use a compatible version of MetalLB as my bare metal load balancer.

### Describe the solution you'd like

I would like MetalLB to add official support and testing for Kubernetes 1.30 in an upcoming release. This would allow users like myself to confidently run MetalLB on the latest Kubernetes version.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
Why are you saying it doesn't support it? Did you try metallb on 1.30 and it does not work?

**Comment by tylerauerbeck** [comment]
Maybe related to #2416 

It might be better for users to see that the current set of tests pass against a certain version rather than having to install it themselves to find out.

**Comment by fedepaol** [comment]
Absolutely, I was just trying to understand if there was a real problem here or if we say somewhere that 1.30 is not supported yet.

**Comment by softlion** [comment]
Btw it does work perfectly with 1.30.1

**Comment by conradwt** [comment]
It does work with Kubernetes v1.30.2.
