### ISSUE TITLE
Update the website theme and document the process

### ISSUE THREAD

**Issue by karampok** [metallb/metallb#2436]
### Is your feature request related to a problem?

In the code we have been using https://github.com/McShelby/hugo-theme-relearn for the website, it would be nice to have an easy process to keep the theme updated

### Describe the solution you'd like

Maybe github action that creates a PR, or an inv command, to be defined.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by ayushrakesh** [comment]
@karampok Please review my PR.
