### ISSUE TITLE
NodeReconciler being invoked too frequently

### ISSUE THREAD

**Issue by shettyg** [metallb/metallb#2451]
### MetalLB Version

0.14.5

### Deployment method

Charts

### Main CNI

ovn-kubernetes

### Kubernetes Version

1.26.2

### Describe the bug

In a decently sized cluster (say 200 nodes), metallb-speaker logs get overwhelmed with logs of the form:

```
"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile" .......

{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile"
```

This likely happens because metallb-speakers watch on nodes for change in node labels and conditions. When it comes to conditions, if a daemon adds something like "lastHeartbeatTime" every 10 seconds for each node, you quickly have a situation of each speaker waking up 100 times a second for a 1000 node cluster and logging the above log messages.

I understand that the watch on conditions was done to look for `corev1.NodeNetworkUnavailable`.

So I am not sure what is a good mitigating strategy here. Can we limit the node watching to only certain labels? Atleast for ARP based lb, this should be okay? Even for BGP based LB, if we know that we are going to limit BGP advertisement to certain nodes, this should still help?

I could also change these logs to debug, but is it okay to wake up so frequently? 

If it is okay to wake up so frequently, probably not log "start reconcile" and "end reconcile" when no action is taken in that reconcile loop.

### To Reproduce

Create a medium sized k8s cluster that has conditions "lastHeartbeatTime" enabled.

### Expected Behavior

Not to log so incessantly. 

### Additional Context

Descibed above 

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
First thing that comes to my mind is all the node selectors we have for bgp / l2 advertisements.
Those requires labels to assert if a speaker should still advertise / stop advertising from a given node via the L2Advertisement / BGPAdvertisement CRD.

I am not sure what's the best way to avoid it, if not blacklisting at least the well known labels which can change periodically.

**Comment by shettyg** [comment]
To re-iterate, In this case, it is the kubelet adding "LastHeartbeatTime" to node objects "conditions" every 10 seconds. Since every node gets this update, the speakers keep getting woken up.

**Comment by shettyg** [comment]
Looks like this was the commit which added this:

```
commit 79b346ec3878d3b64f3d222dbad1180de232a1c5
Author: liornoy <lnoy@redhat.com>
Date:   Thu Mar 30 21:03:49 2023 +0300

    Respect node NetworkUnavailable condition

    This commit adds the feature of respecting the node NetworkUnavailable condition.
    In other words, when a node's NetworkUnavailable condition is True, do not
    announce the LB service from the speaker in this node.

    This makes the speaker to reload the service handler every time
    a node is updated, and adds the logic to delete the LB service announcement
    if the NetworkUnavailable condition is True.

    Note:
    1) We propagate the speaker's node collection into the ShouldAnnounce so
    that the layer2_controller can use that as part of the leader election
    and have the other nodes be aware of the unavailable node not being part
    of the elections.

    2) We make the node controller to listen for all node events,
    not only to the speaker's node. that is for the L2 re-elections.

    3) As for the BGP controller: in the ShouldAnnounce func added the
    check for NodeNetworkUnavailable condition, in case of true,
    do not announce.

    Signed-off-by: liornoy <lnoy@redhat.com>
```

**Comment by fedepaol** [comment]
Sorry, I misunderstood your " Can we limit the node watching to only certain labels? " question, that lead me 
to think the `lastHeartbeatTime` was a label (while it's a condition).

The most natural solution here is just to care about changes in the NetworkUnavailable condition in that predicate here https://github.com/metallb/metallb/blob/79b346ec3878d3b64f3d222dbad1180de232a1c5/internal/k8s/controllers/node_controller.go#L87

Fancy filing a pr :P ?

**Comment by shettyg** [comment]
Something like this?:
```
diff --git a/internal/k8s/controllers/node_controller.go b/internal/k8s/controllers/node_controller.go
index cc67477b..f7eb261c 100644
--- a/internal/k8s/controllers/node_controller.go
+++ b/internal/k8s/controllers/node_controller.go
@@ -18,10 +18,10 @@ package controllers

 import (
        "context"
-       "reflect"

        "github.com/go-kit/log"
        "github.com/go-kit/log/level"
+       k8snodes "go.universe.tf/metallb/internal/k8s/nodes"

        corev1 "k8s.io/api/core/v1"
        "k8s.io/apimachinery/pkg/labels"
@@ -82,9 +82,9 @@ func (r *NodeReconciler) SetupWithManager(mgr ctrl.Manager) error {
                                level.Error(r.Logger).Log("controller", "NodeReconciler", "error", "old object is not node", "name", oldNodeObj.GetName())
                                return true
                        }
-                       // If there is no changes in node labels, ignore event.
+                       // If there is no changes in node labels or conditions' network availablity status, ignore event.
                        if labels.Equals(labels.Set(oldNodeObj.Labels), labels.Set(newNodeObj.Labels)) &&
-                               reflect.DeepEqual(oldNodeObj.Status.Conditions, newNodeObj.Status.Conditions) {
+                               k8snodes.IsNetworkUnavailable(oldNodeObj) == k8snodes.IsNetworkUnavailable(newNodeObj) {
                                return false
                        }
                        return true
```
