### ISSUE TITLE
servicel2statuses.metallb.io CRD contains duplicate key

### ISSUE THREAD

**Issue by rich0** [metallb/metallb#2460]
### MetalLB Version

0.14.6

### Deployment method

Manifests

### Main CNI

none

### Kubernetes Version

1.29.5

### Cluster Distribution

k3s

### Describe the bug

CRD servicel2statuses.metallb.io defined in config/crd/bases/metallb.io_servicel2statuses.yaml contains a duplicate key:
.spec.versions[0].schema.openAPIV3Schema.properties.status.properties.serviceName.x-kubernetes-validations

This is at file line 76, introduced in commit 495dadec7ec104936db35db2a96058cdb4c7f1eb in this version.

(This was detected by Flux when trying to apply the kustomization.)

It looks like the error still exists in the main branch.

### To Reproduce

Flux detects the error with a dry run, but this is a basic syntax error.

### Expected Behavior

kustomization should apply without errors.

### Additional Context

n/a

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by rich0** [comment]
(Not attaching requested logs/etc as the actual kustomization is not being applied due to the duplicate key.)

Flux event output is:
  Warning  ReconciliationFailed     3m55s (x3 over 17m)  kustomize-controller  CustomResourceDefinition/servicel2statuses.metallb.io dry-run failed: failed to create typed patch object (/servicel2statuses.metallb.io; apiextensions.k8s.io/v1, Kind=CustomResourceDefinition): .spec.versions[0].schema.openAPIV3Schema.properties.status.properties.serviceName.x-kubernetes-validations: duplicate entries for key [rule="self == oldSelf"]

**Comment by fedepaol** [comment]
Thanks! We'll look into it asap!

**Comment by fedepaol** [comment]
Fix merged, closing this. Will release today / tomrrow at most
