### ISSUE TITLE
v0.14.7 speaker init container crashloop in frr mode

### ISSUE THREAD

**Issue by cehoffman** [metallb/metallb#2462]
### MetalLB Version

0.14.7

### Deployment method

Manifests

### Main CNI

cilium

### Kubernetes Version

1.29.4

### Cluster Distribution

talos

### Describe the bug

Upgrading from v0.14.5 ref to v0.14.7 ref results in crash loop on the init container for the speaker pods. The `cp-reloader` and `cp-metrics` containers try to exec `/bin/sh` but the speaker container no longer has a shell. It looks like in the helm based install this was switched to `/cp-tool`. This swap also looks to have been done in the main branch, but did not make it to the v0.14.7 tag.

### To Reproduce

Deploy config sources in kustomize `github.com/metallb/metallb/config/frr?ref=v0.14.7`

https://github.com/metallb/metallb/blob/456406b903560b15dd730f799bc0ba8ae808f442/config/frr/speaker-patch.yaml#L39-L52

### Expected Behavior

Upgrade doesn't result in a crash loop of the speaker daemonset when using the kustomize sources for frr mode.

### Additional Context

I can't submit what seems like an oversight in a past release without lying in the check boxes for the bug template that the bug is reproducible in the main branch. Not sure desired path for reporting bugs in released versions that don't appear to be caught by the next release. The `/cp-tool` change existed in main prior the the most recent tag.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Thanks! We'll fix it, sorry for the issue

**Comment by oribon** [comment]
Just released 0.14.8 that should solve this, mind checking?
thanks for raising this!

**Comment by mzac** [comment]
Looks good on my K3S system!

**Comment by oribon** [comment]
@mzac awesome thanks! closing the issue, feel free to re-open if needed :)
