### ISSUE TITLE
Confusing release version v0.0.17 vs tag v0.14.7

### ISSUE THREAD

**Issue by tanvp112** [metallb/metallb#2468]
### MetalLB Version

v0.0.17 or v0.14.7?

### Deployment method

Not relevant

### Main CNI

Not relevant

### Kubernetes Version

Not relevant

### Cluster Distribution

Not relevant

### Describe the bug

Noticed the recent two release versions (v0.0.17, v0.0.16) has stopped following the tag (v0.14.7, v0.14.6). The image URI quay.io/metallb/speaker:v0.14.7 and the helm chart are  using the release tag, should the project Release page uses the same like the before? Otherwise this is confusing not knowing what v0.0.17 means or map to.

### To Reproduce

Not relevant.

### Expected Behavior

Should unify to use release tag.

### Additional Context

Not relevant.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Apologies! That was clearly a mistake. Fixed it and thanks for raising!
