### ISSUE TITLE
Version Number issues on Relases ?

### ISSUE THREAD

**Issue by ttbakiatwoam** [metallb/metallb#2484]
### MetalLB Version

0.14.8 or is it 0.14.18

### Deployment method

Not relevant

### Main CNI

NA

### Kubernetes Version

NA

### Cluster Distribution

NA

### Describe the bug

It appears that the numbering system for Versions recently changed on GitHub, skipping from 0.14.5 to 0.14.16. However, the release tags didn't change. 0.14.5 to 0.14.8. If this is intentional, can you update your site documentation and the tags? if it's a mistake can you correct the release names? 

<img width="1350" alt="Screenshot 2024-08-08 at 14 10 44" src="https://github.com/user-attachments/assets/3997f156-af69-4936-8c6a-27ef28421f31">

### To Reproduce

Try to pull v.0.14.18, but it doesn't exist.

### Expected Behavior

Version Release names should match GitHub release tags. 

### Additional Context

Please ignore me if I am wrong here or if I have missed some information. If I do not understand your numbering scheme again, please ignore it. There seem to be some typos. 

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by ttbakiatwoam** [comment]
This is a duplicate of https://github.com/metallb/metallb/issues/2480 with screenshot.

**Comment by oribon** [comment]
fixed, thanks!
