### ISSUE TITLE
k8s 1.22 install v0.14.8 metallb-native.yaml error

### ISSUE THREAD

**Issue by xiaopanggege** [metallb/metallb#2493]
### MetalLB Version

0.14.8

### Deployment method

Manifests

### Main CNI

calico

### Kubernetes Version

1.22.4

### Cluster Distribution

k8s

### Describe the bug

kubectl apply -f metallb-native.yaml

namespace/metallb-system created
customresourcedefinition.apiextensions.k8s.io/bfdprofiles.metallb.io created
customresourcedefinition.apiextensions.k8s.io/bgpadvertisements.metallb.io created
error: error validating "metallb-native.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[1].schema.openAPIV3Schema.properties.spec.properties.connectTime): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.versions[1].schema.openAPIV3Schema.properties.spec.properties.enableGracefulRestart): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps]; if you choose to ignore these errors, turn validation off with --validate=false

### To Reproduce

I found a version mapping between k8s and metallb in the documentation

### Expected Behavior

I found a version mapping between k8s and metallb in the documentation

### Additional Context

I found a version mapping between k8s and metallb in the documentation

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by ygqygq2** [comment]
#1615

**Comment by xiaopanggege** [comment]
@ygqygq2 也就是换成低版本的就可以了对吗，其实我之前是准备用低版本的，但是不知道选择哪个版本，官方没有给出版本对应表，还得自己一个个测试哪个版本合适。。。

**Comment by ygqygq2** [comment]
@xiaopanggege 你什么版本，我现在 1.21 版本，用的0.13.7，是可以的。然后我经过测试，使用 l2，要配置 L2Advertisement指定节点来广播 arp，不然无法在 k8s 外部正常访问 slb IP和端口。

**Comment by xiaopanggege** [comment]
@ygqygq2 感谢，我是1.22版本K8S，刚才用0.13.8能正常安装成功，我后面也试一下看看有没有外部访问slb ip：端口不正常的问题

**Comment by fedepaol** [comment]
Not sure I understand the discussion. Would you mind switching to english and telling us if it's still an issue (or close it)? Thanks!

**Comment by xiaopanggege** [comment]
@fedepaol Thank you, the problem has been solved, the main reason is that the official document does not introduce different k8s version to use which version of metallb, resulting in my k8s version 1.22 using the latest version of metallb 0.14.8 abnormal, need to choose to use 0.13.8 is normal

**Comment by fedepaol** [comment]
@xiaopanggege are you sure you are not hitting the ignore-lb behaviour described here https://metallb.io/troubleshooting/#metallb-is-not-advertising-my-service-from-my-control-plane-nodes-or-from-my-single-node-cluster ?

**Comment by fedepaol** [comment]
Also, see https://github.com/metallb/metallb/issues/2285

**Comment by fedepaol** [comment]
Closing the issue as seems to be solved anyhow
