### ISSUE TITLE
L2 advertisement assigns IP to NotReady node

### ISSUE THREAD

**Issue by nvlan** [metallb/metallb#2514]
### MetalLB Version

0.14.6

### Deployment method

Charts

### Main CNI

cilium

### Kubernetes Version

1.28.11

### Describe the bug

Hello, in a 13 node cluster where 4 were in the "NotReady,SchedulingDisabled" status, Metallb was assigning one ot the SVC ips to one of the notready nodes. Deleting and re-creating the SVC had the same effect, the metallb-speaker daemonset was down to 9 pods but it was as if the controller was still considering all 13 nodes for picking one.

### To Reproduce

1. Create a L2 advertisement & IP pool.
2. Create a LoadBalancer SVC.
3. Cordon and stop node that is advertising the IP.
4. IP stays in the NotReady node.

### Expected Behavior

Metallb would move the IP to a live node, if not automatically then after deleting and re-creating the SVC.

### Additional Context

-

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by karampok** [comment]
If I understand the statement, I think this commit https://github.com/metallb/metallb/commit/cbb36c74d1eb20495cd8b721c86bea7ed266da3f should resolve the issue.

**Comment by fedepaol** [comment]
Indeed. Closing as https://github.com/metallb/metallb/pull/2470 was merged
