### ISSUE TITLE
Speaker resources are deployed when using Helm chart altough speaker is disabled in its values

### ISSUE THREAD

**Issue by unai-ttxu** [metallb/metallb#2519]
### MetalLB Version

0.14.8

### Deployment method

Charts

### Main CNI

calico

### Kubernetes Version

1.30

### Describe the bug

Some speaker related resources and configuration are created even if `speaker.enabled` value is set to `false`.

### To Reproduce

1. Deploy `metallb` using its Helm chart and setting `speaker.enabled: false`
2. Check the following resources are created:
- clusterrole `metallb:speaker`
- clusterrolebinding `metallb:speaker`
- serviceaccount `metallb-speaker`
- servicemonitor `metallb-speaker-monitor` (if `prometheus.serviceMonitor.enabled: true`)
- service `metallb-speaker-monitor-service` (if `prometheus.serviceMonitor.enabled: true`)
- podmonitor `metallb-speaker` (if `prometheus.podMonitor.enabled: true`)

### Expected Behavior

When `speaker.enabled: false` no `speaker` related resources must be created. Also no `speaker` related configuration must be present.

### Additional Context

I opened https://github.com/metallb/metallb/pull/2466 to fix this issue.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [ ] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [x] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [x] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment]
Closing as the corresponding pr was merged
