### ISSUE TITLE
CI flake: Unknown stream id 1, discarding message 

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#2526]
### MetalLB Version

not relevant

### Deployment method

Not relevant

### Main CNI

Not relevant

### Describe the bug

We are seeing flakes on ci like https://github.com/metallb/metallb/actions/runs/10797181713/job/29948033121?pr=2525

The vtysh calls are failing with " Unknown stream id 1, discarding message". 

### To Reproduce

It's a flake!

### Expected Behavior

CI stable

### Additional Context

We should implement some retry mechanism to make the ci more stable

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by karampok** [comment]
Some notes:
https://kubernetes.io/blog/2024/08/20/websockets-transition/
1.31: Streaming Transitions from SPDY to WebSockets
and our kubectl version changed to v1.31 as part of this commit https://github.com/metallb/metallb/commit/88aa1b6969e265c7f673908cd1bec6a506f8711e

Reverting to older version is not ideal ofc.
I am thinking that we can exclude the stderr and take only the stdout here https://github.com/metallb/metallb/blob/main/e2etest/pkg/executor/executor.go#L70

**Comment by karampok** [comment]
> I'd say let's retry it a few times in case of error. WDYT?

I am not sure what you suggest.

The actual error is nil, the output combines stderr/stdout, In that in that case
stderr = `E0910 18:08:54.853077  339136 websocket.go:296] Unknown stream id 1, discarding message`
stdout =
 ```
\n{\n\"default\":{\n \"vrfId\": 0,\n \"vrfName\": \"default\",\n \"tableVersion\": 0,\n \"routerId\": \"172.19.0.2\",\n  
\"defaultLocPrf\": 100,\n \"localAS\": 64512,\n \"routes\": {  }  } \n,\n\"red\":{\n \"vrfId\": 5,\n \"vrfName\": \"red\",\n 
\"tableVersion\": 0,\n \"routerId\": \"172.31.0.4\",\n \"defaultLocPrf\": 100,\n \"localAS\": 64513,\n \"routes\": {  }  } \n}\n",
```` 
which is  valid json, but combined not

I found this ref that 

https://github.com/kubernetes/kubernetes/blob/88df7e307b755ea1a0c3223a85d881d9703f2cf7/staging/src/k8s.io/client-go/tools/remotecommand/websocket.go#L296


if we print only the stdout, I think we are covered (next steps will also fail if there is malformed output)

I created a PR with two version to dicsuss https://github.com/metallb/metallb/pull/2536
Thanks

**Comment by fedepaol** [comment]
if  that solves in a cleaner way, even better. I was suggesting to retry unitl it works.
