### ISSUE TITLE
Replace internal/k8s with kooper

### ISSUE THREAD

**Issue by danderson** [metallb/metallb#26]
internal/k8s is all the icky glue between Kubernetes and the cleaner interfaces used by the binaries. I need to do research on how k8s usually tests such client logic.

**Comment by danderson** [comment]
Instead of doing this, we should probably replace internal/k8s with [kooper](https://github.com/spotahome/kooper), and rely on their tests.

**Comment by fedepaol** [comment]
Closing this as we are switching to controller-runtime
