### ISSUE TITLE
Local externalTrafficPolicy not working in BGP mode with kube-proxy in ipvs mode

### ISSUE THREAD

**Issue by stephan2012** [metallb/metallb#290]
**Is this a bug report or a feature request?**:
Bug

**What happened**:
Configured a service of type `LoadBalancer` with `externalTrafficPolicy` set to `Local`. IP address is configured and BGP-announced correctly but loadbalancer IP is not accessible in the cluster except for the nodes that the Pods are running on. Traffic coming from outside the Kubernetes cluster seems still to be balanced to other Pods instead of remaining local causing connections to be establish only when balanced to the local host. Whenever traffic is directed non-local, all packets seem to be dropped.

**What you expected to happen**:
Inbound traffic stays local to the ingressing node. All cluster members can access the loadbalancer IP address.

**How to reproduce it (as minimally and precisely as possible)**:

Create a service of type `LoadBalancer`with `externalTrafficPolicy`set to `Local`.

```
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
```

Run two Pods for this service located on different K8s workers. Try to access loadbalancer IPs from outside the cluster:

```
$ curl -x '' --connect-timeout 3 http://192.168.111.0/whoami.txt
I am nginx-6bb5496466-6gdgq
$ curl -x '' --connect-timeout 3 http://192.168.111.0/whoami.txt
curl: (28) connect() timed out!
$ curl -x '' --connect-timeout 3 http://192.168.111.0/whoami.txt
I am nginx-6bb5496466-6gdgq
$ curl -x '' --connect-timeout 3 http://192.168.111.0/whoami.txt
curl: (28) connect() timed out!
```

BGP announced route directs traffic to node n0206:

```
# kubectl get pods -o wide -n nginx
NAME                     READY     STATUS    RESTARTS   AGE       IP                NODE
nginx-6bb5496466-6gdgq   1/1       Running   7          12d       192.168.178.88    n0206
nginx-6bb5496466-c68st   1/1       Running   0          3d        192.168.177.101   n0205
```

From inside the cluster, there is no connectivity at all:

```
# curl -x '' --connect-timeout 3 http://192.168.111.0/whoami.txt
curl: (28) Connection timed out after 3001 milliseconds
```

**Anything else we need to know?**:
kube-proxy runs in ipvs mode. Pod networking implemtened by kube-router.

**Environment**:
- MetalLB version: 0.7.1
- Kubernetes version: 1.11.1
- BGP router type/version: Bird running on Linux, 1.6.3
- OS (e.g. from /etc/os-release): Debian GNU/Linux 9.5
- Kernel (e.g. `uname -a`): `Linux n0201 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux`

**Comment by danderson** [comment]
Okay, two initial thoughts...

One, IPVS mode has famously not been very good in the past with preserving correct behavior for external LBs, so maybe this is yet another upstream bug for Kubernetes. I hope not :(.

Two, kube-router might be conflicting with kube-proxy, depending on the configuration it might also be trying to route the service.

Can you paste the output of the following commands (run them on a node that has a pod for your service) : 
 - `ip addr`
 - `iptables -L -n -v`
 - `iptables -t nat -L -n -v`

**Comment by eknudtson** [comment]
possibly related? : https://github.com/kubernetes/kubernetes/issues/66062

Here's what we're seeing : 

worker 1 : 10.0.0.1
worker 2 : 10.0.0.2

I created a type : LoadBalancer service with two echoheader pods : 
```
$ k get svc -o wide
NAME          TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE   SELECTOR
echoheaders   LoadBalancer   10.11.11.1   10.12.12.1     80:32141/TCP   75m   run=echoheaders
```

```
$ k get pods -o wide
NAME                          READY   STATUS    RESTARTS   AGE   IP           NODE                                     NOMINATED NODE
echoheaders-1   1/1     Running   0          49m   10.10.10.51   worker-1.example.com   <none>
echoheaders-2   1/1     Running   0          49m   10.10.10.54   worker-2.example.com   <none>```

When creating a MetalLB service, I see IPVS entries for the hostport the service creates : 

```
TCP  10.0.0.1:32141 rr
  -> 10.10.10.51:8080              Masq    1      0          0```

This looks good in that it only directs traffic to the pod on the worker.

For the MetalLB external IP on the other hand : 

```
TCP  10.12.12.1:80 rr
  -> 10.10.10.51:8080              Masq    1      0          0
  -> 10.10.10.54:8080              Masq    1      0          0
```

It would appear traffic is properly arriving on a worker advertising the MetalLB IP via BGP, but then IPVS is occasionally round robin'ing the traffic to a pod on another other worker without SNAT due to the externaltrafficpolicy.

**Comment by danderson** [comment]
That definitely sounds like a bug in kube-proxy (i.e. upstream k8s). With `externalTrafficPolicy: Local`, nodes should never route service traffic outside localhost. What you're observing definitely explains the observed traffic loss, because nothing in k8s's traffic routing logic is prepared to handle split routing (which is what happens when you send traffic across nodes without SNAT).

**Comment by FF7C7** [comment]
Hello.
You probably need to specify for the service:
`sessionAffinity: ClientIP` (default: None)

https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-ipvs
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L1012

**Comment by eknudtson** [comment]
Shouldn't that behavior occur when setting `externalTrafficPolicy:Local`?  It seems like a bug in the IPVS implementation of the config item.

**Comment by eknudtson** [comment]
following up, this appears to be fixed in k8s 1.14 (there are a few dupe issues related to this) : https://github.com/kubernetes/kubernetes/pull/72432

**Comment by stephan2012** [comment]
Let’s test when Kubernetes 1.14 final is out.

**Comment by misterdorm** [comment]
Has anyone been able to verify this is fixed in 1.14?  We are running 1.13 and I'm seeing this behavior also with MetalLB and IPVS kube-proxy.  Looking for some hope that 1.14 will solve this for me!

**Comment by chrono2002** [comment]
same here
even figured out a blocking iptables rule:
iptables -t nat -L KUBE-SERVICES -v --line-numbers
iptables -t nat -D KUBE-SERVICES 1            # KUBE-LOAD-BALANCER

**Comment by champtar** [comment]
@misterdorm I'm not using BGP, but 1.14 fixed what @eknudtson describe for me (IPVS sending to all pods despite `externalTrafficPolicy:Local` and without SNAT)

**Comment by russellb** [comment]
Based on the last set of comments, it sounds like this is no longer an issue
