### ISSUE TITLE
Add liveness and readiness probes for MetalLB components

### ISSUE THREAD

**Issue by muffin87** [metallb/metallb#307]
Hi,

currently I'm experimenting with MetalLB and it works like a charm.
For getting it into production, I would like to add Readyness and LivenessProbe for the controller and speaker. In the documentation and in the official helm chart I couldn't find any probe.

Are there any ideas how to test the two states?
Using the Prometheus metrics port feels a little bit unsafe I guess...

**Environment**:
- MetalLB version: 0.7.3
- Kubernetes version: 1.10.6
- BGP router type/version: Checkpoint Model ?
- OS (e.g. from /etc/os-release): CentOS 7.5
- Kernel (e.g. `uname -a`): Linux 4.18.1-1.el7.elrepo.x86_64 #1 SMP Wed Aug 15 16:28:40 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by danderson** [comment]
There's no readiness check currently. Liveness, the prometheus metrics port will provide a very basic "is this process alive at all", which is about as good as we can get.

I'll keep this open as a feature request to do something better.

**Comment by fedepaol** [comment]
Closing, we have both in the helm chart
