### ISSUE TITLE
Pool affinity  for Namespace

### ISSUE THREAD

**Issue by AMyltsev** [metallb/metallb#383]
**Is this a bug report or a feature request?**:
Question

Is there possibility to configure affinity only specific pool for namespace?

**What you expected to happen**:
Configure multiple pools in metallb and provide them for different namespaces in multi tenancy cluster. 
Allow use only specific pool for specific namespace.

**Anything else we need to know?**:
Layer 2 configuration

**Comment by alexlovelltroy** [comment]
Default per namespace would be helpful to me as well.  Also to support multitenancy

**Comment by danderson** [comment]
There's no way to do this currently. Marking as an enhancement.

**Comment by uablrek** [comment]
This proposal has two independent parts;
* Address allocation (controller)
* Address announcement (speaker)

The address allocation is quite easy to implement but address announcement is very hard if I interpret the request for "multitenancy" correctly; I guess tennans may have different external networks, so a loadBalancerIP in one tennants namespace should only by announce on that tennants external network (or BPP peers).

I think however that only address allocation is useful without support for mulitennant networks. It would remove the need for annotations in the services (to select pools) for a new application, an appropriate namespace configuration is sufficient.

That said I hereby focus on address allocation. Address announcement remains as-is which means that external addresses from all services are announced regardless of namespace.

This is an idea of how configuration may look like. A "namespace" tag is added;
```
    address-pools:
    - name: someapp-pool
      namespace: someapp
      protocol: bgp
      addresses:
      - 10.0.0.0/28
      - 1000::/124
```

If the "namespace" tag is missing the addresses are handed out to services in any namespace **except** services in namespaces that has explicit pools specified. This is backward compatible.

Services in namespaces that have explicit pools allocated will get loadBalancerIP's from those pools only, even if "global" pools exist.

`auto-assign: false` will still work but will be less useful for pools with defined namespaces.

**Comment by fedepaol** [comment]
this is solved by the namespace selector we added in ipaddresspool
