### ISSUE TITLE
BFD support

### ISSUE THREAD

**Issue by creativie** [metallb/metallb#396]
**Is this a bug report or a feature request?**:

Feature request

**What happened**:

Bidirectional Forwarding Detection not supported

**What you expected to happen**:

Detect faults between two forwarding engines connected by a link

**Anything else we need to know?**:

https://en.wikipedia.org/wiki/Bidirectional_Forwarding_Detection

**Environment**:
- MetalLB version: 0.7.3
- Kubernetes version: 1.13.2

**Comment by aojea** [comment]
I can share my experience with BFD implemented in software and ... simply don't use it, BFD operates in the order of miliseconds , there is a nice explanation here https://networkengineering.stackexchange.com/a/45926

I'm curious about your needs, are the routing protocol timers not enough?

**Comment by creativie** [comment]
I also have experience with software BGP
I use BGP with BFD in load balancers (between Nexus and linux servers), and with thousands of requests per second, fast traffic switching is necessary
Therefore, BGP timers are not enough

**Comment by dshcherb** [comment]
BGP timers is a control plane mechanism while BFD is used for data plane. In a _generic_ BGP deployment, control plane may be separated from the data plane and so failure to reach the next hop of a route is not the same as a BGP speaker failure.

More importantly, hold time is specified in [seconds](https://tools.ietf.org/html/rfc4271#section-4.2) and cannot be less than that while for certain types of applications <200ms failover time is required to avoid noticeable impact. On [hold timer expiry a BGP connection is closed](https://tools.ietf.org/html/rfc4271#section-6.5) and routes that have been advertised by a speaker associated with that connection [are removed](https://tools.ietf.org/html/rfc4271#page-10) from a router's RIB & FIB, however, between the actual failure time and eviction time, ECMP load-sharing continues to work as before and some L4 traffic flows will be black-holed as hashing is static per L4 flow for a given routing table size and the failed route(s) will still be there and will be used for forwarding before eviction.

I can also see that the default hold time in the example config [is 120 seconds](https://github.com/google/metallb/blob/v0.7.3/manifests/example-config.yaml#L21-L23) which is a lot in terms of failure detection.

**Comment by danderson** [comment]
+1 for BFD, it would be nice. I'm not prioritizing it until I have proper e2e tests in place to make it safe to extend MetalLB, however. But, consider the request recorded and prioritized :)

**Comment by salanki** [comment]
A Linux kernel BFD implementation would be the best.

**Comment by Thoro** [comment]
Not sure if it's relevant for anyone here, but I did a BFD implementation in Go. Since it provides a grpc api, I'm sure someone could find a use for it.

https://github.com/Thoro/bfd

**Comment by mcarbonneaux** [comment]
With the support of BFD while optimize greatly the BGP time convergence, without it the router need to wait hold time timer (generaly around 120s) to black list the route to dead target ip... with BFD can be below seconds...

In distributed architecture like k8s can make greatly the difference...

**Comment by vskovzgird** [comment]
+ 1 for BFD. Most of hardware BGP routers in DC rely on this protocol while builds BGP sessions.

**Comment by mcarbonneaux** [comment]
@danderson to make e2e test you can use bird that support bfd as client and server.
https://bird.network.cz/?get_doc&v=20&f=bird-6.html#ss6.2 

the advantage is to abel to test with container or vm with bird installed on it, it's full software.
Sample configuration can be found [here](https://docs.cilium.io/en/v1.9/gettingstarted/bird/).

**Comment by mcarbonneaux** [comment]
@aojea BFD are not implemented in hardware (as electronique componant, like asic) in "hardware" router, but in software (but on realtime OS generaly) but are embeded in specifique hardware "blackbox" from network hardware provider... the network routing can be accelerated with specifique asic or soc, but the out of band check that are generaly done by the main cpu of the "hardware" router... and modern hardware router use generic network oriented specialized SOC like octeon/thunder from cavium... generaly arm cpu...

and you can configure bfd timing on each side, in that way you can remove route below the seconds in place of default bgp hold timer that are generaly near 120s....

**Comment by mcarbonneaux** [comment]
@salanki the bgp implementation of metal lb are software only in userspace, why implement it bfd in kernel ?

**Comment by fedepaol** [comment]
FYI: BGP + BFD is currently being proposed as part of this design proposal: https://github.com/metallb/metallb/pull/927

**Comment by aojea** [comment]
>  but in software (but on realtime OS generaly) but are embeded in specifique hardware "blackbox" from network hardware provider

thanks for the detailed description, my point is that BFD (uses to) operates in second/millisecond order, if you implement BFD in user space you are at the mercy of the environment constraints like CPU or interfaces buffer saturation per example, there is no discrimination on the server to treat specially your BFD packets.

BFD in your VM, during simple testing or non-busy environments will work perfectly fine, BFD userspace under load (you can just saturate server CPU or the NIC) in user space will not, my 2 cents.

**Comment by fedepaol** [comment]
Closing this as it was added in FRR mode
