### ISSUE TITLE
Match BGP connection source address to router ID

### ISSUE THREAD

**Issue by briantopping** [metallb/metallb#422]
### What happened: 
Peering BIRD and MLB on the same host node was possible by fiddling with the addresses that BIRD and MLB expect to see each other on. The processes were peering, but the origin for the propagated routes from MLB was somehow showing as the upstream peer to the BIRD instance, not the BIRD host itself. This caused routing loops as soon as the unaggregated MLB routes were propagated.

### What you expected to happen:
The goal was that the upstream would know what host to direct traffic at per address. But with the routing loop, there was no way to get that properly working.

### Resolution
Forthcoming small patch will set the source address of the TCP connection to the router ID specified in configuration, rather than relying on the Go resolver to provide one. With the patch, MLB connects to BIRD from the matching router ID. This apparently avoids some issue that might more properly be rejected by it for a session opening.

**Comment by russellb** [comment]
The associated PR was closed over a year ago, so I assume this issue is no longer needed.

**Comment by briantopping** [comment]
@russellb Problem still exists, unfortunately. I just keep manually patching on my end when I need to upgrade.

**Comment by russellb** [comment]
> @russellb Problem still exists, unfortunately. I just keep manually patching on my end when I need to upgrade.

Sorry about that.  I'm closing stuff a bit quickly in a cleanup round.  Should the PR be reopened then?  Is that the patch you're carrying to make your environment work at each upgrade?

**Comment by briantopping** [comment]
> Should the PR be reopened then? Is that the patch you're carrying to make your environment work at each upgrade?

Probably. I don't remember what the objections were, but I've been using it cleanly for a long time.

**Comment by russellb** [comment]
> > Should the PR be reopened then? Is that the patch you're carrying to make your environment work at each upgrade?
> 
> Probably. I don't remember what the objections were, but I've been using it cleanly for a long time.

It looks like more of a misunderstanding about whether it was still needed?

**Comment by briantopping** [comment]
Not really sure. I could update the PR if that's desirable.

**Comment by briantopping** [comment]
Closed in deference to #670
