### ISSUE TITLE
IP assignement is not persistent accross cluster restart

### ISSUE THREAD

**Issue by champtar** [metallb/metallb#435]
Using k8s 1.14.1 + ipvs + metallb 0.7.3
I just had 1 IP configured in metallb default pool, and 2 loadbalancer services (A & B)
A was attributed the IP, and service B was `<pending>`
After reboot (single server lab, so "full cluster" restart), service B was attributed the IP, and A was pending
I haven't tested with no missing IP, but I guess neither k8s nor metallb write the attribution down

Possible workaround are:
- use loadBalancerIP in the service definition
- use named address pools

I'm opening this bug more to reference this unexpected behaviour than to get a fix (but I'm not opposed to it ;) )

**Comment by danderson** [comment]
This is an issue with k8s, not MetalLB. If k8s preserves the Service objects and MetalLB's ConfigMap correctly, everything should come back up correctly. My guess in this case is that k8s reported an incomplete cluster state to MetalLB during startup, and it cleared the assignment for service A. There's nothing I can do about that, unfortunately. If you want guaranteed stable IPs, you should assign them explicitly using the `LoadBalancerIP` field of the `Service` object.

**Comment by russellb** [comment]
@champtar Do you still want to keep this open?

**Comment by champtar** [comment]
nop let's close it
