### ISSUE TITLE
Update documentation for Debian Buster gotchas

### ISSUE THREAD

**Issue by trezm** [metallb/metallb#451]
As @danderson explained in the slack, Debian Buster will require disabling the new nftable firewalls, as seen [here](https://wiki.debian.org/nftables).

```
# update-alternatives --set iptables /usr/sbin/iptables-legacy
# update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
# update-alternatives --set arptables /usr/sbin/arptables-legacy
# update-alternatives --set ebtables /usr/sbin/ebtables-legacy
```

**Comment by danderson** [comment]
Thanks for filing! Got a busy several days, but I'll get to this.

**Comment by danderson** [comment]
Punting for this release, just because there's no good place in the documentation to put it. That's on the plans for the release after next.

**Comment by neowisard** [comment]
Thanx so much for this )   In the docs is necessary.

**Comment by Foltik** [comment]
Seems like kube-proxy as of Kubernetes 0.17 now supports nftables, as discussed in https://github.com/kubernetes/kubernetes/issues/71305

**Comment by champtar** [comment]
@Foltik is this really related to MetalLB at all ? This config is just to have a working K8S cluster, and MetalLB doesn't configure any iptables / nftables rules as far as I know, kube-proxy takes care of that.
@danderson you can correct me if I'm wrong ;)
