### ISSUE TITLE
Support BGP announcements for multiple IP addresses

### ISSUE THREAD

**Issue by sfudeus** [metallb/metallb#453]
This is a feature request.

Kubernetes generally supports adding multiple IP addresses to the status field of a service (status.loadBalancer.ingress[].ip), not just a single one. 

metallb-speaker does not process those unfortunately. 
We do have cases, where a service shall be exposed on multiple IP addresses (from different IP ranges, differently firewalled). 
We'd be willing to provide a PR ourselves if the idea sounds reasonable.  

I'd not aim for making this available for metallb-controller based IP selection, only if you have an own operator which patches a service object. 
I have no idea how relevant/feasible this is for layer2 support, I have no such setup around.

**Comment by johananl** [comment]
https://github.com/metallb/metallb/issues/439 looks similar but for layer 2.

**Comment by fedepaol** [comment]
Closing as per the same reason of #439 
The solution to this issue is to have multiple services sharing the same set of endpoints.
Doing this is functionally equivalent to having a service with the two ips.
