### ISSUE TITLE
Add chart to https://hub.helm.sh ?

### ISSUE THREAD

**Issue by davidkarlsen** [metallb/metallb#460]
What do you think about adding the chart to https://helm.sh/blog/intro-helm-hub/ and then retire https://github.com/helm/charts/tree/master/stable/metallb ?

**Comment by danderson** [comment]
Yes! I've been meaning to do that. It takes a little bit of extra effort to generate a chart repository with the manifest index and stuff, so I haven't done it yet, but ideally I would like `metallb.universe.tf/helm` to be a repository for MetalLB, as you suggest.

**Comment by davidkarlsen** [comment]
You can use github pages for hosting. I can find info for you if you are interested?

**Comment by danderson** [comment]
The website is already hosted on Netlify, I would prefer to keep everything there. I just need to spend a little bit of time to understand how to build the various metadata files that Helm wants.

**Comment by johanfleury** [comment]
I did something similar to host a helm repository on GitLab pages at work. I can have a look, if needed.

**Comment by runningman84** [comment]
@danderson is there a reason why helm is not supported anymore?

**Comment by russellb** [comment]
I'm closing this since helm support was dropped from the repo in commit 416e01d79092d795a14c7db69bdce6917c3a9e01
