### ISSUE TITLE
Update reference to config.inline configuration of chart in documentation

### ISSUE THREAD

**Issue by krichter722** [metallb/metallb#475]
https://metallb.universe.tf/installation/ mentions `config.inline` which doesn't exist in the list of configuration values at https://github.com/helm/charts/tree/master/stable/nginx-ingress

It seems that there's a mismatch in the `ConfigMap` name in https://kubernetes.github.io/ingress-nginx/deploy/baremetal/ as well. There it says `config` whereas at https://metallb.universe.tf/installation/ it says `metallb-config`.

**Comment by oskapt** [comment]
#476 fixes the second part of your issue.

**Comment by evrardjp** [comment]
Is that still valid? I don't see what this relates to.

**Comment by oskapt** [comment]
I don't think this issue is still valid. Everything appears to have been cleaned up when the docs were updated for Kustomize.

**Comment by evrardjp** [comment]
Agreed @oskapt ... Which means we can probably close this.

**Comment by daxmc99** [comment]
Fixed in https://github.com/metallb/metallb/commit/5fff8b37444fc11b4bce3a6c2ac6cfedb479e4a2
