### ISSUE TITLE
BGP Failover too slow

### ISSUE THREAD

**Issue by holmesb** [metallb/metallb#485]
Here's my experience.  Two node cluster with a LB Service fronting a DaemonSet (pod on both nodes).  Node A goes down, everything continues to work fine on Node B.

However, when Node A returns and within 15-20 minutes Node B goes down, traffic is lost to my LB Service (`curl: (28) Connection timed out...`)

On the BGP router, I notice there are no routes:
```
# get router info routing-table details 10.0.0.0/32
% Network not in table
```
Looking at the speaker logs, MLB seems very slow to update the BGP Peer (router) after a node recovers.  The `updatedAdvertisements` events, which I expect are responsible for publishing routes to BGP, take a long-time to trigger.  If I manually restart the Speaker pod on a recovered Node, the router is immediately updated successfully (`get router info routing-table details` returns the route), and I can subsequently failover.  Obviously this is not a solution.  I think the problem is worsened by [this issue](https://github.com/kubernetes/kubernetes/issues/55713), which means DaemonSet pods remain in a "Running" state throughout a node failure (assuming a network problem rather than OS crash).  

There is a [workaround script](https://github.com/mattmattox/drain-node-on-crash) that watches for failed nodes and drains them, which forces the DS pod (Speaker) to restart when the failed node returns.  Again, not a real solution.  Is there any way of making Speakers' BGP route publishing frequency configurable, occur more frequently, or even better trigger when a node transitions from NotReady to Ready?

- Version of MetalLB - 0.8.1
- Version of Kubernetes 1.15.3
- Name and version of network addon: Calico
- Whether you've configured kube-proxy for iptables or ipvs mode: ipvs

**Comment by schaze** [comment]
I ran into this as well, however I am not very happy with the draining script as I only require a solution for MetalLB, the rest of the cluster works just fine. I checked the code for the speakers and it seems that it is watching for node label changes and if detected updates the the BGP peer.
Maybe there could be simple script that just watches for node readiness status changes and applies a label with a timestamp value of the last ready=true status. This would be much more unintrusive.

**Comment by diddi-** [comment]
I'm running into this constantly when rebooting nodes or doing other maintenance that cause the BGP session to go down. Once the node is back and ready for action I have to wait an additional 15 minutes for the BGP session to establish. 

Is there no way to set a retry timer or similar to get it to connect quicker?

**Comment by rata** [comment]
Have you tried configuring the [hold time][link]? The min value allowed per RFC, IIRC, is 3s. My guess is that will do the trick


[link]: https://github.com/metallb/metallb/blob/57b9de6bcdb09528d175fe9eabef5daa5552876b/manifests/example-config.yaml#L21-L23

**Comment by emandret** [comment]
reopening for visibility - the issue still arises when a BGP session drops, the LB speaker will take up to 15 minutes to re-establish the session with the upstream peers.

**Comment by fedepaol** [comment]
> reopening for visibility - the issue still arises when a BGP session drops, the LB speaker will take up to 15 minutes to re-establish the session with the upstream peers.

Can you provide a bit more details? What implementation are you using? Can you share some logs with us?

**Comment by fedepaol** [comment]
Also, might be related to https://github.com/metallb/metallb/issues/2093
