### ISSUE TITLE
Fix release script for post-helm world.

### ISSUE THREAD

**Issue by danderson** [metallb/metallb#489]
After removing helm and adding kustomize, the release script is missing a couple of renaming points for version numbers:

- `manifests/metallb.yaml` needs to be updated (used to be done by updating helm chart and regenerating from there).
- Kustomize install options burn the version into a query parameter, which the regexes don't know to look for.

**Comment by russellb** [comment]
commit 9094482fa fixed the manifest version number update.

It doesn't look like anything fixes the version number in the kustomize install docs, though.

**Comment by rata** [comment]
@russellb thanks! I missed this issue and created another one for the second item: https://github.com/metallb/metallb/issues/594.

Will close that and just keep this
