### ISSUE TITLE
external peering with cisco doesnt work

### ISSUE THREAD

**Issue by ittrainingdotpro** [metallb/metallb#497]
When trying to peer with cisco router:
{"caller":"main.go:249","event":"endUpdate","msg":"end of service update","service":"default/my","ts":"2019-11-18T21:33:38.438194304Z"}
{"caller":"bgp.go:58","error":"read OPEN from \"10.8.2.1:179\": message length 29 too small to be OPEN","localASN":55000,"msg":"failed to connect to peer","op":"connect","peer":"10.8.2.1:179","peerASN":51000,"ts":"2019-11-18T21:34:49.306836819Z"}

on cisco end:
Nov 18 21:20:43.533: %BGP-5-ADJCHANGE: neighbor 10.8.2.102 Up
Nov 18 21:20:43.533: %BGP-5-ADJCHANGE: neighbor 10.8.2.102 Down BGP Notification sent
Nov 18 21:20:43.533: %BGP-3-NOTIFICATION: sent to neighbor 10.8.2.102 3/11 (invalid or corrupt AS path) 9 bytes 40020602 010000D6 D8
Nov 18 21:20:43.533: BGP: 10.8.2.102 Bad attributes FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0030 0200 0000 1440 0101 0240 0206 0201 0000 D6D8 4003 040A 0802 6620 0A08 FC00

**Comment by Zyt612** [comment]
what is your BGP config on Cisco and MetalLB side?

**Comment by aleksey005** [comment]
Not work to external access - another configuration (BGP router Mikrotik):

metallb version - main (from dockerhub tag)
Kubernetes version 1.16.3 (Rancher 2.3.3)

Mikrotik configuration:
`
/routing filter
add action=accept chain=AS54513-bgp-in prefix=195.209.176.128/27 prefix-length=32
add action=discard chain=AS54513-bgp-in
add action=accept chain=AS54513-bgp-out prefix=0.0.0.0/0
add action=discard chain=AS54513-bgp-out

/routing bgp peer
add default-originate=always in-filter=AS54513-bgp-in instance=mlb name=peer1 out-filter=AS54513-bgp-out remote-address=10.111.224.2 remote-as=64513 ttl=default update-source=vrrp1124
add default-originate=always in-filter=AS54513-bgp-in instance=mlb name=peer2 out-filter=AS54513-bgp-out remote-address=10.111.224.3 remote-as=64513 ttl=default update-source=vrrp1124
add default-originate=always in-filter=AS54513-bgp-in instance=mlb name=peer3 out-filter=AS54513-bgp-out remote-address=10.111.224.4 remote-as=64513 ttl=default update-source=vrrp1124
add default-originate=always in-filter=AS54513-bgp-in instance=mlb name=peer4 out-filter=AS54513-bgp-out remote-address=10.111.224.5 remote-as=64513 ttl=default update-source=vrrp1124

/routing bgp instance
add as=64512 client-to-client-reflection=no name=mlb out-filter=AS54513-bgp-out router-id=10.111.224.1

...
`
`
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb
  name: metallb-config
data:
  config: |
    peers:
    - peer-address: 10.111.224.1
      peer-asn: 64512
      my-asn: 64513
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 195.209.176.128/27
      avoid-buggy-ips: true
      bgp-advertisements:
      - aggregation-length: 32
`
curl from node work, ip addresses inject in routing table mikrotik, external request show in tcpdump in worker node, reply not show.

**Comment by johananl** [comment]
@ittrainingdotpro is this still relevant?

**Comment by russellb** [comment]
This issue looks stale.  If you need futher help, please try metallb-users or #metallb on slack.  https://metallb.universe.tf/community/
