### ISSUE TITLE
Update service after IP pool has been changed

### ISSUE THREAD

**Issue by bianchi2** [metallb/metallb#501]
Not sure if it's supposed to work like this... but what if I change the IP range in a configmap. Existing services are still bound to old IPs. Is metallb supposed to update them and reassign IPs from a new range?

Using the latest metallb version and Weave CNI.

**Comment by heimdull** [comment]
no, the service needs to request a new ip and this will happen when K8s reschedules the service next. So if you want your services to get the new ip range you need to bounce the service.

**Comment by stuartpb** [comment]
> So if you want your services to get the new ip range you need to bounce the service.

And how do you do that?

**Comment by johananl** [comment]
> > So if you want your services to get the new ip range you need to bounce the service.
> 
> And how do you do that?

AFAICT "bounce the service" means deleting the service and re-creating it (just the `Service` object, not the pods).

I'm closing this since looks like the original question has been answered.
