### ISSUE TITLE
externalTrafficPolicy does not preserve IP anymore (L2 mode)

### ISSUE THREAD

**Issue by remche** [metallb/metallb#504]
###      - The bug itself, as detailed as you can.

After upgrading some clusters to k8s 1.15.6, target pod cant see source IP anymore. LB service are configured with `externalTrafficPolicy: Local`.
Traffic effectively flows only to the local pod, but the ClientIP is the node one.

###      - Version of MetalLB

0.8.3

###      - Version of Kubernetes

1.15.6-rancher1-2

###      - Name and version of network addon (e.g. Calico, Weave...)

Flannel + Calico (Canal)

###      - Whether you've configured kube-proxy for iptables or ipvs mode
iptables mode.

I tracked rules for a LB service (public IP is hidden) :

```
# iptables-save |grep GS7VUV4NFC2NA6UK
:KUBE-FW-GS7VUV4NFC2NA6UK - [0:0]
:KUBE-SVC-GS7VUV4NFC2NA6UK - [0:0]
:KUBE-XLB-GS7VUV4NFC2NA6UK - [0:0]
-A KUBE-FW-GS7VUV4NFC2NA6UK -m comment --comment "traefik/traefik:webs loadbalancer IP" -j KUBE-XLB-GS7VUV4NFC2NA6UK
-A KUBE-FW-GS7VUV4NFC2NA6UK -m comment --comment "traefik/traefik:webs loadbalancer IP" -j KUBE-MARK-DROP
-A KUBE-NODEPORTS -p tcp -m comment --comment "traefik/traefik:webs" -m tcp --dport 31163 -j KUBE-XLB-GS7VUV4NFC2NA6UK
-A KUBE-SERVICES -d 10.43.238.216/32 -p tcp -m comment --comment "traefik/traefik:webs cluster IP" -m tcp --dport 443 -j KUBE-SVC-GS7VUV4NFC2NA6UK
-A KUBE-SERVICES -d xxx.xxx.xxx.xxx/32 -p tcp -m comment --comment "traefik/traefik:webs loadbalancer IP" -m tcp --dport 443 -j KUBE-FW-GS7VUV4NFC2NA6UK
-A KUBE-SVC-GS7VUV4NFC2NA6UK -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-7COCHRO3VKLLNBYW
-A KUBE-SVC-GS7VUV4NFC2NA6UK -j KUBE-SEP-YVVGR5GWIKLB47FM
-A KUBE-XLB-GS7VUV4NFC2NA6UK -m comment --comment "masquerade LOCAL traffic for traefik/traefik:webs LB IP" -m addrtype --src-type LOCAL -j KUBE-MARK-MASQ
-A KUBE-XLB-GS7VUV4NFC2NA6UK -m comment --comment "route LOCAL traffic for traefik/traefik:webs LB IP to service chain" -m addrtype --src-type LOCAL -j KUBE-SVC-GS7VUV4NFC2NA6UK
-A KUBE-XLB-GS7VUV4NFC2NA6UK -s 10.42.0.0/16 -m comment --comment "Redirect pods trying to reach external loadbalancer VIP to clusterIP" -j KUBE-SVC-GS7VUV4NFC2NA6UK
-A KUBE-XLB-GS7VUV4NFC2NA6UK -m comment --comment "Balancing rule 0 for traefik/traefik:webs" -j KUBE-SEP-YVVGR5GWIKLB47FM

# iptables-save |grep YVVGR5GWIKLB47FM
:KUBE-SEP-YVVGR5GWIKLB47FM - [0:0]
-A KUBE-SEP-YVVGR5GWIKLB47FM -s 10.42.2.98/32 -j KUBE-MARK-MASQ
-A KUBE-SEP-YVVGR5GWIKLB47FM -p tcp -m tcp -j DNAT --to-destination 10.42.2.98:443
-A KUBE-SVC-GS7VUV4NFC2NA6UK -j KUBE-SEP-YVVGR5GWIKLB47FM
-A KUBE-XLB-GS7VUV4NFC2NA6UK -m comment --comment "Balancing rule 0 for traefik/traefik:webs" -j KUBE-SEP-YVVGR5GWIKLB47FM
```
I'm not fluent with kube-proxy/iptables, but couldn't masquerade rule be the cause ?

**Comment by tommyknows** [comment]
I'm actually experiencing the same issue, and have partially resolved it by using `use-proxy-protocol: true` in the `nginx-ingress`.

My setup:
- MetalLB with layer-2 -> nginx-ingress -> application
- The applications did not find the actual source IP, but rather the node IP (or was it the virtual IP, not sure, long ago). That's why I enabled `use-proxy-protocol: true` in my nginx-ingress-config, which solved the source-IP issue. Now, however, I cannot redirect HTTP-requests, or use ACME-challenges with cert-manager, as these try to go through HTTP.

It seems like MetalLB does not add the PROXY-protocol to HTTP-requests, so nginx complains with 
```
broken header: "HEAD /.well-known/acme-challenge/au HTTP/1.1
Host: myhost.com
User-Agent: curl/7.64.1
Accept: */*

" while reading PROXY protocol, client: 192.168.254.134, server: 0.0.0.0:80
```

HTTPS works fine though, but now always when I need to create or renew certificates, I need to temporarily change the `use-proxy-protocol` in nginx, which is annoying.

**Comment by remche** [comment]
@tommyknows I'm not sure to understand, but I think it's not MetalLB job to deal with PROXY-protocol. MetalLB just deals with L2.
Did you configure you LB with `externalTrafficPolicy: Local` ?

**Comment by tommyknows** [comment]
I did, my nginx-ingress service has `externalTrafficPolicy: Local`. 
Doesn't Metallb use Haproxy, which in turn deals with the PROXY-protocol?

**Comment by remche** [comment]
MetalLB works at IP level, Haproxy at L4/L7.

**Comment by tommyknows** [comment]
Uhm yeah, you're right... 🤦‍♂ 
where the hell does the PROXY-information come from then 😅 

Anyway, so my workaround relies on behaviour that I do not understand, but:
i'm still seeing the same issue as you described, had it on Kubernetes 1.16 and 1.17. 

Let me know if I can be of any help.

**Comment by remche** [comment]
I had some issue with NetworkPolicie too (see https://github.com/rancher/rke/issues/1830).

The two issues might be linked, and in my case rebooting the nodes seems to fix the both. I'm pretty sure it's not a MetalLB issue, but an RKE or Calico one.

@tommyknows do you use RKE ? Calico ?

**Comment by tommyknows** [comment]
Neither - baremetal with kubeadm. CNI is kube-router, networkPolicies are enabled, though no policy is deployed (yet). Also tried disabling networkPolicies (kube-router calls it `firewall`), no change.

Logs from nginx-ingress (with disabled `use-proxy-protocol`):
```
192.168.1.82 - [192.168.1.82] - - [17/Dec/2019:17:01:38 +0000] "GET / HTTP/1.1" 308 177 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" 357 0.000 [emby-emby-80] [] - - - - 47a07251b0baf5de6e54c417cdb6e20e
127.0.0.1 - [127.0.0.1] - - [17/Dec/2019:17:01:38 +0000] "GET / HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" 187 0.001 [emby-emby-80] [] 192.168.254.220:8096 5 0.004 302 8b089b1fd72297747fd0645fd9763d15
127.0.0.1 - [127.0.0.1] - - [17/Dec/2019:17:01:38 +0000] "GET /web/index.html HTTP/2.0" 200 955 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" 21 0.002 [emby-emby-80] [] 192.168.254.220:8096 2541 0.004 200 7c20f6d19096890496a58d654aa274e3
```

`192.168.1.82` is my actual IP, after that, everything is `127.0.0.1`. And emby reports the localhost-IP too.

Reenabling PROXY-protocol though gives me this:
```
192.168.1.82 - [192.168.1.82] - - [17/Dec/2019:17:07:14 +0000] "GET / HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" 179 0.003 [emby-emby-80] [] 192.168.254.220:8096 5 0.000 302 301052a3464f3b7d9be49f6571148c84
192.168.1.82 - [192.168.1.82] - - [17/Dec/2019:17:07:14 +0000] "GET /web/index.html HTTP/2.0" 200 955 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" 20 0.002 [emby-emby-80] [] 192.168.254.220:8096 2541 0.004 200 be82332732ec0011b89d7651802866ca
```

Guess I have to figure out where this PROXY-protocol is coming from, or why enabling it fixes everything...

**Comment by iceman91176** [comment]
Same issue here - in L3 mode. Service is configured with externalTrafficPolicy: Local, but i see the Node-IP-Adress in my nginx-proxy. 
According to the documentation https://metallb.universe.tf/usage/#traffic-policies Local-Policy should avoid the issue of the Node-IP. Can't tell if it was broken by a K8S update, because we added Metallb only recently.

We are also using calico , but are using IPVS mode.

ipvsadm output for a service-ip

```
TCP  <HIDDEN>:80 rr
  -> 10.113.20.1:80               Masq    1      0          0
```

I don't know if we are having a metallb issue here, or a k8s - issue ?

**Comment by iceman91176** [comment]
We got it working ;-)
In our Service-Spec we had both loadBalancerIP AND externalIPs set to the loadbalanced-ip. The latter one was a remainder of TungstenFabric-SDN.

So it looked like this 

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.20.0
    component: controller
    heritage: Tiller
    release: ngix-ingress-public
  name: ngix-ingress-public-nginx-ingress-controller
  namespace: infra-public
spec:
  clusterIP: 10.127.40.106
  externalIPs:
  - HIDDEN
  externalTrafficPolicy: Local
  healthCheckNodePort: 15217
  loadBalancerIP: HIDDEN-BUT-IDENTICAL-TO-externalIPs
  ....
```

According to https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/ as soon as you have "Service External IP + port" it masqurades.  But with loadbalancerIP PLUS externalTrafficPolicy=local traffic is just accepted.

So we removed the externalIPs-configuration from the service-manifest, and immediately the real-client IP shows up.

@remche check if you also have a similar-configuration

**Comment by remche** [comment]
@iceman91176 we dont use Tungsten neither have externalIPs field... I'm pretty sure it's not a MetalLB issue though.

**Comment by rata** [comment]
@remche @iceman91176 Is it safe to close this issue, then? :)

**Comment by remche** [comment]
@rata I'm pretty sure it's not a metallb issue, it's safe to close for me.

**Comment by rata** [comment]
Thanks, closing then :)

**Comment by Shuliyey** [comment]
> 
> 
> Neither - baremetal with kubeadm. CNI is kube-router, networkPolicies are enabled, though no policy is deployed (yet). Also tried disabling networkPolicies (kube-router calls it `firewall`), no change.
> 
> Logs from nginx-ingress (with disabled `use-proxy-protocol`):
> 
> ```
> 192.168.1.82 - [192.168.1.82] - - [17/Dec/2019:17:01:38 +0000] "GET / HTTP/1.1" 308 177 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" 357 0.000 [emby-emby-80] [] - - - - 47a07251b0baf5de6e54c417cdb6e20e
> 127.0.0.1 - [127.0.0.1] - - [17/Dec/2019:17:01:38 +0000] "GET / HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" 187 0.001 [emby-emby-80] [] 192.168.254.220:8096 5 0.004 302 8b089b1fd72297747fd0645fd9763d15
> 127.0.0.1 - [127.0.0.1] - - [17/Dec/2019:17:01:38 +0000] "GET /web/index.html HTTP/2.0" 200 955 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" 21 0.002 [emby-emby-80] [] 192.168.254.220:8096 2541 0.004 200 7c20f6d19096890496a58d654aa274e3
> ```
> 
> `192.168.1.82` is my actual IP, after that, everything is `127.0.0.1`. And emby reports the localhost-IP too.
> 
> Update: using the LoadBalancer directly (without the ingress in between) works fine.
> Must be the nginx-ingress then, not MetalLB 🙂
> thanks for your help!
> 
> Reenabling PROXY-protocol though gives me this:
> 
> ```
> 192.168.1.82 - [192.168.1.82] - - [17/Dec/2019:17:07:14 +0000] "GET / HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" 179 0.003 [emby-emby-80] [] 192.168.254.220:8096 5 0.000 302 301052a3464f3b7d9be49f6571148c84
> 192.168.1.82 - [192.168.1.82] - - [17/Dec/2019:17:07:14 +0000] "GET /web/index.html HTTP/2.0" 200 955 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" 20 0.002 [emby-emby-80] [] 192.168.254.220:8096 2541 0.004 200 be82332732ec0011b89d7651802866ca
> ```
> 
> Guess I have to figure out where this PROXY-protocol is coming from, or why enabling it fixes everything...

Hi @tommyknows, when i use metallb + nginx-ingress, and set the `use-proxy-protocol: true` in `nginx-configuration` `ConfigMap`

I get broken header error in the `nginx-controller` pod

```
I0811 12:24:42.186053       6 event.go:209] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"ingress-nginx", Name:"nginx-configuration", UID:"68cf23a2-b10c-4c16-9c86-d8d9d2a0204a", APIVersion:"v1", ResourceVersion:"177414", FieldPath:""}): type: 'Normal' reason: 'UPDATE' ConfigMap ingress-nginx/nginx-configuration
I0811 12:24:42.293380       6 controller.go:170] Configuration changes detected, backend reload required.
I0811 12:24:42.748936       6 controller.go:188] Backend successfully reloaded.
[11/Aug/2020:12:24:42 +0000]TCP200000.003
2020/08/11 12:24:54 [error] 480#480: *559933 broken header: "N	�̉e_&��v��}�w
                                                                            ��0�G��ik�! Bݓ�L���2F�̍$|��!�+j�=.2�J�"jj�+�/�,�0̨̩����/" while reading PROXY protocol, client: 10.1.31.1, server: 0.0.0.0:443
2020/08/11 12:24:54 [error] 481#481: *559934 broken header: "_�]�������G6��1����jO����p�- Bݓ�L���2F�̍$|��!�+j�=.2�J�"**�+�/�,�0̨̩����/" while reading PROXY protocol, client: 10.1.31.1, server: 0.0.0.0:443
2020/08/11 12:24:54 [error] 483#483: *559935 broken header: "x�a?5""������Ǩ�F"p��:I���1 Bݓ�L���2F�̍$|��!�+j�=.2�J�"zz�+�/�,�0̨̩����/" while reading PROXY protocol, client: 10.1.31.1, server: 0.0.0.0:443
2020/08/11 12:24:54 [error] 480#480: *559938 broken header: "��e�Wy����i������>o���(��Ւ Bݓ�L���2F�̍$|��!�+j�=.2�J�"���+�/�,�0̨̩����/" while reading PROXY protocol, client: 10.1.31.1, server: 0.0.0.0:443
2020/08/11 12:24:54 [error] 481#481: *559939 broken header: "e�ڎWe�J��X&
                                                                        ��N�ƍ[9y�Z7�N�Lr Bݓ�L���2F�̍$|��!�+j�=.2�J�"���+�/�,�0̨̩����/" while reading PROXY protocol, client: 10.1.31.1, server: 0.0.0.0:443
2020/08/11 12:24:59 [error] 482#482: *560002 broken header: "���{:C*�Z��������j�U\^Mc�g}χ Bݓ�L���2F�̍$|��!�+j�=.2�J�"���+�/�,�0̨̩����/" while reading PROXY protocol, client: 10.1.31.1, server: 0.0.0.0:443
2020/08/11 12:24:59 [error] 482#482: *560003 broken header: "ne�ا�if��fh�&̱�͆�(C�ճ Bݓ�L���2F�̍$|��!�+j�=.2�J�"���+�/�,�0̨̩����/" while reading PROXY protocol, client: 10.1.31.1, server: 0.0.0.0:443
```

below logs in your comment
```
192.168.1.82 - [192.168.1.82] - - [17/Dec/2019:17:07:14 +0000] "GET / HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" 179 0.003 [emby-emby-80] [] 192.168.254.220:8096 5 0.000 302 301052a3464f3b7d9be49f6571148c84
192.168.1.82 - [192.168.1.82] - - [17/Dec/2019:17:07:14 +0000] "GET /web/index.html HTTP/2.0" 200 955 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" 20 0.002 [emby-emby-80] [] 192.168.254.220:8096 2541 0.004 200 be82332732ec0011b89d7651802866ca
```

where is coming from, is it from your application pod, or `nginx-controller` pod

**Comment by tommyknows** [comment]
I'm sorry, I never got around solving this issue actually. I worked around it by removing `--enable-ssl-passthrough`, which in turn made it possible to remove the PROXY protocol support for me.

**Comment by zwiy** [comment]
It's maybe related to this Canal (cni plugin) issue: https://www.suse.com/support/kb/doc/?id=000020231.
Client source IP in the 192.168.0.0/16 range and RKE cluster with canal cni plugin -> source-ip not visible.
It helped me to solve this issue.

(Workaround/Solution from linked issue above)
> In order to workaround the issue in existing clusters, the Calico ippool configuration can be edited to disable outgoing nat, which removes programming of the cali-nat-outgoing iptables rules. To implement this workaround run kubectl against the affected to edit the default-ipv4-ippool object: kubectl edit ippools default-ipv4-ippool. Edit the line natOutgoing: true to set natOutgoing: false and save the change. Calico will detect the configuration update and remove the cali-nat-outgoing iptables rules.
