### ISSUE TITLE
Can MetalLB work with a static pool of available IPs ? 

### ISSUE THREAD

**Issue by Inv0k-er** [metallb/metallb#510]
I have a static pool Ip address and I want to configure Metallb on Layer 2 mode. I know Metallb can work with DHCP pool Ip address but I can not find, Can it Metallb work with static pool of available IP's ?     It is a possible ? 
And How to need configure (I mean, configmap, services) ? Can you give me examle ?

**Comment by heimdull** [comment]
This is explained very well on this page: https://metallb.universe.tf/usage/

We have one default pool of ips and then the services that needs an external ip is set in the Service as:

apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
  - port: 80
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 1.1.1.1

This ip needs the be in "a" pool thats set in your config

config:
- name: default
  protocol: layer2
  addresses:
  - 1.1.1.1-1.1.1.2

**Comment by Inv0k-er** [comment]
> 
> 
> This is explained very well on this page: https://metallb.universe.tf/usage/
> 
> We have one default pool of ips and then the services that needs an external ip is set in the Service as:
> 
> apiVersion: v1
> kind: Service
> metadata:
> name: service
> spec:
> ports:
> 
>     * port: 80
>       type: LoadBalancer
>       externalTrafficPolicy: Cluster
>       loadBalancerIP: 1.1.1.1
> 
> 
> This ip needs the be in "a" pool thats set in your config
> 
> config:
> 
>     * name: default
>       protocol: layer2
>       addresses:
>       
>       * 1.1.1.1-1.1.1.2

Thank you I understand this. I think need to add to guide.
Happy New Year.

**Comment by johananl** [comment]
Assuming the question was "how to to request a specific IP address for a service", as said above it's [explained](https://metallb.universe.tf/usage/#requesting-specific-ips) in the docs.

I'm closing this. In case I've misunderstood the question, please re-open and provide a clear description of the problem/request.
