### ISSUE TITLE
After installed, the kubentes machine can't access the internet.

### ISSUE THREAD

**Issue by tiandong19860806** [metallb/metallb#512]
Is this a bug report or a feature request?:

# What happened:
After install metallb, my kubernetes machine can't access internet now.
_**even though I drop all pod/service/deployment/namespaces from ns=metallb-system,**_
And restart all my kubernetes machine, these kubernetes machine also can't access internet.

# What you expected to happen:
Let my kubernetes machine return normal, can access internet.

# How to reproduce it (as minimally and precisely as possible):
step 1: install metallb.yaml
root >> kubectl apply -f \
https://raw.githubusercontent.com/danderson/metallb/main/manifests/metallb.yaml
![01_install_metal](https://user-images.githubusercontent.com/12596666/71427671-00799600-26f6-11ea-8e44-f11d54aa24f0.jpg)

step 2: install configmap
* 02_metal_configmap.yaml as below attachment.
root >> kubectl apply -f {02_metal_configmap.yaml}
[02_metal_configmap.yaml.txt](https://github.com/danderson/metallb/files/3999299/02_metal_configmap.yaml.txt)
* execute result as below:
![03](https://user-images.githubusercontent.com/12596666/71427734-94e3f880-26f6-11ea-95a2-a3cb86534e1d.jpg)

step 3: check the pod log is normal
root >> kubectl logs -f controller-5f898b44f4-4pkk6 -n metallb-system
![4](https://user-images.githubusercontent.com/12596666/71427747-c066e300-26f6-11ea-8f9d-74ea2fb2950a.jpg)

step 4: check the kubernetes machine begin change that can't access internet.
![图片](https://user-images.githubusercontent.com/12596666/71427787-20f62000-26f7-11ea-8944-fcae5b8d0b11.png)

# Anything else we need to know?:
Environment:
    MetalLB version: image: metallb/speaker:main
    Kubernetes version: v1.14.1
    BGP router type/version: bgp
    OS (e.g. from /etc/os-release):  CentOS Linux 7 (Core)
    Kernel (e.g. uname -a): Linux CNT7XDCK11D02 4.4.190-1.el7.elrepo.x86_64 #1 SMP Sun Aug 25 07:32:44 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
    kubernetes machine ip : 192.168.3.96 / 97 / 98 (3 master + 3 slave + flannel)
    kubernetes service ip : SERVICE_CLUSTER_IP_RANGE="10.3.0.0/16"
    kubernetes pod ip :  podCIDR: "172.16.0.0/16"

**Comment by tiandong19860806** [comment]
Hi @danderson ,

     Could you give me a suggest about these kubernetes machine restore access internet.
And check whether my install configmap yaml file has error settings (then I retry to install metal again).

Thanks.

**Comment by tiandong19860806** [comment]
I had resolve my kubernetes machine issue, as below( clear matallb-system namespace at first)

Hi @grssam ,
    How about the progress of your issue. I also happen the similar issue.
Just know the component assign a used ip that it had been assigned to physical machine or router.
When I delete the error ip owner (which has same value at external-ip), these all kubernetes machine return normal, can access internet now.

look below check result and operation.
step 1: query the error repeate ip , and remove its owner service.
![图片](https://user-images.githubusercontent.com/12596666/71430959-d4681000-2709-11ea-8e8e-ed93932af051.png)

step 2: retry to check the kubernetes machine to access internet, it's OK.
![图片](https://user-images.githubusercontent.com/12596666/71430994-05484500-270a-11ea-9484-6a9a0f7ee3ae.png)

**Comment by russellb** [comment]
This issue is now pretty old, so I'm guessing you've moved on from this.  If you're still looking for support, please try the metallb-users mailing list or #metallb on kubernetes slack
