### ISSUE TITLE
Is IPVS on metallb stable?

### ISSUE THREAD

**Issue by fabioyy** [metallb/metallb#513]
Hi
Is IPVS on metalb stable?

I'm running metallb using Nat mode on 36 servers,(we managed to reach 20k request/s without problem ). but we are having problem with some kube-proxy/iptables rules opening some pod ports to the external world.

**Comment by russellb** [comment]
If you're still looking for help, I'd encourage you to try #metallb on kubernetes slack or the metallb-users mailing list
