### ISSUE TITLE
Future Release Schedule

### ISSUE THREAD

**Issue by kthurs** [metallb/metallb#515]
Is 0.8.3 the latest version of MetalLB with a release date of 10/30/2019?  Does MetalLB happen to have a release schedule that they follow? I see dates for old releases but don't see anything about following a certain schedule for future releases. If anyone has anything to provide that would be great.

**Comment by rata** [comment]
A new release has just happened! We don't have a release schedule yet, but will try to update if we define one :)

**Comment by russellb** [comment]
It looks like this question was answered.

Releases are tracked as milestones: https://github.com/metallb/metallb/milestones

If there's a schedule set, I expect we would add the dates to the milestones.  Right now the maintainers are discussing releases as feature-based and not time-based.
