### ISSUE TITLE
Why Helm no longer officially supported?

### ISSUE THREAD

**Issue by theothermike** [metallb/metallb#523]
I saw in the 0.8.2 release notes that
 "The MetalLB Helm chart in the official helm repository is no longer a supported installation method."

What does this mean?  no more helm support at all?  or moving to a new chart repo?

**Comment by huydinhtiki** [comment]
This project is lacking of manpower :D Create PR to keep it alive.
>The majority of code changes, as well as the overall direction of the project, is a personal endeavor of one person, working on MetalLB in their spare time as motivation allows.

**Comment by theothermike** [comment]
Well so far the Helm chart has been working great for us!  I'll be sure to send PRs if necessary!

**Comment by holmesb** [comment]
Yes helm is the defacto standard package manager in Kubernetes.  Kustomize is something else to learn.  Installing across multiple clusters using manifests doesn't scale well.  Would be great if we can keep the chart alive with PRs without @danderson having to contribute, but kind of relies on him reviewing them, at least initially.  Latest version chart supports is increasingly jurassic (v0.8.1 - latest is v0.9.3).

**Comment by nicklasfrahm** [comment]
Helm is the standard way of installing most packages on Kubernetes. I would like to take on the challenge of adding official support for Helm again by moving the Helm chart to this repository and making it Helm 3 compatible. Can we reopen this?

**Comment by nicklasfrahm** [comment]
I can create a PR to document the Bitnami helm chart: bitnami/charts/pull/2068
