### ISSUE TITLE
Allow allow-shared-ip to be set globally

### ISSUE THREAD

**Issue by schemen** [metallb/metallb#525]
Hi!

I followed https://github.com/metallb/metallb/issues/121 and would love to see the ability to set this option globally!

My use-case specifically is that in L2 mode, my cluster is entirely in a private network and has a single IP from said private network it uses for services. On the firewall, a destination NAT is created to map to that VIP.

I surely can attach that label to all services but setting it globally would reduce human error significantly :) 

Cheers!

**Comment by fedepaol** [comment]
And, feel free to reopen if there's a strong use case.
