### ISSUE TITLE
关于Metallb设置的LB局域网无法访问的问题

### ISSUE THREAD

**Issue by zhangq123456** [metallb/metallb#526]
环境说明：
kubernetes：1.14版本
Metallb：0.8.2版本
metallb-controll：0.8.2版本
我创建的应用nginx ，在k8s节点上可以访问，但是在同网段的其他服务器上无法访问。

这个是什么原因呢。

**Comment by sunney2010** [comment]
我用 docker for mac 在K8S也是无法访问的，是不是与mac的通信机制有关系呢？

**Comment by russellb** [comment]
Using google translate ...

Title:  About the problem that the LB LAN set by Metallb cannot be accessed #526

---------------

Environmental description:
kubernetes: version 1.14
Metallb: version 0.8.2
metallb-controll: version 0.8.2
The application nginx I created is accessible on the k8s node, but cannot be accessed on other servers in the same network segment.

What is the reason for this?

---------

I use docker for mac and it is not accessible on K8S. Is it related to the communication mechanism of mac?

**Comment by russellb** [comment]
For help, please try Slack of the metallb mailing list.  Thank you!

https://metallb.universe.tf/community/
