### ISSUE TITLE
on a node with 2 active network interfaces, both MAC addresses are sent on ARP query

### ISSUE THREAD

**Issue by admun** [metallb/metallb#531]
I am running a 3 node clusters at home, each host is a CS24-SC which has 2 NIC. Both NIC is up and active on the same subnet. One of the IPs on the host is used by k8s

env: 
- rancher 3.3.5
- 1.17.2 (RKE) with canel
- kube-proxy is in iptables mode

When arping for a LB IP, I am seeing both MAC addresses, while only one IP is used by k8s. Client often resulted in host unreachable/timeout when using the MAC for the unused IP.

```
arping -c 2 -I eth0 192.168.0.80
ARPING 192.168.0.80
60 bytes from 00:23:8b:bd:87:ec (192.168.0.80): index=0 time=4.036 msec
60 bytes from 00:23:8b:bd:87:eb (192.168.0.80): index=1 time=5.978 msec
60 bytes from 00:23:8b:bd:87:eb (192.168.0.80): index=2 time=3.042 msec
60 bytes from 00:23:8b:bd:87:ec (192.168.0.80): index=3 time=4.838 msec
```

I think this might be the same as https://github.com/metallb/metallb/issues/277, but I think in this case the issue materialized as a bug, rather than an enhancement.

**Comment by admun** [comment]
Note, I work around the issue by disable the unused network interface.

**Comment by rata** [comment]
> Both NIC is up and active on the same subnet

What do you mean with this, exactly? What is the output of `ip a` and `ip r`?

Why do you have two nics on the same subnet? Just to understand your setup.

Also, just to be clear, what problem do you see if you connect to the IP assigned by metalLB to the service? Do you see any hiccups or something? If you do, can you paste the command you are using and the output?

**Comment by admun** [comment]
> Why do you have two nics on the same subnet? Just to understand your setup.
>
 It was not thought out thoroughly, I was thinking to bind different pod to different interface. But at the end, it doesn't work that way on k8s. I left it there but it caused issue to metallb.

The problem I am seeing is connections to load balancer time out from outside of the cluster nodes, and sometimes it will work a bit, then failed again.

enp8s0 is now disabled:

ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:23:8b:17:87:07 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.73/24 brd 192.168.0.255 scope global noprefixroute dynamic enp0s25
       valid_lft 67872sec preferred_lft 67872sec
    inet6 fe80::223:8bff:fe17:8707/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: enp8s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:23:8b:17:87:08 brd ff:ff:ff:ff:ff:ff
...
...

**Comment by rata** [comment]
IIUC, your network setup was broken, is that what you are saying? And did you forgot to send the `ip r` output? :)

In any case, using only one network interface per subnet I guess it works fine when you connect to the service external IP, right? Can you confirm this?

**Comment by liuyuan10** [comment]
This is working as expected. You can both interface on the same subnet so both of them will be able to see the ARP request for the IP. So there is a ARP response from each interface. As you said, an enhancement is to configure metallb on what interface to use

**Comment by admun** [comment]
@rata, sorry for missing `ip r` command result. I no longer have the 2nd interface enabled, so that command will not yield useful info. I do not think having 2 NIC on the same network is a broken setup; If i am running services on the bare metal host, I could have 2 httpd running on the same host, with each instance listen on one network interface.

Meanwhile, this sounds like the same problem I am seeing https://github.com/metallb/metallb/issues/597

**Comment by rata** [comment]
@admun well, it really depends on the routing. I think in most setups that won't work, as you have a src IP to use for a subnet, that will be on only one of the interfaces and therefore the request will arrive via one NIC and the reply might go via the other one. If you are not using bond, etc. I think it won't work as expected, unless you are using a very specific configuration (that is why I was asking for `ip r`).

That issue is different in that the NICs are on different subnet. I think here, as @liuyuan10 was saying, it is working as expected.

Am I missing something? Is something that you think it should work and is not working? Like, connectivity to the service external IP?

**Comment by dansomething** [comment]
I'm having a similar problem to this where multiple interfaces are active, but only one has an address assigned yet two mac addresses are being reported by ARP. Has anybody else seen this? What's the expected behavior for this scenario?

**Comment by fedepaol** [comment]
Hi @dansomething , we are going to support this scenario in th next release. See https://github.com/metallb/metallb/pull/1347

**Comment by dansomething** [comment]
@fedepaol I'll take a look. Thanks for the quick response!
