### ISSUE TITLE
[Feature request] Allow override BGP.next_hop in L3 mode

### ISSUE THREAD

**Issue by Dragonn** [metallb/metallb#532]
It would be very useful for me to have a way to override next_hop address in propagated routes via BGP as a way to solve coexistence with Calico BGP peering. As the best way to use this would be with environment variable.

I am currently using Kubernetes with Calico v3.10 in IPIP mode with meshed BGP and I want to remove NAT for outgoing connections. Because of that I need to peer Calico with infrastructure (doing it via iBGP with BIRD router) and this unfortunately colides with MetalLB deployed with `hostNetwork: true`.

Therefore I tried to remove outgoing NAT from Calico configuration and peer MetalLB speaker with BIRD directly (removed `hostNetwork: true` from DaemonSet specification) but routes exported by MetalLB contain next_hop self (inner pod IP address) but I need to have hostIP address here.

From BIRD's perspective I am not able to distinguish multiple speaker pods from each other and cannot overwrite next-hop on this side.

I hoped that environment variable `METALLB_HOST` will do the trick, but unfortunately it serves another purpose.

**Comment by balboah** [comment]
I'm also looking for this option as my nodes have internal IPs, when peering with an external peer they try to set next hop to the private IP that the other network doesn't know about. Currently using Calico but might be using metallb instead for external traffic

**Comment by Jean-Daniel** [comment]
> Not sure if this was exactly the same issue but I'm also looking for the `next_hop` option that my peers announces. As my nodes have internal IPs, when peering with an external peer they try to set next hop to the private IP that the other network doesn't know about.

I have the same issue, but I'm not using any other BGP component on my machine (using cilium with L2 routing between nodes).
