### ISSUE TITLE
MetalLB Slow to Route Packets to Pod Node

### ISSUE THREAD

**Issue by davesargrad** [metallb/metallb#539]
I configure a simple RESTful micro-service on a small k8s bare metal cluster.

The pod container listens on port 8080. 
I expose this pod with a LoadBalancer.

MetalLB is properly installed.
![image](https://user-images.githubusercontent.com/48793689/76422445-97f89780-637b-11ea-8266-4ee17186ddcf.png)

I am using the example configuration.
![image](https://user-images.githubusercontent.com/48793689/76422499-b068b200-637b-11ea-95e2-525005ed03cb.png)

My service has EXTERNAL-IP 192.168.1.241
![image](https://user-images.githubusercontent.com/48793689/76422550-c4141880-637b-11ea-9fb6-6a56a10832b9.png)

In the following we see that a curl to the EXTERNAL-IP works, yet sometimes it takes just over a minute to respond properly.

![image](https://user-images.githubusercontent.com/48793689/76422708-0ccbd180-637c-11ea-919b-08335facba06.png)

Here we see that the return from **kubia-unhealthy-thtds** took 1 minute and 3 seconds to return.

The pod log in /var/log/pods/ (on the node that responds) is in line with the timing illustrated above

![image](https://user-images.githubusercontent.com/48793689/76423504-4c46ed80-637d-11ea-927c-8ceeafc4d8f6.png)

Note, **thtds** is on my other node (spain). whereas **r5kb1** is on the local node (tonga).
![image](https://user-images.githubusercontent.com/48793689/76422786-2bca6380-637c-11ea-84c3-e26a42b8d572.png)

![image](https://user-images.githubusercontent.com/48793689/76422854-43a1e780-637c-11ea-99a0-2924ff829570.png)

I've found that whichever node the curl is running on, (spain or tonga), the response from the pod on that node is fast. However when the request is load balanced to the other node, it seems that it takes a minute for the request to arrive at the pod.

I just ran another experiment. Here I am monitoring the traffic to the POD IP. Its clear from tcpdump that the traffic is delayed by a minute. Furthermore there are several SYN packets that lead up to that. 

![image](https://user-images.githubusercontent.com/48793689/76456512-7ca68000-63ad-11ea-9c64-4f1573a06dd4.png)

Its interesting to see that the SYN packets that lead up to the successful request have increasing time delays (in seconds): 1, 2, 4, 8, 16, 32. Then we see the successful response

**Version of MetalLB**
0.8.3
**Version of Kubernetes**
1.17
**Name and version of network addon (e.g. Calico, Weave...)**
Flannel 0.11
**Whether you've configured kube-proxy for iptables or ipvs mode**
iptables (I think)

**Comment by davesargrad** [comment]
The Limitations described [here](https://metallb.universe.tf/concepts/layer2/), highlight that Layer 2 behaves like a Failover. They also suggest that the failover should not take more than 10 seconds, and if failover seems to then "file a bug". 

Every request that is being routed to the other node is taking 60 seconds.. This is significant.

**Comment by davesargrad** [comment]
I see the same behaviour whether I use the BGP configuration or the L2 configuration. In both cases, I've used the sample configurations provided on the MetalLB web site. 

I thought the sample for the L2 should simply work, since I dont think the IP address 192.168.1.240 to 192.168.1.249 needed to map to any interface already on my system. 

I think the addresses in the BGP configuration need to map to external network resources.

Now that I see the same behaviour, I wonder if its my MetalLB configuration that needs to be tweaked.

Would you expect the [sample L2 configuration](https://metallb.universe.tf/configuration/#layer-2-configuration) to work for me, as is?

**Comment by champtar** [comment]
Hi @davesargrad 
MetalLB is only configuring K8S and responding to ARP, Kubernetes / Flannel / Kubeproxy is responsible for the datapath.
What happens if you use the ClusterIP (10.96.143.84) instead of the LoadBalancerIP ?

**Comment by davesargrad** [comment]
Hi @champtar 

You are right! I just verified I have the same problem when accessing the service via its ClusterIP.

![image](https://user-images.githubusercontent.com/48793689/76564487-f8bcc880-647e-11ea-928c-ee9002235793.png)

Thanks for your fast response.

**Comment by champtar** [comment]
Can you close this issue, open a new one in k8s repo, and add the link here so we know what was the cause ? Thanks

**Comment by davesargrad** [comment]
Sure thing
