### ISSUE TITLE
docker for mac. K8S EXTERNAL-IP cannot be accessed

### ISSUE THREAD

**Issue by sunney2010** [metallb/metallb#541]
- The bug itself, as detailed as you can.
- version of docker desktop v2.2.0.3
 - Version of MetalLB  v0.8.3
 - Version of Kubernetes  1.15.5
 - canal
 docker for mac. K8S EXTERNAL-IP cannot be accessed

**Comment by rata** [comment]
Sorry, can you please write as detailed as you can? Also, I don't have mac, so really really including as much detail as possible is very helpful.

**Comment by rata** [comment]
Friendly ping?

**Comment by rata** [comment]
I assume this is a question on how to run with docker for mac that is running Kubernetes in some way (not sure which). Please go to slack for this questions, if we make it work we can document it in the website later :)
