### ISSUE TITLE
Incorporate upstream fix for infiniband devices.

### ISSUE THREAD

**Issue by jcatana** [metallb/metallb#547]
Hello. I'm running metallb on an on-prem HPC cluster utilizing an infiniband network and IPoIB (IP over Infiniband).

I found an issue with how packets are being checked and differences between the Ethernet and Infiniband networks. It was fixed upstream in mdlayher/arp. Can you please incorporate these fixes into your package? 

https://github.com/mdlayher/arp/issues/18
https://github.com/mdlayher/arp/pull/22

**Comment by champtar** [comment]
@jcatana do you think you can make a PR ?

**Comment by rata** [comment]
@jcatana can you check if the PR linked here solves the issue for you, please? :)

**Comment by jcatana** [comment]
It fixes the issue. I did not test against that specific PR, but applied the change from that PR to the v0.9.5 release and compiled and tested it.
