### ISSUE TITLE
Description of secret creation is not correct.

### ISSUE THREAD

**Issue by olegmayko** [metallb/metallb#550]
Hi, I've noticed minor issue that the description of [secret creation](https://github.com/metallb/metallb/blame/main/website/content/installation/_index.md#L50) is not correct. It generates secret with '-' at least on mac.
Maybe it can be replaced with something more universal 
`openssl rand -base64 128 | xargs -0 -I {} kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="{}"`

**Comment by champtar** [comment]
Woops ...
Can you try: `kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"`

**Comment by olegmayko** [comment]
yes, this works as well.

**Comment by champtar** [comment]
Do you want to send a PR or should I ?

**Comment by olegmayko** [comment]
yes, I can create PR.

**Comment by rata** [comment]
Fixed in the merged PR, closing :)
