### ISSUE TITLE
Make dev environment work

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#552]
Running `inv dev-env` doesn't seem to work on current `main` (e82a77d4). A couple of recent changes seem to have broken the dev environment:

- In 514091a2 the k8s namespace resource got moved to a kustomization and is no longer created in `manifests/metallb.yaml`.
- In #527, HashiCorp memberlist support was added, which requires a secret to be present in the `metallb-system` namespace in order for speakers to converge successfully.

In addition, looks like the environment assumes the developer uses kind `v0.5.1` or earlier, which is a pre-release. The latest kind version at time of writing is `v0.7.0`. Among other improvements, this version simplifies kubeconfig handling, which allows us to remove some code from `tasks.py`. We may want to update the environment to use the latest kind.

I'll open a PR to handle the above.

**Comment by rata** [comment]
Thanks! :)

**Comment by johananl** [comment]
https://github.com/metallb/metallb/pull/553 open.

I guess we aren't running `inv dev-env` in the CI, right? Maybe we should to avoid this kind of breaks in the future.

**Comment by danderson** [comment]
`inv dev-env` requires an environment that can run Docker, which is rare in CIs. I think currently on CircleCI we run in containers, so docker-in-docker doesn't work. I think CircleCI supports VMs for free, but it'll make all CI much slower.

Sounds like a good idea to test this, I'm just not sure how to do it well.
