### ISSUE TITLE
Update website to work with new hugo versions (>= 0.67.1)

### ISSUE THREAD

**Issue by rata** [metallb/metallb#554]
When trying to run `hugo serve` with hugo `0.67.1` (also tested `0.68.1` released 12hs ago) it fails with:

```
metallb/website/content/_header.md:1:1": plain HTML documents not supported
```

This error message seems to be introduced here (from a quick google search): https://github.com/gohugoio/hugo/pull/7034

Using older hugo versions build the site but, after a binary search, only up to hugo version 0.62.2 showes the header correctly.

PS: I've checked and it seems no security release was made for hugo, so I guess it is not risky to point it out here (also, site is static, as long as we review PRs to the website, it seems okay :))

**Comment by russellb** [comment]
I fixed this in #822
