### ISSUE TITLE
docs: Layer 2 explanation can be expanded with recent changes

### ISSUE THREAD

**Issue by rata** [metallb/metallb#556]
https://metallb.universe.tf/concepts/layer2/ says:

> MetalLB on the other hand relies on Kubernetes to know when pods and nodes go up and down. It doesn’t need to speak a separate protocol to select leaders, instead it just lets Kubernetes do most of the work of deciding which pods are healthy, and which nodes are ready.

v0.9.0 was released with improvements to that. Maybe those can be reflected on the documentation as well?

**Comment by russellb** [comment]
I think I did this as part of https://github.com/metallb/metallb/pull/602.  I didn't reference this issue because I hadn't seen it.  I'm going to close this out, but @rata let me know if you had more info in mind for this one.

**Comment by rata** [comment]
Perfect, thanks!
