### ISSUE TITLE
Speakers do not respond to ARP requests in L2 mode

### ISSUE THREAD

**Issue by cmcarey** [metallb/metallb#560]
I appreciate that troubleshooting specific system configurations is something that belongs in the #metallb slack channel rather than here, however I have found no assistance for a few days there, so as a last resort I must ask here.  I would appreciate even tips on where to look to debug this myself.

Each node in my cluster has an ethernet interface and an address in 10.0.0.0/24, with netmask /16.  Pod CIDR is 10.30.0.0/16, and cluster networking uses Calico.  MetalLB is configured in L2 mode with address pool 10.0.1.1-10.0.1.254.

I have an ingress-nginx service of type LoadBalancer.  MetalLB correctly assigns the IP 10.0.1.1 to it.  When I run `arping` from another device in the network, I see no arp response packets, though I have confirmed every node _does_ receive the arp request packet.  I see nothing indicative in the controller/speaker logs, aside from it confirming that the arp responder was successfully created for the correct interfaces.

I am running MetalLB v0.9.3.  My K8s cluster is on v1.18.0.  The cluster was built using kubeadm, which from what I can tell runs kube-proxy in iptables mode.  Each cluster node is Ubuntu 18.04 LTS.

Again I appreciate this is not the correct avenue for asking for help with this, so I mainly ask the places I should look to figure out what is going wrong - perhaps some checklist could be added to the troubleshooting page on the website.

**Comment by champtar** [comment]
Hi @cmcarey 
Can you "describe" the LoadBalancer object, to confirm on which node it's attributed.
Then please run both tcpdump, to confirm the arp request comes in, and strace the metallb speaker process to see if anything is happening. Maybe you have some firewalling blocking the packets ?

**Comment by cmcarey** [comment]
Thanks for the prompt response @champtar !
Here is the result of `kubectl -n ingress-nginx describe svc ingress-nginx-internal`:

```
Name:                     ingress-nginx-internal
Namespace:                ingress-nginx
Labels:                   app.kubernetes.io/name=ingress-nginx-internal
Annotations:              kubectl.kubernetes.io/last-applied-configuration:
                            {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"ingress-nginx-internal"},"name":"ingr...
Selector:                 app.kubernetes.io/name=ingress-nginx-internal
Type:                     LoadBalancer
IP:                       10.100.191.20
LoadBalancer Ingress:     10.0.1.1
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  32104/TCP
Endpoints:                <none>
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  31077/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason       Age   From                Message
  ----    ------       ----  ----                -------
  Normal  IPAllocated  78s   metallb-controller  Assigned IP "10.0.1.1"
```

I'm not sure where that specifies it's attributed to a node.  For completeness, here is the result of `kubectl -n ingress-nginx get svc ingress-nginx-internal -o yaml`:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"ingress-nginx-internal"},"name":"ingress-nginx-internal","namespace":"ingress-nginx"},"spec":{"ports":[{"name":"http","port":80,"targetPort":80},{"name":"https","port":443,"targetPort":443}],"selector":{"app.kubernetes.io/name":"ingress-nginx-internal"},"type":"LoadBalancer"}}
  creationTimestamp: "2020-03-28T18:45:12Z"
  labels:
    app.kubernetes.io/name: ingress-nginx-internal
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: controller
    operation: Update
    time: "2020-03-28T18:45:12Z"
  name: ingress-nginx-internal
  namespace: ingress-nginx
  resourceVersion: "64375"
  selfLink: /api/v1/namespaces/ingress-nginx/services/ingress-nginx-internal
  uid: 60d77137-a27b-490e-b064-27cfdf02a104
spec:
  clusterIP: 10.100.191.20
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32104
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31077
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/name: ingress-nginx-internal
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.0.1.1
```

Which node should I be running tcpdump on?  I have five nodes, and I see that the algorithm for which speaker should announce seems to be based off of a [hash of the node and service name](https://github.com/metallb/metallb/blob/main/speaker/layer2_controller.go#L78-L97).  I can run tcpdump/strace on all nodes if you like.

**Comment by cmcarey** [comment]
Someone in #metallb (@james, thank you so much) was able to help me solve this -

Issue was I had a bad selector on my service, so it wasn't picking up the endpoint of the pods.  Fixing the service selector then resulted in the speaker logging to the service that it was announcing from a specific speaker, and after that it worked flawlessly.

So again, thank you to @james, and I would ask that there be a slight addendum to the troubleshooting documentation saying that you should check that a speaker says it will announce, and if it does not, it could be because the service does not have sufficient endpoints.

**Comment by champtar** [comment]
@cmcarey PR are always welcome ;) (don't forget to close this one)

**Comment by cmcarey** [comment]
@champtar done :) https://github.com/metallb/metallb/pull/563
