### ISSUE TITLE
[Question] How to avoid service disruptions in L2 mode

### ISSUE THREAD

**Issue by liuyuan10** [metallb/metallb#561]
Currently in L2 mode, master is selected by sorting the hashing of node+service name so that each speaker can do this by themselves. One downside I can see is that when a node is added, it may change  master of some services (even all is possible) causing service disruptions. What's worse is when a node is restarted, it causes two service disruptions in a row for those with masters on the node.

So I'm wondering if we can have sticky master selection in some way. One straightforward way is to do master selection at a centralized place (like the controller) which can stick a service to a node. The reason not doing so must have been clear but some quick answers are appreciated.

**Comment by rata** [comment]
Just curious, how much time does this disruption take and using which OS? From https://metallb.universe.tf/concepts/layer2/:

> All modern versions of major OSes (Windows, Mac, Linux) implement layer 2 failover correctly, so the only situation where issues may happen is with older or less common OSes.

Just to understand the impact of the current behavior. Of course, improving is always good and thanks for noticing this use case that can be improved :-)

**Comment by liuyuan10** [comment]
Here I'm talking about existing TCP connections got disrupted because connection state is missing on a new master. Gateway doesn't play a role here. When a new node shows up, some of services may be migrated to this node but existing TCP connection states are not (kept in conntrack in most cases). If we can have sticky master election, a new node will not causing such migration

**Comment by champtar** [comment]
Grafana team implemented a small KV store on top of Memberlist: https://grafana.com/blog/2020/03/25/how-were-using-gossip-to-improve-cortex-and-loki-availability/
That might be a way to exchange info and have "sticky" nodes

**Comment by guoh1988** [comment]
@liuyuan10 
你好 
在k8s service ExternalTrafficPolicy =Local 下LB IP会将流量固定一个节点上的pod，当这个pod重启或者退出，会将流量切到其他节点上的pod，但是当这个节点上pod起来还是会将流量切回来，多了一次不必要的中断
如192.168.1.105/192.168.1.106两个udp测试pod程序，发现在k8s service ExternalTrafficPolicy =Local模式下，流量一般都是从105上走，当105上的程序退出或者重启，流量会切到106上去，但当105上的pod起来还会切到105，这个中间多了一次中断
在local模式下的lb的主节点好像默认选择105，不太清楚当中的算法

**Comment by russellb** [comment]
It looks like this discussion has been quiet for a good while now, so I'm going to close this out.  #metallb on kubernetes slack is another good place to discuss further.  Thanks!
