### ISSUE TITLE
Replace danderson/metallb with metallb/metallb

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#567]
We seem to have references to the old location of the repository - `danderson/metallb`. There is a GitHub redirect in place which forwards requests and Git actions to the current repo, however we should probably update these refs to `metallb/metallb` to avoid confusing people.

**Comment by nodesocket** [comment]
Can you provide links/paths were danderson/metallb exists?

**Comment by rata** [comment]
Agree, and adding to the list:
- [ ] in the tasks.py file there are references to `google/metallb`

**Comment by aditsachde** [comment]
Opened a PR, turns out there were a lot of places with old references. Most were in the changelogs, I felt that they should be updated too.

Shields still work, as those services also followed github redirects it seems.
