### ISSUE TITLE
namespaces "metallb-system" not found

### ISSUE THREAD

**Issue by nodesocket** [metallb/metallb#568]
Fresh install of MetalLB on a on-prem Kubernetes cluster running flannel.

```
kube-master - ubuntu ➜  metallb kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.9.3/manifests/metallb.yaml
podsecuritypolicy.policy/controller created
podsecuritypolicy.policy/speaker created
Error from server (NotFound): error when creating "https://raw.githubusercontent.com/google/metallb/v0.9.3/manifests/metallb.yaml": namespaces "metallb-system" not found
```

- Version of MetalLB: **0.9.3**
- Version of Kubernetes: **1.18.0**
- Name and version of network addon (e.g. Calico, Weave...): **Flannel**

**Comment by nodesocket** [comment]
Just noticed, this was a breaking change from 0.8.3.

```
kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.9.3/manifests/namespace.yaml
```

Curious why the namespace creation is not just bundled into the main metallb.yaml?

**Comment by champtar** [comment]
Hi @nodesocket 
https://github.com/metallb/metallb/pull/516
