### ISSUE TITLE
v0.9.3 won't deploy because 'memberlist' secret is missing from manifest

### ISSUE THREAD

**Issue by brokenjacobs** [metallb/metallb#569]
Using the deployment manifests for v0.9.3 fails to deploy the speaker daemonset. All pods fail with CreateContainerConfigError due to a missing 'memberlist' secret:
```
METALLB_ML_SECRET_KEY:  <set to the key 'secretkey' in secret 'memberlist'>  Optional: false
```

The deployment specifies this non-option secret through the spec/env list in the manifest, but the secret is not defined. Therefore you cannot deploy.

**Comment by nodesocket** [comment]
This was a recent change. You just need to create the secret:

```
kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
```

**Comment by champtar** [comment]
Manual is up to date ;)
https://metallb.universe.tf/installation/#installation-by-manifest

**Comment by rata** [comment]
I think it is safe to close this one, but please re-open if I'm missing something (like the steps in the documentation don't work or whatever you think can/should be improved)

**Comment by a0s** [comment]
terraform version
```hcl
resource "random_id" "metallb_memberlist" {
  byte_length = 128
}

resource "kubernetes_secret" "metallb_memberlist" {
  metadata {
    name = "memberlist"
    namespace = kubernetes_namespace.metallb.metadata[0].name
  }

  data = {
    secretkey = random_id.metallb_memberlist.b64_std
  }
}
```
