### ISSUE TITLE
Source IP not preserved for Layer2 “Local” traffic policy

### ISSUE THREAD

**Issue by MaxRenaud** [metallb/metallb#572]
I have deployed a whoami service and the RemoteAddr is the one of the local pod. I would expect RemoteAddr to be the actual client IP. The whoami pod lives on kworker3 (Same as the advertised from node)This is my service:
max@dev:~$ k describe service whoami -n whoami
Name:                     whoami
Namespace:                whoami
Labels:                   app.kubernetes.io/instance=whoami
                          app.kubernetes.io/managed-by=Tiller
                          app.kubernetes.io/name=whoami
                          app.kubernetes.io/version=v1.4.0
                          helm.sh/chart=whoami-0.3.2
                          io.cattle.field/appId=whoami
Annotations:              field.cattle.io/publicEndpoints:
                            [{"addresses":["192.168.36.230"],"port":80,"protocol":"TCP","serviceName":"whoami:whoami","allNodes":false}]
Selector:                 app.kubernetes.io/instance=whoami,app.kubernetes.io/name=whoami
Type:                     LoadBalancer
IP:                       10.43.163.97
LoadBalancer Ingress:     192.168.36.230
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  30206/TCP
Endpoints:                10.42.5.47:80
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     30830
Events:
  Type    Reason                 Age                From                Message
  ----    ------                 ----               ----                -------
  Normal  IPAllocated            36m                metallb-controller  Assigned IP "192.168.36.230"
  Normal  ExternalTrafficPolicy  34m                service-controller  Cluster -> Local
  Normal  nodeAssigned           13m (x4 over 35m)  metallb-speaker     announcing from node "kworker3"

---
     - Version of MetalLB: 0.9.3
     - Version of Kubernetes: Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
     - Name and version of network addon: Canal, seutp via rancher
     - Whether you've configured kube-proxy for iptables or ipvs mode: iptables

**Comment by rata** [comment]
Hi! Thanks for the report. Is it reproducible in your setup? Can you post a detailed way to reproduce it, so we can more easily debug it?

Thanks!

**Comment by MaxRenaud** [comment]
Thanks for the reply! It's I can reproduce it by removing metallb, adding a new worker node, reapplying metallb + the config and scheduling a whoami container on that node. 
I can access the whoami container so the ARP advertising works fine but for some reason, the client address appears to be from the worker. So in my case, the service lives on "kworker3" with a host IP of 192.168.36.226. The whoami web server sees the client IP as 192.168.36.226 instead of my laptop's IP. 
I can confirm that the external traffic policy is set to local:
External Traffic Policy:  Local

**Comment by russellb** [comment]
This sounds the same as #619.  Can you clarify what kind of networking you're using for your cluster?  I don't think MetalLB actually handles the forwarding of traffic to the endpoints, so I don't think it'd be the cause here.  It could be that your network backend doesn't support the local traffic policy?

**Comment by zwiy** [comment]
@MaxRenaud I'm not sure which IP is your client-source IP. But if it's from the 192.168.0.0/16 range and using RKE with the Canal CNI plugin it's related to this issue: https://www.suse.com/support/kb/doc/?id=000020231

**Comment by MaxRenaud** [comment]
I don't have this setup anymore so I cannot provide more info. Feel free to close as not reproducible
