### ISSUE TITLE
website: Add testing as nodePort to troubleshooting steps

### ISSUE THREAD

**Issue by rata** [metallb/metallb#576]
In my little experience on slack users channel, sometimes there is another unrelated issue that would have been catched if the service was tested as nodePort (note all services type LoadBalancer are also NodePort) 

We should consider adding that in the troubleshooting guide.

_Originally posted by @rata in https://github.com/metallb/metallb/pull/563_

**Comment by fedepaol** [comment]
closing as the related pr is merged
