### ISSUE TITLE
[QUESTION] How to configure L2 mode without binding an IP to the interface?

### ISSUE THREAD

**Issue by nielsbasjes** [metallb/metallb#577]
Note 1: I've tried to get into the Kubernetes Slack but I was not able to understand how that works, so I'm asking it here.

Note 2: I've asked this same question a while ago on [serverfault.com](https://serverfault.com/questions/1007372/separating-the-host-and-external-loadbalancer-networks-in-kubernetes) but so far I have not seen any answer that helps.

What I want is to separate the "node network" from the "external network" as good as possible.
So I'm trying to do what the manual says:

> Layer 2 mode does not require the IPs to be bound to the network interfaces of your worker nodes. It works by responding to ARP requests on your local network directly, to give the machine’s MAC address to clients.

To see if I can get this running I created an experimental setup: a CentOS 7 VM with 2 separate network interfaces, Kubernetes 1.17, Calico 3.13.1 and MetalLB 0.8.2 (and today with 0.9.3).

The effect I get is that if the external interface in CentOS does NOT have an IP then my firewall does get the correct arp records (i.e. ip/mac mapping) but I'm unable to connect. If the interface DOES have an IP then it all works. In both scenarios I can connect to the external IP when locally on the k8s node itself.

Full details of my config and what I have tried so far can be found here: 
https://serverfault.com/questions/1007372/separating-the-host-and-external-loadbalancer-networks-in-kubernetes

I assume this is simply a matter of fixing a configuration somewhere, but so far I have not been able to figure out which setting this should be.

As I have this is experimental single node K8S specifically to figure out how to get this running I can and I'm willing to try out any suggestion you can provide (even trying a different Linux distro to run k8s on).

P.S. If I manage to get this running I'll put up a pull request for some additional documentation so other can do this also.

**Comment by rata** [comment]
> Note 1: I've tried to get into the Kubernetes Slack but I was not able to understand how that works, so I'm asking it here.

Have you tried https://slack.k8s.io/ ?

> The effect I get is that if the external interface in CentOS does NOT have an IP then my firewall does get the correct arp records (i.e. ip/mac mapping) but I'm unable to connect. If the interface DOES have an IP then it all works. In both scenarios I can connect to the external IP when locally on the k8s node itself.

Sorry, where is your firewall located? I didn't see that here. From the link you posted, is not clear to me if you allow traffic to the external IP (the one metalLB is assigning to the service) to reach the nodes. You need that, if not... that is why you see timeout :)

But please, try to join slack and let's continue this there. I hope this pointers help, but unsure about the setup. If not possible via slack, join on IRC (freenode #metallb). There is less people there, so not as helpful, but still better than here.

To have this under control, I'd prefer to keep this for issues and questions on slack, etc.

Please feel free to re-open if you can't join those. Thanks!
