### ISSUE TITLE
How to do version upgrade

### ISSUE THREAD

**Issue by nalakawula** [metallb/metallb#579]
Is there is a proper guidance to update metallb version? I want to upgrade metallb from v0.8.1 to v0.9.3

Thank you

**Comment by rata** [comment]
Hi!

Good point, there is none at the moment. The usual way is to download the new manifests and `kubectl apply -f` them. 

For minor releases, you may want to look at the [release notes](https://metallb.universe.tf/release-notes/) to see the changes and action required items. It's always recommended to do so, even for patch releases, but patch releases are usually just bug fixes and chances of breaking something are way lower.

Would you like to do that in your setup and send a PR for the website to document the guideline? :)

**Comment by nalakawula** [comment]
I'll try to PR for the website to document the guideline
