### ISSUE TITLE
Installation conflict with Docker EE

### ISSUE THREAD

**Issue by darkhonor** [metallb/metallb#581]
There is an installation conflict when applying the MetalLB manifest on a Kubernetes cluster that is part of a Docker EE server cluster.  The error is a port conflict with Swarm.  Here are the error logs generated:

`$ kubectl logs pod/speaker-k2wq4 -n metallb-system
{"branch":"main","caller":"main.go:82","commit":"9d6de1ee","msg":"MetalLB speaker starting (commit 9d6de1ee, branch main)","ts":"2020-04-14T01:08:29.480424823Z","version":""}
{"caller":"main.go:202","component":"MemberList","msg":"memberlist.go:145: [DEBUG] memberlist: Got bind error: Failed to start TCP listener on \"10.110.57.13\" port 7946: listen tcp 10.110.57.13:7946: bind: address already in use","ts":"2020-04-14T01:08:29.480944095Z"}
{"caller":"main.go:118","error":"Could not set up network transport: failed to obtain an address: Failed to start TCP listener on \"10.110.57.13\" port 7946: listen tcp 10.110.57.13:7946: bind: address already in use","msg":"failed to create memberlist","op":"startup","ts":"2020-04-14T01:08:29.480975464Z"}
`

I was able to overcome this by removing the METALLB_ML_BIND_ADDR environment variable from the speaker DaemonSet.

     - Version of MetalLB: 0.9.3
     - Version of Kubernetes: v1.14.8-docker-1
     - Name and version of network addon (e.g. Calico, Weave...): Calico v3.8.2
     - Whether you've configured kube-proxy for iptables or ipvs mode: N/A

**Comment by champtar** [comment]
@darkhonor just sent a PR to make the port configurable.
By removing METALLB_ML_BIND_ADDR you just disabled memberlist which means dead node detection can take 40s or more (not sure you really want that)

**Comment by rata** [comment]
@darkhonor cool it worked what we talked in slack. If that was all, something like the @champtar PR should do the trick! :)
