### ISSUE TITLE
hashcorp deps are under MPL 2.0 license

### ISSUE THREAD

**Issue by liuyuan10** [metallb/metallb#585]
metallb is under APL which is a permissive free license. However, hashcorp dependencies are under MPL 2.0 which is a copyleft license. People are required to share source code it's being distributed outside organization.

I'm not a license guy so I can't say what it means for metallb. But from my quick search, it seems MPL 2.0 only applies the original code but doesn't pollute code depends on it (unlike GPL). So metallb itself can still be under APL. But anyone making modifications to hashcorp lib must make the modifications available. 

So things still look fine. Opening this issue here to raise some discussions and see if anyone can confirm my observation.

**Comment by champtar** [comment]
Thanks @liuyuan10, I totally forgot to look at the license when adding memberlist

**Comment by danderson** [comment]
From MPL FAQ Q12 (https://www.mozilla.org/en-US/MPL/2.0/FAQ/) :`MPL: The copyleft applies to any files containing MPLed code.`

It's fine. MetalLB files are under Apache License, the memberlist code we pull in is MPL, they coexist happily.
