### ISSUE TITLE
Add a config reference to the docs

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#591]
Right now there are [two](https://github.com/metallb/metallb/blob/main/manifests/example-config.yaml) [manifests](https://github.com/metallb/metallb/blob/main/manifests/example-layer2-config.yaml) which serve as both a configuration reference and as configuration examples.

I think it would be better to have a dedicated configuration reference section in the **docs website** where each MetalLB config option can be fully explained. The config examples, OTOH, should be real world "recipes" for common scenarios rather than an exhaustive listing of every config knob.

**Comment by fedepaol** [comment]
We covered this part with https://github.com/metallb/metallb/tree/main/configsamples
