### ISSUE TITLE
How to use worker's host address as the IP?

### ISSUE THREAD

**Issue by toonsevrin** [metallb/metallb#601]
The following functionality would be really valuable to a lot of us:

Being able to define a Service as type LoadBalancer, if the service has port 80, every worker node will start accepting traffic on port 80 of it's public address (the address that is used for NodePort services) and routing it to the service.

Is this currently possible with metaldb? If so, how?

**Comment by champtar** [comment]
You can configure your cluster to allow NodePort on port 80 I think, else you can use hostPort
MetalLB doesn't configure the dataplane, kube-proxy does that so what you are looking for will be in K8S not in MetalLB

**Comment by toonsevrin** [comment]
Oh I see, my apologies! :) Yeah, there are many ways to do this, for subsequent readers:
The way I would go for is to run your ingress as a DaemonSet and use hostPorts.
