### ISSUE TITLE
Speaker CPU throttling problem

### ISSUE THREAD

**Issue by kiuka** [metallb/metallb#603]
Hello,

My monitoring alerted me about continous CPU throttling connected to the active speaker. To be honest I dont really know what could have happened since I havent done any changes to the cluster in the past one month and I havent experienced any problem.

Since 2 days ago it started to alert me about the speaker want to overuse CPU so yesterday I have restarted that pod and it was good until now.

Grafana shows this: https://snipboard.io/8fvoBX.jpg

kubernetes version: v1.17.4
metallb version: v0.9.3
network addon: calico
kube proxy mode: ipvs

I have the POD running, havent restarted yet, I dont see anything interesting in the logs though, besides of the service updates only the following entries can be found:

```
{"caller":"arp.go:102","interface":"eth0","ip":"x.x.x.x","msg":"got ARP request for service IP, sending response","responseMAC":"00:16:3c:12:5f:7f","senderIP":"10.3.81.47","senderMAC":"00:00:5e:00:01:2a","ts":"2020-05-15T08:23:35.399415995Z"}
{"caller":"arp.go:102","interface":"eth0","ip":"x.x.x.x","msg":"got ARP request for service IP, sending response","responseMAC":"00:16:3c:12:5f:7f","senderIP":"x.x.x.x","senderMAC":"00:16:3c:91:4a:98","ts":"2020-05-15T08:23:43.666975912Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:210: [DEBUG] memberlist: Stream connection from=10.10.10.62:42110","ts":"2020-05-15T08:23:54.237250765Z"}
{"caller":"arp.go:102","interface":"eth0","ip":"x.x.x.x","msg":"got ARP request for service IP, sending response","responseMAC":"00:16:3c:12:5f:7f","senderIP":"10.3.81.47","senderMAC":"00:00:5e:00:01:2a","ts":"2020-05-15T08:24:00.74398505Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:785: [DEBUG] memberlist: Initiating push/pull sync with: 10.10.10.65:7946","ts":"2020-05-15T08:24:01.309651088Z"}
{"caller":"arp.go:102","interface":"eth0","ip":"x.x.x.x","msg":"got ARP request for service IP, sending response","responseMAC":"00:16:3c:12:5f:7f","senderIP":"x.x.x.x","senderMAC":"00:16:3c:91:4a:98","ts":"2020-05-15T08:24:24.878802571Z"}
{"caller":"arp.go:102","interface":"eth0","ip":"x.x.x.x","msg":"got ARP request for service IP, sending response","responseMAC":"00:16:3c:12:5f:7f","senderIP":"10.3.81.47","senderMAC":"00:00:5e:00:01:2a","ts":"2020-05-15T08:24:26.088105932Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:785: [DEBUG] memberlist: Initiating push/pull sync with: 10.10.10.65:7946","ts":"2020-05-15T08:24:31.313569776Z"}
{"caller":"arp.go:102","interface":"eth0","ip":"x.x.x.x","msg":"got ARP request for service IP, sending response","responseMAC":"00:16:3c:12:5f:7f","senderIP":"10.3.81.47","senderMAC":"00:00:5e:00:01:2a","ts":"2020-05-15T08:24:51.944569407Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:210: [DEBUG] memberlist: Stream connection from=10.10.10.65:55836","ts":"2020-05-15T08:24:57.220859672Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:785: [DEBUG] memberlist: Initiating push/pull sync with: 10.10.10.61:7946","ts":"2020-05-15T08:25:01.316431988Z"}
{"caller":"arp.go:102","interface":"eth0","ip":"x.x.x.x","msg":"got ARP request for service IP, sending response","responseMAC":"00:16:3c:12:5f:7f","senderIP":"x.x.x.x","senderMAC":"00:16:3c:91:4a:98","ts":"2020-05-15T08:25:09.422749956Z"}
```

**Comment by johananl** [comment]
Thanks for reporting @kiuka. Is there a way to reproduce the problem?

**Comment by kiuka** [comment]
@johananl thank you for your fast reply.

To be honest I'm not sure what causes the problem or what to check to give you more information, but the POD is still running in case you need more information. My only idea is to strace to process to see what is it doing since I dont see anything in the log.

Do you have any advice what to check?

**Comment by johananl** [comment]
What I meant is - does this happen often enough so that maintainers can reproduce the situation to figure out where the problem comes from?

I'm assuming your deployment has a CPU limit of `100m`. Could you confirm? I admit I'm not sure what the standard CPU utilization of the speaker is when running in layer 2 mode, but could it be that 100 millicores is just too strict?

Anyway, strace sounds like a good next step in figuring out what the speaker is doing since the logs don't seem to provide any clues.

**Comment by champtar** [comment]
I deploy on CentOS 7 host and I know I removed the limits, but never took the time to check if 100m was just too small or if cgroup limits are buggy on CentOS 7 frankenkernel

**Comment by kiuka** [comment]
Well, the problem is present in the past two days, not sure what caused it because I havent deployed anything new and not even deleted anything (I saw another ticket was about deleted pods causing this problem).

This is how it looks like in the past 12 hours (since I deleted the previous pod), so I would say it hits the limit quite often:

![metallb](https://user-images.githubusercontent.com/11283191/82054309-0250ef80-96bf-11ea-8d34-5d6c47963d11.jpg)

I'm using the manifests comes from the official repo (https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml) so the 100m comes from there (maybe it is just a recommendation and if I have more services I should raise this number?)

I could catch a spike, its the one from 14:30 - 14:45 (different timezone in the file (08:30 - 08:45), hopefully you can see something interesting, nothing caught my eyes in it:)

[strace.spike.txt](https://github.com/metallb/metallb/files/4634563/strace.spike.txt)

I also use Centos 7 (3.10.0-1127.el7.x86_64) just as @champtar

**Comment by kiuka** [comment]
it seems it was a problem with my vs, another vs was consuming most of the cpu and thats why it slow down, im closing this and thank you!
