### ISSUE TITLE
Specify which node to announce gratuitous ARP

### ISSUE THREAD

**Issue by silenceshell** [metallb/metallb#605]
According to [this code](https://github.com/metallb/metallb/blob/main/speaker/layer2_controller.go#L78), metallb does not allow user to specify which node to announc gratuitous ARP.

Is it possible(or reasonable?) to add an annotation to specify the node to announce gratuitous ARP? If possible, I would like to implement this feature.

**Comment by russellb** [comment]
I'm curious about the use case you're looking to enable. Why would you like to influence which Node is chosen over what is done in the code right now?  It looks like it will always choose an active Node that hosts at least one Endpoint for a given Service.  What's a case where you'd rather it choose a different one?

**Comment by russellb** [comment]
I did find this PR that has a proposal and some related discussion to what you may be looking for: https://github.com/metallb/metallb/pull/502

**Comment by silenceshell** [comment]
I have two mysql instances behind the service, which have master and standby roles. In this case, I want that when client connect vip, the connection should just redirect to the master instance. And if the standby instance changes to master role, the connection should redirect to the NEW master instance.
However, I decide to use the `selector` to do such thing. The service only select the master instance, and when standby changes to master, I will change the selector of the service.
