### ISSUE TITLE
[feature]  Add annotation to allow for selecting of a LoadBalancer in case of multiple LoadBalancers within the same cluster

### ISSUE THREAD

**Issue by jeff-hillman** [metallb/metallb#607]
RE: Kubernetes issue [91306](https://github.com/kubernetes/kubernetes/issues/91306)

In the case of having multiple LoadBalancer in the same cluster (Openstack-Cloud-Controller-Manager and MetalLB), when a Service type LoadBalancer is requested (or a service exposed as that type), both LBs will try to satisfy the request. Even setting MetalLB specific annotations, such as metallb.universe.tf/address-pool, does not single out a specific LB.

Per the k8s team, it is suggested that the LBs provide a specific annotation or label that will allow them to be specified in the service, so that a choice can be made between them.

A similar bug will be filed for OCCM.

     - The bug itself, as detailed as you can.
     - Version of MetalLB: 0.9.3
     - Version of Kubernetes: 1.17.2
     - Name and version of network addon (e.g. Calico, Weave...): Flannel
     - Whether you've configured kube-proxy for iptables or ipvs mode: ipvs

**Comment by kz12123** [comment]
This is a pain-point for worker nodes deployed on multi cloud using standard k8s (no cloud provider)
An onpremise node running metallb keeps interfering with ingress controllers on cloud worker nodes.

**Comment by alexellis** [comment]
We had a similar request on the [inlets-operator project](https://github.com/inlets/inlets-operator/) and have opted to add one annotation and two modes explained in the README file. Hope this is useful to users of both projects.

**Comment by johananl** [comment]
Thanks @alexellis!

**Comment by fedepaol** [comment]
Closing this as now metallb supports loadbalancer class
