### ISSUE TITLE
Pods should fail if the configuration is missing or invalid

### ISSUE THREAD

**Issue by stuartpb** [metallb/metallb#608]
I just spent at least an hour turning things off and on again, thinking I was having some kind of caching issue, because none of my LoadBalancer services were getting IP addresses, even though, in the Kubernetes Dashboard view for the metallb-system namespace, MetalLB was showing as all green across the board.

After searching Google and the repo's issues for every variation of "metallb not assigning IP" I could think of, I opened up the logs for the controller pod, and this was the second line:

```
{"caller":"k8s.go:387","configmap":"metallb-system/config","error":"could not parse config: yaml: line 2: did not find expected '-' indicator","event":"configStale","msg":"config (re)load failed, config marked stale","ts":"2020-05-29T07:05:42.474694772Z"}
```

It turns out I had a minor typo (one space too many) that made my configuration YAML invalid. However, since the container kept on chugging along peacefully and in silence, I had *no indication* that this was the problem, and was exhausting every other possibility as a consequence - if any other service I used were unable to read its root configuration, that would have been a fatal error, the pod would have clearly shown up as Failing, and I would have recognized and caught the problem immediately.

**Comment by champtar** [comment]
Hi @stuartpb 
I think current behavior allow current LoadBalancer to keep working when you load an invalid config, restarting would break connectivity which you don't want

**Comment by johananl** [comment]
See https://github.com/metallb/metallb/issues/462.

This behavior originates in the desire to be "extra safe" in terms of not killing traffic following config changes. The downside, as you've already learned the hard way @stuartpb, is that nothing shouts at you when you have a broken configuration. Well, at least not loud enough :-)

We plan to disable this mechanism. If this takes time then we should probably put a warning in the docs until this is implemented.

**Comment by johananl** [comment]
I'll close this since we are already tracking this in #462.

**Comment by stuartpb** [comment]
Yeah, like, if I want that kind of safety, I can run multiple replicas in a gradual rollout, right?
