### ISSUE TITLE
Cannot connect to service via public IP on different node with externalTrafficPolicy set to local

### ISSUE THREAD

**Issue by stephan2012** [metallb/metallb#609]
# Issue

A Pod running on node A cannot connect to another service via its public (MetalLB provided) IP address (`externalTrafficPolicy` set to `Local`) running on node B. In my case, an application running in a Pod on node A cannot access the Nginx Ingress Controller via the public IP address. Everything runs fine when either the connection initiating Pod and the target Service/Pod run on the same node or switching `externalTrafficPolicy` to `Cluster` (but then I am loosing the source IP address).

```
$ kubectl get pods -o wide -A |grep -i -e oauth2 -e ingress-nginx-controller
default                oauth2-proxy-5b6fc7bc97-szgq6                           1/1     Running             0          58m     172.30.206.22     n0216   <none>           <none>
ingress-nginx          ingress-nginx-controller-76875d486b-x79g8               1/1     Running             0          2d20h   172.30.63.46      n0217   <none>           <none>
```

Services:

```
$ kubectl get svc -n ingress-nginx 
NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   172.31.208.174   192.168.100.96   80:31037/TCP,443:30485/TCP   2d21h
```

Symptom:

```
$ kubectl exec -ti oauth2-proxy-5b6fc7bc97-szgq6  sh
/ $ wget https://192.168.100.96/
Connecting to 192.168.100.96 (192.168.100.96:443)
wget: can't connect to remote host (192.168.100.96): Connection refused
```

No problems when everything is on one node:

```
$ kubectl get pods -o wide -A |grep -i -e oauth2 -e ingress-nginx-controller
default                oauth2-proxy-7b9cfbbdf4-x8nzs                           1/1     Running       0          14s     172.30.63.20      n0217   <none>           <none>
ingress-nginx          ingress-nginx-controller-76875d486b-x79g8               1/1     Running       0          2d20h   172.30.63.46      n0217   <none>           <none>

$ kubectl exec -ti oauth2-proxy-7b9cfbbdf4-x8nzs   sh
/ $ wget https://192.168.100.96/
Connecting to 192.168.100.96 (192.168.100.96:443)
ssl_client: 192.168.100.96: certificate verification failed: self signed certificate
wget: error getting response: Connection reset by peer
```

(layer 4 connect successful, TLS error is okay here). 

# Configuration

MetalLB operates in Layer 2 mode:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config
  namespace: metallb-system
data:
  config: |
    address-pools:
      - name: default
        protocol: layer2
        addresses:
          - 192.168.100.96-192.168.100.96
          - 192.168.100.88-192.168.100.88
          - 192.168.100.97-192.168.100.97
          - 192.168.100.98-192.168.100.98
```

`kube-proxy` runs in `ipvs` mode:

```yaml
    mode: ipvs
    ipvs:
        excludeCIDRs:
        - 192.168.100.95/32
        minSyncPeriod: 0s
        scheduler: wlc
        strictARP: true
        syncPeriod: 5s
```

# Versions

Kubernetes v1.15.12 (setup via `kubeadm`), MetalLB v0.9.3, Calico v3.14.0

**Comment by niels-s** [comment]
I just noticed to see your issue and was looking up more info about this topic myself. afaik this isn't an issue of MetalLB but the way how services are implemented in Kubernetes, see [loadbalancer docs](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer)

So if you need source IP, for now, you can only use `externalTrafficPolicy: Local` so you will have to limit the nodes that are being advertised by MetalLB and make sure you always have a pod of said service running on those nodes which MetalLB is advertising.
There is some discussion going to improve the `externalTrafficPolicy` https://github.com/kubernetes/kubernetes/issues/85643 but it will take a while before this is implemented.
Hope this helps

**Comment by champtar** [comment]
Hi @stephan2012 
This is a kubeproxy limitation, nothing to fix in MetalLB
I don't remember if this is specific to ipvs mode or not

**Comment by niels-s** [comment]
> I don't remember if this is specific to ipvs mode or not

I can confirm it's not we're using iptables mode which behaves the same

**Comment by stephan2012** [comment]
Looks like my issue is a FAQ candidate…

Thanks for the pointers, @niels-s, @champtar.

To summarize: The only options currently available are

- not to use `externalTrafficPolicy: Local` 
- ensure a target service instance is running on any node
- maybe colocating depending services could be an option

Is there any reason not to close this issue here?

**Comment by champtar** [comment]
@stephan2012 use the clusterIP ?

**Comment by stephan2012** [comment]
@champtar: I am checking if this could be an option but for this very case (OAuth2 Proxy connecting to a proprietary OAuth2 provider) my first attempts were unsuccessful. However, I will investigate a bit more here because it clearly does not make sense to leave the cluster when the target service is available internally.

**Comment by stephan2012** [comment]
A bit off-topic, but managed to access the target service via `ClusterIP`.

As stated above, this is a `kube-proxy` issue, so closing this one.

**Comment by SamDecrock** [comment]
This also happens to me even when the externalTrafficPolicy is set to its default value. If I install the nginx controller as a Deamonset, it's even more erratic: sometimes I connect, sometimes not.

**Comment by fedepaol** [comment]
> This also happens to me even when the externalTrafficPolicy is set to its default value. If I install the nginx controller as a Deamonset, it's even more erratic: sometimes I connect, sometimes not.

please file a new issue with more details, like the metallb version, your configuration, the mode you are using metallb (l2 or frr) and try to do some troubleshooting as described in https://metallb.universe.tf/configuration/troubleshooting/
