### ISSUE TITLE
MetalLB + Ingress + TLS

### ISSUE THREAD

**Issue by soudaburger** [metallb/metallb#612]
Hello! First of all, thanks for writing this tool.  It's really something special.

I have a semi-unique use case and I'm not finding my answers anywhere, so thought I would drop my question in here in hopes that I'm simply not looking in the right place.

Use case: Have `metallb` provision an IP in FRONT of an ingress object so that a multiple node cluster has a VIP and can leverage TLS properly.

1) I have MetalLB working with a VIP over HTTP with a "serviceType: LoadBalancer" kubernetes service.
2) I have an nginx ingress object with Let's Encrypt TLS fully functional with proper certificates tied to the service.

I can reach my ingress (HTTPS) over the node IP, but not the MetalLB IP.

Is there a way to make these two things work together?  Thanks!

**Comment by lgorence** [comment]
I have also been searching for an answer to this question. I want to be able to have an ingress controller in front of my web applications, as well as other services listening on the same IP.

**Comment by knandras** [comment]
> I have also been searching for an answer to this question. I want to be able to have an ingress controller in front of my web applications, as well as other services listening on the same IP.

You can have multiple services sharing an IP: https://metallb.universe.tf/usage/#ip-address-sharing

But I'm also very interested in the answer to the OP question.

**Comment by russellb** [comment]
Hi!  I'd encourage you to try to follow up on this via one of the community support forums: #metallb on kubernetes slack, or the metallb-users mailing list.  Maybe you'll have better luck spawning some discussion there.

https://metallb.universe.tf/community/

**Comment by koraykutanoglu** [comment]
I am having a problem with this. But what needs to happen here is that ingress should be ahead. It is expected that the requests will first pass through ingress at the layer 7 level and then come to the metallb IP and become a loadbalancer. Is there any solution about this? 

Have you made any progress on this? @soudaburger
