### ISSUE TITLE
Consider moving memberlist/speakerlist code to Layer 2

### ISSUE THREAD

**Issue by rata** [metallb/metallb#614]
Memberlist is currently used in Layer 2 only, but the code is at top layer, as if it was independent of BGP or Layer 2. So, memberlist code is a "layer 2 thing" that leaked out of the abstraction for Layer 2.

We should either move memberlist to Layer 2 code only, consider using it for BGP, or document that BGP-only users might want to disable it.

@champtar who wrote the initial memberlist support says that there is no point in using memberlist for BGP: https://github.com/metallb/metallb/pull/595#discussion_r434846171.

We may want to consider the overhead of memberlist and, if not negligible, advise to disable for BGP-only users.

**Comment by johananl** [comment]
TODO:

- [ ] Mention that memberlist port must be open between nodes only when using layer 2 (see https://github.com/metallb/metallb/pull/783#discussion_r548543602).
