### ISSUE TITLE
LoadBalance is not honouring externalTrafficPolicy

### ISSUE THREAD

**Issue by alexanderturner** [metallb/metallb#619]
I have MetalLB set up with 4 hosts, each peered with an upstream BGP router. Discovered, that in an attempt to configure IP whitelisting on ingress-nginx, all source addresses appear to be coming from the leader (as per `externalTrafficPolicy: Cluster`). 

On nginx-ingress
```
LoadBalancer Ingress:     192.168.10.1
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  31443/TCP
Endpoints:                10.42.0.149:80,10.42.1.116:80,10.42.2.140:80 + 1 more...
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  30703/TCP
Endpoints:                10.42.0.149:443,10.42.1.116:443,10.42.2.140:443 + 1 more...
Session Affinity:         None
External Traffic Policy:  Local
```

Validated on ingress logs (tried swapping `externalTrafficPolicy:Cluster` with no difference).
```
2020/06/08 05:12:34 [error] 40#40: *25206 access forbidden by rule, client: 192.168.2.111
``` 

This is on MetalLB 0.9.3 and nginx-ingress-controller:0.32.0

**Comment by russellb** [comment]
What networking are you using for your cluster?  I think this also depends on cooperation from your network plugin.  Metallb doesn't actually do the forwarding from the external IP to the endpoints.

**Comment by russellb** [comment]
I would suggest trying one of the community support forums to discuss this further: either #metallb on kubernetes slack or the metallb-users mailing list.

https://metallb.universe.tf/community/

Thanks!
