### ISSUE TITLE
Feature request: Allow forcing failover

### ISSUE THREAD

**Issue by anton-johansson** [metallb/metallb#621]
This discussion comes from #494.

## Problem

I use Ansible to apply changes to my Kubernetes-cluster. These changes are **mostly** upgrades of Kubernetes version, but could be simple configuration changes.

Whenever I upgrade Kubernetes version, it of course stops `kubelet` and starts it up again with the new version. This forces pods to be recreated on the node (I'm not sure if this happens every upgrade or if it's just if something in the spec changes, but I've seen it multiple times). This pod re-creation causes a small downtime for me, before MetalLB has time to react to the pod being removed.

I can also force a failover by manually deleting the pod (after cordoning the node, to make sure that the node won't get reassigned as the announced node), however this causes the same problem.

## Suggestion

Allow us to manually force a failover without involving a delete of an existing pod. I'm not sure how this would be done, though. I'm assuming that an HTTP API would be a good way to go, but MetalLB does not have anything like that today so it would be a quite big change. Not only would you want to failover, but I'm guessing you would want to tell MetalLB to avoid this node until told otherwise.

Another idea would be to utilize node annotations (or custom node conditions? I'm not sure if this is a possibility, though). MetalLB could watch for changes on nodes and look for a certain annotation. If the annotation is present, it will announce another node and avoid the annotated node for the duration of the annotation.

## Conclusion

All in all, I'd like to see some way of a safe and managed failover system that can be done before-hand, as a preparation for an upgrade or maintenance or whatever.

**Comment by johananl** [comment]
Thanks for filing the issue @anton-johansson :slightly_smiling_face:

The use case is clear to me. I'll share my thoughts regarding possible solutions:

Introducing an API to handle failovers doesn't sound like the right approach to me: Not only is it a fairly big addition to the codebase for a relatively small change in functionality, it is also not very k8s-like. I would rather think about solving the problem in a more "k8s-native" way, namely via the k8s API.

Your idea about node annotations goes more in the right direction IMO. Maybe it could also make sense to use something like node selectors to specify a group of nodes which should should be eligible for announcing services. In both cases it would be up to you to modify labels/annotations on the relevant node.

I've opened https://github.com/metallb/metallb/issues/630 to explore the idea of a generic mechanism for specifying affinity between a pool and a group of nodes. Maybe such a mechanism could help in "exempting" specific nodes to ensure they don't announce services during maintenance. Not sure if this makes sense though.

Possibly related: https://github.com/metallb/metallb/issues/302

**Comment by anton-johansson** [comment]
Yeah, after writing the issue, and also after reading your inputs, I totally agree that annotations is a much better way forward.

And sure, it can be swapped around so instead of what I suggested, we have an annotation that indicates that this node is eligible for announcing from MetalLB. Technically, it doesn't give much addition, because you can accomplish the same with node selectors for the pods that you wish to announce a MetalLB for. However, I still think it's easier to understand the annotation if done this way (negations are never better).

Should we close this activity in favor of #630, or is it good to keep this one open?

**Comment by johananl** [comment]
I'd keep this one open since #630 doesn't deal with forcing failover. https://github.com/metallb/metallb/issues/704 is also related by the way.

**Comment by fedepaol** [comment]
This can be easily implemented now by modifying the l2 node selector of the l2 announcement resource.
