### ISSUE TITLE
[CI] Push a container image for each PR

### ISSUE THREAD

**Issue by russellb** [metallb/metallb#623]
While building out CI, we should consider pushing a container image for each PR to a public registry to make it easy for people to test out a PR.

**Comment by johananl** [comment]
Should we think about cleaning up old images from Docker Hub?

**Comment by russellb** [comment]
> Should we think about cleaning up old images from Docker Hub?

maybe a follow-up issue for this?  It doesn't seem like the PR rate is high enough that this will get crazy too soon.  A script to purge images for merged or closed PRs makes sense though.

**Comment by fedepaol** [comment]
We now have local CI that tests extensively. Closing this.
