### ISSUE TITLE
Metrics: metallb_allocator_addresses* does not show until first assigned External IP

### ISSUE THREAD

**Issue by Aoana** [metallb/metallb#626]
### Problem description

**I want to understand if this is considered a bug.**

Metallb installed and configmap applied with address pool.
metallb_allocator_addresses_in_use_total and metallb_allocator_addresses_total
are not scrapable metrics until a first type:Loadbalancer service have been assigned an External IP.

I would expect that the metrics shows as soon as the configmap is applied.

### Installation steps

kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"

### Steps to reproduce

Configmap (metallb.yaml) and service manifest (service1.yaml) are attached here
[metallb-metric-allocator.tar.gz](https://github.com/metallb/metallb/files/4763163/metallb-metric-allocator.tar.gz)

```
controllerpod=$(kubectl get pods -n metallb-system -o wide | grep controller | awk '{ print $6 }')
kubectl apply -f metallb.yaml
wget -q -O- http://$controllerpod:7472/metrics | grep metallb_allocator
```

**-> BUG?** My expected behavior would be that the metrics are instantiated the moment configmap with address-pool is applied. The in_use could maybe be argued to be instantiated when first service arrives, but the addresses_total is a value only based on configmap and should show even without services.

When you deploy a service the metrics show up as expected.
```
kubectl apply -f service1.yaml
wget -q -O- http://$controllerpod:7472/metrics | grep metallb_allocator 
# HELP metallb_allocator_addresses_in_use_total Number of IP addresses in use, per pool
# TYPE metallb_allocator_addresses_in_use_total gauge
metallb_allocator_addresses_in_use_total{pool="default"} 1
# HELP metallb_allocator_addresses_total Number of usable IP addresses, per pool
# TYPE metallb_allocator_addresses_total gauge
metallb_allocator_addresses_total{pool="default"} 16
```

### System Information

Version of MetalLB: v0.9.3
Version of Kubernetes: v1.18.3
Name and version of network addon: Calico (but not relevant)
Kube-proxy configuration: Not relevant (and issue seen in both ipvs and iptables mode)

**Comment by uablrek** [comment]
Both poolCapacity and poolActive are defined inside the "assign()" function;

https://github.com/metallb/metallb/blob/c65516fcb115772ae0a6ed4dd1fb0fb0a01d3879/internal/allocator/allocator.go#L123-L124

At least for poolCapacity this must be wrong.
