### ISSUE TITLE
Document mirror server

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#635]
The Invoke-based dev environment deploys a set of pods called `mirror-server` which are apparently intended to be used by e2e tests (https://github.com/metallb/metallb/blob/main/e2etest/manifests/mirror-server.yaml).

Assuming these pods are in use, we should document what they do. If they aren't in use, we should probably get rid of them.

**Comment by rata** [comment]
+1. But they are useful for local development, so may make sense to keep it for local dev

**Comment by caboteria** [comment]
I'd be willing to do the work to split the mirror server into its own project under the metallb organization.  It's distinct enough from MetalLB that it should stand on its own.  Of course I'd document it in the process.

**Comment by johananl** [comment]
@caboteria I wonder if creating a separate repo for a single-file app isn't an overkill. Also, if we do that we would have to figure out how to spawn a mirror-server deployment when running `inv dev-env`. Right now mirror-server is compiled from a local directory, the container image is uploaded to kind and then a manifest is applied to the kind cluster.

**Comment by caboteria** [comment]
Right, I was thinking that the mirror-server project could upload a docker image to github or docker hub or whereever and the tests could run it from there.

I was looking at mirror-server as being similar to Virtuakube in that it exists to serve the MetalLB project but isn't really part of the project.  In some ways it's closer in function to Virtuakube than it is to MetalLB.  We've got a metallb organization so adding new projects is trivially easy, and I'm willing to do the work.

**Comment by russellb** [comment]
sounds reasonable to me.

**Comment by rata** [comment]
Well, actually, for local development (the only reason this exist now) for me is helpful to have it in the MetalLB repo. I ocasionally modify the code a little bit, to add a print or do something else. It's just handy to have it there.

I don't really see any reason to have it's own repo for now. If that happens to be better for e2e tests, I'm okay for doing it when we need it. But I don't see why we would do it now, where it just only will make it harder for local dev, that is the only use case?

Am I missing something?

**Comment by tylerauerbeck** [comment]
@johananl I think this can probably be closed since #1621 was merged.

**Comment by johananl** [comment]
Great, done.
