### ISSUE TITLE
annotate chosen node in layer2 mode 

### ISSUE THREAD

**Issue by costela** [metallb/metallb#637]
Please consider optionally annotating the service with the [node chosen to announce the IP](https://github.com/metallb/metallb/blob/a9a6f3195a008c7094a17f11c025899177699c79/speaker/layer2_controller.go#L83) in layer2 mode.   

### Motivation:
Currently it seems to be impossible to determine - from the control-plane - which of the nodes running pods in a service is actually receiving traffic.

Some lower-level integration with metalLB require knowing which nodes get selected for ARP IP announcements.
One example is this little ["floating IP" controller](https://github.com/costela/hcloud-ip-floater) for the budget [Hetzner Cloud](https://hetzner.cloud) provider. In it, we must ensure we attach the floating IP to the same node metalLB picked.

It would therefore be useful to be able to query this information from other controllers via the control-plane.

### Considered alternatives:
Another option would be exporting the logic used for node selection, so that code wishing to integrate with metalLB could import and use it, ensuring the same node choice.
This has the downside of increasing the API surface for metalLB and also tying metalLB to a specific API. E.g.: the current code relies solely on the nodes' and service names to make a deterministic node decision; exporting this API would complicate expanding the logic to require other information.

If this sounds like something that could be accepted - at least on principle - I could try my luck at a PR.

**Comment by russellb** [comment]
I'm trying to understand the use case a little better.  If you have another controller managing floating IP mappings, then what is the layer2 speaker doing?  Why do you need the metallb speaker doing ARP/NDP?  Presumably that's handled already via whatever implements the floating IPs?

**Comment by champtar** [comment]
ExternalIPs

**Comment by costela** [comment]
@champtar I might be overlooking something obvious, but AFAIK `ExternalIPs` require the service to know its IP, introducing unnecessary coupling between the developer deploying their code and the cluster operator. It could work, but wouldn't be as flexible. What am I overlooking?

@russellb the floating IP controller in this case simply signals the cloud provider to point the IP to a node in its SDN. At this point (without metalLB), the node knows nothing about this IP it's supposed to accept packets for. MetalLB does the "heavy-lifting" of handling IP pools and ensuring the nodes actually treat the floating IP as local to accept packets. I.e.: the floating IP controller is very light-weight and defers to MetalLB for IP assignment.
Admittedly, the floating IP controller could try to do the rest as well, but it just felt easier relying on metalLB's considerably better tested code :wink:. The difference in code maturity seems particularly important since the floating IP controller would have to be privileged to handle the IP assignment itself (TTBOMK? Maybe I have some crucial misunderstanding of k8s networking).
Does this clarify anything?

**Comment by champtar** [comment]
You basically want just the MetalLB controller part, and don't need the speaker part, but the IP pool range should be automatically downloaded from Hetzner IMO to make it more usable, so you pull a complex dependency (MetalLB) without a big gain in usability.
An important information, once the LoadBalancerIP is 'attributed', the nodes accept traffic for this IP, so your 'Hetzner Cloud™ IP Floater' is a replacement of the speaker for Hetzner

**Comment by costela** [comment]
@champtar you're right: the automatic generation of metalLB pools is something the controller could do. I have a WIP branch for that. However:

> once the LoadBalancerIP is 'attributed', the nodes accept traffic for this IP

This is probably the root of my misunderstanding. I had until now blindly assumed the IP was added to the node by metalLB, but if I'm getting this right, it's actually done by k8s itself (kube-proxy?) and metalLB "only" implements the service controller part by returning IPs from the pool? (ignoring ARP announcements as they're probably superfluous in this case) 
That means I've been relying on metalLB to do stuff it wasn't even doing ... oh man... that's emparrasing :sweat_smile:

**Comment by champtar** [comment]
@costela don't be embarrassed, K8S is a beast, it takes some time to understand what part does what.
Some more details:
1) MetalLB controller chooses an IP from the config and patch the LoadBalancer object status to make K8S use this IP
2) kube-proxy setup iptables (& IPVS) to accept the traffic for this IP and have it go to the right pod
In IPVS mode the IP is configured on the host, but not in iptables mode (it's not needed)
3) MetalLB then 'configure the network' to actually have the packets come to the nodes, for that it either uses ARP or BGP

You are already doing 3, just need to implement 1

**Comment by russellb** [comment]
The other part it sounds like you were relying on was the logic in the layer2 speaker to choose a host to direct the IP's traffic to.  You'd still have to implement that, too.  The logic the layer2 speaker uses isn't that complicated though:

- Determine the set of hosts running an endpoint for the service.
- Pick one of those.  :-)

**Comment by costela** [comment]
@champtar yup, that sounds about right. Thanks for clearing that up!  

@russellb yeah, we're currently copying the little metalLB name hashing logic, which should be enough.

Alright, since this proposal was born of a mistaken assumption, I'll just go ahead and retract it.
Thanks for the clearing up and sorry for the noise!

**Comment by eplightning** [comment]
The way Hetzner have implemented the floating IPs actually requires ARP/NDP announcements - or at the very least I wasn't ever able to get it working without it. 

So the MetalLB's L2 speaker is still pretty much required for that provider.

**Comment by champtar** [comment]
kube-proxy in IPVS mode + strictARP false would respond to ARP on all nodes
@eplightning @costela can you make sure you see ARP requests from Hetzner with `tcpdump -i ethx -nnpev -Q in arp`, maybe you need to configure the IP on the host else you don't accept the traffic, but you don't need the ARP responses

**Comment by costela** [comment]
kube-proxy in IPVS mode does indeed add the IPs to all nodes (in my case to `kube-ipvs0`).

For future reference: this probably explains part of my misunderstanding. I originally developed the controller on a "vanilla" cluster with iptables-mode kube-proxy, but later switched (for unrelated reasons) to IPVS-mode. So the initial dev setup required metalLB, while the current one doesn't. Will have to document this interaction on the controller.

**Comment by champtar** [comment]
To be clear kube-proxy iptables mode doesn't had the IPs because it's not strictly needed
please run the tcpdump command when you get a chance that will help make sure which way to go

**Comment by costela** [comment]
@champtar I can confirm that the node that has the floating IP "attached" (as defined by the cloud provider) *does* see ARP requests:
```
23:35:08.758405 xx:xx:xx:xx:xx:xx > zz:zz:zz:zz:zz:zz, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 88.XX.XX.XX tell 172.31.1.1, length 28
```
The other nodes do not.

Interestingly (and unrelated to the problem at hand) I also see ARP requests for IPs not in my account, which may indicate their SDN is not cleaning up after itself (presumably leaving the dangling attachments for deleted IPs?)
