### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "permission denied"

### ISSUE THREAD

**Issue by liuyuan10** [metallb/metallb#643]
I got this error when running a local built metallb-controller in k8s (v1.17.4)

The root cause is that output binary of "go build" is of permission 750. When copied into docker image, the permission is kept but owner is changed to "root".

Steps to reproduce:
inv build -t 1
docker run -it --entrypoint /bin/sh  metallb/controller:1-amd64
ls -l controller
-rwxr-x---    1 root     root      34229033 Jun 18 03:35 controller

We are running controller as non-root user in metallb.yaml so it doesn't have execute permission.  The public metallb docker image doesn't have this issue. So I'm wondering if it's an issue for me only. Should we add a "chmod a+x" into the Dockerfile?

golang version:
go version go1.13.4 linux/amd64
docker version:
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by russellb** [comment]
I wasn't able to reproduce this.  I did:

```
$ inv build
...
$ podman run -it --entrypoint /bin/sh metallb/controller:dev-amd64
/ # ls -l controller 
-rwxrwxr-x    1 root     root      33923403 Jun 19 20:24 controller
```

**Comment by liuyuan10** [comment]
This is due to security setting on my desktop that doesn't give others execution permission after "go build". I think it's beneficial to fix it in upstream to avoid wasting time by others. Nothing guarantees that "others" always has exec permission. Please see PR #644

**Comment by liuyuan10** [comment]
I can easily fix it in my case by setfacl but the pr can probably help others with the same issue. So if the PR is not merged, anyone with the same issue can fix it:
setfacl -d -R -m o::x go.universe.tf/
getfacl go.universe.tf/
# file: go.universe.tf/
# owner: liuyuan
# group: primarygroup
user::rwx
group::r-x
other::---
default:user::rwx
default:group::r-x
default:other::--x

**Comment by rata** [comment]
@liuyuan10 thanks for the PR. I think it looks fine, but do you happen to know what setting in your setup is causing this? I'd like to know if other `inv` command might be affected :)

**Comment by liuyuan10** [comment]
It's about umask config. It happens that our company has a default umask set.
https://geek-university.com/linux/set-the-default-permissions-for-newly-created-files/

**Comment by rata** [comment]
Oh, it is just umask? Great. Thanks!
