### ISSUE TITLE
Scaling replicas resulted in warning

### ISSUE THREAD

**Issue by therealbubbasour** [metallb/metallb#645]
Hi, I'm learning metallb and deployed it on K3s today following the documentation. The flannel backend is host-gw. So far so good.

The LB IP is still accessible, but I'm wondering:
1. When I scale the number of replicas I notice this warning, and I'm not sure exactly how to fix it or what it mean. Would appreciate some guidance here.
2. Why did the speaking node change from node-5 to node 1 when I issued the scale command, is there a reason for changing the speaking node? 

```
$ kubectl describe svc hellw-world-2
Name:                     hellw-world-2
Namespace:                default
Labels:                   app=hellw-world-2
Annotations:              <none>
Selector:                 app=hellw-world-2
Type:                     LoadBalancer
IP:                       10.43.83.234
LoadBalancer Ingress:     192.168.85.242
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  31841/TCP
Endpoints:                10.42.0.10:80,10.42.0.11:80,10.42.0.12:80 + 97 more...
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                        Age                     From                       Message
  ----     ------                        ----                    ----                       -------
  Normal   IPAllocated                   10m                     metallb-controller         Assigned IP "192.168.85.242"
  Normal   nodeAssigned                  7m31s (x2 over 10m)     metallb-speaker            announcing from node "node-5"
  Normal   nodeAssigned                  3m42s (x25 over 7m30s)  metallb-speaker            announcing from node "node-1"
  Warning  FailedToUpdateEndpointSlices  3m38s (x18 over 6m1s)   endpoint-slice-controller  Error updating Endpoint Slices for Service default/hellw-world-2: Error updating hellw-world-2-jfgj4 EndpointSlice for Service default/hellw-world-2: Operation cannot be fulfilled on endpointslices.discovery.k8s.io "hellw-world-2-jfgj4": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by russellb** [comment]
>     1. When I scale the number of replicas I notice this warning, and I'm not sure exactly how to fix it or what it mean. Would appreciate some guidance here.

This isn't related to MetalLB.

>     2. Why did the speaking node change from node-5 to node 1 when I issued the scale command, is there a reason for changing the speaking node?

In layer2 mode the Node where the IP is announced from is determined by an algorithm that takes the following as inputs: the service name and the set of Nodes currently running one of the Endpoints for that Service.  If those inputs change, the result may change.  In this case, by scaling the number of replicas, the set of Nodes running an Endpoint changed.
