### ISSUE TITLE
Re-implement helm chart

### ISSUE THREAD

**Issue by gclawes** [metallb/metallb#653]
I have started a re-implementation of the metallb helm chart based on a combination of the previous chart in this repo, the [stable/metallb](https://github.com/helm/charts/tree/master/stable/metallb) chart in the soon-to-be-deprecated stable repo, and the [bitnami/metallb](https://github.com/bitnami/charts/tree/master/bitnami/metallb) chart.

My feature goals for this are:
* Use modern helm chart base from Helm v3
* Support new configuration options related to MemberList features
* Improve RBAC
* Switch from ServiceMonitor to PodMonitor, removing the need to create services for metrics

**Comment by Maxpain177** [comment]
@gclawes Nice work! Any ETA?

**Comment by gclawes** [comment]
Remaining tasks (in no particular order):

- Helm tests (pods to run in kind during CI).
- Add JSONSchema validation for values (and possibly ConfigMaps provided in the values)
- Chart release GitHub Action

I'm hoping to be able to get these done by next week.  See #658 for progress.
