### ISSUE TITLE
Installation By manifest : `error: exactly one NAME is required, got 3` when creating the secret

### ISSUE THREAD

**Issue by sushicodeur** [metallb/metallb#656]
Hello,

I tried the installation of MetalLB following the "Installation by Manifest" section of the documentation : https://metallb.universe.tf/installation/#installation-by-manifest

I had some error with the last step of the documentation : 

```shell
kubectl create secret generic memberlist --from-literal=secretkey="$(openssl rand -base64 128)"

kubectl create secret generic memberlist --from-literal=secretkey=[some characters
from the generated
secretkey but in 3 lines=]
error: exactly one NAME is required, got 3
See 'kubectl create secret generic -h' for help and examples
```

It appeared that the `openssl rand -base64 128` subcommand generated a key but presented on 3 lines, which wasn't accepted by k8s.

Doing instead :

```shell
kubectl create secret generic memberlist --from-literal=secretkey="$(openssl rand -base64 128 | tr -d '\n')"
```
solved my problem.

If it can help to improve the documentation, or maybe I misunderstod something, I'm quite new to all this stuff :)

**Comment by caboteria** [comment]
What version of kubectl are you using, what version of openssl, and on what platform?  kubectl v1.18.5 with openssl 1.1.1d on Linux works fine for me with the three-line secret.

When I run only the openssl command I get:
```
metallb$ openssl rand -base64 128
QN0Ei/qVwpHuTntAAlHWTG9jLQjVm4vIVrEDxdCzl9KnqG5TxOdy12R7//+fpejZ
10qCCMjThEpwBlA/ipWT2T3KLzhfb2eRfRYVYUU/Mlp4glgi8AaznE8NKJiXryb6
qyCTXxfrpbUUfRFLpPtFo8p7wg+vqrnTqCGAvMUUR/M=
```
Sure enough, that's three lines, but kubectl is OK with it.

```
metallb$ kubectl create secret generic memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
secret/memberlist created
```

I'm curious to see how your setup differs from mine.

**Comment by fedepaol** [comment]
Closing this as it's pretty old, and we did not have any other reports. Feel free to reopen in case you are still hitting it.
