### ISSUE TITLE
MetalLB reject new config when IP are already attributed

### ISSUE THREAD

**Issue by champtar** [metallb/metallb#660]
A wrong ip was configured, then attributed by MetalLB

After fixing the configuration:
```
{"caller":"main.go:117","configmap":"metallb-system/config","error":"new config not compatible with assigned IPs: service \"ingress-nginx/ingress-nginx\" cannot own \"10.254.145.63\" under new config","msg":"applying new configuration failed","op":"setConfig","ts":"2020-07-07T11:26:49.584367712Z"}
```

Fixing the configuration requires restart of the controller.
This behavior is safe but really confusing, at least we need to be explicit in the log message.

MetalLB 0.9.3

**Comment by johananl** [comment]
This is described in https://github.com/metallb/metallb/issues/462 AFAICT.
