### ISSUE TITLE
Unify logging

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#664]
We should take a look at the way we instantiate loggers and pass them around the codebase and make sure things make sense there.

For example, in the speaker code we instantiate a logger in `main.go`:

https://github.com/metallb/metallb/blob/80bfe1cf45bf4338e6eced11ab7a88d3d2356663/speaker/main.go#L65

We then use it directly within `main.go`...

https://github.com/metallb/metallb/blob/80bfe1cf45bf4338e6eced11ab7a88d3d2356663/speaker/main.go#L86

...and pass it around to other packages:

https://github.com/metallb/metallb/blob/80bfe1cf45bf4338e6eced11ab7a88d3d2356663/speaker/main.go#L138-L142

However, in some cases we seem to be doing something else:

https://github.com/metallb/metallb/blob/80bfe1cf45bf4338e6eced11ab7a88d3d2356663/speaker/main.go#L122-L123

We should try to use one "standard" way for logging in the project. If there are cases where we have to do something special, we should explain it in a comment.

**Comment by johananl** [comment]
While we're at it, we may want to switch to the standard library `log` library unless there is a good reason to use `go-kit`. The `go-kit` logger seems to return an error for some reason, which causes a linting hassle since we aren't checking these errors.

**Comment by champtar** [comment]
We have proper json logs, if we move to anything it's structured logs like k8s but why go back to free form log ?

**Comment by johananl** [comment]
> We have proper json logs, if we move to anything it's structured logs like k8s but why go back to free form log ?

That's why I wrote "unless there is a good reason to use go-kit"...

My main concern is the fact that we currently have to either error-check every logging statement or deal with linting errors (see https://github.com/metallb/metallb/pull/855). I didn't say we should stop doing structured logging.

**Comment by champtar** [comment]
The last exemple you are giving is normal, memberlist expect a stdlib logger so we wrap our go-kit logger allowing to have every memberlist logs tagged with "component: Memberlist".

**Comment by champtar** [comment]
For me std log == free form, and you hinted at going to std log ;)

**Comment by champtar** [comment]
I would also prefer to switch library that tag the whole codebase with linter silencer :)

**Comment by champtar** [comment]
Also if we could have log level we could silence Memberlist by default

**Comment by champtar** [comment]
> Maybe we could wrap this logger in a new metallb package and handle the error in that package.

We don't want to loose the call site (file/line) IMO
