### ISSUE TITLE
Add Copyright Year and Name to the License

### ISSUE THREAD

**Issue by sha224** [metallb/metallb#666]
Right now, the license is the default template that GitHub automatically provides. It needs to be modified [here](https://github.com/metallb/metallb/blob/main/LICENSE#L190) to reflect the copyright year and name. I stumbled upon this while filling out a Software Approval Form at my job which requires me to provide the copyright holder's name and the copyright year.

**Comment by russellb** [comment]
I do not believe that changing the LICENSE file is correct.  That is the literal text of the license: https://www.apache.org/licenses/LICENSE-2.0.txt and is just providing general instructions about noting the license within another file

**Comment by sha224** [comment]
My bad. I misunderstood how licensing a project works. Thanks for the clarification.
