### ISSUE TITLE
support selecting the source address when speaker sets up a bgp session

### ISSUE THREAD

**Issue by deitch** [metallb/metallb#670]
When the speaker sets up a bgp session, because this is low-level networking, it sometimes is important to set the source address for the socket without necessarily relying on the kernel's routing table. 

This [line in the speaker](https://github.com/metallb/metallb/blob/81dc21aa9ae9aa7478bb93523fb4664ce7f3ecf1/internal/bgp/bgp.go#L523) explicitly just takes the default:

```go
func dialMD5(ctx context.Context, addr, password string) (net.Conn, error) {
	laddr, err := net.ResolveTCPAddr("tcp", "[::]:0")
```

We already have the ability to set the `router-id` in the config yaml. For example, if I have 2 addresses on my default interface, say private `10.10.10.10` and public `100.200.100.200`, with the default route set to via the public, then if in a certain config I use the router-id as 10.10.10.10, or even 10.100.100.100, I will want to do one of two things:

* use the router-id as my source address - this was suggested in #422 with a related PR that was closed for reasons unknown
* explicitly set the source address

Either of these would work. The UX on the config would look something like:

```yaml
    peers:
    - my-asn: 65000
      peer-asn: 65530
      peer-address: 1.2.3.4
      router-id: 10.10.10.10
      router-id-as-src: true
```

or 

```yaml
    peers:
    - my-asn: 65000
      peer-asn: 65530
      peer-address: 1.2.3.4
      router-id: 10.10.10.10
      src: 10.10.10.10
```

The second seems a bit redundant, but is flexible in certain cases.

FWIW, much bgp-aware routing software has the possibility to do this, bird being the most prominent example.

In our use case, metallb flat out doesn't work without being able to control the packets. We could mess around with routing tables on the host, but there are 2 major shortcomings to it:

1. We don't always have access to the host; the speaker _is_ the agent that runs on the host.
1. More importantly, I don't always want packets targeted at 1.2.3.4 to be sourced from 10.10.10.10. It is just for certain low-level things (like bgp from the metallb speaker).

I am more than happy for this to be an option, rather than the default, but some way to make it happen is important.

cc @johananl @rata

**Comment by rata** [comment]
Hi @Avi Deitcher. I'm not sure I got the use case. Can you please comment on the scenario where this is needed? To better understand.

Also, I understand the source IP selected by the kernel is not guaranteed to be the one that you want, but the route (next-hop) the kernel will use is okay and you don't want to update the host routing table? Or do you have some source IP routing configured and you need to set the source IP to use that route or something like that?

**Comment by deitch** [comment]
Hi @rata

Correct. The source IP selected by the kernel is not the one we need to use, but the next hop is correct. In theory, we could try to update the host routing table but that has two issues:

- We might not have access to the host to modify it. Often, this (the speaker) is the only DaemonSet that is controlling routing, and we don't want to add logic to play with routes here. 
- More importantly, this routing rule (get to the peer IP range using specific source) is true only for this specific case, the bgp peer, and not in general. 

This very much is a specific source IP routing and control in the network infrastructure, as you surmised.

The question I would ask is, is there any reason not to do it as an option?

**Comment by adamdunstan** [comment]
@deitch Its quite easy to change to routerID because its uniform to all of the speakers however, changing the source is not as simple because each node requires a different address.  Routing software (bird and FRR) have logic they use filters to import and export routes between their routing tables and the host routing tables based upon interface pattern masks,  an alternative would be to use an interface mask as a filter.  MetaBGP has a very simple BGP process, it just advertises routers, it doesn't change the host routing table, it does have hostnetwork access, that is  needed to send from the host IP.  Not following your use case, are you simply trying to address the problem of multiple BGP speakers on the node (metallb and another), that has been covered elsewhere at length or policy routing at the other end of the peer messing up your sessions?

**Comment by deitch** [comment]
@adamdunstan wrote:

> Its quite easy to change to routerID because its uniform to all of the speakers

Indeed.

> changing the source is not as simple because each node requires a different address

And yet, I can set it on bird or FRR, as you mentioned, whether explicitly or with patterns. I can set it on any networking software I write, and many do. Something as basic as nginx or apache (which is listening, not sending, but same idea) lets me pick which IPs to listen on (and hence the source of the response packet). Even the very basic `ping` has `ping -S <src-addr>`. I am hard-pressed to think of network-related software (high-level or low-level) that doesn't let me do it, although I am sure they must exist.

In terms of "each node requires a different address", there is a number of ways to handle this. We already support selectors, so it is easy to narrow the peer config based on a selector. I have a kubernetes controller deployed that modifies the ConfigMap for exactly that purpose, since who says that the upstream peers are the same for all nodes. In my case, they are very different by node.

An alternative would be more complex, supporting some kind of pattern, e.g. "set the source IP to the first private ipv4 address on interface X", but I am skeptical we want to go down that path.

Besides, isn't "router-id" exactly that? I have speaker running on 4 nodes, the router-id had better be different.

> have logic they use filters to import and export routes between their routing tables and the host routing tables based upon interface pattern masks

Or you can set the source address per-bgp peer explicitly or for all of them.

> MetaBGP has a very simple BGP process, it just advertises routers, it doesn't change the host routing table, it does have hostnetwork access, that is needed to send from the host IP.

Agreed, metallb is not trying to change the _host_ routing table, nor should it, in my opinion. But every software that can open a network connection to send packets can select its source address, even if it is not sufficiently privileged to change the host routing table.

If I advertise routes, send an icmp ping, make an http request, open an ssh connection, whatever I do, I always have the option of selecting my source IP when creating the local side of the socket, or just letting the kernel assign it.

What I am recommending here is not that the speaker get involved in changing host routing tables, but rather that it have the option to do what every piece of network-using software can do, i.e. select its source IP.

> are you simply trying to address the problem of multiple BGP speakers on the node (metallb and another)

Funny you say that. This is not my current use case, but someone messaged me yesterday to say that they are starting to look into that. What are the chances I look back on my Slack messages and it was us? 😀

> policy routing at the other end of the peer messing up your sessions

Indeed. It is common for the network infra to handle packets that are coming from the same interface to the same switch differently based on the source IP (or destination IP, obviously). I might let your packet go to my BGP peer if your source IP is a private address but not a public one, or I might route all public-IP-sourced packets directly to the internet gateway, but private-IP-sourced packets to a broader range of internal peer systems or network devices.

Again, coming back to my summary question: given that (a) it is quite common in network-related software to have the option to set a source IP (viz. ping, nginx, apache, bird, etc.), and (b) it is easy to do technically (a single line I referenced above, plus the extension of the config to support it), why would we _not_ do it?

**Comment by deitch** [comment]
Heh, curl too: `curl --interface 10.10.10.10 https://example.com`

**Comment by deitch** [comment]
BTW @johananl referenced me to how calico does this [here](https://docs.projectcalico.org/reference/node/configuration#ip-autodetection-methods).

It has a series of "algorithms" from which you can pick that calico uses to decide the source interface. That would go a long way towards your comment @adamdunstan :

> each node requires a different address

Something like that - where I might have a `first-private-ip` algorithm or similar would work as well.

But at this point, anything that lets us control the source is a big step up.

**Comment by adamdunstan** [comment]
In previous implementation project, I have been able to work around this problem.  That said, I do understand the problem, many of the workarounds create other reach-ability problems especially during failures and make the routing topology unnecessary complex.   

A NIC filter mask would be a simple solution, however I didnt read the L2 code, only the BGP code.  The current version of metallb use a single speaker, not sure exactly whats going on in the L2 code or the best place to put this selection.  It could be valuable in both modes.  Separating the speakers has been suggested previously, this would make it much easier to add new features.

**Comment by deitch** [comment]
Yeah, exactly. The reality is that this is low-level software, so every solution to any problem comes with its own problems. :-)

> A NIC filter mask would be a simple solution, however I didn't read the L2 code, only the BGP code.

Not 100%. You might have 2 IPs on the same NIC and need to use one of them (I do). It would work in some cases.

My personal preference is the rules engine @johananl mentioned, followed by an IP regex, followed by just a fixed IP. But for now, I would like the fastest solution that doesn't constrain us going forward. That probably is the fixed IP.

**Comment by johananl** [comment]
I agree that being able to influence the source IP address used for BGP sessions makes sense.

As far as I can tell, right now we are using the equivalent of `0.0.0.0` as the source address in the socket, which likely makes the kernel select the actual IP that ends up used.

For the sake of simplicity, I'm wondering if it would be enough to change the default behavior to be "find the IP address via which you would reach the remote peer address and use that address as the source". This is basically the `can-reach` algorithm in Calico where the remote peer address is used as the destination.

@deitch would that address your use case? If so, this will be simpler than implementing multiple fancy options for figuring out the source address like Calico does (but of course we can add more of those in the future).

Personally I am not fond of "use the router ID as the source". I'm aware it can solve your use case but at the BGP level it doesn't make sense to me to couple the source IP address with a router ID. A router always has one router ID but often multiple interfaces used for multiple BGP peers. For that reason it's common to use **loopback** interfaces for the router ID, namely interfaces which aren't connected to a specific peer, while using the physical interfaces for the source/destination of BGP sessions:

![Untitled Diagram (1)](https://user-images.githubusercontent.com/14969425/87690071-462ca780-c789-11ea-82c2-a593dae339a7.png)

In the diagram above, Peer 1 sees `10.0.0.1` as the source IP address in packets sent by Router 1 while seeing `1.2.3.4` as the router ID. Peer 2 sees `10.0.0.5` as the source IP and still `1.2.3.4` as the router ID.

**Comment by champtar** [comment]
It seems to me a lot of BGP configurations (and some L2) are pending proper per speakers config, maybe someone need to tackle that and then it'll be easy to fix many of the open issues
my 2 cents

**Comment by deitch** [comment]
> Personally I am not fond of "use the router ID as the source". I'm aware it can solve your use case but at the BGP level it doesn't make sense to me to couple the source IP address with a router ID.

You make a good argument there. I believe bird has an option to use it using `router id from ... `, which is what led me to suggest it, as a possible simple solution.

> find the IP address via which you would reach the remote peer address and use that address as the source
> 
> @deitch would that address your use case?

How do you define, "find the IP address via which you would reach the remote peer"? Do you mean you would find every address on the device (ignoring loopback and CNI and...) and try to reach the peer on the bgp port? So wherever we can get a proper session going?

It might be a bit slow - if you have 6 IPs on 3 interfaces, then you need to define the timeout, etc. - but it definitely would be better than what we have now. 

Essentially, you are adding "hidden smarts" to the peer session setup, without changing the config at all. Ironically, I think this would be _harder_ to implement than a static config for the source address, but _easier_ to manage, as the config doesn't change.

If I understood it correctly, it would answer, but how hard/long would it take to do it?

**Comment by deitch** [comment]
@champtar wrote:

> It seems to me a lot of BGP configurations (and some L2) are pending proper per speakers config, maybe someone need to tackle that and then it'll be easy to fix many of the open issues

There is per-speaker config, based on labels. That is exactly what I do in my environment where the peer is different per speaker. What I don't have is the ability to configure the source IP, though.

**Comment by johananl** [comment]
@deitch the `router id from` is the _other_ direction: configure the router ID based on the IP address used to talk to the peer. This option **does** make sense to me and is already implemented by MetalLB: since MetalLB supports per-peer router IDs, it makes sense to just let MetalLB set the router ID based on the IP address that is used as the source IP address when talking to some router. But you are trying to influence the source IP, not the router ID.

>How do you define, "find the IP address via which you would reach the remote peer"?

By consulting the Linux routing table. Quoting the Calico [docs](https://docs.projectcalico.org/reference/node/configuration#can-reachdestination):

>The `can-reach` method uses your local routing to determine which IP address will be used to reach the supplied destination.

We don't have to send packets to figure out reachability to an address. Calico solves this problem by opening a UDP socket, checking which address was used by the kernel for the socket and then using that address. See [here](https://github.com/projectcalico/node/blob/a94f4dfa070dc7ae2f325846aafe0f41b4321714/pkg/startup/autodetection/reachaddr.go#L26).

I agree that actually sending packets to determine reachability is a bad idea.

>If I understood it correctly, it would answer, but how hard/long would it take to do it?

I think this is a relatively simple feature if we're talking about changing the default to use the "can reach" logic instead of whatever the kernel gives you by default. To me it makes more sense than hardcoding the source address in the config (but there is nothing that's preventing us from having *both* as far as I can tell).

**Comment by johananl** [comment]
> It seems to me a lot of BGP configurations (and some L2) are pending proper per speakers config, maybe someone need to tackle that and then it'll be easy to fix many of the open issues
> my 2 cents

@champtar yes, I've tagged a bunch of issues with the `flexibility` label, some of which deal with per-speaker config. I've also opened https://github.com/metallb/metallb/issues/630 to discuss a generic mechanism which would allow flexible combinations of speakers and pools. As far as per-speaker **BGP** config, you can already tune most of the important BGP parameters at the *peer* level. If you think there is a place to discuss tuning parameters at the *speaker* level as well, feel free to open an issue.

**Comment by deitch** [comment]
> By consulting the Linux routing table. Quoting the Calico docs:

That wouldn't work. Let's say I have 2 IPs on my `eth0`, with the following upstream gateways:

* private `10.10.10.10` upstream `10.10.10.1`
* public `20.20.20.20` upstream `20.20.20.1` (no idea how I managed to snag that great public IPv4 address).

My peer is somewhere unique, say, `169.254.10.20`, and my routing table looks like:

```
default via 20.20.20.1 dev eth0
10.0.0.0/8 via 10.10.10.1 dev eth0
```

If you looked at the routing table, you would source via `20.20.20.20`. I may or may not want that. 

This issue is specifically where the routing table is _not_ sufficient to determine the source. Going back to my original comment opening the issue:

* I may not be able to change the routing table, since metallb speaker _is_ the DaemonSet process running on every host, and we do not want to get the speaker in the business of changing routes
* I may not want to change the routing table, since that route - using the private `10.10.10.10` as the source - may be only for bgp, and not for other purposes. This is quite common when dealing with networking protocols.

**Comment by deitch** [comment]
Of course, I might have completely and totally misunderstood it @johananl ; wouldn't be the first time! 😂

**Comment by deitch** [comment]
To emphasize:

> may be only for bgp, and not for other purposes. This is quite common when dealing with networking protocols.

This is _precisely_ why curl, ping, bird, etc. etc. all have options to set the source interface and address explicitly.

**Comment by deitch** [comment]
Ironically, metallb actually allows you to set the local address to use when binding for the member list, but not when binding for BGP peers. See [here](https://github.com/metallb/metallb/blob/80bfe1cf45bf4338e6eced11ab7a88d3d2356663/speaker/main.go#L76)

**Comment by johananl** [comment]
@deitch Sorry, I guess I was assuming that there is a route towards your BGP peer which points at the interface with the correct IP address. If your default route is what gets selected and `20.20.20.20` isn't the right address, you are right that my proposed solution wouldn't work.

To emphasize, the "can reach" solution doesn't work for cases where the route in the speaker's route table uses a source address that isn't the desired address. In your specific case, the following is true:

- The peer address isn't directly connected.
- There is no specific route towards the peer address in the speaker's route table, which means the default route applies.
- The address that's specified as the source address in the default route is not the desired address to be used as the source.

**Comment by johananl** [comment]
So, allowing the user to hardcode a source IP address in the ConfigMap is probably the simplest solution to implement. It won't cover all cases but I guess we can always consider adding fancier solutions like IP autodetection in the future.

I'm wondering if adding a `source-address` knob to the `peers` section makes sense to people:

```yaml
    peers:
    - my-asn: 65000
      peer-asn: 65530
      peer-address: 1.2.3.4
      router-id: 10.10.10.10
      source-address: 10.10.10.10
```

One downside is that one would have to edit the ConfigMap and specify the correct source for each peer. Another problem that I'm seeing is that a MetalLB peer can be applied to multiple speakers, in which case hardcoding an address can't work because each speaker has different IP addresses.

@rata @daxmc99 WDYT?
@russellb @caboteria please feel free to chime in as well.

**Comment by deitch** [comment]
You're right @johananl ; it wouldn't work. I had thought you meant "can-send" would send out packets and try to detect. That would work well. 

For now, simplest may be hard coding it. It is just an option, so anyone not wanting it can avoid it, and we can make this smarter later.

**Comment by johananl** [comment]
Right. So if we add `source-address` we would have to put a note in the docs saying "this can only be used when a peer is applied to a single node".

I'm trying to think if there is *some* generic way to indicate which IP address to use without hardcoding. I guess the tricky part is that you have multiple IP addresses *on the same NIC* so you can't just say "always use the address from `eth0`".

**Comment by deitch** [comment]
Well you could use it on multiple, but it might get weird. 

There are lots of ways, like regex or discovery (send packets as each IP until you get a response), but those are harder to implement.

**Comment by johananl** [comment]
Yeah. Well, for one thing this sort of hardcoding works well with peer autodiscovery which we're trying to get merged (https://github.com/metallb/metallb/pull/593).

**Comment by johananl** [comment]
I guess we can fall back to the current behavior if the source IP address doesn't apply to the speaker host (namely when the host doesn't have such an IP address).

**Comment by johananl** [comment]
Opened https://github.com/metallb/metallb/pull/672 as a draft implementation. Seems to work fine on my testing.

**Comment by johananl** [comment]
Following discussions I've closed #672 and incorporated the source IP selection into #593.

**Comment by briantopping** [comment]
I kind of lost track of this since #423, but it seems that this bike shed has become a world class facility for keeping vehicles that do not belong in the office perfectly dry! 😂😂😂

I will go ahead and close #422. I only came back to this after seeing the #423 source in my local tree and was wondering if I could delete it or not. 

Do people like @rata think it's finally time after three years to get these changes merged? I'd personally rather have a misfeature that doesn't impact existing users who don't attempt to use it than no options whatsoever when the need arises.

**Comment by russellb** [comment]
> Do people like @rata think it's finally time after three years to get these changes merged? I'd personally rather have a misfeature that doesn't impact existing users who don't attempt to use it than no options whatsoever when the need arises.

Are you referring to a specific open PR, or just that you want this issue resolved in general?

**Comment by briantopping** [comment]
Thanks @russellb. Of course this is open source and I was trying add a little humor to the endeavor. These efforts look excellent and it's hard to believe they could get much better without more community feedback than will be available as un-merged PRs. This consumed some weeks of time back when I first found the problem and ran custom builds for two years until I found room in my cage to add a router that could IGP to my boxes and EGP to my ISP. 

Another option with this is to simply leave the features undocumented but merged. Those who read source would find it and use it. It's kind of an underground means of testing in the wild without subjecting those who might not be ready for random behavior. $0.02.

Thanks for your continued work on the project and congrats to the team for the Cilium integration!

**Comment by flokli** [comment]
There's a specific usecase for a simple `source-address` field described in https://github.com/equinix/cloud-provider-equinix-metal/issues/178 (where there is per-node peer configs, so configuring explicit IPs is fine).

It'd be really nice if something like @johananl's https://github.com/metallb/metallb/pull/672 could be resurrected - we could add a big fat warning to the docs that this shouldn't be set for multiple speakers (so explicitly pinned to specific nodes).

I assume having something like this as a first step would fix a lot of these usecases, and are probably easier to build than complicated source address discovery strategies like [Calico](https://docs.projectcalico.org/reference/node/configuration#ip-autodetection-methods) implemented.

**Comment by johananl** [comment]
I just took a fresh look at this again. Initially I meant to merge a solution for source IP configuration as part of #593, however looking at the current state of #593 I can't see the relevant commit(s) there. In addition, I vaguely recall discussing the separation of source IP configuration from peer autodiscovery (likely with @rata), and in any case it does make sense to me not to couple the two features together (because even though peer autodiscovery is going to allow specifying source IPs, we also want to allow specifying source IPs for per-node peers in the static config).

So, I'm going to take a fresh look at the implementation proposed in #672 and open a new PR. I think we can drive this towards a merge fairly quickly.
