### ISSUE TITLE
Update Code of Conduct contact information

### ISSUE THREAD

**Issue by russellb** [metallb/metallb#675]
MetalLB has a code of conduct here: https://metallb.universe.tf/community/code-of-conduct/

It currently still lists Dave's email address as the contact.  This should probably be updated to be one/some/all of the current maintainers.  Perhaps it could point to the maintainers page once this PR goes in: #661

**Comment by rata** [comment]
@russellb I think I lean towards asking Dave later if he prefers to be the contact or not. Maybe he wants to still be there, and is more of an outsider now that he is not so active, so it can be a good thing :-)

**Comment by russellb** [comment]
Yeah, good point!  

@danderson thoughts?

**Comment by danderson** [comment]
I'm fine with it being a current maintainer. Fingers crossed, it'll never be an issue either way, but the contact should be someone actively working on MetalLB, i.e. not me :)

**Comment by rata** [comment]
Thanks. Added this to the next community meeting, in case someone wants to discuss something else. I volunteer for being the point of contact :)
