### ISSUE TITLE
netstat does not show port 443 open 

### ISSUE THREAD

**Issue by mseewooth** [metallb/metallb#684]
Hello, 

I have deploy metallb on my cluster. Its working gr8 but i have a question. 

When i telnet the ip of worker-node 1 : 

```
 telnet 95.XXX.XXX.XX 443
Trying 95.XXX.XXX.XX...
Connected to 95.XX.XX.XX.
Escape character is '^]'.
```

But when i do a netstat -ntplu |grep 443 on that server 95.XXX.XXX.XXX 

I do not see such port 443.  

Can someone please explain ? 

Thanks

**Comment by Aoana** [comment]
Hi!

MetalLB is working with a single resource within K8s and that is the External-IP (VIP) of services of type:Loadbalancer.
Reaching the worker node IP directly, MetalLB is not (should not) be involved at all.
Unless your system is wrongfully configured and you have set worker IPs as the range of IPs in MetalLB address pools (?).

Could you explain a bit more why you believe this is related to MetalLB?
Are you not able to reach 95.XXX without MetalLB installed? (if unsure please verify without MetalLB)

Best Regards
Anders

**Comment by mseewooth** [comment]
Hi, 

I'm not sure its related to MetalLB. In the configmap of metallb , i have assigned the ip 95.xx only . there's no range of ip etc. 

The server 95.xxx without metallb , apache or nginx when telnet on port 80 or 443 returns connection refused  which sounds normal. 

Metal lb deployed with ingress 80, 443 deployed. When i telnet ip 95.xxxx on 80 or 443 ,  its connected with is ok for me. 

But when i log into server 95.xxx and do a netstat -ntplu to grep the port 80 or 443 , netstat does not show me the port established or listening while the telnet on 95.xxx reponds correctly , even i have sites loading on that ip 95.xxx 

It do not have a problem with metal LB, i just want to know why a netstat -ntplu |grep 80 on ip server 95.xx does not display the port 80.

**Comment by adamdunstan** [comment]
Not really an issue, would suggest that you move this to the slack channel and ask questions there.   Metallb doesnt have anything to do with opening ports, it just attracts ip traffic to nodes and k8s distributes from there.   The status of specific ports and how they are handled is undertaken by k8s and probably in this case programmed by kubeproxy.  An external service (what metallb provides) with kubeproxy in iptables mode matches a pre-routing rule.

**Comment by champtar** [comment]
Your server is not listening on 95.xxx, MetalLB controller "patch" your k8s load balancer service, and kubeproxy uses iptables to add rules to redirect the traffic to the endpoint. There are multiple ways on Linux to receive traffic: use a normal socket, redirect traffic to another socket (on another host) using iptables/nftables/tc (not sure)/XDP eBPF, and also raw sockets (tcpdump uses raw sockets)

**Comment by Aoana** [comment]
Hi!

I agree with @adamdunstan, please close ticket and post a question in slack channel if needed more discussion, this is not an issue on MetalLB most likely.
Your 443 socket will be visible inside the pod of Ingress Controller most likely.
A pod by default runs in its own linux network namespace and is not visible on host.
So when you use the workernode ip as VIP you get forwarded to the linux netns and reaches the socket (why telnet works).
Use slack and ping me AndersMarkendahl

Best Regards
Anders

**Comment by mseewooth** [comment]
Hello, 

Thank for the clarification

**Comment by mseewooth** [comment]
https://www.stackrox.com/post/2020/01/kubernetes-networking-demystified/
