### ISSUE TITLE
Issue Metallb re-assigning IP , bogus

### ISSUE THREAD

**Issue by DarkBlaez** [metallb/metallb#686]
Question, how do I stop metallb from re-assigning IP addresses when a service is removed. This creates an issue when certain services are referenced by IP.

Example:

1. svc1: 100.100.0.10
2. svc2: 100.100.0.11
3. svc3: 100.100.0.12

If service 2 gets removed service 3 not gets a new IP of 100.100.0.11. This by default should not happen. While using DNS not an issue but if IP based this creates an issue.

Thanks
DB

**Comment by DarkBlaez** [comment]
Guess no-one can address this behavior that should not exist. When MetalLB assigns an address that is requested from the DHCP server, it should not reassign the IP addresses of other entities once a resources is released. This is by far the most cumbersome behavior I have seen.

**Comment by champtar** [comment]
@DarkBlaez what version are you running ?
are you restarting your cluster ? or metallb controller ?
you can force the ip using `loadBalancerIP` field

**Comment by russellb** [comment]
Can you provide more details about how to reproduce this behavior?  I just tried this and was not able to reproduce.

```
kubectl get svc
NAME         TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)        AGE
kubernetes   ClusterIP      10.96.0.1        <none>         443/TCP        10d
nginx        LoadBalancer   10.106.88.254    192.168.10.0   80:30076/TCP   10d
nginx2       LoadBalancer   10.106.62.241    192.168.10.1   80:30286/TCP   6s
nginx3       LoadBalancer   10.110.165.254   192.168.10.2   80:30485/TCP   3s

$ kubectl delete svc nginx2
service "nginx2" deleted

$ kubectl get svc
NAME         TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)        AGE
kubernetes   ClusterIP      10.96.0.1        <none>         443/TCP        10d
nginx        LoadBalancer   10.106.88.254    192.168.10.0   80:30076/TCP   10d
nginx3       LoadBalancer   10.110.165.254   192.168.10.2   80:30485/TCP   15s
```

**Comment by DarkBlaez** [comment]
What I have found is that this, lets say I have 50 IP addresses assigned to services through MetalLB. If say service #25 gets deleted, then services those already assigned above it will get reassigned starting with the deleted service's IP. While I can assign IP addresses and that works fine, I am finding that there is an active re-assignment even when things do not get deleted, they just happen to get their original IP addresses.

I am using metallb v0.9.3 (controller) and same for the speaker. This is on k3os

My ConfigMap:

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 10.10.10.254
      peer-asn: 64512
      my-asn: 64513
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.25.0.10-10.25.3.250
Pfsense DHCP server is assigning the IPs.

**Comment by champtar** [comment]
did you disable k3s LoadBalancer ? can you make sure you don't have multiple MetalLB running somehow ?

**Comment by russellb** [comment]
> did you disable k3s LoadBalancer ? can you make sure you don't have multiple MetalLB controller running somehow ?

yeah, another controller fighting the MetalLB controller would explain this and why I'm not able to reproduce

**Comment by DarkBlaez** [comment]
MetalLB is the only service running as the LB. k3os by default uses Traefik. However, upon install of all k3os nodes I insure it is disabled.

**Comment by DarkBlaez** [comment]
Think I found the issue, seems k3os by default includes a less feature rich LoadBalancer, aervicelb , I think this is still running and needs to be disabled, which means fresh install...arrrgg. Guess it is what it is. I will see about about reinstalling this cluster. Let's leave this issue open but pause until I confirm. Thanks

**Comment by DarkBlaez** [comment]
The issue was indeed related to servicelb running in k3os/k3s and thus requires a re-install of the cluster to resolve. Thank you for bringing this to my attention, I would have never thought to look for another LB running. K3s/k3os documentation is lacking so never so this enumerated. Thanks again
