### ISSUE TITLE
Move website to CNCF-provided Netlify account under metallb.io

### ISSUE THREAD

**Issue by russellb** [metallb/metallb#691]
@johananl and @rata say that the `metallb.io` domain was registered by Kinvolk for use by the project.  As a first step we should migrate the web site to use this domain.

**Comment by russellb** [comment]
https://metallb.universe.tf/community/#the-website discusses how the web site works.

It looks like this move will take 2 steps:

1. Netlify configuration to add a new domain alias for the site, `metallb.io`
2. After #1, the owner of `metallb.io` will need to update DNS to point to netlify, per their documentation

https://docs.netlify.com/domains-https/custom-domains/#definitions

cc @daxmc99 as well

**Comment by russellb** [comment]
From a slack conversation, it turns out @danderson had already registered `metallb.org`.  It's partly set up, so we should just finish that setup and move to that as the primary domain.

Dave also says he's happy to hold on to the domain until we sort out a long term owner for it.

**Comment by russellb** [comment]
An update, 1 year later!
 
 We've been accepted into the CNCF Sandbox (https://github.com/cncf/toc/issues/720) and are transferring all domains to the CNCF: metallb.org/.com/.net/.io.

We had a super formal poll on slack about which domain we'd like to use as primary and the top choice was metallb.io.  https://kubernetes.slack.com/archives/CTU63S7K3/p1632411847071100

We'll need to update both metallb.io DNS and netlify configuration to get metallb.io fully set up, though.  We can follow up on that once domain transfers are complete.

**Comment by johananl** [comment]
Summarizing the TODO items:

- [ ] Finish transferring all MetalLB domains to CNCF
  - [ ] metallb.io
  - [ ] metallb.org
  - [ ] metallb.com
  - [ ] metallb.net
- [ ] Request Netlify access from CNCF
- [ ] Move website to CNCF-provided Netlify account
- [ ] Configure metallb.io as the "main" domain
- [ ] Set up HTTP redirects for the rest of the domains to metallb.io
- [ ] Look for references to metallb.universe.tf and replace them with metallb.io

**Comment by danderson** [comment]
Still needed, still blocked on CNCF induction process.

**Comment by danderson** [comment]
I don't appear to own this domain any more, so I guess it's out of my hands at this point. Unsubscribing so I stop getting the passive-aggressive robot nags that I have no power to address.

**Comment by RobertKielty** [comment]
A service desk request has been logged and I am traging the work to be done on this now.

**Comment by fedepaol** [comment]
Thanks @RobertKielty !

**Comment by RobertKielty** [comment]
@fedepaol I have completed the initial triage, check the request you should have an email notificaion.

Lets track the work on your CNCF Service Desk request

We can post outcomes and results of our work here.

@danderson I may need to liase with you to transfer accross the Netlify Site. Best place to reach me to do this would be on the CNCF Slack if you have access to that.

**Comment by danderson** [comment]
@RobertKielty Sure thing, I've joined the CNCF slack, I'm `danderson` there too. FWIW for coordination, I'm in the US Pacific timezone.

**Comment by danderson** [comment]
Migration of the Netlify site is done, I updated the checklist in https://github.com/metallb/metallb/issues/691#issuecomment-931193105 with the completed items.

**Comment by danderson** [comment]
In terms of remaining references to metallb.universe.tf: there are many website links, the Go package canonical location, and k8s annotation names.

I'll keep metallb.universe.tf serving a website for as long as practical (I assume at least several years, but no specific SLA). Right now it's still pointing at the same netlify site and serving the live site directly, can I suggest also setting up a 301 permanent redirect? universe.tf is the canonical URL that shows up in search engines, it would be good to teach them the new location.

Similarly, `go.universe.tf/metallb` will continue to serve the appropriate redirects to make go mod happy for as long as practical. But updating the paths would be good to ensure everything's under the project's direct control.

k8s annotation names: I can't remember how annotation migration works in k8s, so I'll leave that to you.

**Comment by fedepaol** [comment]
> In terms of remaining references to metallb.universe.tf: there are many website links, the Go package canonical location, and k8s annotation names.
> 
> I'll keep metallb.universe.tf serving a website for as long as practical (I assume at least several years, but no specific SLA). Right now it's still pointing at the same netlify site and serving the live site directly, can I suggest also setting up a 301 permanent redirect? universe.tf is the canonical URL that shows up in search engines, it would be good to teach them the new location.

Makes sense, I'll file an issue to avoid forgetting it

> 
> Similarly, `go.universe.tf/metallb` will continue to serve the appropriate redirects to make go mod happy for as long as practical. But updating the paths would be good to ensure everything's under the project's direct control.
> 
> k8s annotation names: I can't remember how annotation migration works in k8s, so I'll leave that to you.

I'll handle this part.

Thanks again for the help!

**Comment by fedepaol** [comment]
I filed https://github.com/metallb/metallb/issues/2393, https://github.com/metallb/metallb/issues/2392, https://github.com/metallb/metallb/issues/2391 to track the leftovers. 

Closing this for good.
