### ISSUE TITLE
Move images to quay.io

### ISSUE THREAD

**Issue by rata** [metallb/metallb#696]
Just received an email from dockerhub. More info here: https://www.docker.com/pricing/retentionfaq
>
>    The container image retention policy will apply to the following plans:
>    * Free plans will have a 6 month image retention limit
>    * Pro and Team plans will have unlimited image retention
>
>    What is an “inactive” image?
>    An inactive image is a container image that has not been either pushed or pulled from the image repository in 6 or months.

We might want to consider other alternatives to Dockerhub. Today the paid option in dockerhub seems to be 7 USD per user per month.

cc @daxmc99 @johananl @russellb

**Comment by johananl** [comment]
We've decided to move to quay.io following discussions in the developer meetings.

**Comment by johananl** [comment]
TODO:

- [ ] Add Docker registry argument to `push-multiarch` Invoke [target](https://github.com/metallb/metallb/blob/ca572eca2098bef9005b060228ab431c6d3dee33/tasks.py#L134).
- [ ] Execute `inv push-multiarch` manually to make a test push to quay.io and verify things look sane for all supported architectures. [This](https://github.com/metallb/metallb/blob/ca572eca2098bef9005b060228ab431c6d3dee33/.circleci/config.yml#L39) can help.
- [ ] **Add** two jobs similar to [this](https://github.com/metallb/metallb/blob/ca572eca2098bef9005b060228ab431c6d3dee33/.circleci/config.yml#L26) one (while keeping the existing ones) to automatically push images to quay.io in parallel with Docker Hub.
- [ ]  Monitor things for a while and ensure things look sane on quay.io.
- [ ] Open a PR to point all the manifests at quay.io.
- [ ] Copy all existing images from Docker Hub to quay.io just in case.
- [ ] Retire Docker Hub repositories when we feel safe to do so.

**Comment by johananl** [comment]
I've added the option for specifying a Docker registry. WIP is [here](https://github.com/kinvolk/metallb/tree/johananl/quay).

Got bitten by https://github.com/docker/for-linux/issues/396 when Invoke executes `manifest-tool`. Looking for a fix/workaround that's nicer than asking everybody to do `chmod o+x /etc/docker`.

**Comment by johananl** [comment]
Started copying image from Docker Hub to Quay. We have about 264 images in each of the repositories (`controller` and `speaker`).
Copying is straightforward, however pull-pushing a multiarch image from Docker Hub to Quay doesn't automatically make it work for multiple architectures. I probably have to do the `manifest-tool` magic against Quay. Will update.

**Comment by johananl** [comment]
> Got bitten by [docker/for-linux#396](https://github.com/docker/for-linux/issues/396) when Invoke executes `manifest-tool`. Looking for a fix/workaround that's nicer than asking everybody to do `chmod o+x /etc/docker`.

I ended up doing `chmod o+x /etc/docker` and everything seems fine after that. On second thought "everybody" is just our CI so it's fine.

**Comment by johananl** [comment]
Pasting here the scripts I've used to perform the migration, for the record.

Getting a list of all images in a repo:

```python
import requests
import os
import json

docker_user = os.environ['DOCKER_USER']
docker_pass = os.environ['DOCKER_PASS']
docker_org = os.environ['DOCKER_ORG']
docker_repo = os.environ['DOCKER_REPO']

page_size = 100

r = requests.post(
    'https://hub.docker.com/v2/users/login/',
    headers={'Content-Type': 'application/json'},
    json={
        'username': docker_user,
        'password': docker_pass,
    },
)

token = json.loads(r.text)['token']

headers = {
    'Content-Type': 'application/json',
    'Authorization': f'JWT {token}',
}

r = requests.get(
    f'https://hub.docker.com/v2/repositories/{docker_org}/{docker_repo}/tags?page_size={page_size}',
    headers=headers,
)

tags = []

while True:
    j = json.loads(r.text)
    batch = j['results']
    next_page = j['next']

    tags += batch

    if next_page is None:
        break

    r = requests.get(next_page, headers=headers)

for t in tags:
    print(t['name'])
```

Copying all images from Docker Hub to Quay:

```bash
#!/bin/bash

set -eoux pipefail

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 <src> <dst> <tags_file>"
    echo "src - a Docker URI from which to copy images. Example: docker.io/foo"
    echo "dst - a Docker URI to which to copy images. Example: quay.io/bar"
    echo "tags_file - path to a newline-delimited file containing one image tag per line"
    exit 1
fi

src=$1
dst=$2
tags_file=$3

for tag in $(cat "${tags_file}"); do
    docker pull "${src}:${tag}"
    docker tag "${src}:${tag}" "${dst}:${tag}"
    docker push "${dst}:${tag}"

    docker rmi "${dst}:${tag}" "${src}:${tag}"
done
```

Filtering only multi-arch tags from the list of all tags:

```
cat controller.txt | sed -n '/-\(amd64\|arm\|arm64\|ppc64le\|s390x\)$/!p' > controller-multi.txt
cat speaker.txt | sed -n '/-\(amd64\|arm\|arm64\|ppc64le\|s390x\)$/!p' > speaker-multi.txt
```

Pushing multi-arch manifests:

```
for tag in $(cat controller-multi.txt); do manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x --template "quay.io/metallb/controller:$tag-ARCH" --target "quay.io/metallb/controller:$tag" --ignore-missing; done
for tag in $(cat speaker-multi.txt); do manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x --template "quay.io/metallb/speaker:$tag-ARCH" --target "quay.io/metallb/speaker:$tag" --ignore-missing; done
```

**Comment by johananl** [comment]
https://github.com/metallb/metallb/pull/769 is open for review.

**Comment by johananl** [comment]
> #769 is open for review.

Merged!

**Comment by mazay** [comment]
Just faced with `You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`.

Switched manifests for using `quay.io` repos, maybe the manifests should be upgraded or you may consider filling in this application for removing rate-limits - https://www.docker.com/community/open-source/application

**Comment by johananl** [comment]
Hey @mazay. Yes, we are definitely going to update the manifests (see TODO item above). We wanted to wait a bit and make sure things look OK on Quay before making the change.
