### ISSUE TITLE
Odd behavior, ArangoDb operator

### ISSUE THREAD

**Issue by DarkBlaez** [metallb/metallb#699]
Versions:
speaker/controller: v0.9,3
Arangodb operators: 1.0.5

Once the operators are deployed (CRD, Storage, Deployment) immediately metallb starts a start/end sequence for the storage operator and deployment operator. at least a set per second. This is nearly identical to what was seen when there was another LB within a cluster and the constant churn is the same. I have posted this odd behavior to the ArangoDB git as an issue as well. I would not expect this behavior when the operators are deployed and there is no reference to a type LoadBalancer. Unfortnualtey it makes the deployment of ArangoDb useless as the core/root of the issue is unknown. How can we go about troubleshooting this? It does not seem to happen with any other operators so uncertain what they are doing in the image deployments.

2020-08-17 12:04:39 | 2020-08-17T17:04:39.654050944Z stdout F "caller":"main.go:267","event":"startUpdate","msg":"start of service update","service":"default/arango-deployment-operator","ts":"2020-08-17T17:04:39.653864528Z"
-- | --
  |   | 2020-08-17 12:04:39 | 2020-08-17T17:04:39.653807672Z stdout F "caller":"main.go:271","event":"endUpdate","msg":"end of service update","service":"default/arango-deployment-operator","ts":"2020-08-17T17:04:39.653651675Z"

Thanks
DB

**Comment by russellb** [comment]
maybe something with arango is erasing the changes metallb makes to the service?

**Comment by DarkBlaez** [comment]
Hard to say, The operator looks like it is constructed ok. There are no LoadBalancer references so would assume metal would not pickup any references for ClusterIP. This is what I find odd is why metallb is interacting in this way where there are no type: LoadBalancer.

**Comment by russellb** [comment]
> Hard to say, The operator looks like it is constructed ok. There are no LoadBalancer references so would assume metal would not pickup any references for ClusterIP. This is what I find odd is why metallb is interacting in this way where there are no type: LoadBalancer.

Oh, then metallb probably isn't touching that Service at all if it's not a LoadBalancer.  It's just looking at it to see if it *should* do something with it.  Or do you have some confirmation that metallb has actually done something to it?

As to why it keeps looking at it, metallb is going to process it every time it changes.  If something else is changing it, metallb will keep looking at it to see if it's a LoadBalancer it should handle.  Maybe the operator is busted and keeps updating the service itself for some reason?

So far it sounds like metallb is behaving normally.

**Comment by DarkBlaez** [comment]
The metallb logs indicated that it is looking at it every second. So I suspect the operator is broken and causing something to keep updating the service. I think metallb is exhibiting the behavior it needs and that the ArangoDb operator is broken. We can close this, just wanted to get a second opinion since I suspected it's Arangodb. thanks

**Comment by russellb** [comment]
sounds good, thanks
