### ISSUE TITLE
Add IPv6 BGP support

### ISSUE THREAD

**Issue by danderson** [metallb/metallb#7]
Allegedly, IPv6 support is landing in 1.9 as an alpha feature. This is sooner than I expected, so I'll need to get a 1.9 test cluster set up with v6 support and make MetalLB support IPv6.

Among other things, this implies implementing MP-BGP, ugh.

**Comment by danderson** [comment]
Need a 1.9 cluster with v6 alpha features enabled. Tagging as such.

**Comment by jpds** [comment]
1.9 is now released. :-)

**Comment by valentin2105** [comment]
I got an IPv6-only running cluster,
Is metalLB ready for IPv6 ? I will give a try !

**Comment by mdlayher** [comment]
If you can run the latest build on master, I'd love to see if the IPv6 NDP speaker works!

**Comment by danderson** [comment]
I won't add IPv6 BGP support in 0.4, because it requires a bit more complicated work and I just want to get 0.4 released. I'll plan BGPv6 for a 0.5 followup soon after 0.4.

In the meantime, NDP should work right now, if you install using the manifests in github instead of those on the website. Feedback would be welcome! :)

**Comment by danderson** [comment]
Looking at this again...

One complication for BGPv6 is router ID selection. In IPv4, we can trivially use one of the node's IPv4 addresses as the router ID. But in a v6-only cluster, there is no obvious mapping we can use. Unfortunately, the RFCs that suggest how to pick a BGPv6 router ID all assume that you're manually configuring the world, which doesn't scale at all for what we're doing here.

The ugly solution for now is to lean on node selectors: you can define one peer for each and every machine, and use node selectors to constrain each peer to one hostname. That way, you can specify router IDs manually for each machine. This results in a massive MetalLB configuration, but at least it makes it _possible_ to make things work.

**Comment by danderson** [comment]
@valentin2105 Do you have pointers on how you set up your IPv6 cluster? I'm setting up integration tests that start a v6 cluster, some documentation would be helpful :)

**Comment by valentin2105** [comment]
@danderson Yes, sure, 
https://opsnotice.xyz/kubernetes-ipv6-only/
https://www.projectcalico.org/enable-ipv6-on-kubernetes-with-project-calico/

:)

**Comment by danderson** [comment]
Other options to solve the router ID problem...

The router ID only needs to be unique within an AS. So, we can try to generate router IDs, and if you use an eBGP session to the datacenter routers, all that matters is that there is no collision between MetalLB speakers.

Two ways of doing that:

- Hash the outbound interface MAC address into 32 bits, and use that as the router ID.
- Generate a new random router ID for each connection.

The first has the advantage of stable router IDs, but in the very unlikely case of a router ID collision, there's no way to fix it. OTOH, the second will autonomously fix itself after a collision, but might make debugging a bit harder.

**Comment by valentin2105** [comment]
Hi @danderson,

I currently trying MetalLB, in my production  IPv6-only environement, but face a first small issue, 
```
dial tcp: address 12ef:b400:e:18::ffff:179: too many colons in address
```
If I put some bracket, the config is invalid :  

```
 type: 'Warning' reason: 'InvalidConfig' parsing peer #1: invalid peer IP "[12ef:b400:e:18::ffff]"
```
Any idea how to deal with that ?

**Comment by uablrek** [comment]
If a loadBalancerIP is specified in the service;
```
loadBalancerIP: 1000::2
```

you get;
```
{"caller":"service.go:81","error":"invalid spec.loadBalancerIP \"1000::2\"","msg":"IP allocation failed","op":"allocateIP","service":"default/cgen","ts":"2018-04-29T16:33:47.97643819Z"}
```

Adding brackets does not help;
```
{"caller":"service.go:81","error":"invalid spec.loadBalancerIP \"[1000::2]\"","msg":"IP allocation failed","op":"allocateIP","service":"default/cgen","ts":"2018-04-29T16:38:06.250307907Z"}
```

I am not sure yet if this is a fault in `metallb` (controller) or in Kunernetes.

**Comment by uablrek** [comment]
Remove the "To4()" from [this](https://github.com/google/metallb/blob/224459884d3b27e9f7f7fa87d7bb36eeadb82271/controller/service.go#L133) line fixes the problem. Brackets shall not be used in the manifest.

**Comment by uablrek** [comment]
I used the ipv4 for the local host as routerID and got a bit further. The metallb speakers are now seen from the external router;

```
# gobgp neighbor
Peer       AS  Up/Down State       |#Received  Accepted
2000::1 64500 00:10:53 Establ      |        0         0
2000::2 64500 00:10:53 Establ      |        0         0
2000::3 64500 00:10:53 Establ      |        0         0
2000::4 64500 00:10:53 Establ      |        0         0
```
But advertising does not work;
```
{"caller":"main.go:219","error":"cannot advertise non-v4 prefix \"\u003cnil\u003e\"","ip":"1000::2","msg":"failed to announce service","op":"setBalancer","pool":"default","protocol":"bgp","service":"default/cgen","ts":"2018-05-02T09:23:13.400042834Z"}
```

BTW, I would *really* like to contribute with a PR but I am not allowed by corporate policy. I hope this will change.

**Comment by uablrek** [comment]
For the routerid problems I suggest;

* Use an annotation in the k8s node object
* Use an ipv4 address on the interface towards the GW router

If neither of these exist, do not start BGP routing. If an ipv4 address exists for the node (which I believe is the normal case) it is used even in an ipv6-only k8s cluster.

Example;
```
kubectl annotate node <some-node> metallb.universe.tf/routerid=0.0.0.12
```

There should maybe also be an option to disable the ipv4 fall-back and *require* a configured routerip. In a large cluster it is proably undesired to have bgp speakers announcing routes from *all* nodes. But this can be accomplished with affinity also of course...

I can make a PR for this.

**Comment by uablrek** [comment]
The problem with router-id in ipv6-only environment is common for all routers used in k8s, e.g. `calico` and `kube-router`. I try to push for a common approach;
* Annotation on the k8s node object
* Use a ipv4 address if it exists (optional, assumes dual-stack)
* Generate a router-is using a hash (or crc) on the hostname
See also https://github.com/projectcalico/calico/issues/2229

**Comment by aditsachde** [comment]
Hello, I noticed that there was some mention of this back in the release notes of version 0.8.0. I was wondering if there was any change in the status of this. Is IPv6 BGP support working? Kubernetes has introduced dual-stack support in 1.16, and this issue might come up again soon once dual-stack hits beta hopefully in 1.17.

**Comment by TheEnbyperor** [comment]
IPv6 BGP extensions added in #574

**Comment by ykulazhenkov** [comment]
I uploaded another implementation of IPv6 support https://github.com/metallb/metallb/pull/590
This patch was created some time ago and we actively use it for testing inside my company.
Main differences from PR above:
- support for announcing IPv4 prefixes over IPv6 and vice versa
- separate parameter for IPv6 aggregation length
- MP BGP encoding for IPv4 and IPv6 prefixes, legacy BGP encoding as a fallback for IPv4

**Comment by mmack** [comment]
Any update on this?

**Comment by KoJJang** [comment]
I also have same issue as @uablrek said before. (cannot advertise non-v4 prefix)
there are BGP connection between cluster and switch, but couldn't advertise.

Env : Only ipv6 cluster, v0.10.2 version. 

Is there any way for advertising LB IP (ipv6) ?

**Comment by howels** [comment]
Seeing error creating NDP responder on interface with IPv4 and IPv6 addresses in L2 mode.

**Comment by fedepaol** [comment]
Hi @howels , would you mind filing an issue adding more details and the exact error?
Thanks!

**Comment by howels** [comment]
> Hi @howels , would you mind filing an issue adding more details and the exact error? Thanks!

Had this reported by a colleague who hit the error, I'm trying to follow up and get more details.

**Comment by fedepaol** [comment]
Closing this as it was added in FRR mode!

**Comment by howels** [comment]
> Closing this as it was added in FRR mode!

FRR mode disabled by default and marked as experimental - any idea when FRR will be a stable feature?

**Comment by fedepaol** [comment]
> > Closing this as it was added in FRR mode!
> 
> FRR mode disabled by default and marked as experimental - any idea when FRR will be a stable feature?

That was more of a precaution since it's the first release shipping it. 
- We have good test coverage 
- There are already a good amount of users happy with it.
- The next openshift release, based on the FRR implementation will go out soon and it will be fully supported, which means that bugs will be fixed here too. 

So I'd say try it and report issues, or just wait 3 / 4 months for it to settle. Maybe we should refine the message to encourage users to test it.
