### ISSUE TITLE
BGP in dev environment: network kind not found

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#711]
Running `inv dev-env --protocol bgp` gives me the following:

```
for frr in $(docker ps -a -f name=frr --format {{.Names}}) ; do     docker rm -f $frr ; done
docker run -d --privileged --network kind --rm --name frr --volume /redacted/metallb/dev-env/bgp/frr-volume:/etc/frr frrouting/frr:latest
a89e48752054ce9d1a8700c7fc0f84d3f647d58c1e7f2a51a474463f36016114
docker: Error response from daemon: network kind not found.
```

@russellb - FYI.

**Comment by russellb** [comment]
@johananl :-(  what version of `kind` are you using?  I have `0.8.1`

**Comment by johananl** [comment]
@russellb I was running `0.7.0`. With `0.8.1` I'm not getting the error above. In the website we [mention](https://github.com/metallb/metallb/blob/f41d23acc0efc376e34c927126007e178c6ed278/website/content/community/_index.md#required-software) kind `0.7.0` so I'd say we should either require `0.8.1` or make sure `0.7.0` works (I'm for the former).
