### ISSUE TITLE
go.mod: an unspecified version of the k8s api is used

### ISSUE THREAD

**Issue by uablrek** [metallb/metallb#722]
In `go.mod` the k8s.io/api version is unspecified which normally means something like "what happens to be the case when go.mod was updated";
```
module go.universe.tf/metallb

go 1.12

require (
...
        k8s.io/api v0.0.0-20190620084959-7cf5895f2711
        k8s.io/apimachinery v0.0.0-20190612205821-1799e75a0719
        k8s.io/client-go v0.0.0-20190620085101-78d2af792bab
        k8s.io/klog v0.3.1
)
```
While this usually works it is not very good for maintenance.

As an example metallb can't be built with the current k8s.io/api (v0.19.0). I bumbed immediately into this while working on new features in the controller for https://github.com/metallb/metallb/issues/698.

To select a k8s.io/api version do;
```
go get k8s.io/client-go@v0.19.0
go mod tidy
```
For available versions please see;
https://github.com/kubernetes/client-go#compatibility-matrix

**Comment by rata** [comment]
Thanks! Yes, this was (probably) due to this bug Dave reported: https://github.com/kubernetes/client-go/issues/631

Hopefully we can fix it now :)
