### ISSUE TITLE
Metallb traffic question

### ISSUE THREAD

**Issue by dberadze** [metallb/metallb#728]
Dears, in the case of MetalLB if I have a single VIP does it means that all the traffic goes through a single k8s node?

**Comment by johananl** [comment]
Hi @dberadze. Have you looked at the documentation? Here it is: https://metallb.universe.tf/concepts/

**Comment by russellb** [comment]
Issues really aren't the best place for questions.  I would suggest either #metallb on Kubernetes slack or the metallb-users mailing list.  https://metallb.universe.tf/community/

@johananl leaving this open though since you've already engaged if you want to keep it here :)
