### ISSUE TITLE
Long failover time

### ISSUE THREAD

**Issue by pecheneg12** [metallb/metallb#733]
MetalLB: 0.9.3
K8S: 1.19.2 (pod-network: 10.244.0.0\16)
Network: Flannel (10.244.0.0\16)
Kube-Proxy: ipvs

I have installed MetalLB and this work perfect!
Deploy MetalLB:
kubectl get configmap kube-proxy -n kube-system -o yaml | sed "s/strictARP: false/strictARP: true/" | sed "s/mode: \"\"/mode: \"ipvs\"/" | kubectl apply -f - -n kube-system
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
ConfigMap:
  apiVersion: v1
  kind: ConfigMap
  metadata:
    namespace: metallb-system
    name: config
  data:
    config: |
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 10.71.220.184-10.71.220.187

But I have same issue as https://github.com/metallb/metallb/issues/298
arping stop after down lease node and wating ~5min. After ~5min arping run correctly.

**Comment by russellb** [comment]
Can you provide more complete steps to reproduce, including a test workload?

If the workload behind the service only had one endpoint, and that endpoint was on the node that went down, then this behavior could be that you're waiting for how long it takes for the workload to come up on another node.

**Comment by pecheneg12** [comment]
I have deployment ingress as replicas: 1. Thanks!
Switching to fail:
60 bytes from 00:50:56:94:a1:00 (10.71.220.184): index=175 time=709.965 usec
60 bytes from 00:50:56:94:a1:00 (10.71.220.184): index=176 time=1.069 msec
60 bytes from 00:50:56:94:b9:8a (10.71.220.184): index=177 time=252.652 msec
60 bytes from 00:50:56:94:b9:8a (10.71.220.184): index=178 time=757.206 usec

This work!
