### ISSUE TITLE
Add a linter to the project

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#735]
In order to avoid spending code review time on coding style issues and other things a machine can catch, we should consider adding a linter to the project.

I've had some positive experience with https://github.com/golangci/golangci-lint in another project. Happy to hear other ideas though.

**Comment by russellb** [comment]
For reference, there is an existing lint job:

https://github.com/metallb/metallb/blob/main/.circleci/config.yml

Right now it runs gofmt and go vet.  It's using `gometalinter` which is a script that knows how to run a number of different linters.  The script seems deprecated and unmainatined, though.

https://github.com/alecthomas/gometalinter

It recommends using the tool you've linked in the description.

**Comment by russellb** [comment]
We adopted golangci-lint in #855
