### ISSUE TITLE
Layer2 Different subnets(label for LB, check for interface)

### ISSUE THREAD

**Issue by coolermister** [metallb/metallb#737]
Hi guys. In our enviroments, we usually using different networks, for example public and internal.
We really like the metallb project, but it seems we don't fully understand philosophy of metallb)
It seems like speaker component, if i understand it correctly, does not check is the cluster node actually have an interface in same subnet as balancer ip, and placing it to all nodes of cluster. But in our cases, not all servers have an interface in public network. Maybe there is some kind of check for an interface/subnet on server, or some apportunity to add addresses on specific LB nodes by a label, or something, which i don't find? Is there a plans to implement something like this?
Thank you! And thank you for you work!

- Version of MetalLB v0.9.3
- Version of Kubernetes v1.18.6
- Name and version of network addon Calico-3.14.2
- Kube-proxy configured for ipvs mode, and StrictARP enabled

**Comment by Aoana** [comment]
Hi!

I suggest you direct questions like this in slack channel and not writing a ticket for it. From your comments I believe there is some misunderstanding about how MetalLB works and the slack channel is better for clearing it out.

**Comment by coolermister** [comment]
Well, the same ideas was in [502](https://github.com/metallb/metallb/pull/502) and [605](https://github.com/metallb/metallb/issues/605)
and [511](https://github.com/metallb/metallb/issues/511)
To write questions in slack, i need an invite, which i don't have)
The question is simple, is there a plans to implement something like this?

**Comment by Aoana** [comment]
Hi!

You do not need an invite from a real person to join slack. Register and you will get automatic invite. 

If this is already covered and discussed in other tickets, why not ask status in those tickets?

**Comment by coolermister** [comment]
Hi!
Well, because they most of them are closed, and there is no enough information in there. I'm just asking about plan of implementing this. Metallb in layer2 mode is designed for one big l2 network, and it does not cover use cases, when you have cluster nodes with different networks, eg public internal and so on.
So i'm just interested in this simple question: Is there you guys planning to add support of that use cases?

**Comment by Aoana** [comment]
Ok

I will leave it maintainers to answer (Im not a maintainer nor working on the feature in question). #511 looks to still be opened though and I suggest you direct questions there to not create different tracks for a potential feature.

**Comment by johananl** [comment]
@coolermister if you could specify that an address pool should be announced only from a subset of the nodes (for example using a node selector), would that solve your problem? If so, we have https://github.com/metallb/metallb/issues/630 for this.

**Comment by coolermister** [comment]
@johananl Oh, i see. May be i was blind) Thank you!

**Comment by johananl** [comment]
Great. I'll close this then.
