### ISSUE TITLE
Generate memberlist secret automatically

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#738]
Right now users have to worry about creating a secret for memberlist before being able to deploy MetalLB. Moreover, they have to do so even when they use **BGP**, in which case they don't even use memberlist.

Following a [suggestion](https://kubernetes.slack.com/archives/CTU63S7K3/p1602089687063800) by @danderson, we can look into generating the secret in the MetalLB controller and possibly even rotating it automatically.

**Comment by johananl** [comment]
Things to think about:

- During deployment, what should the speakers do until the secret is generated? Wait for it? Crashloop? Init containers? Something else?

**Comment by liuyuan10** [comment]
qq, how important is this secret? Seems it only encrpyts memberlist traffic that doesn't carry any sensitive information. How much value of it to enable memberlist encryption by default? For those using BGP only, they can simply mark this secret as optional in the metallb yaml to disable the encryption.

**Comment by champtar** [comment]
Anyone that knows the IP of a node can speak memberlist and break/disrupt the cluster, so it's not so much to protect the traffic than to authenticate real member

**Comment by johananl** [comment]
> qq, how important is this secret? Seems it only encrpyts memberlist traffic that doesn't carry any sensitive information. How much value of it to enable memberlist encryption by default? For those using BGP only, they can simply mark this secret as optional in the metallb yaml to disable the encryption.

I had the same line of thought @liuyuan10, however IIUC the important aspect of having a secret is *authentication* to prevent rogue entities from affecting a memberlist cluster if they have network connectivity to it.
