### ISSUE TITLE
Document split brain behavior

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#741]
In the past we [decided](https://github.com/metallb/metallb/issues/195#issue-305335847) to get rid of leader election and not handle split brain scenarios in layer 2. We should explain the behavior in the [limitations](https://metallb.universe.tf/concepts/layer2/#limitations) section of the docs.

Relevant issues:

- https://github.com/metallb/metallb/issues/740#issuecomment-707108775

**Comment by fedepaol** [comment]
closed by https://github.com/metallb/metallb/pull/2064
