### ISSUE TITLE
docs: add hint to calicos eBPF dataplane for IP preservation

### ISSUE THREAD

**Issue by onmyflow** [metallb/metallb#742]
Calico has added a new and exciting feature that creates a eBPF dataplane replacing kube-proxy. 
This enables the preservation of the source IP and other things.

One should add a note or even dedicate a section in the docs to this feature, since it's a viable solution for the souce IP problem, should one use calico.

**Comment by russellb** [comment]
Willing to write up the proposed documentation update?  :)

**Comment by onmyflow** [comment]
Sure! Ill make a PR as soon a i get to it.

**Comment by champtar** [comment]
I think cilium also has the same magic

**Comment by onmyflow** [comment]
Interesting! 
Cillium even seems to default to eBPF, I'll need to check how to implement this into the docs.

**Comment by champtar** [comment]
BTW part of the Calico code comes from Cilium: https://cilium.io/blog/2019/06/24/bpf-code-copyright/

**Comment by onmyflow** [comment]
Seems like Calico used code from Cilium, which violated the Cilium Licence.
They since have relicensed their code to Apache-2.0.
Instead of attributing Calico, i shall rather attribute eBPF to Cillium.

**Comment by onmyflow** [comment]
I've created a PR, let me know what you think.

**Comment by russellb** [comment]
We decided not to merge the proposed doc update in #796, so i'm going to close this out
