### ISSUE TITLE
cannot install metallb on kubernetes v1.19.x via manifest

### ISSUE THREAD

**Issue by honza801** [metallb/metallb#743]
hi,

according to kubernetes documentation:
https://kubernetes.io/docs/setup/release/notes/#avoiding-permanent-beta

kubernetes stops using labels like `beta.kubernetes.io/os` present in `manifests/metallb.yaml`. installation via manifest stops working since kubernetes v1.19. becasuse of the

```
nodeSelector:
        beta.kubernetes.io/os: linux
```

Version of MetalLB 0.9.3
Version of Kubernetes 1.19.x
Name and version of network addon: Calico

please fix this

thanks
have a nice day
jan

**Comment by russellb** [comment]
It sounds like you know what needs to change.  Would you be interested in submitting a PR?

**Comment by gclawes** [comment]
I'll catch this in the helm chart, too.  #653
