### ISSUE TITLE
Stop spamLoop() ticker when not used (golang 1.15+)

### ISSUE THREAD

**Issue by champtar** [metallb/metallb#745]
Now that #736 is merged, an improvement suggested by @russellb is to stop the ticker when not used.
https://github.com/metallb/metallb/blob/0c1ae8cc3b057b745ea4003ed65e81e404d424c9/internal/layer2/announcer.go#L144

Golang 1.15 introduces ticker.Reset(), which would make it easy to stop/start the ticker when needed

**Comment by russellb** [comment]
@champtar we've bumped go version, so we should be able to use ticker.Reset() now
