### ISSUE TITLE
Remove `imagePullPolicy: Always` from release manifests

### ISSUE THREAD

**Issue by champtar** [metallb/metallb#748]
`imagePullPolicy: Always` makes sense for main images, but we should remove it from the release manifests

**Comment by johananl** [comment]
Personally I don't see a reason to set it to `Always` even on `main`. We use a kind-based dev environment which loads up-to-date images directly to the nodes, without the need to push them to a registry and then re-pull them. If someone uses a different dev environment they are free to change `imagePullPolicy` locally.

**Comment by champtar** [comment]
I'm fine with just removing the line to keep the default of the cluster
