### ISSUE TITLE
Test if we need more than CAP_NET_RAW

### ISSUE THREAD

**Issue by champtar** [metallb/metallb#762]
https://github.com/metallb/metallb/blob/main/manifests/metallb.yaml#L330
NET_RAW is enough to listen to and send arbitrary traffic
NET_ADMIN / SYS_ADMIN give unnecessary capabilities for me

**Comment by champtar** [comment]
Just tested with only `NET_RAW` and ARP still works fine
On a CentOS 8 node:
```
# grep -E 'Cap|Priv' /proc/$(pgrep speaker)/status
CapInh:	0000000000002000
CapPrm:	0000000000002000
CapEff:	0000000000002000
CapBnd:	0000000000002000
CapAmb:	0000000000000000
NoNewPrivs:	1

# capsh --decode=0000000000002000
0x0000000000002000=cap_net_raw
```

@hatt in #382 you added `NET_ADMIN` and `SYS_ADMIN` because according to your testing it was needed, but didn't provide instructions to reproduce your finding, can you share them by any chance ?

Functionally, we only respond to ARP / NDP requests, so `NET_RAW` is enough and anything else is a bug that need to be fixed.

Being root with only `NET_RAW` is really not the same thing at all as root with `SYS_ADMIN`, the first one can forge packet, the second one can escape from the container pretty easily, so your statement
> In actual testing, the caps don't really matter because the process is running as root

makes me think you didn't fully understand how capabilities work at the time of this PR.
If I remove the capabilities, I get the following error:
```
{"caller":"announcer.go:105","error":"creating ARP responder for \"ens3\": operation not permitted","interface":"ens3","msg":"failed to create ARP responder","op":"createARPResponder","ts":"2020-10-24T20:28:27.14983281Z"}
```
and do not get ARP answers anymore, so it does make a difference ;)

When people say `root`, they are thinking at uid 0 + all capabilities, but uid 0 with no capabilities is a normal user with only 1 advantage, being the owner of most files on the system, if he can access it (ie is not in a chroot or mount namespace/container). Also NoNewPrivs is set so you can't get more privileges.

It would be nice to have ambient capabilities, but @danderson opened an issue years ago with no luck https://github.com/kubernetes/kubernetes/issues/56374

**Comment by danderson** [comment]
FWIW, I can't think of anything that MetalLB is doing that would require SYS_ADMIN, certainly. I'm a little bit less certain about NET_ADMIN because it's a weird bag of random network permissions, but if both BGP and ARP mode function correctly without them, then, shrug :)

**Comment by danderson** [comment]
oh, NET_ADMIN might be required for BGP auth, which uses a fancy socket option to set TCP MD5 auth. Might want to check what privileges that requires.

**Comment by champtar** [comment]
Good point, I'll check the tcp md5, but NET_RAW already let you have a lot of fun

**Comment by champtar** [comment]
Just tested this small TCP_MD5SIG example program, no capabilities required
https://gist.github.com/critindirecx/57b99c2a7a50fff5dc3f

**Comment by gclawes** [comment]
I've removed NET_ADMIN and SYS_ADMIN from the chart in #658
