### ISSUE TITLE
 layer 2 mode failover is slow

### ISSUE THREAD

**Issue by jcrosel** [metallb/metallb#767]
Hi guys, 
I came across MetalLB as an elegant solution in [bare metal guide of nginx-ingress](https://kubernetes.github.io/ingress-nginx/deploy/baremetal/#a-pure-software-solution-metallb) for my on premise RKE cluster.
It works fine as long as no node dies aka no switch is happening. But if I kill one of my VMs (where the k8s cluster is located) it takes full 5 minutes to do a switch.

Following timeline (logs are from speaker container):

VM turn off at 12:17 and the speaker on the remaining node recognizes that a node left:
`{"caller":"state.go:459","component":"Memberlist","msg":"[INFO] memberlist: Suspect test-test-k8s-worker0 has failed, no acks received","ts":"2020-10-27T12:17:33.141448624Z"} 
{"caller":"state.go:1157","component":"Memberlist","msg":"[INFO] memberlist: Marking test-test-k8s-worker0 as failed, suspect timeout reached (0 peer confirmations)","ts":"2020-10-27T12:17:34.141732086Z"} 
{"caller":"speakerlist.go:313","msg":"node event - forcing sync","node addr":"192.168.0.206","node event":"NodeLeave","node name":"test-test-k8s-worker0","ts":"2020-10-27T12:17:34.141814887Z"} `

some lines later in the log:
`{"caller":"state.go:368","component":"Memberlist","msg":"[DEBUG] memberlist: Failed ping: test-test-k8s-worker0 (timeout reached)","ts":"2020-10-27T12:17:34.641448663Z"} 
{"caller":"state.go:459","component":"Memberlist","msg":"[INFO] memberlist: Suspect test-test-k8s-worker0 has failed, no acks received","ts":"2020-10-27T12:17:37.141342556Z"} `

Every one minute it tries to dial up the other node again:
`
{"caller":"memberlist.go:245","component":"Memberlist","msg":"[DEBUG] memberlist: Failed to join 192.168.0.206: dial tcp 192.168.0.206:7946: i/o timeout","ts":"2020-10-27T12:18:09.540276175Z"} 
{"caller":"speakerlist.go:257","error":"1 error occurred:\n\t* Failed to join 192.168.0.206: dial tcp 192.168.0.206:7946: i/o timeout\n\n","expected":1,"joined":0,"msg":"partial join","op":"memberDiscovery","ts":"2020-10-27T12:18:09.540327876Z"} `
And five minutes (12:17-12:23) after the node died the IP is available on the other node:
`{"caller":"main.go:275","event":"serviceAnnounced","ip":"192.168.0.222","msg":"service has IP, announcing","pool":"default","protocol":"layer2","service":"ingress-nginx/ingress-nginx","ts":"2020-10-27T12:23:27.711869028Z"} 
`

Full log, in case I missed something (IPs and names partly obfuscated as in ticket text above):
[container.log](https://github.com/metallb/metallb/files/5445282/container.log)
Controller logs did not have any new lines during this timeframe.

To me it seems that not the clients are the problem of the slow failover (as suggested in your docs: https://metallb.universe.tf/concepts/layer2/#limitations) but the MetalLB seems to be slow in assigning the IP to the other node. 

My client OS are:
Windows 10 (different network/routed)
Windows Server 2016 (same network as cluster)

Versions:
MetalLB 0.9.4
Kubernetes 1.18.3
canal (deployed by default with RKE)
kube-proxy (hyperkube:v1.18.3)

I hope that's sufficient to investigate, if not feel free to ask for further information you need.

**Comment by champtar** [comment]
You need 2+ ingress-nginx running, else it takes 5min for the ingress-nginx pod to move to a healthy node, so MetalLB doesn't annonce anything because there is no ingress-nginx running ;)

**Comment by jcrosel** [comment]
ok, I see. I checked my pods and I have one on each node, which makes it two.
test-test-k8s-worker0 is the turned off VM and test-test-k8s-worker1 is the running one. 

`PS C:\Users\user> kubectl get pods -n ingress-nginx -o wide
NAME                                        READY   STATUS        RESTARTS   AGE    IP           NODE
 NOMINATED NODE   READINESS GATES
nginx-ingress-controller-64d6696f7b-dbbvh   1/1     Running       0          31m    10.42.5.81   test-test-k8s-worker1   <none>           <none>
nginx-ingress-controller-64d6696f7b-qjnqm   1/1     Terminating   0          156m   10.42.4.73   test-test-k8s-worker0   <none>           <none>`

I think you were suggesting that only one is running in idle and in stress situation (one VM is down) there is none, right?
If not I may not got your point right.

**Comment by champtar** [comment]
You need 2 RUNNING pods, ie set your ingress-nginx deployment replicas to 2+

**Comment by jcrosel** [comment]
I now scaled the nignx-ingress-controller to two replicas, but still the same 5 minute delay -2020-10-27T13:18:45
`PS C:\Users\user> kubectl get pods -n ingress-nginx -o wide
NAME                                        READY   STATUS    RESTARTS   AGE     IP            NODE                    NOMINATED NODE   READINESS GATES
nginx-ingress-controller-64d6696f7b-dbbvh   1/1     Running   0          51m     10.42.5.81    test-test-k8s-worker1   <none>           <none>
nginx-ingress-controller-64d6696f7b-kr766   1/1     Running   0          2m47s   10.42.4.109   test-test-k8s-worker0   <none>           <none>`

**Comment by champtar** [comment]
show the new logs

**Comment by jcrosel** [comment]
In the logs I see that the IP is assigned now pretty fast, but still my clients (same and different network) are not able to load.
VM down: 15:55

[container (1).log](https://github.com/metallb/metallb/files/5446532/container.1.log)

**Comment by champtar** [comment]
It took around 5s for the IP to move, after that you were able to talk to the 2nd ingress-nginx, but it still takes ~5min for the containers behind ingress-nginx to move. K8S doesn't give you instant magic redundancy, you need to run multiple replicas of everything to have redundancy. No MetalLB bug here. If you have more questions please try the slack channel.

**Comment by jcrosel** [comment]
You are right! I though I checked all workloads, but it seems I forgot something. 
So the issue was after all that the workload was not running on the failed node, therefore metallb did not do the VIP switch, as the workload was not running on the still running node. 

Thank you very much for the quick responses!

**Comment by champtar** [comment]
@jcrosel if you feel like it we also welcome pull request to improve documentation ;)
