### ISSUE TITLE
beta.kubernetes.io/instance-type is deprecated

### ISSUE THREAD

**Issue by vapon** [metallb/metallb#768]
- Version of MetalLB: v0.9.3
     - Version of Kubernetes: v1.18.5

See https://raw.githubusercontent.com/google/metallb/v0.9.3/manifests/metallb.yaml
`nodeSelector:
        beta.kubernetes.io/os: linux`

Pod is never deployed due a deprecated node selector.
See https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/

Can be temporary fixed with: 
`kubectl label nodes <node> beta.kubernetes.io/os=linux`

**Comment by Aoana** [comment]
Hi!

Yes, this is already reported in #743
And PR exist #744 that just needs merging

**Comment by vapon** [comment]
> Hi!
> 
> Yes, this is already reported in #743
> And PR exist #744 that just needs merging

Clear! will close the issue, thank you.
