### ISSUE TITLE
Metallb is assigning same IP to services running on two different bare metal k8s cluster

### ISSUE THREAD

**Issue by Rajpratik71** [metallb/metallb#772]
Firstly , System configuration are as following on all bare metal k8s cluster 

 - Version of MetalLB : v0.9.4
 - Version of Kubernetes : v1.19.3 running on Ubuntu 18.04.5 LTS
 - Name and version of network addon :  Weave 
 - Configured kube-proxy for: ipvs mode

Initial Notice and issue due to this bug:

Initially for layer2 mode , in config IP provided following IP range : `172.25.140.1-172.25.140.250`  . In this scenario , MetalLB allocated gateway IP i.e. `172.25.140.1` to a kubernetes service exposed as LoadBalancer , which should not happened.

For workaround of this issue , provided Ip range as following `172.25.140.2-172.25.140.250`.

But , this issue is still there , Still MatalLb is assigning same IP to different  services running on different k8s cluster.

Below , I am attaching services list with date stamp running on different k8s cluster .

**First cluster :** 

![image](https://user-images.githubusercontent.com/12658912/97739258-a14e9400-1b05-11eb-888d-55d58cfa6db2.png)

**Second Cluster :**

![image](https://user-images.githubusercontent.com/12658912/97739149-6e0c0500-1b05-11eb-8cfb-fd963a229ae6.png)

**Comment by russellb** [comment]
The first issue is expected - it will allocate the IPs that you specify.

The second issue I don't understand.  If you've configured the same or an overlapping range of IPs on two different clusters, then the same IPs will get allocated in both places.

If you need further help, I'd suggest either the mailing list or slack.  https://metallb.universe.tf/community/
