### ISSUE TITLE
Metallb is broadcasting BGP routes to nodes that doesn't run the service

### ISSUE THREAD

**Issue by eranyanay** [metallb/metallb#773]
Hi all, I experiment with metallb on k3s and I encounter some issues with BGP routing.
Im using the following:
Version of MetalLB : v0.9.4
Version of Kubernetes : v1.18.9

It's a 3 nodes cluster, and what I see is that each service I create, makes metallb to broadcast to its bgp peers routes to ALL nodes, instead of the specific ones who are actually scheduling the pod.

In my current scenario, I have a deployment with 1 replica running on 10.0.0.110, and my two other nodes are at 10.0.0.111, 10.0.0.7.

In my router (mikrotik hap ac), I can see that it got a routing advertisement from metallb that this service can be found at each of the three IPs of my different nodes.

I expect to see routes only to those who actually have the pod scheduled.
I use a generic configmap for metallb, as shown in the website.

In the attachment below, you can see an example,
My exposed service is 10.50.0.2, and it exists only on 10.0.0.110, however it is broadcasted by all speakers and the route to 10.0.0.7 is the one that is active eventually (A means active)

![image](https://user-images.githubusercontent.com/2053767/97783404-2d14fe80-1ba0-11eb-8dd6-164813a070dc.png)

**Comment by junkiebev** [comment]
https://metallb.universe.tf/usage/#traffic-policies

Assuming you are using Cluster and not Local for `externalTrafficPolicy` on your service, that's as expected.

**Comment by russellb** [comment]
agree with @junkiebev , most likely the expected behavior
