### ISSUE TITLE
Feature request: Configure TCP timeout in BGP Speaker

### ISSUE THREAD

**Issue by antonvdl** [metallb/metallb#777]
Hey MetalLB people,

We are running into the following issue;
MetalLB BGP speakers connects to a Fortigate cluster. 
The Fortigate accepts neighbor ranges; so any IP in the correct range is allowed to setup a BGP session.

All works fine, until there is a failover on the Fortigate side.
The problem is that the TCP session will be gone on the Fortigate side, but is still alive on the BGP Speaker side.

MetalLB will send a KEEPALIVE Message using the non-existing TCP session. The Fortigate firewall will (silently) DROP this packet.
At the MetalLB side the TCP Retransmission mechanism will kick-in; and will keep trying to deliver the KEEPALIVE message.

This will take approximately 15 minutes (default TCP timeout settings). 
During this 15 minutes the Fortigate is not updated with BGP messages, we can keep the old routes online but this can cause blackholing when something changes in the Kubernetes environment at the sime time.

It would be great if MetalLB can have a build-in TCP timeout for the Keepalive message, that way a new TCP session would be created and the BGP session will be recreated.

**Comment by champtar** [comment]
This seems like a bug, if we don't get responses to our KEEPALIVE message, maybe we should reset the tcp connection

**Comment by nickvth** [comment]
@champtar is there any progress on this issue, we hit the same issue

**Comment by russellb** [comment]
#396 is another way to address this (BFD Support), and is expected if we implement BGP using FRR (see #832)

**Comment by nickvth** [comment]
@champtar @markdgray We still hit this issue, any plans to add build-in TCP timeout for the Keepalive message?

**Comment by markdgray** [comment]
@nickvth I can't speak to the native BGP implementation but FRR does allow configuration of timeouts (https://docs.frrouting.org/en/latest/bgp.html#clicmd-neighbor-PEER-timers-0-65535-0-65535) that may help and also BFD is a possibility, as @russellb suggested. Of course, FRR isn't currently integrated into MetalLB but it is being considered.

**Comment by fedepaol** [comment]
Closing this, as both frr and bfd support are available (although marked experimental)
