### ISSUE TITLE
infinite loop if BGP peer is in "Administrative Shutdown" mode

### ISSUE THREAD

**Issue by iameli** [metallb/metallb#780]
Thanks for metallb, it's been really excellent for our use case.

I'm working with a datacenter partner that adds BGP routes to their hardware manually for each server. (I'm not really sure why they need to do this. I suspect that it might have something to do with routing traffic through multiple VLANs. Anyway.) They manually add a BGP route for each server, but keep it in "Administrative Shutdown" mode until I add the metallb configuration on our end and message them. When metallb finds that its peer is in "Administrative Shutdown", it enters an infinite loop state, constantly using 100% of one core's CPU. It constantly spams these two log messages over and over:

```
{"caller":"bgp.go:66","event":"sessionUp","localASN":[redacted],"msg":"BGP session established","peer":"[redacted]:179","peerASN":[redacted],"ts":"2020-08-26T17:19:33.232562297Z"}
{"caller":"bgp.go:401","error":"got BGP notification code 0x0602 (Administrative Shutdown)","event":"peerNotification","localASN":[redacted],"msg":"peer sent notification, closing session","peer":"[redacted]:179","peerASN":[redacted],"ts":"2020-08-26T17:19:33.232600053Z"}
```

I get that we usually want to retry really fast in BGP, but this quickly became 99% of our logs. Presumably there should be some manner of back-off here.

**Comment by johananl** [comment]
Thanks for reporting @iameli.

From your logs above it seems to me like the upstream BGP router actually establishes the BGP session first, then shuts it down. If that's the case, I'm wondering how we are going to distinguish between your "admin down" case and a case where an already-running session gets shut down. AFAICT we *want* MetalLB to try re-establishing a failed session as soon as possible to minimize convergence time.

That said, I do agree that we should never loop uncontrollably and consume lots of CPU so I think we should at least look into this anyway.

**Comment by iameli** [comment]
Yeah, agreed entirely with all of that, seems like some manner of rate limiting would be the play.

FWIW the peer in this instance is running BIRD. If you think it'd be helpful to know the specific BIRD setting that's triggering this behavior I can ask.

**Comment by fedepaol** [comment]
Closing this as it should be fixed by switching to frr
