### ISSUE TITLE
Metallb now working other wi-fi

### ISSUE THREAD

**Issue by lexfrei** [metallb/metallb#789]
The Metallb not working other wifi as expected

My stand:
Kubernetes 1.19.4
Metallb 0.9.5 in l2 mode
5х RPis cluster connected other 5ghz wifi

Can't find any bottlenecks, broadcast limitation, or else.
Flapping in arp tables. Some PCs can access, some can't in one time.
JFYI, but can make any investigations for you

Looks like this, but works sometimes:
![image](https://user-images.githubusercontent.com/1366514/100359526-bb966780-3008-11eb-972b-fd926931ca9d.png)

**Comment by johananl** [comment]
Hi @lexfrei. MetalLB doesn't know or care about the physical media used between it and the clients. This sounds very much like an issue with your local network setup.

If you suspect there is a bug in MetalLB itself, please provide instructions on how to reproduce the problem. Thanks!
