### ISSUE TITLE
selfLink is missing

### ISSUE THREAD

**Issue by brianmay** [metallb/metallb#794]
I am getting the following error:

```
E1214 23:18:43.475271       1 event.go:296] Could not construct reference to: '&v1.Service{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"ingress-nginx-controller-ipv6", GenerateName:"", Namespace:"default", SelfLink:"", UID:"7ccdee5d-3caf-4e36-8d54-75482263c85d", ResourceVersion:"119477090", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63743503894, loc:(*time.Location)(0x1a6e740)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"name\":\"ingress-nginx-controller-ipv6\",\"namespace\":\"default\"},\"spec\":{\"externalIPs\":[\"2001:44b8:4112:8a03::13\"],\"ipFamilies\":[\"IPv6\"],\"ipFamilyPolicy\":\"SingleStack\",\"ports\":[{\"name\":\"http\",\"port\":80,\"protocol\":\"TCP\",\"targetPort\":\"http\"},{\"name\":\"https\",\"port\":443,\"protocol\":\"TCP\",\"targetPort\":\"https\"}],\"selector\":{\"app.kubernetes.io/component\":\"controller\",\"app.kubernetes.io/instance\":\"ingress-nginx\",\"app.kubernetes.io/name\":\"ingress-nginx\"},\"type\":\"ClusterIP\"}}\n"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"kubectl-client-side-apply", Operation:"Update", APIVersion:"v1", Time:(*v1.Time)(0xc0003756c0), Fields:(*v1.Fields)(nil)}, v1.ManagedFieldsEntry{Manager:"kubectl-edit", Operation:"Update", APIVersion:"v1", Time:(*v1.Time)(0xc0003756e0), Fields:(*v1.Fields)(nil)}}}, Spec:v1.ServiceSpec{Ports:[]v1.ServicePort{v1.ServicePort{Name:"http", Protocol:"TCP", Port:80, TargetPort:intstr.IntOrString{Type:1, IntVal:0, StrVal:"http"}, NodePort:31069}, v1.ServicePort{Name:"https", Protocol:"TCP", Port:443, TargetPort:intstr.IntOrString{Type:1, IntVal:0, StrVal:"https"}, NodePort:32066}}, Selector:map[string]string{"app.kubernetes.io/component":"controller", "app.kubernetes.io/instance":"ingress-nginx", "app.kubernetes.io/name":"ingress-nginx"}, ClusterIP:"fc01::5e88", Type:"LoadBalancer", ExternalIPs:[]string{"2001:44b8:4112:8a03::13"}, SessionAffinity:"None", LoadBalancerIP:"", LoadBalancerSourceRanges:[]string(nil), ExternalName:"", ExternalTrafficPolicy:"Cluster", HealthCheckNodePort:0, PublishNotReadyAddresses:false, SessionAffinityConfig:(*v1.SessionAffinityConfig)(nil)}, Status:v1.ServiceStatus{LoadBalancer:v1.LoadBalancerStatus{Ingress:[]v1.LoadBalancerIngress(nil)}}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'IPAllocated' 'Assigned IP "2001:44b8:4112:8a03::"'
```

I believe the key error here is "selfLink was empty, can't make reference".

But selfLink is deprecated in Kubernetes 0.20.0.

Relevant references:

* https://github.com/kubernetes/enhancements/issues/1164
* https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25 (appears to have a workaround)

**Comment by rata** [comment]
@brianmay thanks for the report! Just to clarify, what is the impact this has? Does metalLB work fine in your 1.20 cluster and logs an error or doesn't work at all?

I'm away due to the holidays, so if you can provide a clearer impact it will help me to prioritize. Thanks!

**Comment by brianmay** [comment]
My understanding is without the workaround - `--feature-gates=RemoveSelfLink=false` -  which will stop working in 0.21.0, then metaLB is usable.

**Comment by brianmay** [comment]
I believe the error I quoted is a hard error. As in in stopped it from working.

**Comment by mrin** [comment]
The same issue on Kubernetes 1.20.0 
I don't know if this issue related - but I cant reach a service through lb ip, also I don't see any Events on newly created lb service (kubectl describe service ...), like  "assigned ip ....".

**Comment by Isaroth** [comment]
I am experiencing same issue in my 1.20 cluster. Main impact is that all active connections routed by lb are dropped, especially annoying when it comes to long-running queries.

**Comment by yenneferofvengerberg** [comment]
I have the same issue both on a real cluster and on minikube. Minikube seems to work with `--feature-gates=RemoveSelfLink=false`, while the cluster has hiccups when connections are long standing. Both of them are 1.20. 

The issue is strange because even though you have the errors in the logs and the feature is broken, you still get a sort of IPs:

Note that my minikube plane is located at 192.168.49.2:8443, while the LAN has 10.71.0.0/16

And ''config.yaml'' used before and after enabling the addon was:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
      name: default
      protocol: layer2
      addresses:
      - 10.71.15.0/24
      avoid-buggy-ips: true
      auto-assign: true
```
The ips returned are:

NAME                   |TYPE           |CLUSTER-IP       |EXTERNAL-IP    |PORT(S)          |AGE
-|-|-|-|-|-
hello-blue-whale-svc   |LoadBalancer   |10.105.161.223   |192.168.49.2   |80:32141/TCP     |37s
hello-minikube1        |LoadBalancer   |10.108.9.86      |192.168.49.1   |8080:32390/TCP   |5m
kubernetes             |ClusterIP      |10.96.0.1        |<none>         |443/TCP          |5m
my-service             |LoadBalancer   |10.99.167.231    |**192.168.49.0**   |8080:31031/TCP   |5m

Now this happens randomly, however, have a look at the IPs assigned, they are completely out of range, and sometimes, you also get a *.0*.

**Comment by brianmay** [comment]
I am not seeing any invalid IP addresses being assigned here. I think that might be unrelated?

**Comment by yenneferofvengerberg** [comment]
@brianmay Hi, my concern in this case was 192.168.49.0 which is not a valid IP and event if it were, I used ```avoid-buggy-ips``` to prevent it. I could have misread the doc, but I feel I am missing something: either a misconfiguration or an unexpected behavior.

**Comment by brianmay** [comment]
Yes, but this bug report is about `selfLink` being missing. I don't think that the invalid IP addresses are related to `seflLink` being missing (correct me if I am wrong...). Please consider opening another bug report.

**Comment by yenneferofvengerberg** [comment]
Ok, I thought it was a consequence of ```SelfLink``` missing. Thank you,

**Comment by mkhpalm** [comment]
What version of metallb and in what configuration is this ticket about? I'm not seeing this issue with 0.9.3 in layer2 on k8s v1.20.2.

**Comment by brianmay** [comment]
This was metallb version 0.9.5 using the helm chart version 1.0.2, on k8s version 1.20.0

I can't imagine that this would come good with k8s version 1.20.2 as the `SelfLink` is a deprecated feature. They are hardly likely to bring back a deprecated feature. metallb shouldn't be using it anymore.

@mkhpalm Please check if you have the `SelfLink` attribute:

```
kubectl get service $name  -o yaml
```

If you do have it, it you should see something like:

```
apiVersion: v1
kind: Service
metadata:
  [...]
  selfLink: /api/v1/namespaces/default/services/ceryx-service
  [...]
```

If you do have it.

**Comment by mkhpalm** [comment]
> @mkhpalm Please check if you have the `SelfLink` attribute:

I do not have selfLinks but I did run into a similar problem with rook 1.2.4 on k8s 1.20.2 when trying to create block devices. I came across this ticket when trying to see how wide spread the fallout of this change is. I also ran some tests with metallb 0.9.3 and forced all the nginx ingress controller pods onto new hosts to make sure the controller-manager wasn't logging anything unusual and whether the speakers announced. Also listened in on the port to triple check the traffic is where it was meant to go to after speakers should have announced.

I believe this is likely an issue but I wonder if its somehow related to the changes in metallb > 0.9.3. I have no good explanation why I do not see it as you do. I do not have the workaround applied to these tests and I can't find any logs suggesting something is going on. Maybe I'll upgrade metallb to see if it breaks with a newer build.

**Comment by brianmay** [comment]
Weird. It is always possible I did something wrong. But I am not the only one to have experienced this issue.

Will be interesting to know if you can reproduce with metallb 0.9.5.

For reference, I am using layer2 config, not the bgp stuff. Not sure if this matters here though.

**Comment by groundhog2k** [comment]
As far as I understand, the problem is related to the Kubernetes libraries that are used in the MetalLB sources, which are very old. The selfLink features is deprecated and will be removed with Kubernetes 1.21. The --feature-gates=RemoveSelfLink=false trick will only work for 1.20.x - Only real solution is compiling MetalLB with newer Kubernetes Go libraries.

See waiting PR https://github.com/metallb/metallb/pull/723

**Comment by stefanbethke** [comment]
Any chance we can get a release including this fix soon-ish?

**Comment by johananl** [comment]
> Any chance we can get a release including this fix soon-ish?

[You got it](https://github.com/metallb/metallb/releases/tag/v0.9.6) @stefanbethke. Thanks for your patience!

**Comment by brianmay** [comment]
Just upgraded. So far looks good to me. Good job. Thanks for fixing this.
