### ISSUE TITLE
The leader election issue

### ISSUE THREAD

**Issue by koojw99** [metallb/metallb#795]
I have deployed mtallbs v 0.9.5 with l2 mode

quick question:

Old leader vm is down then new leader is elected. 
Once old leader VM is up and join, then leader is re-elected. this makes service to have impact since the tcp connection should be re-established. Actually, saying that changing ip address or moving one of endpoints cause the leader to be elected again seems more accurate.  

This is right behavior ?? Is there any way to have new leader keeping as ownership after old leader is join??

related : #704, do you know how this feature is going??

thanks

**Comment by russellb** [comment]
The behavior you describe is the current expected behavior
