### ISSUE TITLE
Feature Request: Force leader election

### ISSUE THREAD

**Issue by chrono2002** [metallb/metallb#800]
Hello! 

I've got following nodes: 
node610111
node610112
node610113
node610114

I want node610111 to be the leader of election every time when available, but metallb always selects last from the list of nodes (probably machine sorted), e.g.:
  Normal   nodeAssigned                  16m (x1342 over 29d)     metallb-speaker            announcing from node "hosting610111"
  Normal   nodeAssigned                  7m20s (x11 over 30m)     metallb-speaker            announcing from node "hosting610113"
  Normal   nodeAssigned                  3m1s (x138 over 3d)      metallb-speaker            announcing from node "hosting610114"

Is there any way to force election or give a priority weights?

**Comment by chrono2002** [comment]
got following case:
my node610114 was veeery buggy and disconnected every minute
but node610111 was quite stable
every time node610114 appeared, metallb switched to it, then switched back to node610111 when node610114 disconnected (loop this 1.000 times)
instead of stable service i've got disaster

**Comment by chrono2002** [comment]
why don't set the most stable (oldest) one as master?

**Comment by russellb** [comment]
MetalLB calculates which node will own each IP address with a hashing algorithm, and it selects from the hosts that are running a pod that backs the service.  There's no weighting done among the candidate nodes.  It sounds like you should be addressing your problematic node?  In any case, MetalLB appears to be behaving as expected.
