### ISSUE TITLE
IP address not shared when multiple services use local external traffic policy

### ISSUE THREAD

**Issue by ianhlavats** [metallb/metallb#801]
Thanks for filing an issue! A few things before we get started:

1. This is not the place to ask for troubleshooting. Unfortunately
   troubleshooting LB issues in k8s takes a lot of time and effort
   that we simply don't have. If your load-balancers aren't working,
   please don't file an issue unless you have identified a _specific_
   bug to fix. Otherwise, please ask for help in the `#metallb`
   channel on the Kubernetes Slack.
   > I have reached out on Slack for help on this issue, no resolution yet.
2. Please search the bug tracker for duplicates before filing your
   bug.
   > I searched and did not find anything.
3. If you're reporting a bug, please specify all of the following:
     - The bug itself, as detailed as you can.
     - Version of MetalLB
     > v0.9.5
     - Version of Kubernetes
     > v1.20.2
     - Name and version of network addon (e.g. Calico, Weave...)
     > Weave v2.8.0
     - Whether you've configured kube-proxy for iptables or ipvs mode
     > I am using the default iptables configuration.

Here is the problem. When I have two or more services with `externalTrafficPolicy: Local`, only one service has the shared IP assigned to it (see screenshot - I am using 127.0.0.1/32 as my shared IP for testing) and the others remain in pending status. When I remove that policy from my services, the shared IP is assigned to all the services. I don’t have port conflicts in my services.  

I believe that MetalLB should support sharing an IP across multiple services that require the local traffic policy. Is this supported?

**With Local Policy**
![image](https://user-images.githubusercontent.com/3005952/105717737-c72adf80-5f20-11eb-9be2-0b22603f3664.png)

**Without Local Policy**
![image](https://user-images.githubusercontent.com/3005952/105717802-d9a51900-5f20-11eb-959e-2ae3f7e26a71.png)

**Comment by maxisam** [comment]
https://metallb.universe.tf/usage/
They both use the Cluster external traffic policy, or they both point to the exact same set of pods (i.e. the pod selectors are identical).

**Comment by briantopping** [comment]
I just found this problem while debugging [here](https://github.com/kubevirt/cloud-provider-kubevirt/issues/18#issuecomment-851215222). Basically, [this code](https://github.com/metallb/metallb/blob/967124824a6bd5d6d220655e4e5402b3ed247112/internal/allocator/k8salloc/k8salloc.go#L28-L32) uses the selector of the service as a secondary check on the sharing key when `ExternalTrafficPolicy: Local` is used. 

I don't remember any restriction in k8s documentation that service selectors need to reference a pod with a unique label. MetalLB incorrectly creates that restriction.

**Comment by briantopping** [comment]
<nudge/>

**Comment by briantopping** [comment]
I guess "respond to this issue" means it requires complete sentences to remove the label, even though the bot is not sentient. Is this enough words yet?
