### ISSUE TITLE
Feature: Support EndpointSlices

### ISSUE THREAD

**Issue by balboah** [metallb/metallb#806]
I'm using BGP mode for an anycast service.
I've noticed this isn't compatible with [EndpointSlices](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/).

Not sure if the responsibility is on metallb or kubernetes Loadbalancing bur it would be great if this can be supported. It would allow me to receive traffic on the closest node which preferably routes to its local pod, if pod is not available it would forward traffic to any other node in the network.

I'm only able to announce the full /24, even if some services are down on a node there will still be traffic heading there. Thus EndpointSlices would be a life saver in case of issues.

**Comment by GuillaumeOuint** [comment]
Instead of announcing the full /24 in eBGP mode (I'm assuming that you do this), announce IP with /32 in iBGP, only your edge router need to announce /24 to peer/transit.

**Comment by balboah** [comment]
This idea has crossed my mind. However my setup involves announcing public IP space directly to the ISP from several locations around the world with only one server in each dc. I don't have any top rack router in between, even if I did /32, the upstream ISP would announce /24 to the world.

I'm using Local traffic policy as I don't want traffic in a location if no pod runs there. When a pod was restarting due to OOM, the route was still up. Instead of forwarding to a different datacenter that has a live pod, there would be no reply.

If I switch to Cluster policy instead of Local, to have the pod failover across datacenters, I will end up load balancing across Asia, Europe and the US instead of being able to specify a region with the service topology options.

However I will soon be experimenting with two servers and the top rack router option as your suggestion

**Comment by balboah** [comment]
Cool so I think /32 will do it for now.

Now I just need the IPv6 support and everything will be top notch 👌
