### ISSUE TITLE
Q: In L2, How to curl external ip/host from within cluster/pod.

### ISSUE THREAD

**Issue by doug62** [metallb/metallb#825]
Not an expert but:  In L2 mode (non BGP) I am trying to connect/curl to http (traefik/ingress/reverse proxy) using external FQDN which resolves to external metallb IP from within a pod.  I get no connectivity, I'm assuming due to how ARP/MAC different networks.

Q1: Are my assumptions correct?
Q2: Option - Does MetalLB have the ability to update k8 DNS to point to current node?
Q3: Would BGP resolve this issue and if so is there an Ubuntu service I could run to simulate that?
Q4: Any other workaround?

Thanks in advance.

**Comment by eplightning** [comment]
Are you running kube-proxy in `iptables` or `ipvs` mode? I remember running into this problem when using `ipvs` mode. Switching to `iptables` fixed the issues for me.

**Comment by russellb** [comment]
Please consider slack or the mailing list for questions, thanks

https://metallb.universe.tf/community/
