### ISSUE TITLE
Confusing v0.10.0 release

### ISSUE THREAD

**Issue by davidandreoletti** [metallb/metallb#852]
I am interested in https://github.com/metallb/metallb/pull/658 and noticed Github action reported a successful 0.10.0 release CI run (green tick). Upon further inspection, this CI run [allegedly](https://github.com/metallb/metallb/runs/2337445514?check_suite_focus=true#step:4:9) created a 0.9.6 chart in the https://metallb.github.io/MetalLB Helm repo.

However, no Helm repo is found at this location using `helm repo add metallb https://metallb.github.io/MetalLB`. 

I think there is no actual 0.10.0 release yet. If correct, what's the rough timeline for the next release containing #658  ?

ICYMI: @gclawes @russellb

My setup:
- Helm: v3.5.4

**Comment by gclawes** [comment]
Are you referring to this action run? https://github.com/metallb/metallb/actions/runs/746107314 ([release-notes: Add helm for 0.10.0](https://github.com/metallb/metallb/commit/8a62d1a81565721474c7880e4ea6a2b4db6d94a6))

We had an error with the GitHub action workflow where it would run on non-tag commits in `main`, it was fixed here (immediately after that action ran): https://github.com/metallb/metallb/commit/92d6860a67695a176f5d7c1762d188b5d8144883

No 0.10.0 release or tag was generated, but the GH action did cut a `metallb-charts-0.9.6` release (the GitHub Chart Releaser action uses GH release to store chart artifacts).  This spurious release was cleaned up.

**Comment by russellb** [comment]
Is there anything I missed in the cleanup?

**Comment by gclawes** [comment]
I don't think so, I don't see any `metallb-charts-*` releases or tags in the list.
