### ISSUE TITLE
Add more contrast to code blocks with shell commands

### ISSUE THREAD

**Issue by adriancuadrado** [metallb/metallb#857]
Take this url for instance: https://metallb.universe.tf/installation/

![image](https://user-images.githubusercontent.com/29214635/118166695-14768280-b426-11eb-870a-d253d4a05867.png)

It is just too hard to read that text. Could you please add some more contrast?

**Comment by lirlia** [comment]
How about this explanation ?

* run `kubectl -n kube-system edit configmaps kube-proxy` 
* change `mode: ""` to `mode: ipvs`
* run `kubectl -n rollout restart daemonset kube-proxy`

**Comment by mikemckiernan** [comment]
Changing the markup from `shell` to `bash` changes the text color to white.  It's more readable as white text on a black background.
