### ISSUE TITLE
Feature Gates for MetalLB

### ISSUE THREAD

**Issue by briantopping** [metallb/metallb#867]
It seems like adding feature gates to MetalLB would be an effective means to help contributors push their changes to mainline releases without reducing stability as features are tested across the larger community. The project has done a great job at its core competencies, but contributions to solve edge cases that don't attract significant identification by maintainers are often lost as stale branches. A volunteer team can't be expected to do more than they can do. Is there a way to create a win-win?

Feature branches combined with opt-in metrics collection could provide the team the means to recognize features that are being used and provide justification of stability – without burdening the team to focus directly on each one or burdening the community with unstable software.

Kubernetes itself uses feature branches so this is not a foreign concept.

1. Kubernetes Feature Stages - https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages
2. Some feature flag libraries for Go - https://featureflags.io/go-feature-flags/

**Comment by russellb** [comment]
We just created a `design/` repo where proposals can be posted as PRs.  Maybe this would be a good candidate for a PR against that directory?  There's a few other open PRs with other proposals you can look at.

**Comment by fedepaol** [comment]
Closing this. We currently have CI that should give enough confidence. Feature gates will be considered on per case basis, if necessary
