### ISSUE TITLE
[Question/Feature] Nomad, Consul support.

### ISSUE THREAD

**Issue by blmhemu** [metallb/metallb#868]
I understand that metallb is mainly focused on kubernetes.
But I was wondering if `metallb` can be used in conjunction with `nomad` and `consul`

**Comment by johananl** [comment]
Hi there :wave: 

I have no experience with Nomand, however right now the k8s Go client library is tightly integrated into the MetalLB codease. Therefore, I can't see how MetalLB could run as-is on Nomad, unless Nomad has an API that's compatible with k8s.

**Comment by blmhemu** [comment]
Cool! Thanks for the help!
