### ISSUE TITLE
Metallb/Calico/BGP workaround

### ISSUE THREAD

**Issue by cobravsninja** [metallb/metallb#869]
Hey MetalLB Team✋🏻

First of all, thank you for an amazing product. Regarding my idea about implementing BGP with Calico and MetalLB, I decided to follow the following steps:

1. Move Speaker DaemonSet to pod's private namespace
2. Create macvtap logical device in host's default namespace and point it to host's default NIC (e.g. eth0)
3. Assign another private IP in the host's network
4. Move newly created macvtap device to Speaker's pod
5. Establish BGP session with Speaker through newly created macvtap logical device

[Here](https://raw.githubusercontent.com/cobravsninja/mymetallbcalicobgpworkaround/main/mymetallb.yaml) is a DaemonSet example, which of course has its own limitations, but still was enough for my k8s infrastructure. Hope this workaround will help someone. Thank you again and have a nice day👍🏻

**Comment by johananl** [comment]
Thanks for the info @cobravsninja. Since this is an "FYI" issue which doesn't seem to need attention from maintainers, I'll go ahead and close it. It will still appear in search results of course.
