### ISSUE TITLE
MetalLB fails to send ARPs if interface is attached to Open vSwitch

### ISSUE THREAD

**Issue by mnaser** [metallb/metallb#871]
Thanks for an awesome piece of software.

When using Open vSwitch and attaching a port to it, the port ends up being assigned to the `ovs-system` port, which remains to be an interface that is down.

```
# ip link | grep ovs
18: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
111: bond0.1002@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master ovs-system state UP mode DEFAULT group default qlen 1000
```

This effectively means that `bond0.1002` is skipped because it has a `master` assigned to it, and `ovs-system` is skipped beacuse it is naturally `DOWN`, which means no ARP ever goes out.  I think it would make sense that we check first if the bridge the interface is attached to up before skipping it.

**Comment by mnaser** [comment]
@fedepaol does https://github.com/metallb/metallb/pull/1536 technically solve this?

**Comment by frittentheke** [comment]
> @fedepaol does https://github.com/metallb/metallb/pull/1536 technically solve this (or allow you to work around it at least)

?

**Comment by fedepaol** [comment]
sorry I missed the previous ping. I guess #1536 won't help here as it restricts the set of interfaces here, whereas in the original example we want the bond to be considered even if it has a master interface which is down
