### ISSUE TITLE
v0.10.0 manifests point to main tag instead of release tag

### ISSUE THREAD

**Issue by SriRamanujam** [metallb/metallb#874]
I noticed that the v0.10.0 manifests' images are pointing at the `main` tag instead of the `v0.10.0` tag. Is this expected? Previously, manifests for a tagged release would always point at the tagged image corresponding to that release.

**Comment by russellb** [comment]
Thanks.  This is supposed to be automated, but the automation broke because the regex in the script doesn't match anymore.  It used to match `image: metallb/controller`, but since moving from docker hub to quay.io, it needs to match `image: quay.io/metallb/controller`, for example.

@johananl FYI

**Comment by russellb** [comment]
The good news is that main matches v0.10.0 for now.  We'll definitely get this fixed before merging anything risky into `main`.
