### ISSUE TITLE
artifacthub registration

### ISSUE THREAD

**Issue by kfox1111** [metallb/metallb#875]
The helm repository should get added to artifacthub.io so it can be easily found.

**Comment by russellb** [comment]
@gclawes would you mind taking a look at this?

**Comment by gclawes** [comment]
Yeah, I can look into this.

**Comment by kfox1111** [comment]
still an issue

**Comment by gclawes** [comment]
Still on my plate, apologies for falling behind on this.  I'll try to get this rolling either this week or this weekend.

**Comment by gclawes** [comment]
I've created a metallb organization in artifacthub.io.  If maintainers log in to artifacthub.io with their github accounts, I can add them.
