### ISSUE TITLE
Add helm based e2e CI job

### ISSUE THREAD

**Issue by russellb** [metallb/metallb#881]
We have a couple of helm based CI jobs: `helm-lint` and `helm-conftest`.  Now that we have a couple of end-to-end CI jobs (`e2etest-layer2` and `e2etest-bgp`), we should add an e2etest job that uses the helm chart to deploy MetalLB.  We could just change one of the existing e2etest jobs to use helm to get additional test coverage without a new CI job required.

- [ ] Update the dev-env code in `tasks.py` to optionally use helm to deploy MetalLB instead of applying the manifest directly
- [ ] Update one of the e2etest CI jobs to use helm in the dev-env

**Comment by fedepaol** [comment]
@sabinaaledort let's keep this for the missing CI to github actions

**Comment by tylerauerbeck** [comment]
@fedepaol Is there anything specific that is still missing here? Would be happy to take a look.

**Comment by fedepaol** [comment]
Nope, I think this is good to be close now. My comment in https://github.com/metallb/metallb/issues/881#issuecomment-993701573 is because in https://github.com/metallb/metallb/pull/1073 we added it to circle while we were moving towards gh actions.
