### ISSUE TITLE
controller won't run on k8s > 1.20 without fsGroup

### ISSUE THREAD

**Issue by TheKangaroo** [metallb/metallb#890]
I identified an issue while upgrading our (outdated) 1.17 cluster to 1.21.
With the TokenRequest and TokenRequestProjection featuregates graduated to GA in 1.20 the SerivceAccount token is now mounted via the [projected volume API](https://kubernetes.io/docs/concepts/storage/volumes/#projected).
Since metallb runs as nobody user and the projected token is only readable by root(600) or root and fsGroup if set(640) we need to set the fsGroup in the helm chart, or at least, make securityContext configurable via values.yaml.

I'll happily provide a PR for the chart, I'm just curious if I'm doing something wrong and there's another way to run metallb on k8s > 1.20 or if just nobody run it on 1.20+ yet (what I couldn't imagine tbh).

**Comment by champtar** [comment]
Maybe the projected token should be configured to be readable by everyone instead of running the controller as root again

**Comment by TheKangaroo** [comment]
@champtar theres no need to run the controller as root. As discussed in https://github.com/kubernetes/kubernetes/issues/82573 and fixed in https://github.com/kubernetes/kubernetes/pull/89193 you can make the token readable by a specific group by setting fsGroup. Theres no way to make the projected token readable by everyone as far as I know so the fsGroup is the only viable solution.

**Comment by champtar** [comment]
why not just add fsGroup and fix it for everyone instead of making it configurable ?

**Comment by TheKangaroo** [comment]
Sure I can change the PR. I wasn't 100% sure if it would brake things for some use cases, so I wanted to make it optional. I'll adjust my PR.

**Comment by champtar** [comment]
Or make it configurable but the new default need to fix the issue and if it breaks old use cases we will rethink, the idea is to have everything working out of the box

**Comment by TheKangaroo** [comment]
Good point @champtar, I made securityContext configurable via values and set fsGroup as default. So it _clould_ be overwritten if necessary, but default should work out of the box.
