### ISSUE TITLE
Speaker sends ARP reply over incorrect interface

### ISSUE THREAD

**Issue by ahdzesq** [metallb/metallb#894]
I have a Kubernetes cluster with 1 master node and 5 worker nodes, I have already installed Metallb into the cluster and configured it as layer 2 mode, also I'have assigned 20 addresses to use  (192.168.200.170-192.168.200.190)

the worker nodes have six network interfaces, four of them have an IP address of a different segments that I'm using for different purposes.

The main problem that I'm trying to figure out is that the speakers are sending ARP messages into the incorrect interface.

As an example:

I have created the next LoadBalancer service:

`
service/back-end-expose-service   LoadBalancer   10.103.97.115   192.168.200.170   80:32365/TCP,443:32691/TCP   14m   app=back-end
`

the worker node has the IP address 192.168.200.195 into the interface enp1s0f0 but the speaker is sending the ARP Reply over the interface enp180s0 with address 10.240.44.243 instead of enp1s0f0

What could be causing this?
Hope the provided info helps to figure out the issue.

Thanks!

**Comment by ahdzesq** [comment]
Update:

Getting a little bit in deep on logs and into the sh of the speaker pod I'have found that the pod is not creating the ARP responder on interface "enp1s0f0", the interface is present in the container but the ARP announcer is not created.

the only error that I see into some of the speaker pods is the next one:

`{"caller":"announcer.go:114","error":"creating NDP responder for \"enp180s0d1\": listen ip6:ipv6-icmp fe80::4973:9674:cf24:197e%enp180s0d1: bind: cannot assign requested address","interface":"enp180s0d1","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2021-06-18T00:42:54.002568452Z"}`

I assume that the ARP responder is not created because of this part of the code into the announcer:

```
if keepNDP[ifi.Index] && a.ndps[ifi.Index] == nil {
	resp, err := newNDPResponder(a.logger, &ifi, a.shouldAnnounce)
	if err != nil {
		l.Log("op", "createNDPResponder", "error", err, "msg", "failed to create NDP responder")
		return
	}
	a.ndps[ifi.Index] = resp
	l.Log("event", "createNDPResponder", "msg", "created NDP responder for interface")
}
```

I'm not sure what is causing the error to bind the ARP listener into this interface.

I've found this other issue #248 where disabling ipv6 on the interface solves the issue.

**I'm not sure if return in the line 115 of the announcer.go file it's ok, I think this could cause to skip the rest of the interfaces where NDP receivers or ARP receives could successfully being created.**

Thanks!

**Comment by sabinaaledort** [comment]
Hi, 

I'm trying to reproduce the issue.

I set a cluster with 2 workers and 1 master.

```
NAME                 STATUS   ROLES                  AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION            CONTAINER-RUNTIME
kind-control-plane   Ready    control-plane,master   26h   v1.21.1   172.18.0.3    <none>        Ubuntu 21.04   5.11.22-100.fc32.x86_64   containerd://1.5.2
kind-worker          Ready    <none>                 26h   v1.21.1   172.18.0.4    <none>        Ubuntu 21.04   5.11.22-100.fc32.x86_64   containerd://1.5.2
kind-worker2         Ready    <none>                 26h   v1.21.1   172.18.0.2    <none>        Ubuntu 21.04   5.11.22-100.fc32.x86_64   containerd://1.5.2
```
and created the LoadBalancer service:
```
NAMESPACE     NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE     SELECTOR
default       kubernetes   ClusterIP      10.96.0.1       <none>        443/TCP                  26h     <none>
default       nginx        LoadBalancer   10.96.167.163   172.18.0.10   80:31402/TCP             3h23m   app=nginx
kube-system   kube-dns     ClusterIP      10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   26h     k8s-app=kube-dns
```
In the speaker log i can see both ARP and NDP responders were created successfully on the right interface (eth0 which has IP address 172.18.0.4)
```
{"branch":"main","caller":"main.go:81","commit":"0abdf212","goversion":"gc / go1.16.5 / amd64","msg":"MetalLB speaker starting (commit 0abdf212, branch main)","ts":"2021-06-29T05:53:04.313015941Z","version":""}
{"caller":"announcer.go:109","event":"createARPResponder","interface":"vethe07aca37","msg":"created ARP responder for interface","ts":"2021-06-29T05:53:04.314508259Z"}
{"caller":"announcer.go:109","event":"createARPResponder","interface":"vethce8765df","msg":"created ARP responder for interface","ts":"2021-06-29T05:53:04.314647999Z"}
{"caller":"announcer.go:109","event":"createARPResponder","interface":"eth0","msg":"created ARP responder for interface","ts":"2021-06-29T05:53:04.314753387Z"}
{"caller":"announcer.go:118","event":"createNDPResponder","interface":"eth0","msg":"created NDP responder for interface","ts":"2021-06-29T05:53:04.315098274Z"}
{"caller":"announcer.go:109","event":"createARPResponder","interface":"veth15e90aa2","msg":"created ARP responder for interface","ts":"2021-06-29T05:53:14.317134592Z"}
{"caller":"announcer.go:109","event":"createARPResponder","interface":"veth7c46db55","msg":"created ARP responder for interface","ts":"2021-06-29T05:53:14.317870614Z"}
```
Any idea what I'm missing?

**Comment by ahdzesq** [comment]
Hello @sabinaaledort ,

I think it would be difficult to replicate due that the error came from an IPV6 error on a certain interface.

Maybe I can try to figure out what is causing the IPV6 error in order to replicate the issue.

Regards!

**Comment by cjyar** [comment]
I can reproduce this problem -- or at least the symptoms. I have a single-node Kubernetes cluster in which the node can't reach its MetalLB IPs if IPv6 is enabled. Disabling IPv6 allows it to work.

With IPv6 enabled, tcpdump shows this packet on the physical interface, but no reply:
```
21:50:20.800467 ARP, Request who-has 10.0.0.2 tell 10.0.0.9, length 44
```

**Comment by fedepaol** [comment]
Closing this in virtue of the fact that we now have an interface selector for selecting interfaces.
Feel free to reopen if this is still an issue / is reproducible
