### ISSUE TITLE
Helm chart is no longer working after Chart Update

### ISSUE THREAD

**Issue by dschunack** [metallb/metallb#896]
Hi,

you set the Version to v0.0.0 in #893 @russellb, but now the helm chart is no longer working. It look like you use this Version values also for the image tags and after a update of the controller and speak is the image tag now "v0.0.0"

Please, fix this issue in the chart. Thanks

[controller.yaml](https://github.com/metallb/metallb/blob/a628c64bbe30348156bc5faf8583ca9069f1e291/charts/metallb/templates/controller.yaml#L42)

[speaker.yaml](https://github.com/metallb/metallb/blob/a628c64bbe30348156bc5faf8583ca9069f1e291/charts/metallb/templates/speaker.yaml#L39)

```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  9m27s                   default-scheduler  Successfully assigned metallb/metallb-controller-568fc64f66-jnp5k to XXXXXX
  Normal   Pulling    7m54s (x4 over 9m27s)   kubelet            Pulling image "quay.io/metallb/controller:v0.0.0"
  Warning  Failed     7m54s (x4 over 9m27s)   kubelet            Failed to pull image "quay.io/metallb/controller:v0.0.0": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/metallb/controller:v0.0.0": failed to resolve reference "quay.io/metallb/controller:v0.0.0": quay.io/metallb/controller:v0.0.0: not found
  Warning  Failed     7m54s (x4 over 9m27s)   kubelet            Error: ErrImagePull
  Warning  Failed     7m27s (x7 over 9m26s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    4m19s (x20 over 9m26s)  kubelet            Back-off pulling image "quay.io/metallb/controller:v0.0.0"
  ```

**Comment by russellb** [comment]
I didn't expect the chart to be used from main. I expected only released versions of the chart to be used. CC @gclawes, what do you think?

**Comment by gclawes** [comment]
The image tags can still be overridden:
https://github.com/metallb/metallb/blob/a628c64bbe30348156bc5faf8583ca9069f1e291/charts/metallb/values.yaml#L132
https://github.com/metallb/metallb/blob/a628c64bbe30348156bc5faf8583ca9069f1e291/charts/metallb/values.yaml#L179

@russellb I agree, I don't think it should be a supported use case to install the chart directly from `main`.  We should validate that the the chart versions available from the chart repo index are indeed valid release versions, just in case.

@dschunack  how are you installing the chart?  I would guess based on this report that you are cloning the repo and installing from the local files, but can you confirm that?

**Comment by gclawes** [comment]
Helm repo versions look fine to me:
```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "metallb" chart repository
...Successfully got an update from the "nfs-subdir-external-provisioner" chart repository
...Successfully got an update from the "netdata" chart repository
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "cilium" chart repository
...Successfully got an update from the "enix" chart repository
...Successfully got an update from the "fairwinds-stable" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "teleport" chart repository
...Successfully got an update from the "grafana" chart repository
...Successfully got an update from the "prometheus-community" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo --versions metallb
NAME            CHART VERSION   APP VERSION     DESCRIPTION
metallb/metallb 0.10.2          v0.10.2         A network load-balancer implementation for Kube...
metallb/metallb 0.10.1          v0.10.1         A network load-balancer implementation for Kube...
metallb/metallb 0.10.0          v0.10.0         A network load-balancer implementation for Kube...
```

**Comment by dschunack** [comment]
Hi,

In your old Documentation to 0.9.6 was no helm chart repo described and that was the reason that we used the github chart. But, we see the repo is now describe and will will switch to the official helm repo. 

Thanks, I will close the Issue.
