### ISSUE TITLE
specifying imagePullSecrets in Helm Chart values does not work

### ISSUE THREAD

**Issue by drz9** [metallb/metallb#897]
I am specifying the imagePullSecrets as follows in my values-file:

imagePullSecrets:
  - name: test

and what I get is this error:

Error: values don't meet the specifications of the schema(s) in the following chart(s):
metallb:
- imagePullSecrets.0: Invalid type. Expected: string, given: object

I have tried many other ways too like using quotes, indendation etc but none of them work out. Can anyone also reproduce this issue?

 Here is helm version:
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

**Comment by russellb** [comment]
@gclawes FYI

**Comment by gclawes** [comment]
This should address it: https://github.com/metallb/metallb/pull/903

`values.schema.json` was validating `imagePullScrets` as an array of strings, not an array of objects with the single field `"name"`

https://kubernetes.io/docs/concepts/containers/images/#referring-to-an-imagepullsecrets-on-a-pod
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#pod-v1-core
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#localobjectreference-v1-core
