### ISSUE TITLE
Migrate away from Freenode

### ISSUE THREAD

**Issue by rata** [metallb/metallb#906]
The website says:
>     If you prefer a more classic chat experience, we’re also on #metallb on the Freenode IRC network. You can use Freenode’s web client if you don’t already have an IRC client.

However, with the Freenode issues everybody knows now, we should either considering to migrate to OFTC, Libera.chat or maybe deprecate IRC (as much as that hurts me :))

My vote is moving to Libera.chat, I connect to that IRC server for other reasons, so I can easily be on the metallb IRC channel there if we create one.

Any opinions on where to move or just stop using IRC?

**Comment by daxmc99** [comment]
K8s chat is what I primarily use so I am fine with dropping it

**Comment by johananl** [comment]
I've never used IRC in the context of MetalLB :shrug:

**Comment by danderson** [comment]
Dropping IRC probably makes the most sense. And leaving Freenode is 100% the right call, that place went off the rails really fast.

**Comment by johananl** [comment]
We've removed the IRC mention from the website.
