### ISSUE TITLE
Remove master toleration from speaker

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#907]
Right now we deploy speaker pods on all k8s nodes, including the control plane nodes:

https://github.com/metallb/metallb/blob/9ff85804aeca4626821c95d20526649151a17ed5/manifests/metallb.yaml#L389-L392

Unless there is a special reason to deploy speakers on control plane nodes, I suggest we remove this toleration because users normally don't want to use their controller nodes for application traffic.

**Comment by champtar** [comment]
MetalLB has always been 'just works', so I would say NACK

**Comment by russellb** [comment]
I don't feel that strongly, since I know we can't please every use case with our defaults. I think how it is now is OK, though. Maybe we need to improve our installation documentation to highlight this as one of the defaults people may want to consider changing?

**Comment by johananl** [comment]
> MetalLB has always been 'just works', so I would say NACK

@champtar are you saying removing the toleration contradicts the "just works" idea? I'm not sure I understand your comment.

**Comment by johananl** [comment]
> I don't feel that strongly, since I know we can't please every use case with our defaults. I think how it is now is OK, though. Maybe we need to improve our installation documentation to highlight this as one of the defaults people may want to consider changing?

Yeah, what I'm proposing is that we make the default "deploy MetalLB only on worker nodes" because I'm pretty sure the use cases which require a speaker on control plane nodes aren't mainstream. I'm not strongly-opinionated about this either.

**Comment by champtar** [comment]
Until #595 is merged it'll actually break `externalTrafficPolicy: cluster` when memberlist is disabled, after #595 ok with me actually

**Comment by russellb** [comment]
Yeah, that's a really good point.  With how layer2 works right now, we really should leave the default as-is.

**Comment by fedepaol** [comment]
As an additional datapoint, this is what happened in https://github.com/metallb/metallb/issues/933 because I believe the ingress controller pods are running only on masters (which sound reasonable)

**Comment by fedepaol** [comment]
Closing this as discussed with @russellb  and since it looks like users are relying on this.
