### ISSUE TITLE
doc: Revise use of "load balancer" and "load-balancer"

### ISSUE THREAD

**Issue by mikemckiernan** [metallb/metallb#912]
Documentation lingo:
* Use "load balancer" as a noun--as in "...you request a load balancer,...".
* Use "load-balancer" as an adjective--as in, "...load-balancer service...".

Those two catch my eye when they aren't applied quite correctly.  I plan to apply that change throughout.

I'd like to reserve the right to expand the scope on lingo--and maybe style--as time allows.  I'm time-boxing this to a few hours.

I can't imagine any resistance, but I'm opening this issue to feel that out before I open a PR.  Please let me know if there's a reason *not* to make the change.

**Comment by russellb** [comment]
sounds good to me.  You could start a "style guide" doc to capture guidance on common things that apply to MetalLB if you feel inspired to do so.  :)
