### ISSUE TITLE
Helm PodSecurityPolicy policy/v1beta1 is deprecated

### ISSUE THREAD

**Issue by michael-robbins** [metallb/metallb#914]
Installing the latest version of MetalLB v0.10.2 (I'm assuming) through Helm results in deprecation warnings for the PodSecurityPolicy.

```
% helm install metallb metallb/metallb -f helm-configmap.yaml
W0714 20:05:36.548135    9776 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0714 20:05:36.560333    9776 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0714 20:05:36.963580    9776 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0714 20:05:36.964055    9776 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME: metallb
LAST DEPLOYED: Wed Jul 14 20:05:35 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
MetalLB is now running in the cluster.
LoadBalancer Services in your cluster are now available on the IPs you
defined in MetalLB's configuration:

config:
  address-pools:
  - addresses:
    - 192.168.0.1-192.168.0.10
    name: k8s-lb
    protocol: layer2

To see IP assignments, try `kubectl get services`.
```

This is running Kubernetes 1.21:
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/arm"}
```

**Comment by remkolems** [comment]
From https://kubernetes.io/docs/reference/using-api/deprecation-guide/#psp-v125

Quote from mentioned link
> PodSecurityPolicy
> PodSecurityPolicy in the policy/v1beta1 API version will no longer be served in v1.25, and the PodSecurityPolicy admission controller will be removed.
> 
> PodSecurityPolicy replacements are still under discussion, but current use can be migrated to 3rd-party admission webhooks now.

3rd-party admission webhooks
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

**Comment by superherointj** [comment]
This error was affecting my FluxCD/kustomize service. I was able workaround the error by commenting PodSecurityPolicy. I'm unsure of consequences but while a replacement routine isn't finalized seemed reasonable. Can we do this in the meanwhile? If yes, I could propose a patch.

**Comment by michael-robbins** [comment]
As per Kubernetes 1.23 looks like ![PodSecurity](https://kubernetes.io/docs/concepts/security/pod-security-admission/) is the successor and will replace PodSecurityPolicy

**Comment by ViktorBarzin** [comment]
+1 on this issue. My CI/CD system is failing when trying to `tf apply` the `pod_security_policies`. Can we remove the definitions as a short term mitigation?

**Comment by fedepaol** [comment]
Closing as duplicate of https://github.com/metallb/metallb/issues/1401
I am going to cut a release, probably today
