### ISSUE TITLE
Container Speaker not running after install Metallb

### ISSUE THREAD

**Issue by MinhDuc010194** [metallb/metallb#930]
I was tried to install metallb but when done I got an error from pod/speaker-z7l54

> Error from server (BadRequest): Unable to find "/v1, Resource=pods" that match label selector "name=pod/speaker-z7l54", field selector "": unable to parse requirement: values[0][name]: Invalid value: "pod/speaker-z7l54": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

my k8s version is 1.21 and I use calico network
Please tell me how to fix this. thanks

**Comment by champtar** [comment]
This doesn't look like MetalLB log, please share the command you are using, also what MetalLB version

**Comment by MinhDuc010194** [comment]
yes. it isn't metallb log. I install it by using this command and it passes with no error

> kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/namespace.yaml
> kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/metallb.yaml
  but after that, i check all namespace metallb-system then I saw there are no pods running. pod speaker error with status Create container config error. Then i logs this pod and got that message logs

**Comment by champtar** [comment]
If pods are not creating they don't have logs ;)
Look at the controller logs, I bet you have a timeout speaking to the k8s api

**Comment by MinhDuc010194** [comment]
oh. have you any idea to check the connection between k8s API and metallb. because I can still call to this API  
curl -X GET https://10.0.10.50:6443/api --header "Authorization: Bearer $TOKEN" --insecure
and I got
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "10.0.10.50:6443"
    }
  ]

**Comment by champtar** [comment]
Look at the controller logs, also show us `kubectl get pods -n metallb-system`

**Comment by MinhDuc010194** [comment]
this is what I got from `kubectl get pods -n metallb-system`
NAME                          READY   STATUS                       RESTARTS   AGE
controller-65db86ddc6-87fnw   0/1     Pending                      0          13m
speaker-5vtt7                 0/1     CreateContainerConfigError   0          13m

**Comment by champtar** [comment]
Can you 'describe' the controller ? We need to know why it's pending

**Comment by MinhDuc010194** [comment]
sorry, it was my fault. my cluster has only one node and it still is master too. and this master has not taint so all pods are pending when creating a container

**Comment by MinhDuc010194** [comment]
but speaker still CreateContainerConfigError. is that problem or not?

**Comment by champtar** [comment]
Is the controller now running and ready ?

**Comment by MinhDuc010194** [comment]
yes. all issues are gone. Both controller and speaker are working. Thank you all for supporting me.
