### ISSUE TITLE
Unclear if metallb speakers need to be on same node as ingress service

### ISSUE THREAD

**Issue by btrepp** [metallb/metallb#933]
If you have setup a k3s cluster, and followed the line around tainting nodes to make sure the control plane isn't overloaded https://rancher.com/docs/k3s/latest/en/installation/ha/.

The default metallb (0.10.2) will never work. It seems k3s will schedule it's traefik node to the server nodes, but metallb will be scheduled to the worker nodes. So now you can never route to the traefik instance. I think the cause is that the metallb pods need to run on the same node as the service pods.  This is using layer2

When deploying using helm, what got me a routable instance again was in `values.yaml` adding the below.
```
speaker:
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
```
This caused it to schedule to the server nodes, and traffic was routeable again.

To be honest I'm not sure I understand enough about how metallb operates. I could be completely wrong.  I have something workable, I could PR some notes into the troubleshooting with what I did, but to be honest need to confirm if my understanding isn't complete nonsense.

**Comment by fedepaol** [comment]
> The default metallb (0.10.2) will never work. It seems k3s will schedule it's traefik node to the server nodes, but metallb will be scheduled to the worker nodes. So now you can never route to the traefik instance. I think the cause is that the metallb pods need to run on the same node as the service pods. This is using layer2
> 

It could be if the `ExternalTrafficPolicy` of the service is `Local`. With Local, you are supposed to serve traffic only from those nodes where a backend pod is running from.
In this case, you won't have any eligible node with a speaker running on.

**Comment by fedepaol** [comment]
@btrepp mind double checking the TrafficPolicy of the service so we can close this issue if that is the case?

**Comment by fedepaol** [comment]
@btrepp closing this, feel free to comment if my assumptions were not true and you need help triaging this.
