### ISSUE TITLE
Annotate nodes with address pool/weighted address pools

### ISSUE THREAD

**Issue by ChipWolf** [metallb/metallb#941]
We'd like to be able to weight address pools by node, so if a service is bound to an endpoint on a specific node, that node's address pool is preferred as a priority.

The reason for this is with a globally distributed cluster and address pools for each region, to enable the lowest latency service we should be able to dynamically issue IP addresses closest to the origin.

Thanks

**Comment by fedepaol** [comment]
Hi @ChipWolf , adding a node selector to the AddressPool object is currently part of [this proposal](https://github.com/metallb/metallb/pull/942) 

Would that solve your issue? As part of that, the idea is to enable the TrafficPolicy local for L2 load balancing. With that, metallb will advertise from a node selected by the selector AND with a running backend pod.

**Comment by ChipWolf** [comment]
Hi @fedepaol, the proposal you referenced does appear to match our requirements. Thank you!
