### ISSUE TITLE
Add support for setting runtimeClassName on speaker template.

### ISSUE THREAD

**Issue by jlclx** [metallb/metallb#945]
Some kubernetes runtimes do not support `hostNetwork: true` for pod configuration specs.
In some kubernetes clusters a runtime that does not support `hostNetwork: true` may be the default selection.
It would be nice to configure a different runtime, that does support `hostNetwork: true`, so that the speaker pod can execute without failure.

e.g.
Within `charts/metallb/templates/speaker.yaml`
```
...
spec:
 ...
  template:
  ...
    spec:
      {{- if .Values.speaker.runtimeClassName }}
      runtimeClassName: {{ .Values.speaker.runtimeClassName }}
      {{- end }}
      ...
```

Thank you.

**Comment by champtar** [comment]
Can send a PR ?

**Comment by jlclx** [comment]
Yes, here.
https://github.com/metallb/metallb/pull/946

**Comment by fedepaol** [comment]
Closing as the PR was merged
