### ISSUE TITLE
Helm Chart v0.10.2 not matching repository state

### ISSUE THREAD

**Issue by drz9** [metallb/metallb#947]
Hello,

I was trying to install metallb with the helm Chart version 0.10.2 on my OpenShift Cluster but metallb won't start simly because the controller UID doesn't match the UID I provide via helm Chart. The values file looks somewhat like this:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000680000

but the Deployment will always have UID 65534. So I downloaded the Chart from https://metallb.github.io/metallb and in the templates/controller.yaml the securityContext part is hardcoded with runAsUser: 65534

So it seems the provided version of the helm Chart in the helm repo does not match with the version here in the repository?

**Comment by fedepaol** [comment]
Hi @drz9 , this is a known issue with MetalLB and OCP, documented here https://metallb.universe.tf/installation/clouds/#metallb-on-openshift-ocp .

I am not an helm expert, but I think either modifying the chart or changing the values to not apply runAsUser as part of securityContext would do the same as the documentation suggests.

**Comment by fedepaol** [comment]
@drz9 closing this, feel free to comment if what's described above is not clear.
