### ISSUE TITLE
Absence of endpoints for health checks in controller and workers

### ISSUE THREAD

**Issue by MalKeshar** [metallb/metallb#952]
I didn't see in source code any traces of endpoints for health checks. It usually used by liveness and readiness checks in k8s.
Is this decision made on purpose or this part not implemented yet?

**Comment by fedepaol** [comment]
I think it would make sense to have a liveness probe (but not a readiness) as part of the pods definitions.

I am torn between marking this as bug or enhancement, will do the latter since it's not critical.

**Comment by mgeri** [comment]
Hi, I would like to try to work on this.

**Comment by mgeri** [comment]
Looking at the MetalLB code I found that the controller exports an HTTP Prometheus endpoint `/metrics` that is used in the Helm templates charts both as liveness and readiness probe.
It seems that the Prometheus endpoint could be enough as a liveness probe unless a health check with a different strategy is needed.

**Comment by fedepaol** [comment]
Interesting. I checked only the manifests under `/manifests` and assumed it was not added anywhere.
At this point, I think it's fair to align the manifests.
