### ISSUE TITLE
Huge probably pointless replaces in go.mod

### ISSUE THREAD

**Issue by rata** [metallb/metallb#953]
PR https://github.com/metallb/metallb/pull/951 added a lot of replace lines in the go.mod. 

It seems to me like those lines don't make much sense. For example [client-go][client-go] already has the version but we [add a replace][client-go-replace] that is exactly the same (it just uses a lower patch release version, which is probably not on purpose).

@fedepaol Am I missing something? Can't we just remove all of the replaces there?

[client-go]: https://github.com/metallb/metallb/pull/951/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R28
[client-go-replace]: https://github.com/metallb/metallb/pull/951/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R39

**Comment by fedepaol** [comment]
@rata as a snowball effect of consuming `k8s.io/kubernetes` (because of the test framework) we need to pin the dependencies via the require section (and that's how you pin to a specific version of k8s any how):

```
go get: k8s.io/kubernetes@v1.22.2 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

Said that, I might have been a bit too lighthearted in moving the require section from the e2e go.mod file to the main one, let me try to make it cleaner / more consistent.

**Comment by fedepaol** [comment]
Re client-go, although we have a specific version as a dependency, we need to pin it for indirect dependencies:

```
go: k8s.io/kubernetes@v1.20.2 requires
        k8s.io/client-go@v0.0.0: reading k8s.io/client-go/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Comment by rata** [comment]
@fedepaol ohh, I see that importing k8s.io/kubernetes is not supported (https://github.com/kubernetes/kubernetes/issues/90358#issuecomment-617859364) and yeah, the big fat replaces is the workaround to import it anyways... Too bad, but ok :)

Thanks anyways!

**Comment by fedepaol** [comment]
> @fedepaol ohh, I see that importing k8s.io/kubernetes is not supported ([kubernetes/kubernetes#90358 (comment)](https://github.com/kubernetes/kubernetes/issues/90358#issuecomment-617859364)) and yeah, the big fat replaces is the workaround to import it anyways... Too bad, but ok :)
> 

Yep, and anyway this was a good chance to have the deps more consistent :P

> Thanks anyways!
