### ISSUE TITLE
Move shared secrets to a CNCF-provided password manager

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#973]
As a part of moving to CNCF, we may be able to get access to a password manager.

We should request such access and move any credentials/secrets which aren't personal to a maintainer to the password manager and ensure all maintainers have access to them.

[This](https://www.cncf.io/services-for-projects/#tools) page talks about LastPass, 1Password and Keybase. Personally I prefer 1Password over LastPass since 1Password has a much better UX in my opinion. I don't know Keybase.

Shared secrets which come to mind:

- [ ] Bot accounts on Docker Hub and Quay
- [ ] Netlify API keys
- [ ] IaaS API keys (in case we start running e2e tests which create cloud resources)

**Comment by russellb** [comment]
> > This page talks about LastPass, 1Password and Keybase. Personally I prefer 1Password over LastPass since 1Password has a much better UX in my opinion. I don't know Keybase.
> 
> @rata @daxmc99 @russellb any preference between LastPass, 1Password and Keybase?

I'd prefer 1Password since I'm already using it
