### ISSUE TITLE
Update MetalLB info in CNCF landscape

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#975]
The information about MetalLB in the CNCF [landscape](https://landscape.cncf.io/) is outdated.

https://github.com/cncf/landscape/blob/1873345e220ab784e20435768ad59b7b7fc3659a/landscape.yml#L1909-L1915

We should open a PR to address the following:

- The project's homepage should be metallb.io (blocked by https://github.com/metallb/metallb/issues/691).
- The logo should be updated in case we get a new design from the CNCF.
- The Twitter handle (which is currently Dave's personal handle) should be either removed or updated in case we decide to manage a MetalLB Twitter account.
- The Crunchbase link should be updated to `https://www.crunchbase.com/organization/cloud-native-computing-foundation`.

**Comment by johananl** [comment]
Seems like the CNCF onboarding task list has been completed. Congrats! 🎉 
However, it seems like MetalLB still doesn't show on the CNCF landscape. Apparently one has to open a PR on https://github.com/cncf/landscape#new-entries.

**Comment by fedepaol** [comment]
> Seems like the CNCF onboarding task list has been completed. Congrats! tada However, it seems like MetalLB still doesn't show on the CNCF landscape. Apparently one has to open a PR on https://github.com/cncf/landscape#new-entries.

thanks for raising this, will do pronto!

**Comment by fedepaol** [comment]
It was actually already there https://github.com/cncf/landscape/blob/784fb0e9bcecd8ebbaca7345ee48082c629d2c7c/landscape.yml#L3471

and I can see it under the "service proxy" category on https://landscape.cncf.io/ I'll file a PR to drop the twitter account

**Comment by johananl** [comment]
@fedepaol my bad, I meant to say that I don't see it as a **sandbox** project: https://landscape.cncf.io/card-mode?project=sandbox

This is most likely due to the lack of a `project: sandbox` property in `landscape.yml`.

**Comment by fedepaol** [comment]
Ah apologies, going to do it. And thanks again for keeping an eye on this!
