### ISSUE TITLE
Enforce license text in source files

### ISSUE THREAD

**Issue by johananl** [metallb/metallb#979]
We are currently inconsistent in terms of the inclusion of license text in the project's source files.
We should add a CI job which ensures every source file has a license header with the correct content. We should also ensure the year in the header is correct.

**Comment by fedepaol** [comment]
> We are currently inconsistent in terms of the inclusion of license text in the project's source files. We should add a CI job which ensures every source file has a license header with the correct content. We should also ensure the year in the header is correct.

+1 on this (and I feel guilty too)

I can work on this. 
What would you suggest to check WRT the year? Every time we touch a file we should bump the year?

**Comment by champtar** [comment]
Can we use SPDX-License-Identifier like the kernel ?
Also the year is usually with the copyright, do you want each and every contributor to put a copyright line ?

**Comment by johananl** [comment]
> Can we use SPDX-License-Identifier like the kernel ?

What does that mean in practice @champtar? I'm not sure I understand.

>Also the year is usually with the copyright, do you want each and every contributor to put a copyright line ?

I don't think we want that, no.
