### ISSUE TITLE
No issue with calico

### ISSUE THREAD

**Issue by redtex** [metallb/metallb#986]
There is no more issues with BGP peering co-existence of metallb and calico cni in same k8s installation.
The proper way of such setup is explained in following calico docs https://docs.projectcalico.org/networking/advertise-service-ips

**Comment by fedepaol** [comment]
Asking because I had a hard time parsing the reason of the issue :-)

**Comment by CaptAintHere** [comment]
Same here, I was able to configure Calico to advertise MetalLB's prefixes.

**Comment by fedepaol** [comment]
Closing this, the doc was updated (will go out with hte next release)
