### ISSUE TITLE
Load Balancer Class

### ISSUE THREAD

**Issue by infinitydon** [metallb/metallb#996]
Hi,

Please I will like to know if you are considering supporting the new load balancer class feature:

https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class

**Comment by fedepaol** [comment]
@infinitydon thanks for bringing this up.

I wonder what would be the right behaviour here. We want to cover both when metallb is the default (and only) loadbalancer on the cluster AND when it is an optional one.

I'll try to file a proposal for this.

**Comment by Jean-Daniel** [comment]
> My gut feeling is that something like this should work: if metalLB is started with a flag in the CLI to only look at some class, then it only looks for that. If no flag is given, then defaults to all as it does today. It can be an env var instead of a flag, etc.

When running as the default LB, it should ignore `Service` with this field set: 

From https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class

> Any default load balancer implementation (for example, the one provided by the cloud provider) will ignore Services that have this field set

If you need a backward compatible mode that handle all `Service`, it should be distinct.


> Yep my only fear was how to behave in case a user removes the lb class or changes it (i.e. metallb assignes an ip from the pool to a given service, then we remove the lb class parameter and restart metallb again). 

From Kubernetes doc: `Once [spec.loadBalancerClass] set, it cannot be changed`, so it should not be a concern.

**Comment by fedepaol** [comment]
> > Yep my only fear was how to behave in case a user removes the lb class or changes it (i.e. metallb assignes an ip from the pool to a given service, then we remove the lb class parameter and restart metallb again).
> 
> From Kubernetes doc: `Once [spec.loadBalancerClass] set, it cannot be changed`, so it should not be a concern.

I double checked the code. If we change metallb lb class in a way that it will own services it wasn't owning before, it will change the lb ip if it's not in any pool, will preserve it otherwise (assuming it's restarted and starts receiving new events).

On the other hand, we don't have control on what the other LBs do, and we can only hope they behave as good as metallb and document the behaviour.

**Comment by gris-gris** [comment]
Any updates on that topic folks?

**Comment by mateuszdrab** [comment]
> Any updates on that topic folks?

Second that, loadBalancerClass is now in beta and I wanted to try that feature out

**Comment by DerEnderKeks** [comment]
`loadBalancerClass` is now stable in K8s 1.24. According to the docs the current behivior of MetalLB is basically a bug:

> Any default load balancer implementation (for example, the one provided by the cloud provider) will ignore Services that have this field set.

MetalLB should at least ignore any services with that field set and maybe eventually support having a custom class specified that it uses itself.

**Comment by fedepaol** [comment]
I have a branch with the feature ready, we'll try to release it within the next release.

**Comment by fedepaol** [comment]
Set the target milestone to 0.13

**Comment by fedepaol** [comment]
closed by https://github.com/metallb/metallb/pull/1417
